### ISSUE TITLE
Multiple upload at once

### ISSUE THREAD

**Issue by newnym** [qTox/qTox#3356] opened 2016-06-06 09:00 UTC
You are using qTox version v1.4.0-101-g2cd35e1.
Commit hash: 2cd35e1
toxcore version: 0.0.0 Qt version: 5.5.1
W7 x64

Expected:
When I drop multiple files to chat window, I expect sending them at once.

Actual:
qTox send files one by one...

**Comment by LittleVulpix** [comment] 2016-06-06 11:48
@newnym this is a toxcore "feature". Only one transfer to a single contact in one direction. (meaning you can download and upload to/from one person, and also upload to multiple people at the same time, but not multiple uploads to a single person).

Not up to qTox. If you want to change this behavior, log a ticket with toxcore ( https://github.com/irungentoo/toxcore ). Thanks!

**Comment by zetok** [comment] 2016-06-06 11:57
Duplicate of #1693, thus closing.

Related: #1702, #3274

**Closed as completed by zetok** 2016-06-06 11:57 UTC
Labels: U-low

**Comment by ProMcTagonist** [comment] 2016-06-06 18:00
I'd like to note that parallel file transfers mean you're left with several unusable files in the event of network failure, whereas serial transfers give you a much higher chance of having at least a few whole files.
