### ISSUE TITLE
Cant make video/audio calls

### ISSUE THREAD

**Issue by zvory** [qTox/qTox#2936] opened 2016-02-07 19:21 UTC
You are using qTox version v1.2-346-g49b8a48.  
Commit hash: 49b8a48888b2f003f5c684b6967180ca3a65c318  
toxcore version: 0.0.0  
Qt version: 5.5.1  
OS Version: Ubuntu 15.10 wily, x86_64 Linux 4.2.0-27-generic  

I install qtox using apt-get install qtox (I also tried doing the thing where i install qtox-unity, same problem).
I make an account.  
Me and the person I want to talk to add each other.  
We can text talk, calls (video or audio) fail. I and the person I want to talk to can accept incoming calls, but the call dies after a little bit.
They are on qtox-windows 64-bit and they can talk to echobot@toxme.io or w/e.
I cannot.

```
[14:19:12.849] src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/sadeq/.config/tox/qtox.ini"
[14:19:12.850] src/ipc.cpp:46 : Debug: Our global IPC ID is  6140011525875498210
[14:19:12.853] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
[14:19:12.855] src/ipc.cpp:259 : Debug: Previous owner timed out, taking ownership 13344916483932942504 -> 6140011525875498210
[14:19:12.860] src/main.cpp:170 : Debug: built on:  09:55:03 Feb  4 2016 ( 1454597524 )
[14:19:12.860] src/main.cpp:171 : Debug: commit:  49b8a48888b2f003f5c684b6967180ca3a65c318 
[14:19:12.861] src/nexus.cpp:81 : Debug: Starting up
[14:19:16.901] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/sadeq/.config/tox/alexz.tox"
[14:19:17.070] src/persistence/settings.cpp:354 : Debug: "Saving global settings at /home/sadeq/.config/tox/qtox.ini"
[14:19:17.160] src/persistence/settings.cpp:295 : Debug: Loading personal settings from "/home/sadeq/.config/tox/alexz.ini"
[14:19:18.061] src/core/core.cpp:236 : Debug: Loading user profile
[14:19:18.061] src/persistence/profile.cpp:249 : Debug: Loading tox save  "/home/sadeq/.config/tox/alexz.tox"
[14:19:18.146] src/core/core.cpp:132 : Debug: Core starting with IPv6 enabled
[14:19:18.156] src/core/core.cpp:305 : Debug: Self avatar not found, will broadcast empty avatar to friends
[14:19:18.331] src/widget/systemtrayicon.cpp:93 : Debug: Using the Qt backend
[14:19:19.678] src/core/core.cpp:407 : Debug: "Connecting to 192.99.168.140:33445 (WIeschie)"
[14:19:19.678] src/core/core.cpp:407 : Debug: "Connecting to 198.46.138.44:33445 (nurupo)"
[14:19:24.178] src/core/core.cpp:407 : Debug: "Connecting to 178.62.250.138:33445 (Impyy)"
[14:19:24.178] src/core/core.cpp:407 : Debug: "Connecting to 130.133.110.14:33445 (Manolis)"
[14:19:28.677] src/core/core.cpp:407 : Debug: "Connecting to 104.167.101.29:33445 (noisykeyboard)"
[14:19:28.678] src/core/core.cpp:407 : Debug: "Connecting to 205.185.116.116:33445 (Busindre)"
[14:19:28.831] src/core/core.cpp:374 : Debug: Connected to the DHT
[14:19:28.831] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/sadeq/.config/tox/alexz.tox"
[14:19:52.179] src/audio/audio.cpp:267 : Debug: Opening audio output "Built-in Audio Digital Stereo (HDMI)"
[14:19:52.223] src/audio/audio.cpp:292 : Debug: Opened audio output "Built-in Audio Digital Stereo (HDMI)"
[14:20:22.956] src/widget/form/chatform.cpp:468 : Debug: onVideoCallTriggered
[14:20:22.956] src/widget/form/chatform.cpp:511 : Debug: disableCallButtons
[14:20:22.957] src/core/coreav.cpp:177 : Debug: "Starting call with 1"
[14:20:22.957] src/audio/audio.cpp:225 : Debug: Opening audio input "Monitor of Built-in Audio Analog Stereo"
[14:20:22.965] src/audio/audio.cpp:254 : Debug: Opened audio input "Monitor of Built-in Audio Analog Stereo"
[14:20:22.965] src/audio/audio.cpp:181 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[14:20:22.965] src/audio/audio.cpp:561 : Debug: Audio source 2 created. Sources active: 1
[14:20:23.049] src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video0"
[14:20:23.540] src/audio/audio.cpp:181 : Debug: Subscribed to audio input device [ 2 subscriptions ]
[14:20:23.540] src/audio/audio.cpp:197 : Debug: Unsubscribed from audio input device [ 1 subscriptions left ]
[14:20:23.540] src/widget/form/chatform.cpp:511 : Debug: disableCallButtons
[14:20:23.541] src/core/coreav.cpp:545 : Warning: Call with friend 1 died of unnatural causes!
[14:20:23.541] src/audio/audio.cpp:197 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[14:20:23.541] src/audio/audio.cpp:421 : Debug: Closing audio input
[14:20:23.541] src/audio/audio.cpp:574 : Debug: Audio source 2 deleted. Sources active: 0
[14:20:23.543] src/audio/audio.cpp:455 : Debug: Closing audio output
[14:20:23.551] src/widget/form/chatform.cpp:351 : Debug: onAvEnd
[14:20:23.551] src/widget/form/chatform.cpp:491 : Debug: enableCallButtons
[14:20:23.551] src/widget/form/chatform.cpp:511 : Debug: disableCallButtons
[14:20:23.552] src/widget/form/chatform.cpp:504 : Debug: timer started!!
[14:20:23.640] src/video/camerasource.cpp:282 : Debug: Closing device  "/dev/video0"
[14:20:24.977] src/widget/form/chatform.cpp:542 : Debug: onEnableCallButtons
``
```

**Comment by zvory** [comment] 2016-02-07 21:03
Issue is fixed if I go back 10 commits and compile that.

**Comment by anoadragon453** [comment] 2016-02-07 21:04
@zvory What's the hash of the commit where it is working?

**Comment by zvory** [comment] 2016-02-07 21:28
3a452a700fa0fe2d61ec1a3df5bea691889adb1f

Nevermind, thats more than 10 commits. I did checkout HEAD~10.

**Comment by zetok** [comment] 2016-02-08 06:05
That's weird - there shouldn't have been any changes to the A/V code in the last 10 commits..

@zvory could you perhaps recompile against ~current master, and see if compiled qTox would still work?

```
make clean && git checkout -f
git checkout master
qmake 
```

**Comment by zvory** [comment] 2016-02-08 21:35
Recompiling after running your commands makes it work.
I dunno eh, what could it be.

**Comment by zetok** [comment] 2016-02-09 16:06
@agilob re-opening, since it's a problem with the package. I.e. @zvory tested first the package, and then compiled qTox.

Package is broken, and compiled version works.

**Comment by zetok** [comment] 2016-02-09 16:15
Well, assigning @tux3, since he's the only one with access to fix it.

**Comment by agilob** [comment] 2016-02-09 16:22
Build problem? Did anyone make any changes to build scripts recently? Does jenkins build with latest toxcore every time?

**Comment by tristan-k** [comment] 2016-02-14 14:54
I can confirmt the issue. I tested three different devices with three different architectures (armhf, x86, x64) with the binaries from the github landing page. The calls will be requested but never established.

**Comment by antis81** [comment] 2016-02-15 03:38
@agilob This might relate to issue #2955.

**Comment by zetok** [comment] 2016-02-29 04:28
Could you re-test with newest binaries?

**Comment by zetok** [comment] 2016-02-29 08:01
Since [it seems to be fixed](https://github.com/tux3/qTox/issues/2945#issuecomment-190081706), closing.

**Closed as completed by zetok** 2016-02-29 08:01 UTC
Labels: C-bug, M-packaging, OS-linux, P-very-high, O-need-info, M-audio, M-video
