### ISSUE TITLE
 Build issue on Windows

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3080] opened 2016-03-30 09:31 UTC
Operating System: Windows
qTox version: 1.3

Reproducible: Always

When you run the script "bootstrap.bat" the program hangs at the stage of assembly ffmpeg-2.7

![default](https://cloud.githubusercontent.com/assets/6053197/14137970/3a32784c-f673-11e5-9878-fd47c5c89123.PNG)

**Comment by zetok** [comment] 2016-03-30 10:12
Isn't that a duplicate of #2975?

It looks like a ffmpeg problem if it hangs when compiling it..

**Comment by PKEv** [comment] 2016-03-30 10:30
Looks similar... 
The question is how bypass

**Comment by zetok** [comment] 2016-03-30 10:33
You might want to try with different ffmpeg version, perhaps 2.7, or 2.6

**Comment by PKEv** [comment] 2016-03-30 10:48
could you tell how?

**Comment by zetok** [comment] 2016-03-30 11:01
Huh, apparently it already uses 2.7.
In any case, ffmpeg versions: https://ffmpeg.org/download.html#releases

``` diff
diff --git a/windows/bootstrap.sh b/windows/bootstrap.sh
index 0a31437..e2c02e1 100644
--- a/windows/bootstrap.sh
+++ b/windows/bootstrap.sh
@@ -91,21 +91,22 @@ fi


 ## ffmpeg
-if [ ! -f "ffmpeg-2.7.tar.bz2" ]; then
-    wget http://ffmpeg.org/releases/ffmpeg-2.7.tar.bz2 -O ffmpeg-2.7.tar.bz2
-    rm -rf ffmpeg-2.7
+FFMPEG_VER="2.8.6"
+if [ ! -f "ffmpeg-${FFMPEG_VER}.tar.xz" ]; then
+    wget http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VER}.tar.xz
+    rm -rf ffmpeg-${FFMPEG_VER}
 fi

-if [ ! -d "ffmpeg-2.7" ]; then
-    tar -xvf ffmpeg-2.7.tar.bz2
+if [ ! -d "ffmpeg-${FFMPEG_VER}" ]; then
+    tar -xvf ffmpeg-${FFMPEG_VER}.tar.xz
     rm bin/avcodec-56.dll
-    pushd ffmpeg-2.7
+    pushd ffmpeg-${FFMPEG_VER}
     patch -p1 < $QTOX_DIR/windows/ffmpeg-2.7-mingw.diff
     popd
 fi

 if [ ! -f "bin/avcodec-56.dll" ]; then
-    pushd ffmpeg-2.7
+    pushd ffmpeg-${FFMPEG_VER}
     ./configure --target-os=mingw32 --prefix=$QTOX_DIR/libs \
         --enable-memalign-hack --disable-swscale-alpha --disable-programs --disable-doc --disable-postproc \
         --disable-avfilter --disable-avresample --disable-swresample --disable-protocols --disable-filters \
```

No idea whether diff would work.

**Comment by PKEv** [comment] 2016-04-01 08:39
In addition there is a problem with the Assembly for the override struct timespec.
Maybe someone solved this problem?

**Comment by sudden6** [comment] 2017-05-07 12:09
I'm closing this since it's ancient and more up to date efforts are documented in https://github.com/qTox/qTox/issues/4302

**Closed as completed by sudden6** 2017-05-07 12:09 UTC
Labels: C-bug, upstream, OS-windows
