### ISSUE TITLE
qTox groups auto delete on shutdown.

### ISSUE THREAD

**Issue by LWFlouisa** [qTox/qTox#5971] opened 2020-01-24 23:39 UTC
##### Brief Description

OS: Linux Mint 19.1
qTox version: v1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3
Qt:  5.7.1
Hardware:  Dell Core III
…

Reproducible: Every restart,

##### Steps to reproduce

1. When you start qTox, a group can be created.
2. I can configure all the settings for the group.
3. However when I shut it down, or computer crashes, I have to recreate the group.

##### Observed Behavior
The group behaves mostly as normal, except I have to recreate it every time I need the group.

##### Expected Behavior
The group should remain available regardless of whether I have qTox opened.

I don't have any logs for the issue, as I don't get an error code for it. I wasn't sure if this was an intended feature or not.

**Comment by anthonybilinski** [comment] 2020-01-24 23:54
This was a feature limitation in qTox version v1.16.3. Since then, Toxcore has been updated to support saving and restoring groups across restart, which works with qTox nightly builds available at https://github.com/qTox/qTox-nightly-releases/releases. It will be included in qTox v1.17.0 once it's released, which we're working on now: https://github.com/qTox/qTox/milestone/23.

This issue's a duplicate of https://github.com/qTox/qTox/issues/896, I'll close it off since there's no work remaining except for making the v1.17.0 release.

**Closed as completed by anthonybilinski** 2020-01-24 23:54 UTC
