### ISSUE TITLE
Improve groupchat UI

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#4840] opened 2017-11-26 20:03 UTC
The list of users in group chats is compact, but not very easy to read: 
![qtox groupchats](https://user-images.githubusercontent.com/32248732/33243809-af78611c-d2e4-11e7-9a49-5839919d2f81.png)

I propose to do something like this instead:
![qtox improved groupchats](https://user-images.githubusercontent.com/32248732/33243819-d44eb7f2-d2e4-11e7-99ad-b7ef8777ed0f.png)

Names are only one per line, so easier to read. If we wanted to add things like right click on the user to show options (mute, kick, ban etc) it would work better with this design. Avatars of participants are shown. If this is not possible, we could show them only for friends.

**Comment by Diadlo** [comment] 2017-11-26 20:10
Agree. With future architecture it should be easy to implement. Also, better make contact list starts after header

**Comment by tox-user** [comment] 2017-11-26 21:34
![qtox improved groupchats 2](https://user-images.githubusercontent.com/32248732/33244548-a02b4334-d2f1-11e7-9031-6be5d73e0d89.png)

**Comment by fodrice** [comment] 2017-12-01 17:59
One more thing: make option to hide/show this panel.

**Comment by anthonybilinski** [comment] 2017-12-01 21:31
To hide there could be an "x" inside the panel, and then to re-show the user could click on the "22 users in chat" text so that it's easy to switch between the two views without digging into settings.

**Comment by tox-user** [comment] 2017-12-01 22:59
How about this (except with better icon for the button)?

![qtox improved groupchats 3 1](https://user-images.githubusercontent.com/32248732/33507184-3a8be1fc-d6eb-11e7-8bd9-67eb5c6de675.png)
![qtox improved groupchats 3 2](https://user-images.githubusercontent.com/32248732/33507188-3ff23236-d6eb-11e7-9c09-b397424fc69f.png)

**Comment by zetok** [comment] 2018-09-29 21:10
Proposal is a duplicate of #677, thus closing.

**Closed as completed by zetok** 2018-09-29 21:10 UTC
Labels: U-low, proposal, M-ui
