### ISSUE TITLE
New video view: qTox spams log file and crashes sometimes

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2423] opened 2015-10-19 16:32 UTC
Hello,

I'm not sure why it was ignored, so here again:
https://github.com/tux3/qTox/pull/2093#issuecomment-138590880
- During a video chat I changed my avatar and qTox crashed sometimes
  - But it happens only sometimes. Perhaps some of you could also test it.
- Tox log file is spammed: http://pastebin.com/6J0nwyuF

**Comment by ovalseven8** [comment] 2015-10-19 17:05
Some new information about the crash - I tested with two instances of qTox on my device:
Finally, both instances crashed - that's the report in terminal:
`Speicherzugriffsfehler (Speicherabzug geschrieben)`
in English something like:
`Memory access error`

**Comment by ovalseven8** [comment] 2015-10-19 17:09
Now qTox crashed again, this one time with the following report in terminal:
`[19:08:06.636] src/ipc.cpp:258 : Debug: Previous owner timed out, taking ownership 14609214455770097701 -> 5941558863648664925`

One way to reproduce:
Start two instances of qTox. The profile's of the two instances have to be friend, then start a video call. Then ring off. Now, one of the instances have to change the avatar. => CRASH

Be aware: Sometimes it also happens DURING a chat.

**Comment by ovalseven8** [comment] 2015-10-19 17:13
One way to reproduce:
Start two instances of qTox. The profile's of the two instances have to be friend, then start a video call. Then ring off. Now, one of the instances have to change the avatar. => CRASH

Be aware: Sometimes it also happens DURING a chat.

**Comment by agilob** [comment] 2015-10-19 17:26
> Now qTox crashed again, this one time with the following report in terminal:

IPC related.

**Comment by zetok** [comment] 2015-10-19 17:54
Duplicate of #2408, thus closing.

**Closed as completed by zetok** 2015-10-19 17:54 UTC
Labels: C-bug, U-low, P-medium, C-crash

**Comment by ovalseven8** [comment] 2015-10-19 18:16
I see. But perhaps someone could fix that the log file won't be spammed anymore.

**Comment by agilob** [comment] 2015-10-19 18:19
I'm not convinced it's duplicate, similar behaviour, but is cause the same? @antis81 ?

**Comment by zetok** [comment] 2015-10-19 18:43
@agilob I had #2408 happen randomly, and independently from whether there is a login screen or not launched - generally, you just need to have multiple instances, and thanks to @ovalseven8 there's a way to reproduce it `:)`

**Comment by ovalseven8** [comment] 2015-10-20 20:00
Shall I create an extra issue for the log file spam?

**Comment by zetok** [comment] 2015-10-20 20:35
@ovalseven8 yeah, you probably should
