### ISSUE TITLE
Segfault on sending message (missing dependency - qt sql plugin)

### ISSUE THREAD

**Issue by seisatsu** [qTox/qTox#2019] opened 2015-07-19 20:10 UTC
On the newest version of qTox compiled from git, when attempting to send a message, the following appears in the console for several hundred lines, followed by a segfault. The message does not send.

[13:06:56.581] :0 : Warning: QSqlQuery::exec: database not open
[13:06:56.581] :0 : Warning: QSqlQuery::exec: database not open
[13:06:56.581] :0 : Warning: QSqlQuery::exec: database not open
[13:06:56.581] :0 : Warning: QSqlQuery::exec: database not open
...

**Comment by skeptr** [comment] 2015-08-22 18:06
Same here on my openSUSE 13.2.
I checked on versions 1.0.2-12.6 and from git 20150821.

**Comment by necrophcodr** [comment] 2015-10-12 14:38
I can confirm to still have this issue with qTox 1.1 on Void Linux amd64. However, deleting both qtox.ini and qtox.log somehow resolved the issue (for now).

**Comment by tux3** [comment] 2015-10-12 14:41
@necrophcodr Can you post the result of running `ls -la ~/.config/tox/` please?

**Comment by necrophcodr** [comment] 2015-10-13 14:58
After running it for a while, the issue seems to have returned.

Output is 

drwxr-xr-x 1 necrophcodr necrophcodr  156 13 okt 16:57 ./
drwx------ 1 necrophcodr necrophcodr 1326 10 okt 09:58 ../
drwx------ 1 necrophcodr necrophcodr    0 23 sep 16:05 avatars/
-rw-r--r-- 1 necrophcodr necrophcodr   80 23 sep 16:20 necrophcodr.ini
-rw-r--r-- 1 necrophcodr necrophcodr 4802 23 sep 16:20 necrophcodr.tox
-rw-r--r-- 1 necrophcodr necrophcodr   24 23 sep 16:19 tox_save.ini
-rw------- 1 necrophcodr necrophcodr 5711 23 sep 18:53 tox_save.tox

**Comment by necrophcodr** [comment] 2015-10-18 22:15
Problem seems to persist even through deleting those files. I am unable to receive any messages as it appears to crash the entirety.

The log file grows by megabytes per second, containing the following line:

```
[time] :0 : Warning: QSqlQuery::exec: database not open
```

Having had the application running for just a few seconds after sending a single message, before killing it, it had already output a massive >130.000 lines like the one above.

It appears that JUST before this happens, the following was printed:

```
[time] :0 : Warning: QSqlDatabase: QSQLITE driver not loaded
[time] :0 : Warning: QSqlDatabase: available drivers:
[time] :0 : src/misc/db/plaindb.cpp:28 : Warning: "Can't open file: :memory:, history will not be saved!"
[time] :0 : Warning: QSqlQuery::exec: database not open
[time] :0 : Warning: QSqlQuery::exec: database not open
...
```

**Comment by necrophcodr** [comment] 2015-10-18 22:38
My apologies. Upon further inspection, I have informed the package maintainers of Void Linux to add the qt5-plugin-sqlite package as a runtime dependency. It seemed it wasn't installed, and caused the crash.

**Comment by zetok** [comment] 2015-10-19 08:15
> My apologies. Upon further inspection, I have informed the package maintainers of Void Linux to add the qt5-plugin-sqlite package as a runtime dependency. It seemed it wasn't installed, and caused the crash.

Well then, since it's not a problem with qTox itself, closing.

**Closed as completed by zetok** 2015-10-19 08:15 UTC
Labels: P-high, C-crash
