### ISSUE TITLE
qTox not connecting

### ISSUE THREAD

**Issue by Nevo0110** [qTox/qTox#4397] opened 2017-05-12 18:13 UTC
The title says it all, after downloading the executable for windows and installing on arch neither client connects.

OS: Windows / Linux(Arch)
qTox version: v1.9.0-104-g5d117e6
Commit hash:  5d117e6af854de194dc16575f1fe5c95a43741c8
toxcore: 0.1.8  
Qt:  5.5.1
Hardware:  
CPU: FX-8350
GPU: GTX 1060 6GB variant
MOBO: Gigabyte GA-78LMT
SSD: Samsung 850 Evo
HDD: Western Digital Blue

(not sure what other information about hardware could be useful if any more is needed I will happily comment)

Reproducible: Always

##### Steps to reproduce

1. Start the program

##### Observed Behavior
No connection

##### Expected Behavior
Connection

##### Additional Information
As a side note however I am able to connect on both machines using uTox
Also when getting version information it says to restart qTox to install version v1.9.0-104-g5d117e6 which as you can see is already installed.
I have checked my firewall settings as well and everything is allowed.
Attached below is also a photo of the online status indicator
![capture](https://cloud.githubusercontent.com/assets/24445772/26010987/29ccb256-371d-11e7-93bc-9d441ab3a085.PNG)

**Comment by zetok** [comment] 2017-05-12 20:13
Duplicate of #4385, thus closing.

**Closed as completed by zetok** 2017-05-12 20:13 UTC
Labels: U-low

**Comment by Nevo0110** [comment] 2017-05-12 20:16
My bad
