### ISSUE TITLE
qTox and arabic language

### ISSUE THREAD

**Issue by AboShanab** [qTox/qTox#2780] opened 2016-01-08 19:17 UTC
Hello guys, i have some problem when i try to communication some person using arabic language, the problem is when i write the message using arabic language and i send it, the message will sent but the problem i can't see the message in the chat box, it visible as empty message, screenshot : https://i.imgur.com/2BN5hme.png
i got currently an idea to chat a person using arabic langauge, the idea is write any letter of english language before the arabic message to fix that's problem, screenshot : https://i.imgur.com/taiUICH.png
So yes, the message now visible on the chat box, currently we will use this way to communication using qTox, but we want a fix for that's problem, This problem work in all of qTox versions and in all platforms.
My qTox is nightly, it using Qt 5.5.0, and my distribution is fedora 23 using xfce.
Thanks for reading.

**Comment by zetok** [comment] 2016-01-08 21:38
Duplicate of #1887, thus closing.

**Closed as completed by zetok** 2016-01-08 21:38 UTC
Labels: U-low
