### ISSUE TITLE
qTox crashes if password used

### ISSUE THREAD

**Issue by TasPats** [qTox/qTox#4551] opened 2017-07-30 02:38 UTC
##### Brief Description

OS: Linux GNU Debian 9.1
qTox version: 1.11.0-27-gad58c176  
Commit hash:  ad58c1767b2ab4ff8340076d5ede53aa6e889972
toxcore:  0.1.2
Qt:  5.7.1 
Hardware:  i5/16GB/GTX750i
…

Reproducible: Always if password not empty

##### Steps to reproduce

1. run ./qtox
2. enter password
3. crash

##### Observed Behavior
qtox closes

##### Expected Behavior
qtox runs

##### Additional Info
(links, images, etc go here)

qTox crashes if password used, if I leave password empty, qTox runs fine

----
[02:25:15.494 UTC] nexus.cpp:90 : Debug: Starting up
[02:25:21.157 UTC] persistence/profile.cpp:110 : Debug: Loading tox save  "/home/ija/.config/tox/ija.tox"
[02:25:21.232 UTC] persistence/settings.cpp:451 : Debug: "Saving global settings at /home/ija/.config/tox/qtox.ini"
[02:25:21.525 UTC] persistence/settings.cpp:325 : Debug: Loading personal settings from "/home/ija/.config/tox/ija.ini"
[02:25:21.575 UTC] :0 : Warning: QObject::connect: invalid null parameter
[02:25:22.202 UTC] :0 : Warning:   OpenType support missing for script 16
[02:25:22.233 UTC] :0 : Warning:   OpenType support missing for script 16
[02:25:22.355 UTC] core/core.cpp:264 : Debug: Loading user profile
[02:25:22.355 UTC] core/core.cpp:128 : Debug: Core starting with IPv6 enabled
[02:25:22.426 UTC] persistence/profile.cpp:75 : Debug: Self avatar not found, will broadcast empty avatar to friends
[02:25:22.614 UTC] widget/systemtrayicon.cpp:82 : Debug: Using the Qt backend
[02:28:49.525 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/ija/.config/tox/qtox.ini"
[02:28:49.601 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  3032122788710534962
[02:28:49.602 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[02:28:49.602 UTC] ipc.cpp:251 : Debug: Previous owner timed out, taking ownership 5471822863079913026 -> 3032122788710534962
[02:28:49.602 UTC] main.cpp:234 : Debug: built on:  04:53:48 Jul 30 2017 ( 1501379468 )
[02:28:49.609 UTC] main.cpp:235 : Debug: commit:  ad58c1767b2ab4ff8340076d5ede53aa6e889972

**Comment by sudden6** [comment] 2017-07-30 08:35
Can you check if it's not a duplicate of https://github.com/qTox/qTox/issues/4054

**Comment by zetok** [comment] 2017-08-31 13:51
Needed info not provided for over a month, thus closing.

**Closed as completed by zetok** 2017-08-31 13:51 UTC
Labels: O-need-info
