### ISSUE TITLE
Crash when proxy host is set to "localhost"

### ISSUE THREAD

**Issue by naxuroqa** [qTox/qTox#5062] opened 2018-04-06 12:57 UTC
##### Brief Description

OS: Arch Linux
qTox version: v1.14.0-40-gff578413
Commit hash: ff578413c1bfba50db950f60924f595f435889d0
toxcore: 0.1.11
Qt: 5.10.1
Hardware:  
yes

Reproducible: Always

##### Steps to reproduce

1. Set a socks5 proxy with host "localhost"
2. (optional) Disable udp
3. Restart qtox

##### Observed Behavior

Error message `toxcore failed to start with your proxy settings. qTox cannot run; please modify your settings and restart.` and crash after clicking ok.

##### Expected Behavior

No crash.

##### Additional Info
Seems to work fine with an ip address (e.g. "127.0.0.1")

[stacktrace](https://paste.ee/p/WHavk)

**Comment by anthonybilinski** [comment] 2018-04-07 03:25
I think this is a toxcore issue.
```
if (addr_resolve_or_parse_ip(tox_options_get_proxy_host(options), &m_options.proxy_info.ip_port.ip, nullptr) == 0) {
    SET_ERROR_PARAMETER(error, TOX_ERR_NEW_PROXY_BAD_HOST);
```
```
 * input
 *  address: a hostname (or something parseable to an IP address)

int addr_resolve(const char *address, IP *to, IP *extra)
```
seems like it should handle `localhost`. It seems to handle other non-IP hostnames fine.

I was able to reproduce this, then when looking into it lost the ability and can't reproduce it anymore, so it may be a little more complex than expected. I wonder if pinging `localhost` caused it to get looked up properly then cached, which toxcore can now access.

EDIT:
bonus bugs that are definitely qTox's fault:

1. seg fault on invalid proxy host on start 100%
```
    QObject::connect(coreThread, &QThread::started, core, [=]() {
        core->start(toxsave);

        const ToxPk selfPk = core->getSelfPublicKey();
```
tox is null during getSelfPublicKey.

2. seg fault on reconnect ~10% of time
`Core::getToxSaveData` called from `Core::reset` has a null tox

**Comment by anthonybilinski** [comment] 2022-03-17 12:30
Looks like this was fixed by https://github.com/qTox/qTox/pull/5185.

Following repro steps, my qTox starts correctly, the SOCKS5 and localhost proxy is shown in settings, and qTox never connects (as expected). Closing.

**Closed as completed by anthonybilinski** 2022-03-17 12:30 UTC
Labels: C-crash
