### ISSUE TITLE
qTox does not encrypt

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2432] opened 2015-10-21 18:25 UTC
1. Create account without password
2. Set password
3. qTox doesn't encrypt the history file immediately!
4. After restart it's apparently encrypted BUT there's still the unencrypted file!

Don't know if the tox profile file gets encrypted properly too.

**Comment by TheNain38** [comment] 2015-10-22 10:52
I think it's a regression since #2346 was merged in commit c07aee18ad67414d45744fbda61c289796c8f4c7. It also happened to me

**Comment by zetok** [comment] 2015-10-22 12:04
@PKEv ?

**Comment by tux3** [comment] 2015-12-19 04:01
Fixed by the new SQLCipher database code in master.

**Comment by ovalseven8** [comment] 2015-12-19 09:45
@tux3:
Now, qTox doesn't encrypt the database at all...

**Comment by tux3** [comment] 2015-12-19 11:29
@ovalseven8 If you have a password, it should be encrypted now. If you don't have a password, then it can't be encrypted.

If you found a bug where it's not encrypted, can you tell me what the steps are to reproduce exactly?

**Comment by TheNain38** [comment] 2015-12-19 12:16
For me it works as expected

**Comment by ovalseven8** [comment] 2015-12-19 12:17
@TheNain38:
Seems like only the builds from tox.chat are affected. Did you compile qTox?

**Comment by TheNain38** [comment] 2015-12-19 12:23
Yes, I compiled it. @tux3 The builds on tox.chat don't have the libsqlcipher-dev installed when compiling I think...

**Comment by tux3** [comment] 2015-12-19 13:05
The Jenkins build were linking to SQLite instead of SQLCipher, I'm currently fixing that.

**Closed as completed** 2015-12-21 17:19 UTC
Labels: C-bug, M-packaging, P-very-high
