### ISSUE TITLE
qTox freeze on user "delete" button press

### ISSUE THREAD

**Issue by lenovero** [qTox/qTox#4896] opened 2018-01-07 14:26 UTC
##### Brief Description

OS: Windows 
qTox version: (version numbers in menu `Settings → About`)  v1.13.0.
Commit hash:  Commit hash: 531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore:  0.1.10
Qt:  5.9.3
Hardware:  i5 3210m - 8gb ram
…

Reproducible: Always / 

##### Steps to reproduce

1. download https://build.tox.chat/view/qtox/job/qTox-cmake-stable_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox-cmake-stable_build_windows_x86-64_release.zip
2.  extract
3. open qtox, create a user, try to delete it or logout, freeze to me.

log:

[14:25:41.824 UTC] persistence/profile.cpp:111 : Debug: Loading tox save  "C:/Users/Lenovo/AppData/Roaming/tox\\rhtt.tox"
[14:25:41.824 UTC] persistence/settings.cpp:332 : Debug: Loading personal settings from "C:/Users/Lenovo/AppData/Roaming/tox/rhtt.ini"
[14:25:41.824 UTC] persistence/settings.cpp:459 : Debug: "Saving global settings at C:/Users/Lenovo/AppData/Roaming/tox\\qtox.ini"
[14:25:42.150 UTC] :0 : Warning:   OpenType support missing for "MS Shell Dlg 2", script 16
[14:25:42.151 UTC] :0 : Warning:   OpenType support missing for "Arial", script 16
[14:25:42.151 UTC] :0 : Warning:   OpenType support missing for "MS UI Gothic", script 16
[14:25:42.151 UTC] :0 : Warning:   OpenType support missing for "Gulim", script 16
[14:25:42.151 UTC] :0 : Warning:   OpenType support missing for "SimSun", script 16
[14:25:42.152 UTC] :0 : Warning:   OpenType support missing for "PMingLiU", script 16
[14:25:42.152 UTC] :0 : Warning:   OpenType support missing for "Segoe UI Emoji", script 16
[14:25:42.153 UTC] :0 : Warning:   OpenType support missing for "Segoe UI Symbol", script 16
[14:25:42.191 UTC] core/core.cpp:270 : Debug: Loading user profile
[14:25:42.191 UTC] core/core.cpp:130 : Debug: Core starting with IPv6 enabled
[14:25:42.202 UTC] persistence/profile.cpp:76 : Debug: Self avatar not found, will broadcast empty avatar to friends
[14:25:42.880 UTC] widget/systemtrayicon.cpp:83 : Debug: Using the Qt backend
[14:25:44.003 UTC] core/core.cpp:411 : Debug: "Connecting to tox.verdict.gg:33445 (Deliran)"
[14:25:44.117 UTC] core/core.cpp:411 : Debug: "Connecting to 2a02:f680:1:1100::3313:33445 (ru_maniac)"
[14:25:48.220 UTC] persistence/profile.cpp:641 : Debug: Removing profile "rhtt"
[14:25:48.222 UTC] persistence/db/rawdatabase.cpp:450 : Debug: Removing database  "C:/Users/Lenovo/AppData/Roaming/tox\\rhtt.db"
[14:25:48.222 UTC] :0 : Warning: QMetaMethod::invoke: Dead lock detected in BlockingQueuedConnection: Receiver is Nexus(0x37e1a10)
[14:25:49.301 UTC] core/core.cpp:380 : Debug: Connected to the DHT

**Comment by sudden6** [comment] 2018-01-07 14:55
Could reproduce also on Linux.

**Comment by tox-user** [comment] 2018-01-08 00:44
Duplicate of https://github.com/qTox/qTox/issues/4841?

**Comment by sudden6** [comment] 2018-01-08 11:10
yes, will close the other one, because the PR is already linked here.

**Closed** 2018-01-11 12:26 UTC
Labels: I-bug
