### ISSUE TITLE
UDP bootstrap for initial peer discovery

### ISSUE THREAD

**Issue by gianni76** [qTox/qTox#4084] opened 2017-01-18 16:54 UTC
I have been using Qtox mainly for simple secure chat and file transfers with colleagues when on the field (so almost exclusively in mobile an not-so-stable conditions). 

Due to bandwith issues (very strict limits on mobile connections) we have to turn off UDP.
This is not a problem in normal situation, after the connection is established and peers discovered.
But starting with UDP disabled, we rarely get the peers discovered at all.

So what  we do (and it works!) is:
1) turn the 'Enable UDP' flag on for 10-15 seconds initially after start-up
2) let QTox actually discover the peers (see the green dot close to his/her name), 
3) Immediately after the peer is discovered, turn off the 'Enable UDP' flag and press the button Reconnect. 

The 'second' connection, which is with UDP turned off, keeps track of the previous discovery and is very fast. This way we have a rapid peer discovery, but don't waste continuous bandwith with UDP peer packet transmission.

The program itself could have this udp bootstrap mode option built internally, where the UDP channel would be kept open until the peer discovery mechanism is complete and than being closed down.
Would help easing the manual process and speed up the initial peer discovery mechanism.

**Comment by zetok** [comment] 2017-01-22 16:24
> turn the 'Enable UDP' flag on for 10-15 seconds initially after start-up

If you don't press `Reconnect` after checking that box, there's only placebo effect happening.

Regardless, this is a workaround for the problem, and is not going to be done in qTox. The only workaround that is acceptable is having `Reconnect` button.

The problem seems to be an unreliable (buggy) bootstrapping in TCP-only mode, and it should be reported on the toxcore repo: https://github.com/TokTok/c-toxcore/issues/new

**Comment by anthonybilinski** [comment] 2020-05-18 11:27
It's been a few years since this was opened, multiple new toxcore versions and some changes to how qTox bootstraps, so I re-tested this.

I tried a few tests with two profiles in TCP-only mode. Profile A started and sat open for about 1-2 minutes, then I started profile B.

Time from start of qTox to start of bootstrapping:

1. 3.2s
1. 8.7s
1. 1.4s
1. 2.8s

Time from start of bootstrapping to finish of bootstrapping, e.g. green light.

1. 9.3s
1. 13.3s* (This connected -> disconnected -> connected. Time is from the start to the second connect.)
1. 12.3s
1. 13.3s

Time from connected to seeing profile A online:

1. 3.0s
1. 58.0s* (Note, this bootstrap connected -> disconnected -> connected)
1. 7.0s
1. 4.1s

Overall this looks pretty good except for the second test being a bit jank.

@gianni76 are you able to reproduce your issue on version 1.17.2, with just keeping TCP enabled, not using any kind of UDP-enabling workaround? If not or if we don't hear back I'll assume the issue is fixed.

**Comment by anthonybilinski** [comment] 2020-05-18 11:36
Is more support needed for this, or can the issue be closed?

**Comment by anthonybilinski** [comment] 2020-08-16 02:23
Closing based on previous comment.

**Closed as completed by anthonybilinski** 2020-08-16 02:23 UTC
Labels: upstream, O-need-info
