### ISSUE TITLE
qTox autoupdates when there are no new updates

### ISSUE THREAD

**Issue by wDraw** [qTox/qTox#4093] opened 2017-01-25 08:33 UTC
##### Brief Description

OS: Windows 7
qTox version: 1.7.0
Commit hash:  12c21b21d2d62a27b0002c1add7e4d7faa0d018d
toxcore:  0.1.4
Qt:  5.5.1

Reproducible: Always

##### Steps to reproduce

1. Restart qTox
2. Check "About" section in the options

##### Observed Behavior

qTox autoupdates every time I restart the client, even though there are no new updates.

##### Expected Behavior

qTox to update only if new updates are available.

##### Additional Info

![update](https://cloud.githubusercontent.com/assets/20287696/22283047/9fc320a0-e2e8-11e6-92cb-ffcd089335cd.PNG)

----

[qtox.txt](https://github.com/qTox/qTox/files/728996/qtox.txt)

**Comment by yurivict** [comment] 2017-02-05 08:16
Duplicate of https://github.com/qTox/qTox/issues/3771 ?

**Comment by zetok** [comment] 2017-02-05 08:25
@yurivict Yeah, thanks.

**Closed as completed by zetok** 2017-02-05 08:25 UTC
Labels: C-bug, U-low, M-packaging, OS-windows
