### ISSUE TITLE
[Feature Request] Proxy with authentication

### ISSUE THREAD

**Issue by ghoulll** [qTox/qTox#4625] opened 2017-09-03 11:13 UTC
I'd like to ask if it's possible to implement support for **proxy server** where **authentication is required**.
Currently, there we can configure just IP address of proxy server but no credentials (username + password).

I could imagine two additional fields for **username and password in proxy setting**, those credentials could be used for proxy authentication if required.

Thank you for your answer.

**Comment by sudden6** [comment] 2017-09-06 16:27
duplicate of #1286

**Closed as completed by sudden6** 2017-09-06 16:27 UTC
