### ISSUE TITLE
qTox crash on windows 7 (32bit and 64bit) after logout

### ISSUE THREAD

**Issue by nikitasius** [qTox/qTox#2833] opened 2016-01-21 14:10 UTC
Hello!

When you click "Logout" tox restarting itself and... login form becoming white and windows telling you about errors and offering to close it.

Doesn't matter how much copies you run, single or multiple. It was in december version, and exists in latest too.

**Comment by nikitasius** [comment] 2016-01-21 14:13
![qtox_logout_fail_01](https://cloud.githubusercontent.com/assets/3670331/12482726/843593aa-c051-11e5-86a9-852496dac29b.PNG)

**Comment by zetok** [comment] 2016-05-11 04:26
Is it still reproducible on newest (1.4.1) version?

**Comment by zetok** [comment] 2016-07-01 13:23
Looks like a duplicate of #2480, thus closing.

**Closed as completed by zetok** 2016-07-01 13:23 UTC
Labels: C-bug, U-low, P-very-high, C-crash
