### ISSUE TITLE
How to filter the history by keywords?

### ISSUE THREAD

**Issue by Granitoid** [qTox/qTox#2935] opened 2016-02-07 14:57 UTC
I could not find a function!
I need a button "filter" and field for entering a keywords.
Also this field should will be open by hotkey Ctrl + F.
Something like this:
![qtox-hist](https://cloud.githubusercontent.com/assets/16450834/12873011/1bdd8580-cdc4-11e5-8eae-07c6cc20e78f.jpg)

**Comment by zetok** [comment] 2016-02-07 19:15
Duplicate of #1734, thus closing.

**Closed as completed by zetok** 2016-02-07 19:15 UTC
Labels: U-low, proposal, M-ui
