### ISSUE TITLE
Smiles should be unified or be correctly displayed on another client with another pack

### ISSUE THREAD

**Issue by DMantis** [qTox/qTox#3600] opened 2016-08-07 16:25 UTC
I've tested qtox on two computers and found out that if I use different smiles pack (for example, basic and universe) at my qtox clients smiles display incorrectly. 

Using IM in real life, it's really silly and inconvenient to ask another person every time which smiley pack he is using. 

At least default packs should be supported and correctly displayed at qtox clients with different settings. 

P.S. And it's much better to talk with another most popular tox-clients teams about unifiying such kind of stuff if tox really have a plan to compete with skype. If I use one client and smilepack and my friend use another and I try to sent sad smile, my friend should receive sad smile, not the crap image or something because of incompability.

**Comment by zetok** [comment] 2016-08-07 18:16
Sounds like a duplicate of #596, thus closing.

> And it's much better to talk with another most popular tox-clients teams about unifiying such kind of stuff if tox really have a plan to compete with skype.

Other clients are free to use emoticons available in qTox. You should bring that to attention of Antox & Antidote developers, hopefully they would be interested in supporting those emoticons :)

**Closed as completed by zetok** 2016-08-07 18:16 UTC
Labels: U-low
