### ISSUE TITLE
allow to copy link by right click

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2188] opened 2015-09-07 21:12 UTC
Sometime I don't want to leftclick a link and have the defult browser opne it straight away. 
Almost every chat application and brwoser recognizes links and allow to copy the link by clicking "copy link" in context menu of right click. Would be nice to have it.
thx

**Comment by zetok** [comment] 2015-09-08 11:27
Duplicate of #1236, thus closing.

**Closed as completed by zetok** 2015-09-08 11:27 UTC
Labels: U-low

**Comment by aaannndddyyy** [comment] 2015-09-08 11:32
Hadn't seen it. Sorry n thx.
