### ISSUE TITLE
File transfers from auto-accept users fail

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3849] opened 2016-11-02 18:48 UTC
This isn't a dialog issue (https://github.com/qTox/qTox/issues/3284) because there should be no dialog. And this isn't a toxcore issue (see https://github.com/irungentoo/toxcore/issues/1468).

Single, one at a time file transfer from auto-accept users should succeed. This should be high priority.

**Comment by zetok** [comment] 2016-11-02 19:10
Logs, and other info?

edit: can't reproduce on  6ee3b95b6f315af2b63c685b2ff38067e04b9fc7

**Comment by yurivict** [comment] 2016-11-02 19:30
When the file comes in, only this is printed:

```
[19:20:12.531 UTC] src/core/corefile.cpp:311 : Debug: "Received file request 6:65536 kind 0"
[19:20:18.853 UTC] src/widget/form/chatform.cpp:509 : Debug: enableCallButtons
[19:20:18.854 UTC] src/widget/form/chatform.cpp:522 : Debug: timer started!!
```

At this time it hangs for many minutes at ~60% complete.

**Comment by yurivict** [comment] 2016-11-02 19:34
Transfer never succeeds, just sits in half-finished state. Maybe peer connection-down is what causes the actual failure on the qTox side.

Some such transfers succeed, but most fail this way.

1.5.2 on FreeBSD

**Comment by yurivict** [comment] 2016-11-06 23:38
Any idea how to troubleshoot this? Any way to increase the log level? This might be FreeBSD-specifit, and it might be in toxcore too.

**Comment by ElLamparto** [comment] 2016-11-10 08:50
I might add, when the sender is µTox and the receiver qTox (on autoaccept), the transfer always succeeds. Recently I pomped 2.2 GB file over without problems. Smaller files I transfer quite often.

**Comment by sudden6** [comment] 2016-11-10 21:42
@yurivict 

> Any idea how to troubleshoot this? Any way to increase the log level?

The log level is already at the maximum, the next best option would be to start qtcreator and look at qTox through the debugger.

**Comment by fcore117** [comment] 2016-11-14 10:20
yurivict: this might be core problem? i get this daily and on utox-utox, qtox-utox, utox-qtox. I usually work around this just closing and reopening client, friends get this same be it qtox or utox.

**Comment by yurivict** [comment] 2016-11-14 16:58
@fcore117  Are you on FreeBSD?

**Comment by fcore117** [comment] 2016-11-14 18:06
yurivict: nope windows but sometimes ubuntu and same applies to friends so it is not a os problem.

**Comment by yurivict** [comment] 2016-11-14 18:09
So this is a general problem. I thought it was a FreeBSD problem.

**Comment by zetok** [comment] 2016-11-14 20:00
Looks like a duplicate of #3292, thus closing.

**Closed as completed by zetok** 2016-11-14 20:00 UTC
Labels: U-low
