### ISSUE TITLE
Profile photo background should not be inverted

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2165] opened 2015-09-02 16:37 UTC
Currently if you set a profile picture (PNG) with a transparent background qTox inverts the picture colour to display it.
That neither looks nice nor is it useful, so either you should display the correct background (so transparent is really transparent) or display a static colour like white.

**Comment by zetok** [comment] 2015-09-02 19:51
Duplicate of #944, closing.

**Closed as completed by zetok** 2015-09-02 19:51 UTC
Labels: U-low

**Comment by Getron** [comment] 2015-09-08 11:47
+1
