### ISSUE TITLE
Offline messege not sended after restart

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1805] opened 2015-06-05 17:34 UTC
Description:

Info:
OS: Win 7 x32

Reproducible: Always 

Steps to reproduce:
1. in settings setup "Faux offline messaging" 
2. send message to offline friend 
3. restart app
4. message look like it was delivered then you restart app

What happened:
message look like it was delivered, but in fact no

What should happen:
message must  be undelivered and sended only then friend be online

**Comment by PKEv** [comment] 2015-06-05 23:20
find broken index in db
message in app:
![default](https://cloud.githubusercontent.com/assets/6053197/8016843/b332c49e-0bf1-11e5-9556-087ae77e75d6.png)
history in db:
![1](https://cloud.githubusercontent.com/assets/6053197/8016847/c52baf08-0bf1-11e5-81ab-b7f3c4c017cc.png)
status in db: (look - id's Much more than in the table history 
![2](https://cloud.githubusercontent.com/assets/6053197/8016865/16bc2c4e-0bf2-11e5-91c4-4d51999785e7.png)

How it happened I do not know.....
(in setting: pragma_synchronous = FULL)
UPD: (all message sended to offline friend)

**Comment by tux3** [comment] 2015-06-05 23:35
It's strange, it usually gets sent after some time.
Does it always stay stuck even after a restart?

**Comment by PKEv** [comment] 2015-06-06 10:53
strange what count 'message' < count 'status'

**Comment by zetok** [comment] 2015-08-29 23:14
Duplicate of #1098, closing.

**Closed as completed by zetok** 2015-08-29 23:14 UTC
Labels: C-bug, U-low
