### ISSUE TITLE
Arabic characters invisible when sent

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3165] opened 2016-04-20 20:31 UTC
If one sends Arabic characters they appear to be invisible, for instance if I send (no idea if this means anything, I don't speak Arabic) `سش` it will look like this once it is sent though I can see it in the message box where I type (to avoid confusion the name of the test account I am being sent these messages from is called `panda`):

![arabic_characters_invisible_in_qtox](https://cloud.githubusercontent.com/assets/11575271/14689382/f4a87aec-073e-11e6-97da-d73ae697879c.png)

It is rather strange though because if I right-click on the message and click `Copy` the following is copied to the clipboard:

```
[21:26:53] panda: سش
```

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and `qtox` version `1.3.0-221-ged9ccbe-1`.

**Comment by sudden6** [comment] 2016-04-20 21:26
To add some info:

the above mentioned text doesn't show for me too, however if I enter a much longer text like `سشسشسشسشسشسشسشسشسشسشسشسشسشسشسشسشسشسشسشسش` a part of it (or the whole? can't tell) becomes visible.

I suspect this is some layout issue, where the date/time on the right overlaps the chatmessage somehow. This can be reproduced with sending the messages to groupbot.

System: openSUSE 42.1, https://github.com/tux3/qTox/commit/01c56a3af6338394c1b0f200c88c20d696b37994 and Qt 5.5.1

**Comment by zetok** [comment] 2016-04-21 05:28
~~Duplicate of #3165, thus closing.~~

Edit: look below

**Closed as completed by zetok** 2016-04-21 05:28 UTC
Labels: C-bug, U-low, M-ui

**Comment by ZIEXED** [comment] 2016-05-30 20:54
To work around the issue right click on chat textbox and choose "Insert Unicode control character >LRM Left-to-right mark"
But you have to do that every time before you start typing
If you need more information I will try to help as much as I can.

**Comment by ZIEXED** [comment] 2016-05-30 21:00
This affects all "right to left" languages
heighten the priority please

**Comment by ZIEXED** [comment] 2016-05-30 21:08
You closed the both of them
open this again

**Comment by zetok** [comment] 2016-05-30 21:25
Uh, sorry, copypasted the wrong issue number, it's a duplicate of #1887
