### ISSUE TITLE
Doesn't change language completely

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2098] opened 2015-08-22 15:40 UTC
Hello,

small bug reports:

---
1. Go to the Tox settings and change the language
2. Switch to the 'Advanced' tab
3. The chat history settings (database) aren't translated completely

Screenshot: 
![xquy766](https://cloud.githubusercontent.com/assets/2544251/9502504/a201edee-4c29-11e5-8dff-e804a9d02c80.png)

---

Same issue with Tox settings > 'General' > 'Date Format' for example 

---
1. File transfer in conversation (Language: German):
   ![index](https://cloud.githubusercontent.com/assets/8258609/9519883/06364f96-4cc3-11e5-9897-d2a54ee11569.png)
2. Change language to, for example, English
3. Language didn't change for file transfer:
   ![index](https://cloud.githubusercontent.com/assets/8258609/9519883/06364f96-4cc3-11e5-9897-d2a54ee11569.png)

Only for the **next** file transfer in the chat the language is changed to English. So, there is no equality.
Language should change completely.

**Comment by ovalseven8** [comment] 2015-08-26 10:55
Same issue with Tox settings > 'General' > 'Date Format' for example

**Comment by suhr** [comment] 2015-08-26 13:30
It's the german translation issue actually (except data format).

**Comment by zetok** [comment] 2015-08-26 16:23
@suhr not quite, at least not with what first comment is about. Change of those strings requires qTox restart, as opposed to rest strings in qTox, which change right after setting change.

Edit: and date is too affected by it.

**Comment by ovalseven8** [comment] 2015-08-27 11:26
Next issue:
1. File transfer in conversation -> https://i.imgur.com/mFLEUZh.png (Language: German)
2. Change language to, for example, English
3. Language didn't change for file transfer -> https://i.imgur.com/mFLEUZh.png

Only for the **next** file transfer in the chat the language is changed to English. So, there is no equality. 
Language should change completely.

**Comment by agilob** [comment] 2015-08-27 11:37
edit you comment and upload images to github.

**Comment by ovalseven8** [comment] 2015-08-27 11:42
> edit you comment and upload images to github.

Done. :wink:

**Comment by zetok** [comment] 2015-08-29 22:23
Closing, since it's a duplicate of #1695.

**Closed as completed by zetok** 2015-08-29 22:23 UTC
Labels: C-bug, U-low, P-low
