### ISSUE TITLE
copy the link to clipboard form the message body

### ISSUE THREAD

**Issue by shalnoff** [qTox/qTox#2610] opened 2015-12-01 14:31 UTC
It would be great to implement Copy Link function in context menu opening on Right Mouse Button click. 

Currently user needs to select the whole link that is tricky to do whereas it always selecting the whole message. 

PS Thank you for great product!

**Comment by zetok** [comment] 2015-12-01 14:39
Duplicate of #1236, thus closing.

**Closed as completed by zetok** 2015-12-01 14:39 UTC
Labels: U-low
