### ISSUE TITLE
Rejoining groupchat bug

### ISSUE THREAD

**Issue by Przechu** [qTox/qTox#5594] opened 2019-03-29 17:36 UTC
##### Brief Description

OS: Ubuntu 16.04.4 LTS
qTox version: Nightly
Commit hash: build without git
toxcore: 0.2.9
Qt: 5.5.1
Hardware: 
…

Reproducible: Almost Always

##### Steps to reproduce

1. A joins the group
2. A turns off qTox
3. A turns on qTox

##### Observed Behavior

After restarting qTox, the group either doesn't show or shows as Group #0 and tries to load peers successfully. If it does not show, a new group after creating is named Group #1 instead of Group #0. Invitation to the not showing group doesn't come. It seems like joined groups are stored in .tox file, but I don't know the way to leave them.

##### Expected Behavior

qTox should load the group with all its peers and name or don't load the group, but be still able to manually rejoin.

**Comment by anthonybilinski** [comment] 2019-03-29 17:42
Thanks for the report - I believe it's a duplicate of https://github.com/qTox/qTox/issues/5542.

Until https://github.com/qTox/qTox/issues/5542 is fixed, you can work around the issue by setting a name for the group, either at group creation time or after joining the group.

>It seems like joined groups are stored in .tox file, but I don't know the way to leave them.

you're right that they are still stored in toxcore. As part of fixing https://github.com/qTox/qTox/issues/5542 it will be looked into to expose the nameless groupchats in qTox UI so that they can be left.

**Closed as completed by anthonybilinski** 2019-03-29 17:42 UTC
Labels: U-low
