### ISSUE TITLE
qTox always starts maximized (Windows)

### ISSUE THREAD

**Issue by Draako** [qTox/qTox#1207] opened 2015-02-17 18:02 UTC
qTox always starts maximized, the position is not remembered and none of the options set in a shortcut (either to open in normal, minimized or maximized window) are respected.

**Comment by dubslow** [comment] 2015-02-17 20:32
Probably related to the saving bug on Windows

**Comment by davidak** [comment] 2015-02-20 13:50
also on OS X 10.9

tox starts in fullscreen mode. after ending that, it's over the whole screen, each start.

**Comment by agilob** [comment] 2015-05-11 20:19
@Draako  looking at issues [you reported](https://github.com/tux3/qTox/issues/created_by/Draako), you have a problem with privileges to read/write files. No one else reported it and they all seem to be specific only for you.

**Comment by tux3** [comment] 2015-05-11 20:20
This is actually a dupe of the settings saving bug, closing since the unrelated title and dup is not helpful in tracking this issue.

**Closed as completed by tux3** 2015-05-11 20:20 UTC
Labels: C-bug, U-low
