### ISSUE TITLE
DESKTOP_NOTIFICATIONS: snorenotify is unmaintainer, KNotifications should be used instead

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6278] opened 2020-12-27 19:37 UTC
The cmake option ```DESKTOP_NOTIFICATIONS``` uses ```snorenotify``` but their website says that it is unmaintained, and that ```KNotifications``` should be used instead.

https://github.com/KDE/snorenotify

FreeBSD is going to remove ```snorenotify```: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252217

**Comment by swills** [comment] 2020-12-27 20:01
Duplicate of #6238

**Comment by sudden6** [comment] 2020-12-27 21:39
Closing as duplicate

**Closed as completed by sudden6** 2020-12-27 21:39 UTC
