### ISSUE TITLE
Can one change the qTox call ring?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2938] opened 2016-02-08 13:39 UTC
When someone calls me on qTox is makes a ringing sound, when is the sound file for this stored and how can I change the ring? Is there just a sound file a can replace or something? Or is it not that simple? I am running Ubuntu GNOME 15.10 with GNOME 3.18 and qTox version `1.2-348-geb6082d-1`.

**Comment by sudden6** [comment] 2016-02-08 20:02
There is this project for sound files https://github.com/Tox/Sounds but qTox currently does not implement these.

**Comment by Getron** [comment] 2016-05-16 23:46
+1

**Comment by zetok** [comment] 2016-05-17 06:20
Duplicate of #2440, thus closing.

**Closed as completed by zetok** 2016-05-17 06:20 UTC
Labels: U-low, proposal, M-audio

**Comment by ProMcTagonist** [comment] 2016-05-17 18:03
Can we add to the dup count on that issue to show demand if we're still doing that?

**Comment by zetok** [comment] 2016-05-17 18:13
Oh, right, added it. Thanks for reminder.
