### ISSUE TITLE
qTox Group chats: saving history log.

### ISSUE THREAD

**Issue by TerminalHash** [qTox/qTox#6127] opened 2020-05-02 13:01 UTC
Hello!
When will there finally be a normal saving and loading of group chat history? The fact that their work is repaired is, of course, good, but still I would like to be fully working.

**Comment by TerminalHash** [comment] 2020-05-02 13:02
When you start the client, I note.

**Comment by anthonybilinski** [comment] 2020-05-02 19:59
#5452 is tracking group history. #5454 was created to start adding it, but is old and out of date. Finishing group history is planned for the next minor release of qTox: https://github.com/qTox/qTox/milestone/25 which is planned for September.

I'll close this issue since it's a duplicate of #5452.

**Closed as completed by anthonybilinski** 2020-05-02 19:59 UTC
