### ISSUE TITLE
Internal qTox's updater does not work

### ISSUE THREAD

**Issue by uxname** [qTox/qTox#2592] opened 2015-11-26 09:15 UTC
Internal qTox's updater just does not work.
I propose a simple script updates for Windows (**save to *.vbs and put it to qtox.exe folder**)

---

> ```
> Dim WshShell
> Set WshShell = WScript.CreateObject("WScript.Shell")
> 
> Set obj = CreateObject("Scripting.FileSystemObject") 
> if obj.FileExists("qtox.exe") then obj.DeleteFile("qtox.exe")
> 
> InetFile = "https://build.tox.chat/view/Clients/job/qTox_build_windows_x86_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86_release.zip"
> localFile = WshShell.CurrentDirectory + "\update.zip"
> 
> Set oXMLHTTP = CreateObject("MSXML2.XMLHTTP")
> oXMLHTTP.Open "GET", InetFile, 0
> oXMLHTTP.Send
> 
> Set oADOStream = CreateObject("ADODB.Stream")
> oADOStream.Mode = 3
> oADOStream.Type = 1
> oADOStream.Open
> oADOStream.Write oXMLHTTP.responseBody
> 
> oADOStream.SaveToFile localFile, 2
> 
> Set oXMLHTTP = Nothing
> Set oADOStream = Nothing
> 
> Set ShellApp = CreateObject("Shell.Application")
> Set objDestFolder = ShellApp.NameSpace(WshShell.CurrentDirectory)
> Set objSrcFolder = ShellApp.NameSpace(WshShell.CurrentDirectory + "\update.zip")
> objDestFolder.CopyHere objSrcFolder.Items
> 
> if obj.FileExists("update.zip") then obj.DeleteFile("update.zip")
> ```

**Comment by rugk** [comment] 2015-11-29 18:08
Duplicate of https://github.com/tux3/qTox/issues/2389

**Comment by tux3** [comment] 2015-12-04 19:38
The vbs script is an interesting idea, but it'll be more secure to fix the qTox updater.

**Closed as completed** 2015-12-04 19:37 UTC
Labels: C-bug, U-low, OS-windows
