### ISSUE TITLE
Add a way to renice qTox

### ISSUE THREAD

**Issue by d33tah** [qTox/qTox#1857] opened 2015-06-12 01:06 UTC
On my netbook, I can see that qTox has reproducible freezes when I am fully using my CPU. The freezes stopped when I killed the offending process. This made me think that perhaps qTox wouldn't be affected if it had a higher priority... What do you think of an option that makes qTox run something like `sudo renice -19 `cat /proc/self/stat | cut -f1 -d' '``(or gksu/kdesu) on startup or use any other Linux feature (like``CAP_SYS_NICE`` and an appropriate steps during installation) to achieve the same goal?

**Comment by zetok** [comment] 2015-06-12 06:34
@d33tah no. That's a workaround, not an actual solution. A shitty one at that if you only “think” that it would help…

If it's reproducible, could you please post more info, so that issue could be fixed, rather than proposing workarounds? → https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by tux3** [comment] 2015-06-12 10:51
If something freezes, the freeze should be fixed. Renicing isn't a solution.

**Comment by d33tah** [comment] 2015-06-12 11:12
Why is it not? Generally, Tox is more sensitive to spikes in CPU resource usage and a way to tell that to the system is by requesting a higher priority.

**Comment by tux3** [comment] 2015-06-12 11:15
A higher priority will not fix CPU spikes, it'll just schedule qTox more often.

**Comment by d33tah** [comment] 2015-06-12 12:00
...which might result in qTox getting enough cycles to do its thing with no freezes.

**Comment by tux3** [comment] 2015-06-12 16:47
This is not helpful. You might as well just buy a more expensive computer, that'll "result in qTox getting enough cycles" too.

This is a misguided attempt at a workaround, not a solution. If there is a performance problem, it needs to get fixed, not swept under the rug and worked around.

**Comment by zetok** [comment] 2015-08-29 23:38
Closing, since there rather than workaround qTox needs to fix whatever performance problems it has.

When there are performance problems, please report them.

**Closed as completed by zetok** 2015-08-29 23:38 UTC
Labels: proposal
