### ISSUE TITLE
Segmentation fault after login

### ISSUE THREAD

**Issue by qtox-user-2018** [qTox/qTox#4698] opened 2017-09-28 15:25 UTC
##### Brief Description

OS: Debian GNU/Linux 9 64-bit, KDE Plasma 5.8.6
qTox version: qTox-1.11.0
toxcore:  0.1.10 (also tried with 0.1.2)
Qt:  5.7.1

Reproducible: Always

##### Steps to reproduce
(manual builded)
1. compile toxcore
2. compile qtox
3. start qtox
4. Enter in qtox login window authentication login and password (or create new one, newer mind)
5. Press "Load" button.
6. Now it crushed, in terminal:

myname@dpc:~/programs/qTox/sources/qTox-1.11.0/build$ ./qtox
[15:11:40.999 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/myname/.config/tox/qtox.ini"
[15:11:41.023 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  13964150928264007609
[15:11:41.023 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[15:11:41.023 UTC] ipc.cpp:251 : Debug: Previous owner timed out, taking ownership 13260341140724697041 -> 13964150928264007609
[15:11:41.023 UTC] main.cpp:234 : Debug: built on:  17:44:16 Sep 28 2017 ( 1506609615 )
[15:11:41.023 UTC] main.cpp:235 : Debug: commit:  build without git 

[15:11:41.024 UTC] nexus.cpp:90 : Debug: Starting up
[15:12:49.643 UTC] persistence/profile.cpp:110 : Debug: Loading tox save  "/home/myname/.config/tox/tester.tox"
[15:12:49.722 UTC] persistence/settings.cpp:451 : Debug: "Saving global settings at /home/myname/.config/tox/qtox.ini"
[15:12:49.732 UTC] persistence/settings.cpp:325 : Debug: Loading personal settings from "/home/myname/.config/tox/tester.ini"
[15:12:49.788 UTC] :0 : Warning: QObject::connect: invalid null parameter
[15:12:50.457 UTC] :0 : Warning:   OpenType support missing for script 16
[15:12:50.497 UTC] :0 : Warning:   OpenType support missing for script 16
[15:12:50.608 UTC] core/core.cpp:264 : Debug: Loading user profile
[15:12:50.608 UTC] core/core.cpp:128 : Debug: Core starting with IPv6 enabled
[15:12:50.700 UTC] persistence/profile.cpp:75 : Debug: Self avatar not found, will broadcast empty avatar to friends
Segmentation fault

I have tried to reinstall libsqlcipher-dev (my version is 3.2.0-2), it does not help.
In Debian 8.0 (Jessie) everything was fine. After upgrade to Debian 9.0 (Stretch) qtox fails with seg. fault.

**Comment by sudden6** [comment] 2017-09-28 16:49
Duplicate of #4054

**Closed as completed by sudden6** 2017-09-28 16:49 UTC
