### ISSUE TITLE
Ringtone should be cut off instantly if call is rejected or cancelled on either side

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1250] opened 2015-02-22 02:00 UTC
Right now it sometimes seems like the interface just failed.

**Comment by dubslow** [comment] 2015-02-23 18:31
It's a super crappy oneshot ring that finishes it's ring always. We need one that is indeed tied to the actual calling process, be that lasting as long as necessary or cutting off prematurely as required.

**Comment by zetok** [comment] 2015-08-26 09:03
Possibly may affect: #2094 
Would need to be re-tested after this PR gets merged.

**Comment by zetok** [comment] 2015-10-22 07:14
Ok, now the sound is being cut off instantly when accepting call, but still isn't cut-off instantly when rejecting the call.

**Comment by tux3** [comment] 2015-10-24 01:13
This is fixed by the new AV PR #2456

**Comment by zetok** [comment] 2015-11-06 08:19
Since it should be fixed now, closing.

If you can still reproduce it on new AV, please comment for reopen.

**Closed as completed by zetok** 2015-11-06 08:19 UTC
Labels: C-bug, proposal, P-low, M-ui, M-audio
