### ISSUE TITLE
Add a Tox ID view to the contact list

### ISSUE THREAD

**Issue by torvn77** [qTox/qTox#4681] opened 2017-09-23 10:55 UTC
Translate: Please add to the contact list the ability to view and copy the Tox ID of the people and groups recorded in it, and then neither the contact to share, nor the invitation to the group is not forwarded, and to understand with whom and how it was not possible to rename it.
Call me: 1A8FC6C4B369A6EDE12256CC5A7A885C769AEA4DAF857B234B1F6F7AB7C4A856EDEDFF67CD0B
Original text:Добавте пожалуйста в контакт лист возможность просматривать и копировать Tox ID записанных в него людей и групп, а то ни контактом поделиться, ни приглашения в группу не переслать, да и разобраться с тем, кого и как переименовал не возможно.

**Comment by sudden6** [comment] 2017-09-23 11:30
I don't really understand the translation, @Diadlo or @noavarice can you understand the original?

**Comment by torvn77** [comment] 2017-09-23 11:57
Copy "Toh ID" of a person or group >> Paste into text email, text file or send to a friend >> A friend adds "Tox ID" to their contact list.

**Comment by torvn77** [comment] 2017-09-23 12:00
Rename John in the Bee-Be-Be >> Who is this Bee-Be-Be? >> View Tox ID >> Be-Be-Be It's John!

**Comment by Diadlo** [comment] 2017-09-23 12:55
@torvn77 You can't get the ToxID of existing contact or group member. See #951

**Comment by torvn77** [comment] 2017-09-23 16:59
@Diadlo
Translate:
Found "Show details", thank you.
Can you do the same for the group so that you can send out invitations?
Original text:
Нашёл "Show detals", спасибо.
Можно сделать тоже самое и для группы, чтобы можно было рассылать приглашения?

**Comment by Diadlo** [comment] 2017-09-23 19:02
@torvn77 AFAIK, it is possible to implement getting public key(PK) (it's what you can see in "show details") in group chat, but not ToxID. This is feature of current protocol implementation. ToxId contains changable "nospam" part -> you can change ToxId and save PK.

**Comment by torvn77** [comment] 2017-09-23 19:33
In general, I need an identifier to invite people to a group chat, and that it will not matter.
The main thing is that people, including missing in my contact list could enter the group chat.

В общем мне надо индентификатор для приглашения людей в групповой чат, а что именно это будет не важно.
Главное чтобы люди, в том числе отсутствующие в моём контакт листе могли войти в групповой чат.

**Comment by sudden6** [comment] 2017-09-23 20:04
@torvn77 inviting people to groupchats without them being in your contact list is not possible with the current Tox protocol. You can open a bug in Toktok/c-toxcore about this, but I don't think this will change anytime soon.

**Comment by torvn77** [comment] 2017-09-23 20:54
Diablo told me about the corresponding issue in c-toxcore
https://github.com/TokTok/c-toxcore/issues/568

Мне Diablo сейчас рассказал про соответствующее issue в c-toxcore

**Comment by shalnoff** [comment] 2017-11-07 18:34
Confirmed. 
It is currently impossible to see IDs of contacts in the list. E.g. if you would like to pass ID to someone  else or move to another device, it's just no way to to copy and paste it. User have to request it again.  Please implement it. Highly required feature.

**Comment by sudden6** [comment] 2017-11-07 20:46
@shalnoff the statement in https://github.com/qTox/qTox/issues/4681#issuecomment-331632274 is still true

**Comment by devurandom** [comment] 2018-09-30 18:39
Is this a duplicate of #3405?

**Comment by sudden6** [comment] 2018-09-30 18:52
Yes, in a sense a duplicate of #3405

**Closed as completed by sudden6** 2018-09-30 18:52 UTC
Labels: upstream, M-ui
