### ISSUE TITLE
qtox: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by qtox)

### ISSUE THREAD

**Issue by clickworkorange** [qTox/qTox#3481] opened 2016-07-06 09:14 UTC
##### Brief Description

OS: Ubuntu 14.04 64-bit
qTox version: 691-a01293f

Reproducible: Always
##### Steps to reproduce
1. Run "qtox" from command line
##### Observed Behavior

Recieve error message: qtox: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by qtox)
##### Expected Behavior

qTox should start normally.

This suddenly started happening after running an apt-get upgrade.

**Comment by zetok** [comment] 2016-07-06 09:28
Duplicate of #3358, thus closing.

Use the right repo.

**Closed as completed by zetok** 2016-07-06 09:28 UTC
Labels: U-low
