### ISSUE TITLE
display a date notification if a chat continues on another day

### ISSUE THREAD

**Issue by NoxNoctium** [qTox/qTox#1401] opened 2015-03-15 21:40 UTC
Currently, qTox only displays date information in the chatlog for already saved messages, if you continue a chat with a person on another day this behaviour could lead to confusion (see pictures below)
![image](https://cloud.githubusercontent.com/assets/2098025/6658229/fa348fdc-cb62-11e4-879c-2bd33d3646dd.png)
in this case, the datechange is visible because of the overlapping times.
![image](https://cloud.githubusercontent.com/assets/2098025/6658264/caff0f0c-cb63-11e4-8f3b-35fddebf5c07.png)
didn't manage to capture a direct comparison of the problem here, originally the date information wasn't displayed, only after a reload of the application (this is how it should look in any case).

**Comment by zetok** [comment] 2015-03-15 21:56
Description:
When qTox is turned on across multiple days, there is no indicator in chatlog about new day, which is confusing.

"Notification" is visible if chat history is loaded upon fresh qTox start.

Reproducible: Always

Steps to reproduce:
1. Turn qTox on and message your contact
2. Wait for next day without turning qTox off
3. Message your contact again
4. there is no indicator of different day in chatlog

Edit: um, to be clear; "Notification" shouldn't appear on every new day, but rather only when there's a message on new day

**Comment by TheLastProject** [comment] 2015-03-25 17:36
Could this please get the bug label? Date changes not always being displayed is something I very much consider a bug because it really makes it confusing to tell if messages were sent/received on the same day or not.

**Comment by zetok** [comment] 2015-08-26 17:03
When #2013 gets merged this should be closable.

**Comment by zetok** [comment] 2016-04-23 03:31
Related: #687

**Comment by zetok** [comment] 2016-04-26 04:48
Done in #3181, thus closing.

**Closed as completed by zetok** 2016-04-26 04:48 UTC
Labels: C-bug, U-low, P-low, proposal-accepted
