### ISSUE TITLE
Blank username after deletion from contact list

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2229] opened 2015-09-14 09:28 UTC
Hello,

Alice and Bob are friends in Tox.

Because of reasons, Alice removes Bob from her contact list.

The Tox FAQ says about this:

> **What happens when I remove someone?**
> 
> If you remove someone, they will see you go offline, as if you closed client normally. They can't communicate with you any longer until you add them to your friend list again.

What happened to me:
In Bob's contact list Alice's name is blank now. So, Bob can suppose that he was removed from Alice's contact list.

Desired behaviour:
In Bob's contact list will be the last name Alice used.

Commit hash: 346c2c64db811dec7ffdd21e0152e65733204533

**Comment by suhr** [comment] 2015-09-14 10:27
Duplicate of https://github.com/tux3/qTox/issues/1967.

**Comment by ovalseven8** [comment] 2015-09-14 10:38
Oh, didn't see. Thanks.

**Closed as completed** 2015-09-14 10:39 UTC
Labels: U-low
