### ISSUE TITLE
qTox Portable mode

### ISSUE THREAD

**Issue by hk1mm2** [qTox/qTox#1883] opened 2015-06-17 23:20 UTC
Hi...
It seems that qTox is unable to work as portable mode, it create files under windows user folder : Any information about this ??

Thank you.

**Comment by fcore117** [comment] 2015-06-29 19:06
i can confirm, portable is not working.

**Comment by lovetox** [comment] 2015-07-03 18:14
have the same problem, if i check "Make Portable", nothing happens, at the next start all settings are gone and it takes it again from the local app data folder

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-08-24 23:44
i fixed this by moving my identity files from %APPDATA%/tox/ to the /bin/ directory of qTox (there were already duplicates of my identity in there from previous attempts to make portable)
(make sure makeToxPortable=true is set in your qtox.ini)

and then delete everything in the %APPDATA%/tox/ folder
create an empty qtox.ini in that folder with just this text:

[%General]
makeToxPortable=true

that works for me. i think it reads the %APPDATA%/tox/qtox.ini first and realises that its portable, and then goes back to the /bin/ directory and opens ur other files

**Comment by uxname** [comment] 2015-08-31 08:12
Agree, "Make Portable" just copies profile to current ( ./ ) folder, but  next start uses ( C:\Users\username\AppData\Roaming\tox )

**Comment by smaragdus** [comment] 2015-09-05 04:24
The last qTox build which worked fine in portable mode was the one from 2015.03.14.
I hope portability will be restored soon since it is essential for me.

**Comment by tux3** [comment] 2015-09-05 17:05
We're looking into this issue.

**Comment by smaragdus** [comment] 2015-09-05 17:33
Great news!
It is frustrating for those who use qTox on multiple machines. There is a workaround to copy the app data folder on new machines but this is not very convenient for ordinary users. In winter I began to try to convince friends of mine to dump Skype in favour of qTox and portability was one of the major pros since I explained to them that they just need to copy the qTox folder (to external flash drive, online, etc) and run it from wherever they want. When qTox portability was lost this became a problem since they were forced to keep a very old version of qTox from March.
Since Tox is decentralized and serverless in my opinion portability is an extremely important feature. I would also suggest that qTox would ask whether to save settings on first run (the users should be able to choose between normal and portable mode when they first start it). In fact when I first discovered Tox programs I chose qTox because it offered portable mode, in contrast with uTox, which didn't.
If any tests are needed I can do some testing on Windows 8 x64.
Regards

**Comment by fcore117** [comment] 2015-09-05 17:53
Portable option should work cross platform too.

smaragdus: uTox has way to launch in portable mode, i use this every day.
Windows:
1: create portable.cmd
2: add this inside portable.cmd:
 "utox.exe --portable" OR "utox.exe --portable --theme dark" if you want dark theme(withut "" of course)
Linux:
1: create portable.sh emty file
2: add this inside portable.sh:
#!/bin/sh
SCRIPTDIR="$(dirname "$0")"
"$SCRIPTDIR/utox" --portable
3: make portable.sh as executeable from properties.

**Comment by zetok** [comment] 2015-09-24 10:02
Closing, since issue about profile & settings not being affected by `Portable` mode was fixed.

Separate issue about avatars not being carried over: #2288.

@fcore117 Could you please open a separate issue for your proposal regarding cli switch?

**Closed as completed by zetok** 2015-09-24 10:02 UTC
Labels: C-bug, U-low, P-medium
