### ISSUE TITLE
Font size in qTox ?

### ISSUE THREAD

**Issue by darkman088** [qTox/qTox#1166] opened 2015-02-15 15:29 UTC
Hello,

uTox has the possibility to basically zoom the entire application by 150% and by 200%, if I am not wrong... As I am now more and more trying to completely switch to qTox, I didn't see this feature there. Is it really not implemented yet, or I didn't see it in the settings ?

Many thanks for the answers!

**Comment by TheLastProject** [comment] 2015-02-15 15:48
On that note, I would like to suggest changing "Emoticon Size" to "Font size" and scaling them both at the same moment.

**Comment by zetok** [comment] 2015-02-16 07:51
@TheLastProject that's not the best idea. People may want to have differently sized emoticons and text.

@darkman088 isn't this issue a duplicate?

**Comment by TheLastProject** [comment] 2015-02-16 12:07
@zetok I fail to see a sane use case for different sizes of emoticons and text. It also gives an unprofessional look when they are not equal, because the spacing will be more or less depending on if a message contains an emoticon.

**Comment by d4ndo** [comment] 2015-02-17 14:22
Dont forget the shortcut.
Ctrl +/- and Ctrl mousewheel.

**Comment by zetok** [comment] 2015-02-17 19:57
@TheLastProject maybe it's just me, but I can't see details of those small emoticons well (they all look ~the same), while I can easily read text. I like big, detailed emoticons while I can keep text sufficiently small for my needs.

Looking unprofessional… it kinda misses a point when things like (AFAIK) fb have differently sized text and emoticons. Not to mention that no one forces people to have them sized differently - it's up to user to decide (if they want to do this in the first place) what size their text and emotocons should be.

**Comment by darkman088** [comment] 2015-03-02 21:15
Hello,

I think as well, that text and emotions have to be the same size. Otherwise it simply gets ugly !! The world is FULL of ugly software!! qTox is currently at the VERY nice side, so I simply suggest to stay there...

**Comment by zetok** [comment] 2015-03-03 18:41
@darkman088 what stops you from setting it to the same size?

**Comment by darkman088** [comment] 2015-03-08 12:50
Nothing  stops me from doing so.Currently,the blocking point is that I am unable to change the text size. Please kindly let me know for when is adding this feature planned ? Thanks!

**Comment by tritium21** [comment] 2015-06-27 07:48
Is this a priority?  as it stands I have to use windows magnifier

**Comment by agilob** [comment] 2015-06-27 16:45
Currently font size is hardcoded.  #1882 muse be done first, then font size could be change by style, unfortunately no one know how to finish it :<

**Comment by tritium21** [comment] 2015-06-27 21:46
How do you build a chat app with a hard coded font size?  How is that even a thought that goes through your head?

**Comment by agilob** [comment] 2015-06-28 09:51
@krepa098 did, he wrote chat area with hardcoded font, font size, colours, font colours, background... and everything else. Chat area was designed to have max. performance. Currently it doesn't even support CSS or HTML rendering, my branch puts effort in changing it without losing performance.

**Comment by darkman088** [comment] 2015-07-07 15:28
Good, keep the good work going, Agilob, and please kindly keep us up to date :-)

**Comment by agilob** [comment] 2015-07-07 15:39
last commit in https://github.com/tux3/qTox/pull/1882 b97a23a allows changing font by css.

**Comment by darkman088** [comment] 2015-07-13 21:03
Hi agilob!

please kindly enlighten the poor admin, who has no idea about programming :-D Does it mean that it's done ? B-) Thank you!

**Comment by agilob** [comment] 2015-07-13 22:18
In my branch yes. Font can be changed by css (internal or external).

**Comment by ProMcTagonist** [comment] 2015-07-13 23:55
We just have to wait for @agilob's branch to be merged into main, then it will work when you update, @darkman088

**Comment by quininer** [comment] 2015-07-14 01:40
@agilob 
I compiled your themess branch, it looks nice. But how to edit CSS file?

**Comment by zetok** [comment] 2015-07-14 07:17
> I compiled your themess branch, it looks nice. But how to edit CSS file?

In a text editor..

What @agilob meant by font size being changeable through CSS, is that previously you had to edit C++ source to change it, and now it's allegedly easier, since you have to change it only in CSS…

In other words, @agilob's changes still don't allow font size being changeable by users. Unless you care to make your own CSS theme for qTox…

**Comment by quininer** [comment] 2015-07-14 07:24
@zetok 
I thought it would support the dynamic modification CSS ... after all, no one wanted to debug multiple compilations theme qTox.

**Comment by zetok** [comment] 2015-07-14 13:07
@quininer 

> Font can be changed by css (internal or external).

From what I understand, you are supposed to be able to use external CSS for qTox's theme, so that you wouldn't have to recompile.

With that being said, editing CSS is not something that users would do…

**Comment by quininer** [comment] 2015-07-14 13:23
so, How edit CSS on external?

**Comment by agilob** [comment] 2015-07-14 17:21
> I thought it would support the dynamic modification CSS 

Can be done in ~20minutes after that branch in merged and code tested.

@quininer do you know css? do you have any idea how to design qtox ui? If you do, please improve that design and we will be able to merge it. You need qtcreator, the file(s) to edit is under res/ui/css/ wombat/light/darkblue. Currently after every change in css you must relink project, it takes less than 2seconds on my laptop.

**Comment by quininer** [comment] 2015-07-15 01:46
@agilob 
If you can dynamically modify the CSS, qTox will likely have a lot of third-party themes. :D

**Comment by zetok** [comment] 2015-08-21 07:12
duplicate of #672, closing.

**Closed as completed by zetok** 2015-08-21 07:12 UTC
Labels: U-low, proposal
