### ISSUE TITLE
Unlock the file if the upload/download failed, so user can delete it. Also, add "retry" button for upload action.

### ISSUE THREAD

**Issue by newnym** [qTox/qTox#3355] opened 2016-06-06 08:58 UTC
You are using qTox version v1.4.0-101-g2cd35e1.
Commit hash: 2cd35e17360dd1a9b66f0eb5d0ed163c1903895b
toxcore version: 0.0.0 Qt version: 5.5.1
W7 x64
1. Open contact chat window.
2. Drag-n-drop files.
3. qTox failed to upload big file(receiver side's qTox show downloads in "red square".)
   4.

Expected:
Sender can terminate or retry uploading by pressing the "retry" button or something.
Receiver can terminate downloading.

Actual result:
qTox "lock" the file.
User on both sides can't delete it. (below is windows error dialog)

---

Folder in use

The action can't be...
Close the folder and try again

Send-this-file.zip

Try Again / Skip / Cancel

**Comment by sudden6** [comment] 2016-06-07 19:12
You are right, qTox should unlock files on failed transfers. In the meantime you can close qTox and the file can be deleted.

Adding a retry button would be a good idea.

**Comment by zetok** [comment] 2016-06-14 18:36
> Adding a retry button would be a good idea.

Wouldn't it be just a workaround to the support for resuming file transfers?

**Comment by zetok** [comment] 2016-07-30 20:16
Duplicate of #2555, thus closing.

**Closed as completed by zetok** 2016-07-30 20:16 UTC
Labels: C-bug, U-low, multiple-in-one
