### ISSUE TITLE
No sound from mic when not on Audio/Video settings tab

### ISSUE THREAD

**Issue by nazar-pc** [qTox/qTox#3760] opened 2016-09-30 17:29 UTC
##### Brief Description

OS: Ubuntu 16.10
qTox version: v1.5.1-obs
Commit hash: f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore: 0.0.0
Qt: 5.6.1
Hardware: USB sound card

Reproducible: Always
##### Steps to reproduce
1. Call someone / receive call from someone
2. Stay in chat window
3. Go to Audio/Video settings (do not change anything, just open tab)
##### Observed Behavior

Someone from 1 can hear me in 3, but not in 2
##### Expected Behavior

Someone from 1 can hear me all the time
##### Additional Info

I have USB sound card, configured in the same way system-wide and in qTox settings

[qtox.log.zip](https://github.com/qTox/qTox/files/503476/qtox.log.zip)

**Comment by zetok** [comment] 2016-09-30 17:52
Duplicate of #3538, thus closing.

**Closed as completed by zetok** 2016-09-30 17:52 UTC
Labels: U-low
