### ISSUE TITLE
The "multi-window" branch merge made qtox look ugly for new users (strange default values)

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2240] opened 2015-09-15 22:55 UTC
This is how it looks like when you start it the first time:
![das](https://cloud.githubusercontent.com/assets/6986141/9892282/a45a7144-5c0d-11e5-95c5-561ea888a8c1.jpg)

**Comment by zetok** [comment] 2015-09-16 03:17
Could reproduce.

**Comment by PKEv** [comment] 2015-09-18 13:16
duplicate #2228

**Comment by zetok** [comment] 2015-09-18 14:39
Since it's a duplicate, closing.

**Closed as completed by zetok** 2015-09-18 14:39 UTC
Labels: C-bug, U-low, P-low, M-ui
