### ISSUE TITLE
problem opening files with spaces

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2176] opened 2015-09-04 19:42 UTC
if I get a file "Screenshot from today.png" it transfers fine, bit I cannot open it. Clicking on the chekc mark or on the image itself opens the browser with three tabs: one for Screenshot, one for for and one for today.png.
OS: Linux

**Comment by zetok** [comment] 2015-09-05 10:08
I couldn't reproduce.
It sounds like it's a problem with wrongly associated `file:///` links on your system.

With that being said, #2150 reworks opening directory / files from file transfers, so it would be good if you could re-test after it gets merged.

**Comment by agilob** [comment] 2015-09-05 10:15
I also can't reproduce it, even on master.

**Comment by zetok** [comment] 2015-09-05 17:40
@aaannndddyyy since #2150 got merged, could you test new version?

**Comment by aaannndddyyy** [comment] 2015-09-05 19:18
I just tried with the binary from your website. Still same problem. 
"file:///home/andy/Downloads/from" in Firefox, and also "file:///home/andy/Downloads/18:13:12.png" and "file:///home/andy/Downloads/Screenshot"

**Comment by zetok** [comment] 2016-03-01 19:47
Closing, since it looks like a problem with your system configuration, and not qTox. I.e. there's nothing that qTox can or should do about broken system.

If you are able to reproduce it on a ~clean install of distro of your choice, please comment for reopen.

**Closed as completed by zetok** 2016-03-01 19:47 UTC
Labels: C-bug, OS-linux, O-need-info
