### ISSUE TITLE
Difference between sent and received message

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2899] opened 2016-01-31 09:08 UTC
Hello,

Reproduce:
1. Start two qTox instances
2. Make friends
3. Send the following message to the other instance:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor vel eros vitae tempus. Curabitur a ex tempor, rhoncus leo nec, congue mauris. Donec sed erat et massa tristique tempus eu a dolor. Nam rutrum in orci vel ornare. Vestibulum vitae metus sed erat eleifend rhoncus eu nec purus. Nulla sodales aliquam porta. Aenean neque tellus, ornare vel justo in, tincidunt blandit ex. Duis in ultrices nibh. Cras quis purus mauris. Fusce et consectetur diam. In eu metus libero. Sed dictum consequat libero. Curabitur metus elit, dapibus vitae lectus nec, condimentum auctor orci.

Donec fringilla consequat eros ac tincidunt. Sed facilisis euismod ultrices. Morbi eget finibus arcu. Nulla dui turpis, lobortis id nunc non, efficitur sagittis nulla. Donec sed finibus sem. Aliquam tincidunt nulla odio, condimentum placerat enim facilisis eget. Vestibulum id dignissim risus. Praesent in dui convallis nulla rhoncus tempor sed non sem. Aliquam vehicula erat vitae massa pulvinar, vitae porta leo porttitor.

Maecenas tincidunt urna ligula, vitae pretium ex rhoncus ac. Fusce porta, lectus eget porttitor commodo, sapien tortor sollicitudin elit, at lacinia velit orci sit amet ex. Curabitur ullamcorper, quam in aliquam efficitur, ex elit semper dui, ac sodales libero ante et massa. Donec ac hendrerit enim. Cras lobortis velit rhoncus euismod maximus. Nullam quis ex ac mauris lobortis suscipit. Maecenas congue sem tincidunt metus pharetra, et lacinia enim tristique. Aenean et tempus odio, in tempus elit. Integer vel orci dignissim, gravida ligula vel, aliquet quam. Donec pulvinar felis vitae finibus ultricies.

Cras orci tellus, tincidunt vitae posuere pulvinar, commodo et lectus. Quisque eget lorem diam. Vivamus et lorem ut nisl convallis egestas vel ac massa. Aliquam rhoncus, odio non ultricies congue, felis nisi auctor ipsum, et aliquam nisl dolor vitae tortor. Quisque eget blandit augue, id ultrices arcu. Nam sed semper magna. Aenean eget nulla a metus posuere suscipit id at sem. Nulla tempus justo non suscipit consequat.

Sed dui massa, gravida ut fringilla in, aliquam sit amet ipsum. Etiam condimentum, risus sed posuere faucibus, mi ligula euismod elit, eu facilisis elit sapien a massa. Ut porta et neque in blandit. Suspendisse fermentum augue lectus, at placerat tortor pretium sit amet. Etiam congue neque non interdum ultrices. Sed lobortis lectus sit amet iaculis maximus. Maecenas et luctus arcu. Nunc suscipit commodo ligula, maximus aliquam nunc volutpat semper. Sed rhoncus velit sed eleifend rutrum. In hac habitasse platea dictumst.
```

On my device, the other qTox instance received the following:

```
[10:03:47] Bob: 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent porttitor vel eros vitae tempus. Curabitur a ex tempor, rhoncus leo nec, congue mauris. Donec sed erat et massa tristique tempus eu a dolor. Nam rutrum in orci vel ornare. Vestibulum vitae metus sed erat eleifend rhoncus eu nec purus. Nulla sodales aliquam porta. Aenean neque tellus, ornare vel justo in, tincidunt blandit ex. Duis in ultrices nibh. Cras quis purus mauris. Fusce et consectetur diam. In eu metus libero. Sed dictum consequat libero. Curabitur metus elit, dapibus vitae lectus nec, condimentum auctor orci.

Donec fringilla consequat eros ac tincidunt. Sed facilisis euismod ultrices. Morbi eget finibus arcu. Nulla dui turpis, lobortis id nunc non, efficitur sagittis nulla. Donec sed finibus sem. Aliquam tincidunt nulla odio, condimentum placerat enim facilisis eget. Vestibulum id dignissim risus. Praesent in dui convallis nulla rhoncus tempor sed non sem. Aliquam vehicula erat vitae massa pulvinar, vitae porta leo porttitor.

Maecenas tincidunt urna ligula, vitae pretium ex rhoncus ac. Fusce porta, lectus eget porttitor commodo, sapien tortor sollicitudin elit, at lacinia velit orci sit amet ex. Curabitur ullamcorper, quam in aliquam efficitur, ex elit semper dui, ac sodales libero ante et massa. Donec ac hendrerit enim. Cras lobortis velit rhoncus euismod maximus. Nullam 
[10:03:47] Bob: quis ex ac mauris lobortis suscipit. Maecenas congue sem tincidunt metus pharetra, et lacinia enim tristique. Aenean et tempus odio, in tempus elit. Integer vel orci dignissim, gravida ligula vel, aliquet quam. Donec pulvinar felis vitae finibus ultricies.

Cras orci tellus, tincidunt vitae posuere pulvinar, commodo et lectus. Quisque eget lorem diam. Vivamus et lorem ut nisl convallis egestas vel ac massa. Aliquam rhoncus, odio non ultricies congue, felis nisi auctor ipsum, et aliquam nisl dolor vitae tortor. Quisque eget blandit augue, id ultrices arcu. Nam sed semper magna. Aenean eget nulla a metus posuere suscipit id at sem. Nulla tempus justo non suscipit consequat.

Sed dui massa, gravida ut fringilla in, aliquam sit amet ipsum. Etiam condimentum, risus sed posuere faucibus, mi ligula euismod elit, eu facilisis elit sapien a massa. Ut porta et neque in blandit. Suspendisse fermentum augue lectus, at placerat tortor pretium sit amet. Etiam congue neque non interdum ultrices. Sed lobortis lectus sit amet iaculis maximus. Maecenas et luctus arcu. Nunc suscipit commodo ligula, maximus aliquam nunc volutpat semper. Sed rhoncus velit sed eleifend rutrum. In hac habitasse platea dictumst. 
[10:04:00] Bob: quis ex ac mauris lobortis suscipit. Maecenas congue sem tincidunt metus pharetra, et lacinia enim tristique. Aenean et tempus odio, in tempus elit. Integer vel orci dignissim, gravida ligula vel, aliquet quam. Donec pulvinar felis vitae finibus ultricies.

Cras orci tellus, tincidunt vitae posuere pulvinar, commodo et lectus. Quisque eget lorem diam. Vivamus et lorem ut nisl convallis egestas vel ac massa. Aliquam rhoncus, odio non ultricies congue, felis nisi auctor ipsum, et aliquam nisl dolor vitae tortor. Quisque eget blandit augue, id ultrices arcu. Nam sed semper magna. Aenean eget nulla a metus posuere suscipit id at sem. Nulla tempus justo non suscipit consequat.

Sed dui massa, gravida ut fringilla in, aliquam sit amet ipsum. Etiam condimentum, risus sed posuere faucibus, mi ligula euismod elit, eu facilisis elit sapien a massa. Ut porta et neque in blandit. Suspendisse fermentum augue lectus, at placerat tortor pretium sit amet. Etiam congue neque non interdum ultrices. Sed lobortis lectus sit amet iaculis maximus. Maecenas et luctus arcu. Nunc suscipit commodo ligula, maximus aliquam nunc volutpat semper. Sed rhoncus velit sed eleifend rutrum. In hac habitasse platea dictumst.
```

**Comment by TheNain38** [comment] 2016-01-31 12:02
Can't reproduce. If you received two messages, it is normal, toxcore doesn't support message splitting yet.

**Comment by zetok** [comment] 2016-01-31 16:39
@TheNain38 there are 3 messages received, not 2. And one received message is a duplicate. In other words, I could reproduce on newest qTox.

**Comment by tux3** [comment] 2016-01-31 16:47
The duplicate message is probably due to offline messaging behind a little too impatient, if we don't get a receipt in time we'll assume the message was lost and attempt to resend it.

**Comment by zetok** [comment] 2016-01-31 16:49
Yeah, probably instead of just 5s there should be 15s or 20.

**Comment by ovalseven8** [comment] 2016-01-31 18:23
> The duplicate message is probably due to offline messaging behind a little too impatient

But both Tox IDs were online?

**Comment by tux3** [comment] 2016-01-31 18:43
If toxcore guarantees that it will try resending messages as long as contacts are online and drop them immediately when they go offline, we can simplify the offline messaging by just sending things once on the rising edge of the connection status instead of retrying periodically. 
I'd need to check the toxcore implementation, because of course this isn't in the API doc.

**Comment by zetok** [comment] 2016-01-31 19:23
> If toxcore guarantees that it will try resending messages

Err, it doesn't guarantee resending - i.e. given that UDP is being used, toxcore simply sends data off, and that would be about it.

**Comment by tux3** [comment] 2016-01-31 20:48
Pretty sure toxcore implements some form of reliability of top of UDP. The details are important though.

**Comment by zetok** [comment] 2016-03-24 20:26
So, apparently with #3040 (76d8e19320d2f15aeb019f72ecaaac2d6a23feab) this issue is fixed.

My suspicion was that

> (…) which makes me realize that the root of the problem most likely lies in how qTox handles delivery confirmations for split messages

In any case.

Fix works only if both ends have it included e.g. 
cda05bb772826378594eb7dd471fd279b46c8108 ↔ cda05bb772826378594eb7dd471fd279b46c8108 will not have second message being re-sent, while 
e.g. 252c9c8fae35f0258381537fee444b5eb02a9d7c ↔ cda05bb772826378594eb7dd471fd279b46c8108 will have second message re-sent.

Thus, closing.

If the issue is still reproducible with both clients being newer than cda05bb772826378594eb7dd471fd279b46c8108, please comment for reopen.

**Closed as completed by zetok** 2016-03-24 20:26 UTC
Labels: C-bug, P-high
