### ISSUE TITLE
Use bigger fonts on Windows

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1940] opened 2015-06-29 22:04 UTC
https://impy.me/i/25e578.png

This is somewhat smaller than it should be.

**Comment by rstarkov** [comment] 2016-07-03 12:13
So this was closed as a dupe of another bug that was closed as a dupe of the font size in chat bug, which is closed because you can now increase the font size in chat.

In the meantime, the main UI looks exactly like it did in the original report, and is still far too tiny to be usable. Reopen?...

**Comment by zetok** [comment] 2016-07-03 12:57
@rstarkov um, this issue is open?

**Comment by rstarkov** [comment] 2016-07-03 21:53
@zetok D'oh! Apologies.

**Comment by zetok** [comment] 2016-11-29 12:21
~fixed with #3806, thus closing.

**Closed as completed by zetok** 2016-11-29 12:21 UTC
Labels: OS-windows, P-medium, M-ui
