### ISSUE TITLE
last release qtox lost all my chat history

### ISSUE THREAD

**Issue by call5** [qTox/qTox#1891] opened 2015-06-20 12:40 UTC
last monday i update qtox but i lost all my chat history and now i dont have some option in setting

![](https://0x0.st/xY.png)

**Comment by zetok** [comment] 2015-06-20 15:54
@call5 are you unable to load history by r-clicking in chat form and selecting ``Load chat history...`?

Edit: also, please read https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by agilob** [comment] 2015-06-20 16:09
W8, where are buttons to encrypt history?

**Comment by ProMcTagonist** [comment] 2015-06-20 16:44
History encryption is bound to profile encryption now, and profile encryption is in the profile tab.

**Comment by LittleVulpix** [comment] 2015-06-21 02:58
A friend of mine has this happen to him very often. latest qTox, encrypted profile.

His logs are full of:

[22:35:52.574] src/core/coreencryption.cpp:95 : Warning: Decryption failed
[22:35:52.575] src/persistence/db/encrypteddb.cpp:100 : Warning: pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted

He uses Win 8.1, and he has a very, very, very slow computer with an even slower disk that is usually 100% utilized due to pagefile usage. Even so, qTox should save things safely if synchronous db writing is enabled.

**Comment by zetok** [comment] 2015-06-21 18:09
@call5, @LittleVulpix was history encrypted with different password than profile?

@tux3 why history is deleted when it can't be decrypted?

**Comment by LittleVulpix** [comment] 2015-06-21 19:14
@zetok, I wasn't aware that you can set different passwords for both. No, we just set password for the profile. Sometimes the history loaded, sometimes it was all lost. No changes made inbetween those launches so...

**Comment by zetok** [comment] 2015-06-22 05:54
> Sometimes the history loaded, sometimes it was all lost. No changes made inbetween those launches so...

um, why that hasn't been reported?

**Comment by LittleVulpix** [comment] 2015-06-22 08:05
I reported it yesterday when I first found out, https://github.com/tux3/qTox/issues/1891#issuecomment-113857937 - to clarify, this is happening to my friend, not to me, and he didn't tell me until yesterday. I don't have my profile encrypted, and he showed me the issue when I teamviewed.

**Comment by call5** [comment] 2015-06-22 14:09
@zetok I have the same profile password and password history.
by right click "Load History" nothing appears

**Comment by tux3** [comment] 2015-06-22 14:19
@zetok 

> why history is deleted when it can't be decrypted?

If we can't decrypt, we normally show a dialog box asking for a password until it works or someone clicks the disable button.

The log here seems to say the history was opened and decrypted correctly at first, but then was corrupted in the middle, so there was no chance to save it.

 I haven't been able to reproduce yet so I don't know if it's a bug, a problem with the update, or a failing hard drive.

**Comment by linux-modder** [comment] 2015-06-22 14:26
@zetok  on the  latest  git build (this morning )   was  able to repro that   chat history  issue

**Comment by call5** [comment] 2015-06-22 14:29
@tux3 if you want i can make screencast and share this with you only . before i have just small popup ask me to enter my password for decrypt profil but last monday i update to new release new i have to screen to connect or create new profile. since this time i have problem with chat history

**Comment by LittleVulpix** [comment] 2015-06-22 15:17
@tux3 it's not a failing harddrive for certain.

**Comment by tux3** [comment] 2015-06-22 15:19
Okay, I'll look into it.

**Comment by vit9696** [comment] 2015-10-25 09:29
Well, I am currently experiencing this issue and can hopefully help with understanding it. For now, as a reporter.

I run OS X 10.10 and have just updated from a self-compiled build to
https://github.com/RowenStipe/qTox-OSX/releases/tag/1.0.EXPERIMENTAL.1

I have profile encryption on and DB writing is set to synced (safest). And the bug is also confirmed by the log:

[] ../qTox/src/core/coreencryption.cpp:83 : Warning: Decryption failed
[] ../qTox/src/persistence/db/encrypteddb.cpp:104 : Warning: pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted
[] :0 : Warning: QSqlQuery::value: not positioned on a valid record
[] ../qTox/src/persistence/historykeeper.cpp:149 : Debug: Struct DB updated: Added column av_hash in table aliases.
[] :0 : Warning: QSqlQuery::value: not positioned on a valid record
[] ../qTox/src/persistence/historykeeper.cpp:158 : Debug: Struct DB updated: Added column avatar in table aliases.

To reproduce the bug "easily", you need to send messages to offline contacts and quickly close qTox afterwards. Approximated steps to reproduce:
0. Login and before getting online status;
1. Start to send the messages (copy-paste something longer, ideally) to an offline contact;
2. Immediately close qTox after seeing an online icon;
3. Open tox again, you might see no history.

I suspect there to be races between some process in status change and history I/O.
Another way it may end is an empty message with your nickname you did not send.

Good luck.

**Comment by tux3** [comment] 2015-12-19 04:02
Fixed by the new SQLCipher database code in master.

**Closed as completed by tux3** 2015-12-19 04:02 UTC
Labels: C-bug, P-very-high
