### ISSUE TITLE
[Feature request] option to "Copy URL" when right clicking on a link

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1236] opened 2015-02-19 23:53 UTC
Seras t'il possible aussi que quand on fait un clique droit sur un lien dans un client tox d'avoir "copier l'url" ?
 car quand on fait clique droit sur un lien ça apparait pas

**Comment by ProMcTagonist** [comment] 2015-02-20 03:47
+1

**Comment by ArchangeGabriel** [comment] 2015-02-20 12:06
In english: is it possible to have “Copy URL” when right clicking on a link?

**Comment by Hasshu** [comment] 2016-04-26 10:27
Frankly, I'm surprised this issue is still unresolved, as it seems like a trivial feature to implement.

I, for one, use Firefox's Private Browsing mode on a regular basis, so I often have to highlight, copy, and paste links in the browser manually. Which, needless to say, isn't the most entertaining pastime.

**Comment by zetok** [comment] 2016-09-24 12:10
Actually, it's a duplicate of #927, thus closing.

**Closed as completed by zetok** 2016-09-24 12:10 UTC
Labels: U-low
