### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by Cervero** [qTox/qTox#4417] opened 2017-05-23 20:54 UTC
##### Brief Description

OS: Windows 7
qTox version: qtox64-1.9.0-104-g5d117e6
Commit hash: 5d117e6af854de194dc16575f1fe5c95a43741c8
toxcore: 0.1.8
Qt: 5.5.1
Hardware: 
…

Reproducible: Always 

##### Steps to reproduce

1-install program

2-open the program go to advanced settings and select "make portable"

3-restart the program (the program creates the tox folder inside install folder)

4-close the program

5-copy the installation folder to another location (already portable)

6-uninstall the program.

7-open the program in portable mode from the new location

##### Observed Behavior

When opening the program in portable mode from the new location creates a folder "tox" on the disk the system in C: \ Users \ "User" \ AppData \ Roaming

The folder is empty, and if it is deleted when the program is re-opened it is recreated.

##### Expected Behavior
The program in portable mode should not create ANY file or permanent folder outside of the installation folder

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by Diadlo** [comment] 2017-05-23 21:27
Seems, duplicate of #3929, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-05-23 21:27 UTC
Labels: U-low
