### ISSUE TITLE
Do NOT open minimized on taskbar qtox when receiving new chat message

### ISSUE THREAD

**Issue by averter** [qTox/qTox#3594] opened 2016-08-05 10:23 UTC
This is a very irritating issue that I have with qtox. I couldn't find a workaround.
Whenever I'm chatting, if qtox is on the taskbar it will pop up to the foreground when a new chat message is received. This can be avoided by closing it to the tray icon. However this requires me to click on the icon to open it back. 
Since usually I only work with the keyboard and scan through my opened windows with Alt+Tab this makes the whole operation frustrating and time-consuming.
So the question is: Is there a way to do not open a qtox window to the foreground when receiving a new chat message (and qtox must be on the taskbar so that I can access it with Alt+Tab).

Thanks in advance

OS: Linux Mint 
qTox version: eb743b4-obs.
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always
##### Steps to reproduce
1.  Start a chat
2. close qtox to the taskbar
3. After receiving a message qtox should pop up.

**Comment by zetok** [comment] 2016-08-05 10:35
![spectacle jl1068](https://cloud.githubusercontent.com/assets/3148759/17434093/6575d1a6-5b00-11e6-8ac0-79058da560e7.png)
↑ have you tried this option?

What DE are you using?

**Comment by zetok** [comment] 2016-08-05 10:37
Also, could you update & try with newest qTox?

**Comment by averter** [comment] 2016-08-05 10:41
Thanks for the help. Tried yes and it didn't work out. DE is Cinnamon. I will update and let you know if anything changes.
Update: I don't want to compile from the source. Checked if my version was the latest one from the 
https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox
repo and it is

**Comment by zetok** [comment] 2016-08-05 10:58
> Update: I don't want to compile from the source. Checked if my version was the latest one from the
> https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox
> repo and it is

Err? Latest one seems to be e.g. `qtox_201608051313~34aa905_amd64.deb` which should contain stuff from yesterday?

**Comment by averter** [comment] 2016-08-05 11:15
If I try to install it I get a dependency error related with libavcodec and ffmpeg56 and forward on trying to solve it, issues of ppa not supporting trusty.

**Comment by zetok** [comment] 2016-08-05 11:20
> If I try to install it I get a dependency error related with libavcodec and ffmpeg56 and forward on trying to solve it, issues of ppa not supporting trusty. 

It's not a PPA. It's a repository. Anyway; there is a repo for 14.04, and it shouldn't have problems – are you sure that you have the right repo? (there are 3 separate repos for 3 *buntu versions)

**Comment by averter** [comment] 2016-08-05 11:35
I've tried 14.04 instead of 16.04 and it installed another version. I am using Linux Mint so I cannot say which one I should pick. This is the qtox version I got
You are using qTox version v1.4.0-387-g34aa905-obs.

Everything remains unchanged

**Comment by initramfs** [comment] 2016-08-05 15:42
I also experience this issue when using Cinnamon on Arch since at least the qTox 1.4 release, my workaround is to toggle "Prevent focus stealing" in Cinnamon (Settings -> Windows -> Prevent Focus Stealing). I remember there was an old issue regarding something like this, but I'm unsure of it's exact name.

**Comment by sudden6** [comment] 2016-08-06 13:58
I can't reproduce this with KDE Plasma 5, maybe Cinnamon handles `QApplication::alert()` differently?

**Comment by initramfs** [comment] 2016-08-06 14:22
@sudden6 Yeah it seems to be a Cinnamon thing, I remember seeing another issue that explicitly claimed Cinnamon was the source (I don't have this issue when using bspwm).

**Comment by hashsploit** [comment] 2016-08-20 19:58
+9001
Very annoying, this is a bug that should be fixed very soon.
OS: Debian
DE: Cinnamon

**Comment by rodolpheh** [comment] 2016-08-31 07:46
Had the same issue in Cinnamon, the workaround is to go in the cinnamon settings > Windows > Behaviour tab and then check an option about "avoiding focus stealing" (I don't know the accurate name, as my system isn't in english). I don't know how this option could affect other application but I guess it will satisfy you.

**Comment by averter** [comment] 2016-09-01 08:29
The workaround suggested by Rodolphe Houdas and @initramfs  is pretty good (no side-effects so far):
go in the cinnamon settings > Windows > Behaviour tab and then turn an option about "Prevent focus stealing" ON.

**Comment by hashsploit** [comment] 2016-09-17 20:38
@averter Hmm, I tried that but it still is switching the window back to qtox on any message received. The only setting under Windows > Behavior tab that is on is the "Prevent focus stealing". It switches workspaces to the one qtox is on, but if qtox is on the same workspace that I'm working on with other programs it works normally without popping up.

**Comment by initramfs** [comment] 2016-09-17 23:13
@HashSploit Not the best around to your workspace issue, but in Cinnamon you can pin a program to all workspaces (thus preventing it from switching workspaces upon an incoming message).

**Comment by zetok** [comment] 2017-07-07 08:07
Since it's a behaviour defined by the DE, there's nothing that qTox can do about it, thus closing.

If you feel that this behaviour should be changed, an issue should be opened in Cinnamon's bug tracker for it.

**Closed as completed by zetok** 2017-07-07 08:07 UTC
Labels: upstream, OS-linux
