### ISSUE TITLE
Windows 8.1 Pro x64 desktop gui assertion failure

### ISSUE THREAD

**Issue by ebayShopper** [qTox/qTox#1159] opened 2015-02-14 21:03 UTC
![installerror](https://cloud.githubusercontent.com/assets/7761693/6201040/135ca25a-b462-11e4-940f-c72221520d1e.png)

![installerror2](https://cloud.githubusercontent.com/assets/7761693/6201041/136858de-b462-11e4-9bf6-f881747cfdd6.png)

**Comment by dubslow** [comment] 2015-02-14 23:30
Very interesting... @tux3

**Comment by angryjouster** [comment] 2015-02-18 05:41
I have a friend who is running Windows 7 Ultimate x64 who has also encountered this error.  This was his first time installing qTox and he received the error with both the 64 and 32 bit versions of the installer.

**Comment by tux3** [comment] 2015-02-19 21:49
Duplicate of #1187

If someone still has this issue after updating, please leave a comment.

**Closed as completed by tux3** 2015-02-19 21:49 UTC
Labels: C-bug, U-low
