### ISSUE TITLE
emoji's dont get parsed/displayed in status line

### ISSUE THREAD

**Issue by cjpit** [qTox/qTox#1285] opened 2015-02-26 02:44 UTC
for windows boxes anyway...
just shows the square box

**Comment by TheLastProject** [comment] 2015-02-26 07:48
This sounds like it would be caused by the lack of emoticon support for statuses, combined with bad unicode support. I tried working on emoticons for status lines and names in #1042, but never managed to get it working as I'd like. Maybe someone else could help figure this out.

**Comment by redsteakraw** [comment] 2015-02-27 00:26
There are two separate things here color emoticon emoji like the ones seen in the chat form(with TwitterEmojiSVG as the smiley theme) and regular text.  Displayed text will just use the hardcoded font and if there are any characters that are not in the font it will look to other fonts installed on your computer for the fonts.  Many of these square boxes are from emoji codepoints the [symbola font](http://users.teilar.gr/~g1951d/) (on linux usually the ttf-ancient-fonts package).  If installed it will show the emoji in monochrome font form just like any other character.  The only way to fix this is to either package symbola with qTox, or port the emoticon engine to all widgets that display text. @cjpit  @TheLastProject

**Comment by zetok** [comment] 2015-08-26 09:15
Question is, should they be displayed there at all?

Edit: to clarify;
- ![emoji](https://cloud.githubusercontent.com/assets/3148759/9489817/b140e2b8-4bdb-11e5-97b5-47642c7c6046.png) - emoji - should be displayed
- ![emoticon](https://cloud.githubusercontent.com/assets/3148759/9489829/c241412a-4bdb-11e5-9686-bba75b4cf429.png) - emoticon - should not be displayed in status, only in chatform

I.e. is there a _really good_ reason to display emoticons in status line?

# 

Also, is this still an issue on newest builds?

**Comment by zetok** [comment] 2015-10-10 04:21
> Also, is this still an issue on newest builds?

Since no one responded to that for over a month, closing. If problem is still reproducible, please comment for reopen.

**Closed as completed by zetok** 2015-10-10 04:21 UTC
Labels: C-bug, O-need-info, C-discussion, M-ui

**Comment by copywrong** [comment] 2018-06-03 21:44
Unfortunately, the issue is still present.
For example, this is what appears below a contact's status:
![emoji status](https://user-images.githubusercontent.com/6815768/40891448-35de1c4a-6775-11e8-9ccb-5856228e4ffa.png)
It also occurs when hovering the mouse over many Emojis in the smileys box.

qTox 1.15.0
Arch Linux
no Emoji packages (installing unicode-emoji didn't help)

**Comment by tox-user** [comment] 2018-06-04 13:40
Can't reproduce on Debian. It must be some package missing? Maybe something with fonts?

**Comment by copywrong** [comment] 2018-06-04 23:39
@tox-user package noto-fonts-emoji solved the issue.
