### ISSUE TITLE
Group call not working properly, Group not saving

### ISSUE THREAD

**Issue by Onepamopa** [qTox/qTox#3430] opened 2016-06-23 17:56 UTC
##### Brief Description

OS: Windows 10 build 10586
qTox version: latest (currently)

3 people in group voice call sucks (robot voice).
Same group, 2 people in the call - perfect.

Groups not saving, no auto-rejoining group.

**Comment by zetok** [comment] 2016-06-23 17:57
Duplicate of #896, thus closing.

**Comment by Onepamopa** [comment] 2016-06-23 17:57
"Duplicate of #896, thus closing." opened .... a few years ago and still not fixed ?

**Closed as completed by zetok** 2016-06-23 17:57 UTC
Labels: U-low

**Comment by zetok** [comment] 2016-06-23 17:58
Yep.

Also, #3359
