### ISSUE TITLE
[Feature request] Add option to dele profile picture

### ISSUE THREAD

**Issue by leafcutterant** [qTox/qTox#4837] opened 2017-11-25 20:33 UTC
##### Brief Description

OS: Windows
qTox version: 1.12.1.
Commit hash:  d65c30b879ee2f00c16816aa332567fd627c0b2b
toxcore:  0.1.10
Qt:  5.6.3

Reproducible: Always

Right now there is no way to go back to the identicon or simply to go without a profile picture. I'd suggest an "X" or a button near the picture on the My Profile page to enable deleting it.

**Comment by sudden6** [comment] 2017-11-25 20:36
duplicate of https://github.com/qTox/qTox/issues/4826

try right click on the avatar picture.

**Closed as completed by sudden6** 2017-11-25 20:36 UTC
