### ISSUE TITLE
File sent by the contact disappeared from the history after restart

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2948] opened 2016-02-10 19:31 UTC
The contact sent me a file attachment, I viewed it few times, never deleted. After qTox is exited and restarted the whole record that the file was sent is gone from qTox window.

Restart shouldn't change the user history. File should be openable as before.

**Comment by zetok** [comment] 2016-02-12 07:23
Duplicate of  #1300, thus closing.

**Closed as completed by zetok** 2016-02-12 07:23 UTC
Labels: U-low, proposal, M-ui
