### ISSUE TITLE
Green "unread messages" notification stays forever.

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2247] opened 2015-09-17 11:28 UTC
After qTox start and then reception of an offline message, green "unread messages" notification stays on the bottom-left side, even after the message is read. It should dissapear then...

**Comment by zetok** [comment] 2015-09-17 13:38
Could reproduce.

Notification finally disappears when scrolling down, but not when clicking on it (it should then).

That's a regression, and seems to have appeared after ~~new groupchats~~ detached windows were merged. If needed, I could do `git bisect`, if no one else will want to do it.

**Comment by Diadlo** [comment] 2016-04-24 22:50
@zetok Can't reproduce now. Or I do something wrong

**Comment by zetok** [comment] 2016-04-24 23:52
Welp, I can't reproduce too. I don't even get the unread messages notification anymore, which is a regression…

**Comment by Diadlo** [comment] 2016-04-25 00:18
@zetok  Hm.. It is strange. I still get unread notification.

**Comment by zetok** [comment] 2016-04-25 00:39
Huh. In any case, I've made an issue for it: #3193

**Comment by zetok** [comment] 2016-04-30 17:45
Can ~reproduce with multiple windows mode:
[qtox.webm.zip](https://github.com/tux3/qTox/files/243745/qtox.webm.zip)

**Closed as completed** 2016-05-15 10:44 UTC
Labels: C-bug, P-low, M-ui
