### ISSUE TITLE
qTox won't fetch avatar icons if the user delete /avatars/ folder

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3286] opened 2016-05-10 09:36 UTC
##### Brief Description

OS: Windows 7 64
qTox version: v1.4.0-29-g08263e9.
Commit hash:  08263e98445e543eacb0b16ac4fefc7963baf7a3
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Your qTox is running, and some friends(with their own icons) are online.
2. Close qTox. Go to qtox.exe folder, and delete "avatar" folder.
3. Start qTox. All icons are gone(of course), so I set my avatar again.
4. About other friends icons,
##### Observed Behavior

All user's icon is empty (white icon).
Looks like qTox didn't fetch it again from qTox network.
##### Expected Behavior

If qTox can't find image file from /avatars/, it should fetch their icons.

**Comment by zetok** [comment] 2016-05-10 09:39
Duplicate of #1765, thus closing.

**Closed as completed by zetok** 2016-05-10 09:39 UTC
Labels: C-bug, U-low
