### ISSUE TITLE
need to Add import profile in login window

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2050] opened 2015-08-03 12:48 UTC
In the window select profile, need add the ability to import an existing file Profile

**Comment by ph-One** [comment] 2015-08-26 15:31
:zap:

**Comment by zetok** [comment] 2015-08-30 11:47
Looks like it's done in #2140.

**Comment by zetok** [comment] 2016-03-25 02:16
Actually, this is a duplicate of #1872, thus closing.

**Closed as completed by zetok** 2016-03-25 02:16 UTC
Labels: U-low, P-medium, M-ui
