### ISSUE TITLE
New message system causes segfault whenever a friend is clicked

### ISSUE THREAD

**Issue by hart0** [qTox/qTox#5712] opened 2019-06-21 22:44 UTC
**Brief Description**
 
After compiling this version that came out today with the refactored chatlog, clicking any friend immediately results in a segfault crash. I've tried both online and offline friends (offline had pending messages waiting to be sent), both result in crashing as soon as their profiles are clicked.
 
 **System Details:**
OS: Fedora 30
qTox version: nightly
Commit: 033f28e67ecd61cd0fdb6cc0e8de8a2bc920e1d7
toxcore: v0.2.9
Qt: 5.12.1
 
**Reproducible**: Always
 
 
Running qtox with gdb shows this after clicking a friend:
 
```
Thread 1 "qtox" received signal SIGSEGV, Segmentation fault.
0x00007ffff78ac344 in ?? () from /lib64/libQt5Widgets.so.5
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-atk-2.32.0-1.fc30.x86_64 at-spi2-core-2.32.1-2.fc30.x86_64 gtk-murrine-engine-0.98.2-16.fc30.x86_64 gtk3-3.24.8-1.fc30.x86_64 libXxf86vm-1.1.4-11.fc30.x86_64 libepoxy-1.5.3-2.fc30.x86_64 libpciaccess-0.14-3.fc30.x86_64 libwayland-client-1.17.0-1.fc30.x86_64 libwayland-cursor-1.17.0-1.fc30.x86_64 libwayland-egl-1.17.0-1.fc30.x86_64 libxkbcommon-0.8.3-1.fc30.x86_64 libxkbcommon-x11-0.8.3-1.fc30.x86_64 mesa-dri-drivers-19.0.6-1.fc30.x86_64 mesa-libGL-19.0.6-1.fc30.x86_64 mesa-libglapi-19.0.6-1.fc30.x86_64 nss-mdns-0.14.1-3.fc30.x86_64 sssd-client-2.1.0-2.fc30.x86_64 xcb-util-image-0.4.0-12.fc30.x86_64
(gdb) bt
#0  0x00007ffff78ac344 in  () at /lib64/libQt5Widgets.so.5
#1  0x00007ffff78ac467 in  () at /lib64/libQt5Widgets.so.5
#2  0x00007ffff7832b27 in QWidgetPrivate::inheritStyle() ()
    at /lib64/libQt5Widgets.so.5
#3  0x00007ffff7843173 in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>)
    () at /lib64/libQt5Widgets.so.5
#4  0x00007ffff781ff8b in QLayout::addChildWidget(QWidget*) ()
    at /lib64/libQt5Widgets.so.5
#5  0x00007ffff781ffa3 in QLayout::addWidget(QWidget*) ()
    at /lib64/libQt5Widgets.so.5
#6  0x000000000078870f in GenericChatForm::show(ContentLayout*)
    (this=0x1a91590, contentLayout=0x16fec80)
    at /tmp/build/qTox/src/widget/form/genericchatform.cpp:453
#7  0x000000000077f958 in ChatForm::show(ContentLayout*)
    (this=0x1a91590, contentLayout=0x16fec80)
    at /tmp/build/qTox/src/widget/form/chatform.cpp:686
#8  0x000000000082c7b9 in Widget::openDialog(GenericChatroomWidget*, bool)
    (this=0xed3600, widget=0x18d6d70, newWindow=false)
    at /tmp/build/qTox/src/widget/widget.cpp:1344
#9  0x000000000082c44f in Widget::onChatroomWidgetClicked(GenericChatroomWidget*) (this=0xed3600, widget=0x18d6d70)
    at /tmp/build/qTox/src/widget/widget.cpp:1287
```

**Comment by anthonybilinski** [comment] 2019-06-22 00:30
This looks like an exact duplicate of https://github.com/qTox/qTox/issues/5570, which looks like a Qt bug. It should be fixed in 5.12.4 and not be present yet in versions older than 5.11.0. I'm guessing are using a Qt between those versions?

It's likely you're only hitting it after the chatlog refactor because memory layout or init timing has changed. The frequency of reproducing this issue seems to change with other unrelated changes being made.

AFAIK the solution is to link against an unaffected Qt version, which would require cloning and building a specific Qt version. We should add that as part of #5570.

I'll close this issue and we can continue discussion there if needed.

**Closed as completed by anthonybilinski** 2019-06-22 00:30 UTC
Labels: U-low
