### ISSUE TITLE
[Request future] autotized proxy

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#2966] opened 2016-02-20 21:10 UTC
Hello. Please, add to form settings autorized proxy

**Comment by ProMcTagonist** [comment] 2016-02-20 21:15
Can you please explain with more details what you mean?

**Comment by SergeyDjam** [comment] 2016-02-20 21:19
Now Playing missing fields to configure proxy authentication. There are times when you need to enter a user name and password for that would connect to the proxy to access the Internet

**Comment by ProMcTagonist** [comment] 2016-02-20 22:27
https://github.com/tux3/qTox/issues/1286

**Comment by SergeyDjam** [comment] 2016-02-20 22:29
Yes

**Comment by ProMcTagonist** [comment] 2016-02-20 22:57
Blocked by https://github.com/irungentoo/toxcore/issues/1268

**Comment by zetok** [comment] 2016-02-21 15:41
Since it's a duplicate of #1286, closing.

**Closed as completed by zetok** 2016-02-21 15:41 UTC
Labels: U-low, proposal
