### ISSUE TITLE
qTox: 1.5.2 d'nt open AV preferences tab

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#3812] opened 2016-10-12 13:07 UTC
Hello
##### Brief Description

OS: Linux x86_64, 
qTox version: v1.5.2, 
Commit hash 4b726dd
toxcore: toxcore-0.0.1-0.20160220.2
Qt: 5.6.1
Hardware: 
00:1b.0 Audio device: Intel Corporation 5 Series/3400 Series Chipset High Definition Audio (rev 05)
Bus 002 Device 040: ID 0a5c:4500 Broadcom Corp. BCM2046B1 USB 2.0 Hub (part of BCM2046 Bluetooth)
Laptop_Integrated_Webcam_0.3M

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
##### Steps to reproduce
1. start qTox
2. goto preferens - tab VA 
3. end
##### Observed Behavior

and now tab AV d'nt open
##### Additional Info

```
v4l2-ctl --all
Driver Info (not using libv4l2):
        Driver name   : uvcvideo
        Card type     : Laptop_Integrated_Webcam_0.3M
        Bus info      : usb-0000:00:1a.0-1.4
        Driver version: 4.1.33
        Capabilities  : 0x84200001
                Video Capture
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps   : 0x04200001
                Video Capture
                Streaming
                Extended Pix Format
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
        Width/Height      : 320/240
        Pixel Format      : 'YUYV'
        Field             : None
        Bytes per Line    : 640
        Size Image        : 153600
        Colorspace        : sRGB
        Transfer Function : Default
        YCbCr Encoding    : Default
        Quantization      : Default
        Flags             : 
Crop Capability Video Capture:
        Bounds      : Left 0, Top 0, Width 320, Height 240
        Default     : Left 0, Top 0, Width 320, Height 240
        Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 320, Height 240
Selection: crop_bounds, Left 0, Top 0, Width 320, Height 240
Streaming Parameters Video Capture:
        Capabilities     : timeperframe
        Frames per second: 30.000 (30/1)
        Read buffers     : 0
                     brightness (int)    : min=-64 max=64 step=1 default=0 value=0
                       contrast (int)    : min=0 max=95 step=1 default=0 value=0
                     saturation (int)    : min=0 max=100 step=1 default=64 value=64
                            hue (int)    : min=-2000 max=2000 step=1 default=0 value=0
 white_balance_temperature_auto (bool)   : default=1 value=1
                          gamma (int)    : min=100 max=300 step=1 default=100 value=100
           power_line_frequency (menu)   : min=0 max=2 default=0 value=0
      white_balance_temperature (int)    : min=2800 max=6500 step=1 default=4600 value=4600 flags=inactive
                      sharpness (int)    : min=1 max=7 step=1 default=2 value=2
         backlight_compensation (int)    : min=0 max=3 step=1 default=3 value=3
```

Log:

```
[12:34:39.854 UTC] src/audio/audio.cpp:386 : Debug: Opening audio output "Q5"
[12:34:39.889 UTC] src/audio/audio.cpp:400 : Debug: Opened audio output "Q5"
[12:34:39.897 UTC] src/audio/audio.cpp:345 : Debug: Opening audio input "Встроенное аудио Аналоговый стерео"
[12:34:39.897 UTC] src/audio/audio.cpp:363 : Warning: Failed to initialize audio input device: "Встроенное аудио Аналоговый стерео"
[12:34:40.006 UTC] src/widget/form/settings/avform.cpp:351 : Debug: available Modes:
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 640, height: 480, FPS: 30.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 640, height: 480, FPS: 20.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 640, height: 480, FPS: 15.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 640, height: 480, FPS: 10.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 640, height: 480, FPS: 5.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 352, height: 288, FPS: 30.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 352, height: 288, FPS: 20.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 352, height: 288, FPS: 15.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 352, height: 288, FPS: 10.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 352, height: 288, FPS: 5.000000, pixel format: yuyv422
[12:34:40.007 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 320, height: 240, FPS: 30.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 320, height: 240, FPS: 20.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 320, height: 240, FPS: 15.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 320, height: 240, FPS: 10.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 320, height: 240, FPS: 5.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 176, height: 144, FPS: 30.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 176, height: 144, FPS: 20.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 176, height: 144, FPS: 15.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 176, height: 144, FPS: 10.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 176, height: 144, FPS: 5.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 160, height: 120, FPS: 30.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 160, height: 120, FPS: 20.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 160, height: 120, FPS: 15.000000, pixel format: yuyv422
[12:34:40.008 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 160, height: 120, FPS: 10.000000, pixel format: yuyv422
[12:34:40.009 UTC] src/widget/form/settings/avform.cpp:205 : Debug: width: 160, height: 120, FPS: 5.000000, pixel format: yuyv422
[12:34:40.009 UTC] src/widget/form/settings/avform.cpp:365 : Debug: selected Modes:
[12:34:40.009 UTC] src/widget/form/settings/avform.cpp:283 : Debug: width: 640, height: 480, FPS: 30.000000, pixel format: yuyv422

[12:34:40.009 UTC] src/widget/form/settings/avform.cpp:283 : Debug: width: 320, height: 240, FPS: 30.000000, pixel format: yuyv422

[12:34:40.009 UTC] src/widget/form/settings/avform.cpp:283 : Debug: width: 160, height: 120, FPS: 30.000000, pixel format: yuyv422

[12:34:40.009 UTC] src/video/camerasource.cpp:352 : Debug: Closing device  "none"
[12:34:40.009 UTC] src/video/camerasource.cpp:266 : Debug: Opening device  "/dev/video0"
```

**Comment by Diadlo** [comment] 2016-10-12 13:43
Could you re-test with newest qTox?
Related with #3575?
What do you mean by `AV d'nt open`? qTox freezes?

**Comment by SergeyDjam** [comment] 2016-10-12 16:40
My version 1.5.2, how i can find newest qTox? Git upstream checkout?

Yes, qTox freeze when I open a tab A/V

**Comment by Diadlo** [comment] 2016-10-12 18:31
@SergeyDjam [Here](https://github.com/qTox/qTox/blob/master/INSTALL.md#install-git) is instruction

**Comment by zetok** [comment] 2016-10-28 16:38
@Diadlo not really.

@SergeyDjam since you seem to be using arch, there should be `qtox-git` in AUR.

**Comment by SergeyDjam** [comment] 2016-10-28 17:07
No, i using ROSA LInux Fresh R8

**Comment by SergeyDjam** [comment] 2016-10-30 21:57
I build revision 84208d0b3f70448121958b51a8a403bed456a650
This revision no fix problem

**Comment by SergeyDjam** [comment] 2016-10-30 22:17
i build revision: 2b0fbae44b2576df7abdec4566ce6d21b60d8685
d'nt fix problem

**Comment by Diadlo** [comment] 2016-10-31 04:26
@SergeyDjam Just to be possible to change other settings on AV tab you can use this workaround to reset video device:
1. Open `~/.config/tox/qtox.ini`
2. Find `videoDev=<someValue>` line
3. Remove `<someValue>` i.e. line should be `videoDev=`
4. Save file
5. Start qTox

**Comment by SergeyDjam** [comment] 2016-10-31 10:26
Yes, i'do this
Hm, skype too d'nt viewing test video, but no freeze programm...

**Comment by Diadlo** [comment] 2017-02-24 09:51
Seems, duplicate of #2058, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-02-24 09:51 UTC
Labels: C-bug, P-high, M-video
