### ISSUE TITLE
X86 qTox1.11.0 portable no downlaod

### ISSUE THREAD

**Issue by xz00311** [qTox/qTox#4628] opened 2017-09-05 02:47 UTC
https://build.tox.chat/view/qtox/job/qTox-stable_build_windows_x86_release/lastSuccessfulBuild/artifact/qTox-stable_build_windows_x86_release_1.11.0.zip

**Comment by ezavod** [comment] 2017-09-05 06:07
Seems to be a duplicate of #4592.

**Closed as completed** 2017-09-05 12:09 UTC
