### ISSUE TITLE
"Login Automatically" option present for encrypted profiles

### ISSUE THREAD

**Issue by aphirst** [qTox/qTox#1937] opened 2015-06-29 15:12 UTC
As I understand correctly, when a profile requires a password (i.e. when the profile is encrypted), the "Login Automatically" option on the login screen ought not be present, as (for obvious security reasons) qTox ought not remember your password.

However, the option is indeed present. In accordance with a recommendation from the IRC channel, I've opened a bug so that this doesn't get forgotten.

Feel free to edit with information/corrections.

**Comment by linux-modder** [comment] 2015-06-30 10:52
This is  a bug  --  I personally use   encrypted profiles (and chat logs)
 and auto login and STILL need to input  BOTH passes before  seeing a
 functional client (although I see no  login page due to auto login feature
enablement)  what  OS and  build  version

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672

Find Me  on any of the sites  I teach /frequent:

## https://gist.github.com/linux-modder/ac5dc6fa211315c633c9

Tox:
corey84@toxme.se
9357BC6A5944A08AFC7D1EFFD61F6A73B9EABF8B2FB84ACF1DAC9A1A4D0A4705FFCCD0E5499B
pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Comment by linux-modder** [comment] 2015-07-09 02:20
sheldon.corey@gmail.com sent you an invitation to join MEGA.\n\n";

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and

## communication. Get 50 GB free!

Please create your free MEGA account by clicking on the following
link:\n\n";
https://mega.nz/#newsignupcmVwbHkrMDA1YTViZjA4YTVkMTU3NjEyODFiMDdjZjFhM2NjNGNlNzU0MWRjOGNkYjdiNTNjOTJjZjAwMDAwMDAxMTFhOTIyNmU5MmExNjljZTA1Nzk0MzE3QHJlcGx5LmdpdGh1Yi5jb23UlSl5yKrKwA

Best regards,

Team MEGA

**Comment by stal888** [comment] 2015-07-09 05:24
Thanks for the invite

**Comment by zetok** [comment] 2015-08-30 09:36
Duplicate of #1807, closing.

**Closed as completed by zetok** 2015-08-30 09:36 UTC
Labels: C-bug, U-low, proposal
