### ISSUE TITLE
Switching video device from None to a valid choice doesn't immediately show the video

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3943] opened 2016-12-06 04:23 UTC
On the Audio/Video page switching {None}->{Valid choice} doesn't immediately show the video. The video appears only when I switch to some other tab and back. This isn't right, can confuse users.

1.6.0 on FreeBSD 11

**Comment by zetok** [comment] 2016-12-06 04:52
Can't reproduce on feaedeed841f419a8eb5b7f40a14e27ef1e104cb on Gentoo Linux amd64

**Comment by zetok** [comment] 2016-12-06 12:34
Logs?

**Comment by anoadragon453** [comment] 2017-07-06 11:42
Cannot reproduce on latest master, suggest closing.

**Closed as completed** 2017-07-06 12:53 UTC
Labels: C-bug, O-need-info, M-video
