### ISSUE TITLE
offline message send in backgroud

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1441] opened 2015-03-20 08:28 UTC
now offline messages arrive at their destination only after you select this contact in contact list but not when contact becomes online

**Comment by zetok** [comment] 2015-03-20 14:09
Could not reproduce on 9079b334b9dc7a965555114fb377f84f22c23a89. Please provide [proper informations](https://github.com/tux3/qTox/wiki/Useful-bug-reports) or close the issue.

**Comment by PKEv** [comment] 2015-03-20 20:14
Checked.

The sequence is as follows:
0) disable the network.
1) send messages to offline
2) close qTox
3) enable network
4) start qTox

Messages send all together only after you select a contact

screen shots from a remote user:
disable the network + send messages to offline + close qTox + enable network + start qTox
![1](https://cloud.githubusercontent.com/assets/6053197/6760019/ebdb86ce-cf55-11e4-9148-30a47bcbdff6.png)

select a contact in my list
![2](https://cloud.githubusercontent.com/assets/6053197/6760020/ebde3770-cf55-11e4-8e65-9c6358ee4293.png)

As I understand it, bug associated with the loading message history only after you select a contact

**Comment by PKEv** [comment] 2015-03-21 23:32
offline messages don't send, if history friend don't load, but history loaded only after selecting friend in list

**Comment by agilob** [comment] 2015-05-11 19:45
please close.

**Closed as completed** 2015-05-11 19:48 UTC
Labels: C-bug
