### ISSUE TITLE
Remember a user's password when logging in

### ISSUE THREAD

**Issue by wuniversales** [qTox/qTox#5966] opened 2020-01-23 15:57 UTC
It would be nice to add the option to remember the password of the current user.
It's boring every time I turn on my computer, enter my computer password, and also put the qtox password to log in.

**Comment by sudden6** [comment] 2020-01-23 16:07
The only secure way I know of would be the OS keychain, see https://github.com/qTox/qTox/issues/4136 for that.

**Comment by anthonybilinski** [comment] 2020-01-23 17:54
To elaborate, qTox's login works differently from online accounts. For other online accounts like GitHub, you send your password to the server to check. When you click remember your password, your browser stores a token that it can use to log in with the sever automatically. With qTox, there isn't a server you're logging in with, instead your password is being used to encrypt your private key (your Tox identity) and your chat history, both that are being stored on your machine. For this reason a password isn't required for qTox, you can leave it blank during profile creation or click on your avatar top left and scroll down to "remove password". This means that if someone can read the files on your computer, they could use your private key to impersonate you, impersonate your friends to you, and could read your chat history.

Using a keyring like sudden6 mentioned above gives the benefits from both not having to type in a password every time, but also encrypting your files, by storing your qtox password in a database that's decrypted when you type in your login password, which we unfortunately don't support yet.

**Comment by anthonybilinski** [comment] 2020-01-24 22:49
So for the base feature of not having to enter a password: that's already possible, and note there's also an option in Settings -> General to autostart qTox on boot, and an option to login automatically from the login window. For the improved feature of using an OS keychain, that's a duplicate of https://github.com/qTox/qTox/issues/4136. I don't think there's anything remaining in this issue, so I'll close it off.

**Closed as completed by anthonybilinski** 2020-01-24 22:49 UTC
Labels: C-feature-request
