### ISSUE TITLE
Latest release for Mac not displaying webcam

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6161] opened 2020-05-30 02:59 UTC
##### Brief Description

OS: 
My laptop (works just fine): Debian 10 Buster
Affected user's laptop: OSX Mac laptop. Not sure the model or OS specifically since the user's not too tech savvy. Not a very old Mac laptop, maybe a few years old.
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. Because QTox doesn't have a legitimate Apple developer signature, the affected user had to go in their system preferences to change related settings to enable custom apps on her Mac laptop.
2. After this was done, the user was attempting to access webcam for Mac laptop under Gear Icon (Settings) > Audio/Video, but was only given two options for her webcam.
3. As a result, user was able to see my webcam just fine, but couldn't choose from her actual webcam on her Mac laptop.
4. Affected user also told me that other apps have been able to utilize the webcam just fine.

Images of the options that the affected user has:
![IMG_0376](https://user-images.githubusercontent.com/28350451/83318125-61525080-a1f7-11ea-9030-40bccf24f5df.jpg)
![IMG_0377](https://user-images.githubusercontent.com/28350451/83318127-61eae700-a1f7-11ea-9f59-b08d72bcceed.jpg)

**Comment by sudden6** [comment] 2020-05-30 18:47
Looks like a duplicate of #6056

**Closed as completed by sudden6** 2020-05-30 18:47 UTC
