### ISSUE TITLE
segmentation fault on startup after showing profile (main) window

### ISSUE THREAD

**Issue by martin21** [qTox/qTox#4055] opened 2017-01-05 21:08 UTC
Possible duplicates:

segmentation fault on startup #4054 but there qtox crashes straight after login in, but before displaying profile window. 

Segmentation fault on qTox startup in KDE #1116 but this dates back quite a while, however, I use Plasma.

##### Brief Description

OS: Debian GNU/Linux Sid

qTox version:: 201612181540~b392e2c (qtox-alpha Debian package version) but seems to crash differently thus reporting in a new issue

```
qtox-alpha (201612181540~b392e2c) unstable; urgency=low

  * Build upstream version from git (@b392e2c320800c38f44370dd7deee53e7497b167)

 -- Anton Batenev <[…]>  Sun, 18 Dec 2016 15:40:00 +0300
```

Qt:  5.7.1-1

Plasma 5.8.4 LTS + KF 5.29

Hardware:  ThinkPad T520

```
~> phoronix-test-suite system-info
Phoronix Test Suite v5.2.1
System Information

Hardware:
Processor: Intel Core i5-2520M @ 3.20GHz (4 Cores), Motherboard: LENOVO 42433WG, Chipset: Intel 2nd Generation Core Family DRAM, Memory: 16384MB, Disk: 300GB INTEL SSDSA2CW30 + 480GB Crucial_CT480M50, Graphics: Intel 2nd Generation Core Family IGP, Audio: Conexant CX20590, Network: Intel 82579LM Gigabit Connection + Intel Centrino Advanced-N 6205

Software:
OS: Debian unstable, Kernel: 4.8.15-tp520-btrfstrim+ (x86_64), Desktop: KDE Frameworks 5, Display Server: X Server 1.19.0, Display Driver: modesetting 1.19.0, OpenGL: 3.3 Mesa 13.0.2, Compiler: GCC 6.3.0 20161229, File-System: btrfs, Screen Resolution: 3840x1080
```

Reproducible: Always

##### Steps to reproduce

1. rm -r ~/.config/tox (make backup first!)
2. start qtox
3. Create new profile, I used user "test" with password "12"

##### Observed Behavior

qtox opens the profile window and crashes then:
```
:~> gdb qtox         
GNU gdb (Debian 7.12-4) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from qtox...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/qtox 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd386b700 (LWP 30224)]
[New Thread 0x7fffc91b0700 (LWP 30225)]
[New Thread 0x7fffc89af700 (LWP 30226)]
[20:51:42.792 UTC] persistence/settings.cpp:133 : Debug: No settings file found, using defaults
[20:51:42.792 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from :/conf/qtox.ini"
[20:51:42.814 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  14707469726907367303
[20:51:42.814 UTC] ipc.cpp:77 : Debug: Attaching to the global shared memory
[20:51:42.814 UTC] ipc.cpp:279 : Debug: Previous owner timed out, taking ownership 17917015644364910449 -> 14707469726907367303
[20:51:42.814 UTC] main.cpp:215 : Debug: built on:  12:40:00 Dec 18 2016 ( 1483605623 )
[20:51:42.814 UTC] main.cpp:216 : Debug: commit:  b392e2c320800c38f44370dd7deee53e7497b167 

[20:51:42.814 UTC] nexus.cpp:85 : Debug: Starting up
[20:51:52.939 UTC] persistence/settings.cpp:2383 : Debug: Creating new profile settings in  "/home/martin/.config/tox//test.ini"
[20:51:53.087 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/martin/.config/tox/qtox.ini"
[20:51:53.117 UTC] persistence/settings.cpp:358 : Debug: Loading personal settings from "/home/martin/.config/tox/test.ini"
[New Thread 0x7fffba9f0700 (LWP 30231)]
[New Thread 0x7fffba1ef700 (LWP 30232)]
[New Thread 0x7fffb99ee700 (LWP 30233)]
[20:51:54.549 UTC] core/core.cpp:245 : Debug: Creating a new profile
[20:51:54.549 UTC] core/core.cpp:136 : Debug: Core starting with IPv6 enabled
[New Thread 0x7fffb91ed700 (LWP 30234)]
[20:51:54.552 UTC] core/core.cpp:321 : Debug: Self avatar not found, will broadcast empty avatar to friends
[20:51:54.553 UTC] persistence/profile.cpp:373 : Debug: Saving tox save to  "/home/martin/.config/tox/test.tox"
[New Thread 0x7fffb89ec700 (LWP 30235)]
[20:51:54.674 UTC] widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
[20:51:54.676 UTC] widget/widget.cpp:469 : Debug: Detected buggy QIcon::hasThemeIcon. Icon overrides from theme will be ignored.

Thread 9 "qTox Database" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb89ec700 (LWP 30235)]
0x00007ffff3c2f75d in EVP_EncryptUpdate ()
   from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) bt full
#0  0x00007ffff3c2f75d in EVP_EncryptUpdate ()
    at /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007ffff3f79e3b in sqlcipher_openssl_cipher (ctx=0x7fffa801acc8, mode=<optimized out>, key=0x7fffa801ace8 "\234\370\025\350\b\223/\236\355z(\372\v\233$\327u|Ȫ\251\271\246ٽ#\205-!,", <incomplete sequence \371>, key_sz=<optimized out>, iv=0x7fffa80163c8 "\020%\002e\224q\026\273\020\371\314)\343?\377q\237Xr\266K\030\351\006aI\366\232\357\320\370Ռk\320\363旿\327\366L6q\004xɔu", in=0x7fffa801bb38 "\004", in_sz=960, out=0x7fffa8016008 "") at sqlite3.c:16517
        tmp_csz = 0
        csz = <optimized out>
        ectx = 0x7fffa801f7d0
#2  0x00007ffff3f8a47e in sqlcipher_page_cipher (ctx=ctx@entry=0x7fffa8015fa8, for_ctx=<optimized out>, pgno=1, mode=1, page_sz=<optimized out>, in=0x7fffa801bb38 "\004", out=0x7fffa8016008 "") at sqlite3.c:15696
        c_ctx = 0x7fffa801abb8
        iv_in = 0x7fffa801bef8 ""
        iv_out = 0x7fffa80163c8 "\020%\002e\224q\026\273\020\371\314)\343?\377q\237Xr\266K\030\351\006aI\366\232\357\320\370Ռk\320\363旿\327\366L6q\004xɔu"
        hmac_in = <optimized out>
        hmac_out = 0x7fffa80163d8 "\237Xr\266K\030\351\006aI\366\232\357\320\370Ռk\320\363旿\327\366L6q\004xɔu"
        out_start = 0x7fffa8016008 ""
        size = 960
#3  0x00007ffff3f9c104 in sqlite3Codec (iCtx=0x7fffa8015fa8, data=0x7fffa801bb28, pgno=1, mode=6) at sqlite3.c:14389
        ctx = 0x7fffa8015fa8
        offset = <optimized out>
        rc = <optimized out>
        page_sz = 1024
        pData = 0x7fffa801bb28 "SQLite format 3"
        buffer = 0x7fffa8015ff8
        kdf_salt = 0x7fffa80148f8
#4  0x00007ffff3faa799 in pager_write_pagelist (pPager=pPager@entry=0x7fffa8003aa8, pList=0x7fffa801bf60) at sqlite3.c:48086
        offset = 0
        pData = <optimized out>
        pgno = 1
        rc = 0
#5  0x00007ffff3fb25fa in sqlite3PagerCommitPhaseOne (pPager=0x7fffa8003aa8, zMaster=zMaster@entry=0x0, noSync=noSync@entry=0) at sqlite3.c:50033
        rc = <optimized out>
---Type <return> to continue, or q <return> to quit---
#6  0x00007ffff3fb27cf in sqlite3PagerCommitPhaseOne (noSync=0, zMaster=0x0, pPager=<optimized out>) at sqlite3.c:49932
        rc = 0
        pBt = 0x7fffa80035e8
#7  0x00007ffff3fb27cf in sqlite3BtreeCommitPhaseOne (p=0x7fffa8003588, zMaster=zMaster@entry=0x0) at sqlite3.c:57764
        pBt = 0x7fffa80035e8
#8  0x00007ffff3fb6421 in sqlite3BtreeCommitPhaseOne (zMaster=0x0, p=<optimized out>) at sqlite3.c:89551
        rc = 0
        pBt = <optimized out>
        i = 0
        nTrans = <optimized out>
        rc = 0
        needXcommit = <optimized out>
        mrc = <optimized out>
        eStatementOp = <optimized out>
        isSpecialError = <optimized out>
        rc = <optimized out>
        db = 0x7fffa8002fb8
#9  0x00007ffff3fb6421 in vdbeCommit (p=0x7fffa8014a18, db=0x7fffa8002fb8)
    at sqlite3.c:1586
        pBt = <optimized out>
        i = 0
        nTrans = <optimized out>
        rc = 0
        needXcommit = <optimized out>
        mrc = <optimized out>
        eStatementOp = <optimized out>
        isSpecialError = <optimized out>
        rc = <optimized out>
        db = 0x7fffa8002fb8
#10 0x00007ffff3fb6421 in sqlite3VdbeHalt (p=p@entry=0x7fffa8014a18)
    at sqlite3.c:1993
        mrc = <optimized out>
        eStatementOp = <optimized out>
        isSpecialError = <optimized out>
        rc = <optimized out>
        db = 0x7fffa8002fb8
#11 0x00007ffff3fe5926 in sqlite3VdbeExec (p=p@entry=0x7fffa8014a18)
    at sqlite3.c:71867
---Type <return> to continue, or q <return> to quit---
        zType = <optimized out>
        zLogFmt = <optimized out>
        pc = 42
        aOp = <optimized out>
        pOp = 0x7fffa801d0c8
        rc = 0
        db = <optimized out>
        resetSchemaOnFault = 0 '\000'
        encoding = <optimized out>
        iCompare = <optimized out>
        nVmStep = <optimized out>
        nProgressLimit = <optimized out>
        aMem = <optimized out>
        pIn1 = <optimized out>
        pIn2 = <optimized out>
        pIn3 = <optimized out>
        pOut = <optimized out>
        aPermute = <optimized out>
        lastRowid = 0
#12 0x00007ffff3fe68cf in sqlite3Step (p=0x7fffa8014a18) at sqlite3.c:69631
        db = 0x7fffa8002fb8
        rc = <optimized out>
        db = <optimized out>
        v = <optimized out>
        pStmt = <optimized out>
        v = <optimized out>
#13 0x00007ffff3fe68cf in sqlite3_step (pStmt=<optimized out>) at sqlite3.c:4161
        db = <optimized out>
        v = <optimized out>
        pStmt = <optimized out>
        v = <optimized out>
#14 0x000055555562bb20 in  ()
#15 0x00005555556c6335 in  ()
#16 0x00007fffef357449 in QObject::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fffefd7db2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fffefd852e1 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007fffef32a990 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#20 0x00007fffef32d11d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007fffef37ebf3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff02d27f7 in g_main_dispatch (context=0x7fffa8000990)
    at ././glib/gmain.c:3203
        dispatch = 0x7fffef37ebe0
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0x7fffa80012d0
        current = 0x7fffa4002770
        i = 0
#23 0x00007ffff02d27f7 in g_main_context_dispatch (context=context@entry=0x7fffa8000990) at ././glib/gmain.c:3856
#24 0x00007ffff02d2a60 in g_main_context_iterate (context=context@entry=0x7fffa8000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ././glib/gmain.c:3929
        max_priority = 2147483647
        timeout = -1
        some_ready = 1
        nfds = 1
        allocated_nfds = 1
        fds = <optimized out>
#25 0x00007ffff02d2b0c in g_main_context_iteration (context=0x7fffa8000990, may_block=1) at ././glib/gmain.c:3990
        retval = <optimized out>
#26 0x00007fffef37efff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fffef32897a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007fffef1560f3 in QThread::exec() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007fffef15ada8 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007fffeec24464 in start_thread (arg=0x7fffb89ec700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffb89ec700
        now = <optimized out>
---Type <return> to continue, or q <return> to quit---
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140736290801408, -3101657433683805362, 0, 140737488345599, 0, 140737354125376, 3101788007029783374, 3101695346104449870}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#31 0x00007fffee0ca9df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb) 
(gdb) quit
A debugging session is active.

        Inferior 1 [process 30220] will be killed.

Quit anyway? (y or n) y
```

##### Expected Behavior
qtox runs, as it did with an earlier version. I do not know which one however.

##### Additional Info

```
~/.cache#1> find -iname "*tox*"
~/.cache>
```

libsqlcipher0:amd64  3.2.0-2

**Comment by zetok** [comment] 2017-01-05 21:10
Duplicate of #4054, thus closing.

**Closed as completed by zetok** 2017-01-05 21:10 UTC
Labels: U-low
