### ISSUE TITLE
src/nexus.cpp:82 : Debug: Starting up Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by FabrizioMarana** [qTox/qTox#2553] opened 2015-11-11 08:16 UTC
Yesterday-evening everything was fine, no update arrived in the mean time.  Started up this morning and did not start up automatically, so started from terminal and got a core dumped. 

Relevant info from qtox.log:

2015-11-11 08:43:13 file logger starting
[08:43:13.109] src/main.cpp:143 : Debug: built on:  17:27:19 Nov  8 2015 ( 1447021441 )
[08:43:13.305] src/main.cpp:144 : Debug: commit:  be967e88a3760cc963f7b498eb0d82af30b51696 

[08:43:13.341] src/persistence/profile.cpp:76 : Debug: Loading tox save  "/home/fab-user/.config/tox/qTox User.tox"
[08:43:13.346] src/persistence/settings.cpp:287 : Debug: Loading personnal settings from "/home/fab-user/.config/tox/qTox User.ini"
[08:43:13.391] src/nexus.cpp:82 : Debug: Starting up
[08:43:13.401] src/persistence/settings.cpp:345 : Debug: "Saving global settings at /home/fab-user/.config/tox/qtox.ini"

2015-11-11 08:45:24 file logger starting
[08:45:24.459] src/main.cpp:143 : Debug: built on:  17:27:19 Nov  8 2015 ( 1447021441 )
[08:45:24.459] src/main.cpp:144 : Debug: commit:  be967e88a3760cc963f7b498eb0d82af30b51696 

[08:45:24.459] src/ipc.cpp:125 : Debug: postEvent  "activate" to 0
[08:45:25.501] src/ipc.cpp:258 : Debug: Previous owner timed out, taking ownership 11192279862557661146 -> 11687527440506962436

2015-11-11 08:45:56 file logger starting
[08:45:56.073] src/main.cpp:143 : Debug: built on:  17:27:19 Nov  8 2015 ( 1447021441 )
[08:45:56.073] src/main.cpp:144 : Debug: commit:  be967e88a3760cc963f7b498eb0d82af30b51696 

[08:45:56.073] src/persistence/profile.cpp:76 : Debug: Loading tox save  "/home/fab-user/.config/tox/qTox User.tox"
[08:45:56.073] src/persistence/settings.cpp:345 : Debug: "Saving global settings at /home/fab-user/.config/tox/qtox.ini"
[08:45:56.155] src/persistence/settings.cpp:287 : Debug: Loading personnal settings from "/home/fab-user/.config/tox/qTox User.ini"
[08:45:56.156] src/nexus.cpp:82 : Debug: Starting up

Some system info:
uname --kernel-release&&lsb_release --id --code --release
3.13.0-67-generic
Distributor ID: Ubuntu
Release:    14.04
Codename:   trusty

Anything else you need?

**Comment by towlie** [comment] 2015-11-11 17:57
Update your client and look if it still crashes. Looks like a duplicate of https://github.com/tux3/qTox/issues/2541

**Comment by FabrizioMarana** [comment] 2015-11-11 21:09
Thanks for the feed-back.  I'm awaiting an update to PPA https://pkg.tox.chat/debian/ nightly/release and will feed back after the update comes in.

**Comment by FabrizioMarana** [comment] 2015-11-12 07:49
Confirmed problem solved!  Thanks!  Please mark #2553 as a duplicate of #2541 and close.

**Closed as completed** 2015-11-12 09:33 UTC
