### ISSUE TITLE
Failure to open audio device results in spam in qtox.log

### ISSUE THREAD

**Issue by dongmaster** [qTox/qTox#3514] opened 2016-07-14 17:32 UTC
##### Brief Description

OS: Windows
qTox version: (version numbers in menu `Settings → About`)  v1.4.1-1-g06d78dc.
Commit hash:  06d78dcdee7bfe9a320fe91662f34227d74c3916
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  Not relevant
…

Reproducible: Always
##### Steps to reproduce
1. Have an audio device with a name that contains "ö"
2. Make qtox try to play audio
3. Check the qtox.log file
##### Observed Behavior

My qtox.log file is 51GB in size.
##### Expected Behavior

My qtox.log file should not be 51GB.
##### Additional Info

(links, images, etc go here)
Sample log file: 
[sample log.txt](https://github.com/tux3/qTox/files/364438/sample.log.txt)

**Comment by zetok** [comment] 2016-07-14 17:39
Note: the problem is most likely worked around in 93991368c6202fc9dfe474ad1e9ba5668c8a1e7b, but fixing the actual problem is needed. I.e. with new release logs won't grow that big in size, but spam will still be there.

@antis81 the rework of audio and moving away from openal to RtAudio should help with this, right?

**Comment by dongmaster** [comment] 2016-07-14 17:43
Could this possibly be related to https://github.com/tux3/qTox/issues/2973 ?
Audio did not work at all in qtox at that point in time, probably because qtox couldn't open the audio output.
But I have since updated qtox and audio works and I did not notice any error lines regarding audio near the end of the 51GB log file so maybe the audio issue is fixed?

**Comment by zetok** [comment] 2016-07-14 17:44
Maybe. If log won't grow in size that big, then it's just ~~#2980~~, which is not included in v1.4.1.1 release.

**Comment by zetok** [comment] 2016-07-14 17:46
Oops, wrong issue number, I meant #3440.

**Comment by antis81** [comment] 2016-07-14 19:32
> the rework of audio and moving away from openal to RtAudio should help with this, right?

Yeah, it would fix it. The problem is, that OpenAL encoding in Windows is not UTF-8, but asumingly Codepage Windows-1252. This is internal to OpenAL and cannot easily be fixed. AFAIK it got fixed in OpenAL-Soft, but as we rather require the stuff from RtAudio, it is not worth the effort IMO to fix it beforehand. I made a branch to start RtAudio implementation and as said before, we need to do it in parallel, so it doesn't affect existing features. So, if someone wants to fix it right now, feel free to do so.

**Comment by sudden6** [comment] 2016-07-16 21:46
@antis81 Is your branch already public? I'd be interested in helping out with that :)

**Comment by antis81** [comment] 2016-07-17 13:29
> Is your branch already public? I'd be interested in helping out with that :)

No, but I'll make it public today, so we can add PR's based on that one… :)

**Comment by antis81** [comment] 2016-07-17 14:44
@sudden6 We can now start! :) -> See #3524. Please post your ideas.

**Comment by sudden6** [comment] 2019-08-11 15:01
This is no longer a problem.

**Closed as completed by sudden6** 2019-08-11 15:01 UTC
Labels: C-bug, M-audio
