### ISSUE TITLE
Chat window scrolls up upon new message, requires constant scrolling-down 

### ISSUE THREAD

**Issue by borisgrebenshchikov** [qTox/qTox#5922] opened 2019-11-11 04:46 UTC
##### Brief Description

OS: Gentoo GNU/Linux
qTox version: 1.16.3-726-g7349b441
Commit hash:  7349b44154f22f6ef0be7880a97cb210d55ca982
toxcore:  0.2.10
Qt:  5.12.5
Hardware:  Intel Core 2 Duo, integrated graphics
Reproducible: Always
##### Steps to reproduce

1. Scroll chat log all the way to the bottom, either through Page Down keys, scroll bar, or middle-mouse.
2. Receive a message or a file, and the chat log will float up, cutting off the typing notification, then bottom of message/file transfer message, etc., going further up each new message.

##### Observed Behavior

Upon receiving a message the chat window will scroll up, instead of staying at the bottom and showing new messages and info without cutting off

##### Expected Behavior

Chat window should stay at the bottom to show new messages without cutting off

**Comment by anthonybilinski** [comment] 2019-11-11 21:08
Thanks for the report - I thought this was already in bug tracker, but I guess not.

There's a explanation of the cause of the issue as a review comment on a PR trying to fix the issue here: https://github.com/qTox/qTox/pull/5889#issuecomment-544200966

Now that we actually have an issue for this bug, I'll tag it for the v1.17.0 milestone to make sure it's fixed by the time we release.

**Comment by anthonybilinski** [comment] 2020-03-20 07:59
Fixed by #5991, fix present in v1.17-dev and master.

**Closed as completed by anthonybilinski** 2020-03-20 07:59 UTC
Labels: C-bug, P-high, D-easy, M-ui, U-high

**Comment by borisgrebenshchikov** [comment] 2020-03-31 03:25
Just tried the latest git; it works great, thank you very much!
