### ISSUE TITLE
qTox is not starting on Ubuntu 14.04

### ISSUE THREAD

**Issue by ruslo** [qTox/qTox#2928] opened 2016-02-05 10:37 UTC
Hi,

I can't start qTox on my Ubuntu 14.04 machine. Here are steps to reproduce:

``` bash
> wget https://build.tox.chat/view/Clients/job/qTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_linux_x86-64_release.tar.xz
> openssl sha1 qTox_build_linux_x86-64_release.tar.xz
SHA1(qTox_build_linux_x86-64_release.tar.xz)= d33362c29c6a33f364ecbe12c862cc2cd70ffaf9
> tar xf qTox_build_linux_x86-64_release.tar.xz 
> ./qtox
```

Log messages: https://gist.github.com/ruslo/8153c9b852ee18fd6def

So it seems to start but I see no windows.

**Comment by zetok** [comment] 2016-02-05 22:25
Could you check with `qtox-unity` version?

Did it refuse to work properly during the first start on a clean box, or were you starting with some other, already existing profile, which seems to be the case, according to log?

Did it work with earlier versions, or..?

**Comment by ruslo** [comment] 2016-02-06 05:57
> Could you check with qtox-unity version?

I've downloaded this version:
- https://build.tox.chat/job/qTox-unity_pkg_linux_deb_x86-64_nightly_release/397/artifact/qtox-unity-amd64-420-49b8a48.deb

and it works, I think you should place this link to the main page.

**Comment by zetok** [comment] 2016-04-29 05:15
~related: #3224, this issue seems closable once this gets merged.

**Comment by zetok** [comment] 2016-04-29 11:14
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by ruslo** [comment] 2016-05-06 07:49
> could you check if it works for you?

Nope, not working :(

**Comment by antis81** [comment] 2016-05-06 09:15
How about setting up the nightly "ppa"? Works for me on Ubuntu 14.04.

``` bash
echo "deb https://pkg.tox.chat/debian nightly $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/tox.list
wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install qtox

## optional (I think it's installed by default):
## sudo apt-get install apt-transport-https
```

**Comment by ruslo** [comment] 2016-05-06 09:53
> How about setting up the nightly "ppa"? Works for me on Ubuntu 14.04

Nope, doesn't work.

However new version of `qtox-unity` starts fine:
- https://build.tox.chat/job/qTox-unity_pkg_linux_deb_x86-64_nightly_release/431/artifact/qtox-unity-amd64-462-da2f892.deb

**Comment by zetok** [comment] 2016-05-08 06:29
@ruslo could you perhaps provide the steps that you've tried with community repo? I.e. for other people it seemed to work, so it would be good to know why it didn't work for you.

**Comment by antis81** [comment] 2016-05-08 07:48
@zetok Seems to be a problem with unity - I use Lubuntu (now updated to 16.04) without any panel.

**Comment by abbat** [comment] 2016-05-08 13:46
I can not reproduce problem with qTox community build on default installation Ubuntu Trusty and Xenial with Unity. Seems we need more details.

![qTox on Ubuntu Trusty](http://i.imgur.com/LzdmMQN.png)
![qTox on Ubuntu Xenial](http://i.imgur.com/KnaVBQq.png)

**Comment by ruslo** [comment] 2016-05-08 17:15
> could you perhaps provide the steps that you've tried with community repo?

Sure:

```
> which qtox
qtox not found

> lsb_release -a
No LSB modules are available.
Distributor ID:  Ubuntu
Description:     Ubuntu 14.04.4 LTS
Release:         14.04
Codename:        trusty

> cat /etc/apt/sources.list.d/qtox.list
deb http://download.opensuse.org/repositories/home:/antonbatenev:/tox/xUbuntu_14.04/ /

> sudo apt-get update

> sudo apt-get install qtox
...
The following NEW packages will be installed:
  qtox
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/13.6 MB of archives.
After this operation, 40.9 MB of additional disk space will be used.
Selecting previously unselected package qtox.
(Reading database ... 720418 files and directories currently installed.)
Preparing to unpack .../qtox_201605081758~9a3ba02_amd64.deb ...
Unpacking qtox (201605081758~9a3ba02) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Setting up qtox (201605081758~9a3ba02) ...

> which qtox
/usr/bin/qtox

> qtox
[19:57:39.075] src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/ruslo/.config/tox/qtox.ini"
[19:57:39.078] src/ipc.cpp:46 : Debug: Our global IPC ID is  ...
[19:57:39.078] src/main.cpp:205 : Debug: built on:  15:23:25 May  8 2016 ( 1462720975 )
[19:57:39.078] src/main.cpp:206 : Debug: commit:  9a3ba02145a3357c1e4f3044372d03dfebcfb568
[19:57:39.078] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/ruslo/.config/tox/ruslo.tox"
[19:57:39.078] src/persistence/settings.cpp:378 : Debug: "Saving global settings at /home/ruslo/.config/tox/qtox.ini"
[19:57:39.084] src/persistence/settings.cpp:296 : Debug: Loading personal settings from "/home/ruslo/.config/tox/ruslo.ini"
[19:57:39.084] src/nexus.cpp:81 : Debug: Starting up
[19:57:39.884] src/core/core.cpp:232 : Debug: Loading user profile
[19:57:39.884] src/persistence/profile.cpp:243 : Debug: Loading tox save  "/home/ruslo/.config/tox/ruslo.tox"
[19:57:39.884] src/core/core.cpp:128 : Debug: Core starting with IPv6 enabled
[19:57:39.885] src/core/core.cpp:301 : Debug: Self avatar not found, will broadcast empty avatar to friends
[19:57:40.106] src/widget/systemtrayicon.cpp:93 : Debug: Using the Qt backend
[19:57:41.402] src/core/core.cpp:403 : Debug: "Connecting to ..."
[19:57:41.403] src/core/core.cpp:403 : Debug: "Connecting to ..."
[19:57:45.901] src/core/core.cpp:403 : Debug: "Connecting to ..."
[19:57:45.903] src/core/core.cpp:403 : Debug: "Connecting to ..."
[19:57:48.458] src/core/core.cpp:370 : Debug: Connected to the DHT
[19:57:48.458] src/persistence/profile.cpp:308 : Debug: Saving tox save to  "/home/ruslo/.config/tox/ruslo.tox"
```

I see no window, however seems that client starts in fact. I can send message - icon became orange:

![qtox-not-working](https://cloud.githubusercontent.com/assets/4346993/15099241/5af1628e-1561-11e6-9a1a-35ce6b83837a.png)

Removing qtox and use qtox-unity:

```
> sudo apt-get remove qtox

> which qtox
qtox not found

> wget https://build.tox.chat/job/qTox-unity_pkg_linux_deb_x86-64_nightly_release/431/artifact/qtox-unity-amd64-462-da2f892.deb

> sudo gdebi qtox-unity-amd64-462-da2f892.deb

> which qtox
/usr/bin/qtox

> qtox
[20:02:57.221] src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/ruslo/.config/tox/qtox.ini"
[20:02:57.222] src/ipc.cpp:46 : Debug: Our global IPC ID is  ...
[20:02:57.222] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
[20:02:57.222] src/ipc.cpp:259 : Debug: Previous owner timed out, taking ownership ... -> ...
[20:02:57.223] src/main.cpp:171 : Debug: built on:  03:57:09 Mar 25 2016 ( 1458892441 )
[20:02:57.223] src/main.cpp:172 : Debug: commit:  da2f892d63704d845457eeb0f0beb12592e0fc12
[20:02:57.223] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/ruslo/.config/tox/ruslo.tox"
[20:02:57.223] src/persistence/settings.cpp:371 : Debug: "Saving global settings at /home/ruslo/.config/tox/qtox.ini"
[20:02:57.225] src/persistence/settings.cpp:296 : Debug: Loading personal settings from "/home/ruslo/.config/tox/ruslo.ini"
[20:02:57.225] src/nexus.cpp:81 : Debug: Starting up
[20:02:57.825] src/core/core.cpp:236 : Debug: Loading user profile
[20:02:57.825] src/persistence/profile.cpp:249 : Debug: Loading tox save  "/home/ruslo/.config/tox/ruslo.tox"
[20:02:57.825] src/core/core.cpp:132 : Debug: Core starting with IPv6 enabled
[20:02:57.826] src/core/core.cpp:305 : Debug: Self avatar not found, will broadcast empty avatar to friends
[20:02:58.326] src/widget/systemtrayicon.cpp:39 : Debug: Using Unity backend
[20:02:59.302] src/core/core.cpp:407 : Debug: "Connecting to ..."
[20:02:59.303] src/core/core.cpp:407 : Debug: "Connecting to ..."
[20:03:03.801] src/core/core.cpp:407 : Debug: "Connecting to ..."
[20:03:03.803] src/core/core.cpp:407 : Debug: "Connecting to ..."
[20:03:06.458] src/core/core.cpp:374 : Debug: Connected to the DHT
[20:03:06.461] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/ruslo/.config/tox/ruslo.tox"
[20:03:07.287] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/ruslo/.config/tox/ruslo.tox"
```

Works fine:

![qtox-working](https://cloud.githubusercontent.com/assets/4346993/15099254/c1327240-1561-11e6-99c1-da635e7e7a01.png)

**Comment by abbat** [comment] 2016-05-08 17:41
Would you clean tox settings before run new installed like:

```
mv /home/ruslo/.config/tox /home/ruslo/.config/tox.old
```

?

**Comment by ruslo** [comment] 2016-05-08 17:58
> Would you clean tox settings before run new installed like

Yes, it helps. Can I do clean without loosing my tox-id?

**Comment by abbat** [comment] 2016-05-08 18:01
Ok, seems I understand. You can revert changes:

```
$ rm -rf /home/ruslo/.config/tox
$ mv /home/ruslo/.config/tox.old /home/ruslo/.config/tox
```

Run qtox, and... run qtox in separate terminal again. Now window is visible. Problem in tray icon settings / activity.

**Comment by ruslo** [comment] 2016-05-08 18:20
> Run qtox, and... run qtox in separate terminal again

Yes, it does work too.

> Problem in tray icon settings / activity.

So is it a qTox bug?

**Comment by abbat** [comment] 2016-05-08 18:43
Unity is bug :) I will have to add special build for Unity to support it.

**Comment by abbat** [comment] 2016-05-08 20:19
@ruslo Would you update package and test again?

**Comment by ruslo** [comment] 2016-05-11 11:08
> Would you update package and test again?

It works! Feel free to close.

Thank you guys!

**Comment by zetok** [comment] 2016-05-11 11:15
Thanks for testing :)

**Closed as completed by zetok** 2016-05-11 11:15 UTC
Labels: C-bug, M-packaging, OS-linux
