### ISSUE TITLE
File transfer graphical glitch

### ISSUE THREAD

**Issue by Zer0-One** [qTox/qTox#1876] opened 2015-06-16 06:27 UTC
I was accepting about 20 file transfers from a friend, switched to another window, and then switched back to the qTox window to find that the file transfer dialog that appears in the chatform had been "stamped" over the top and bottom of the window.

![bug](https://cloud.githubusercontent.com/assets/1117820/8177071/ba6b9616-13b5-11e5-9708-946306981a6f.png)

My window manager is `dwm`, platform is a hardened Gentoo: `Linux 3.18.9-hardened #1 SMP Thu Mar 26 22:25:35 PDT 2015 x86_64 Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz GenuineIntel GNU/Linux`

**Comment by zetok** [comment] 2015-06-16 09:19
looks like a duplicate of  #1694

**Comment by zetok** [comment] 2015-08-29 23:56
Closing, since it's a duplicate.

**Closed as completed by zetok** 2015-08-29 23:56 UTC
Labels: C-bug
