### ISSUE TITLE
Multiple profiles in one window

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#4827] opened 2017-11-23 15:54 UTC
It's possible to launch multiple instances of qTox with -p option to use many profiles at the same time. That feature would be much better if users didn't have to run multiple qTox instaces with multiple windows. It would then make sense to have many profiles, because switching between them would be easy. Users might not want to share their Tox ID with everyone, so instead they could create one identity for talking with their friends and another for work and switch between them easily. There could be a bar with tabs for each open profile on the top of the window. Each profile should have separate settings as they have now, including proxy settings. That last part is important, because then we could have some profiles that use Tor and some that don't (for low latency). So everything would be as it is now, just inside one qTox instance and integrated with GUI.

**Comment by Diadlo** [comment] 2017-11-23 16:04
Seems, duplicate of #1018, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-11-23 16:04 UTC
Labels: U-low
