### ISSUE TITLE
`v1.15.0` tag is not GPG-signed – need to verify whether tag has been signed on CI

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#5274] opened 2018-07-27 17:53 UTC
##### Brief Description

Release tags are to be signed, but `v1.15.0` is missing signature.

```
$ git tag --verify v1.15.0
object 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
type commit
tag v1.15.0
tagger Anthony Bilinski <me@abilinski.com> 1524171597 -0700

qTox v1.15.0 release. For details see CHANGELOG.md.
error: no signature found
```

Alternatively, you can check for `Verified` label in [releases](https://github.com/qTox/qTox/releases).

**Comment by anthonybilinski** [comment] 2018-07-27 17:56
Duplicate of https://github.com/qTox/qTox/issues/5125. It was accidentally not re-signed when the tag was moved. Pushing a new tag would change artifact hashes, so it seemed like the best solution was to leave it as is and sign future releases. We should have done a v1.15.1 soon after to get a signed tag =/

**Comment by zetok** [comment] 2018-07-27 18:09
Well, since there are newer release tags that are signed I doubt whether there's an actual need to release signed v1.15.1.

That being said, has the issue with verifying whether tag is signed been addressed? From briefly looking at #5125 and trying to grep `git log` for some keywords it doesn't seem to be the case?

**Comment by anthonybilinski** [comment] 2018-07-27 18:31
No, AFAIK there's still no automatic check in CI or release procedure.

**Comment by Diadlo** [comment] 2018-07-27 18:32
@zetok Heey, glad to see you again!

**Comment by sudden6** [comment] 2019-08-11 13:00
v1.15.0 has been long succeeded.

**Closed as completed by sudden6** 2019-08-11 13:00 UTC
Labels: M-packaging
