### ISSUE TITLE
Link Error + question.

### ISSUE THREAD

**Issue by 648643579** [qTox/qTox#5327] opened 2018-09-06 00:50 UTC
Hi,
the site is a broken link:
https://i.imgur.com/royvDhy.png

wrong: "https://github.com/qTox/qTox/releases/download/v1.16.3/qTox-v1.16.3.x86_64.AppImage"
correctly: "https://github.com/qTox/qTox/releases/download/v1.16.3/qTox-v1.16.3.AppImage"

Why there is no download option qTox portable version (Windows)?
It is totally stupid to install qTox and then create a portable version from the installation...

**Comment by anthonybilinski** [comment] 2018-09-06 16:01
Duplicate of https://github.com/qTox/qTox/issues/5296, PR in review to fix: https://github.com/qTox/qTox/pull/5271.

Portable version missing duplicate of https://github.com/qTox/qTox/issues/4916. @sudden6 do you know the history of portable version? I'm inclined to agree that installing system wide to check an option to make qTox portable doens't make sense.

**Closed as completed by anthonybilinski** 2018-09-06 16:01 UTC
Labels: U-low

**Comment by vatterspun** [comment] 2018-09-21 20:54
> ... installing system wide to check an option to make qTox portable doens't make sense.

One of the primary use cases for portable software is to enable functionality when installation tools have been disabled by sysadmins.  As durable as the Tox network is, a portable version would only add to that by making it more accessible and easier to initiate.

**Comment by sudden6** [comment] 2018-09-22 01:39
@anthonybilinski sorry, didn't follow the portable version much...
IIRC it was never really portable because of the global settings you mentioned.
