### ISSUE TITLE
Getting empty messages

### ISSUE THREAD

**Issue by raingloom** [qTox/qTox#5543] opened 2019-01-31 22:04 UTC
##### Brief Description
Empty messages from new contact. I also get that "couldn't load chat logs" error at startup.

OS: Arch
qTox version: https://github.com/qTox/qTox/commit/8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.9
Qt:  5.12
Hardware:  Thinkpad T400

Reproducible: Always

##### Steps to reproduce

Not sure, only happens with this one contact I've added recently. I haven't had time to investigate it more.

##### Observed Behavior

Gettings lots of empty messages. Selecting them and clicking "quote selected text" verifies that indeed only the other person's messages are missing, mine are there.

![1548971831](https://user-images.githubusercontent.com/8085052/52088280-bce0df80-25ab-11e9-88aa-703cdb5625c4.png)

**Comment by anthonybilinski** [comment] 2019-01-31 22:42
The "couldn't load chat logs" portion sounds like a duplicate of https://github.com/qTox/qTox/issues/5451. SQLCipher package was updated to v4, which is incompatible with the format SQLCipher used to use (so the format that the history was saved in). qTox master will attempt to load history in a way that's compatible with DBs created by SQLCipher v3 (even when running SQLCipher v4). Could you try compiling master and see if that resolves your issue?

As for the messages not appearing - that's weird and should still work correctly even if history fails to load. If that still occurs after compiling master tip, could you post logs?

**Comment by raingloom** [comment] 2019-03-01 11:10
Ah frick, I forgot about this. So, turns out the other person was using some ancient version of qTox and that was causing the issue.

**Closed as completed** 2019-03-01 11:11 UTC
Labels: C-bug, O-need-info
