### ISSUE TITLE
Choosing camera in settings causing qTox to crashing

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#3612] opened 2016-08-10 12:34 UTC
##### Brief Description

OS: Windows 10 Anniversary Update
qTox version: v1.5.0-2-gf05b7e0
Commit hash: f05b7e0
Reproducible: Always
##### Steps to reproduce
1. Go to Audio/Video.
2. Select any camera in Video device.
3. Wait for crash.
##### Additional Info

Only opening device in qtox.log
`[12:25:23.737 UTC] src/video/camerasource.cpp:266 : Debug: Opening device  "video=@device_pnp_\\\\?\\display#int0f38#4&338c1d0d&0&uid134968#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\{0f35712a-70bd-494d-9ccd-5e2dac09cbc8}"`

**Comment by DX37** [comment] 2016-08-11 05:24
Still exist in  v1.5.1-2 23d08db.

**Comment by initramfs** [comment] 2016-08-11 05:26
If you have the older v1.4.0/v1.4.1 binaries around, mind trying that?

**Comment by DX37** [comment] 2016-08-11 05:38
I thinking this might be due to Anniversary Update. Cause I found stable v1.4.1.1 version and selecting cameras isn't working too (When on previous Windows 10 version it was working).
It's time to reinstall camera drivers? :laughing:

**Comment by initramfs** [comment] 2016-08-11 05:41
Yeah, that would be nice if you could try that.

**Comment by DX37** [comment] 2016-08-11 05:45
It's weird, because Windows can work with cameras. Maybe some methods was changed in update...

**Comment by initramfs** [comment] 2016-08-11 05:51
All underlying video code is essentially handled by FFmpeg (within qTox), if a previously working binary fails after a windows update, it's likely that routines within FFmpeg that create/initialize the video device no longer properly work. Though, this should not result in a crash of the application (unless FFmpeg itself crashes), I'll make a note of checking initialization results in subsequent changes to the video subsystem.

In the meantime, I can only ask that you narrow down the issue for us. I'll try qTox under Windows later (I have the anniversary update too).

**Comment by DX37** [comment] 2016-08-11 06:03
Driver update didn't work. qTox v1.5 and v1.4 still crashes.

And here I mean Windows, not qTox :smile: 

> Maybe some methods was changed in update...

**Comment by zetok** [comment] 2016-08-11 08:20
> All underlying video code is essentially handled by FFmpeg (within qTox), if a previously working binary fails after a windows update, it's likely that routines within FFmpeg that create/initialize the video device no longer properly work.

It's worth to note that recently FFmpeg version has been bumped for windows binaries, so if @DX37 didn't try with an old archived one, there's new FFmpeg being used in both versions.

**Comment by DX37** [comment] 2016-08-11 08:41
Hell no, I don't have any versions of qTox with old FFmpeg. I have a stable v1.4.1.1 barely found on [build.tox.chat](https://build.tox.chat) and it didn't work due to Anniversary Update, I suppose.

**Comment by initramfs** [comment] 2016-08-13 08:10
Okay, I can confirm the issue with Windows 10 Anniversary Edition.

**Comment by Re4mstr** [comment] 2016-08-13 13:34
I have the exact same issue.

**Comment by EoleDev** [comment] 2016-08-18 08:28
I just read this post which bring some information about the webcam problem in win 10 anniversary.
Hope it will help, and i hope the update announced will correct the problem.
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/9d6a8704-764f-46df-a41c-8e9d84f7f0f3/mjpg-encoded-media-type-is-not-available-for-usbuvc-webcameras-after-windows-10-version-1607-os?forum=mediafoundationdevelopment

**Comment by mike-mo** [comment] 2016-08-30 21:33
Hey guys, I was pointed to issues with your project in the MSDN forum thread linked above, and I decided to stop by to help you resolve these reports.

We managed to get a local repro of the crash reported here. It appears to be coming from an implementation of the `IBaseFilter::QueryVendorInfo` somewhere in qTox. By looking at the logs of our local repro and the information provided here, I traced it down to `CameraDevice`, which uses [ffmpeg's libavdevice](https://www.ffmpeg.org/doxygen/2.6/dir_ac0f646f7dac5d9f814abb87c8dfa999.html), which implements `QueryVendorInfo` in [line 154 of dshow_filter.c](https://www.ffmpeg.org/doxygen/2.6/dshow__filter_8c_source.html#l00154), where we find the potential culprit in line 160:

```
*info = wcsdup(L"libAV");
```

As per the [IBaseFilter::QueryVendorInfo method](https://msdn.microsoft.com/en-us/library/windows/desktop/dd389531%28v=vs.85%29.aspx) MSDN documentation:

> If the method is supported, it uses the **CoTaskMemAlloc** function to allocate memory for the string. Call the **CoTaskMemFree** function to free the memory.

So, because libavdevice in qTox is allocating the output string using `wcsdup()` instead of `CoTaskMemAlloc()` ([see some more information here](https://msdn.microsoft.com/en-us/library/aa366533%28VS.85%29.aspx)), the memory is allocated from a completely different heap. Subsequently, when our component in Windows attempts to free the string returned from this API using `CoTaskMemFree()`, the heap corruption seen in the crash is triggered.

The reason this wasn't an issue before the Windows 10 Anniversary Update, is because the component on the Windows side didn't call into the implementation of `IBaseFilter::QueryVendorInfo` for this scenario.

We understand that libavdevice may be a popular library, and we'll be reaching out to the ffmpeg team to help them resolve it, as it appears they're tracking the issue [here](https://trac.ffmpeg.org/ticket/5775). This means that qTox and other projects may get the fix once they make the necessary changes.

**Comment by EoleDev** [comment] 2016-09-03 01:45
It seems the ffmpeg teams apply a patch for this error which is include in their last build. May we have a new windows build with the library up to date to test it?

https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/18ce63a60e1bffc35b4df5d8a4f9a1ff1a96cb9a

**Comment by zetok** [comment] 2016-09-03 11:08
cc @nurupo ?

**Comment by nurupo** [comment] 2016-09-03 19:44
Did they release a ffmpeg version that fixes it?

**Comment by nurupo** [comment] 2016-09-03 19:52
Yep, none of the releases include that fix yet. Want me to re-build ffmpeg against its master/dev branch, risking breaking video completely?

**Comment by EoleDev** [comment] 2016-09-03 20:11
why would it break all the video features?
which ffmpeg version is used by qtox?

**Comment by nurupo** [comment] 2016-09-04 03:20
Ok, I have bumped ffmpeg's version from 3.1.1 to 3.1.3 and also patched it with the [the diff of the commit that supposedly fixes the DirectShow issue](https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff_plain/18ce63a60e1bffc35b4df5d8a4f9a1ff1a96cb9a?hp=a8e3833a61c31f8271a55e847e8556d96cb9048a), since that commit haven't made into any ffmpeg release yet.

Please try qTox nightly for Windows [x86](https://build.tox.chat/job/qTox_build_windows_x86_release/702/artifact/qTox_build_windows_x86_release.zip) and [x86-64](https://build.tox.chat/job/qTox_build_windows_x86-64_release/789/artifact/qTox_build_windows_x86-64_release.zip) and see if you can reproduce the issue now. Those nighties use the patched ffmpeg. The download links won't stay up for long, as we keep only N last nightly builds.

**Comment by EoleDev** [comment] 2016-09-04 09:22
Tks for the quick answer, i tried the x86_64 version and if the webcam is not use by another program, it works. But if the webcam is already in use, qtox freeze. I think it's another problem, and it is less important since we can use the webcam again :)
Same for the x86 version.

If i may ask it here, were can i find help to build windows version of qtox because the wiki is out of date?
(I tried a lot of things, building and cross building all the library, but i always end up with a library which is not found.)
Can you send me the information of how you build it?

Thank you verry much for this fix!!!

**Comment by DX37** [comment] 2016-09-05 11:09
It works now, but on my webcam from 720p, 480p, 360p and 240p modes, 480p and 240p acts weird, like on this screenshot:
![2016-09-05_18-08-04](https://cloud.githubusercontent.com/assets/12829428/18246144/d831cbc2-7393-11e6-899e-11d7917d9762.png)

**Comment by initramfs** [comment] 2016-09-05 11:23
@DX37 Mind sending logs?

**Comment by DX37** [comment] 2016-09-05 11:49
> @DX37 Mind sending logs?

[qtox.zip](https://github.com/qTox/qTox/files/454987/qtox.zip)

**Comment by Zibri** [comment] 2016-09-21 09:26
try this: right click on ffmpeg (and ffplay and ffprobe) then go to compatibility and select "run this program as administrator".

**Comment by initramfs** [comment] 2016-09-21 18:29
@DX37 The corrupted video output has been traced to another unrelated bug (and I am able to reproduce it). I'll see what I can do about that later.

**Comment by zetok** [comment] 2016-10-15 22:03
qTox `v1.5.2` was released some time ago with patched FFmpeg, thus closing.

As for the corrupted video, new issue should be opened if it's still reproducible.

**Closed as completed by zetok** 2016-10-15 22:03 UTC
Labels: C-bug, upstream, OS-windows, C-crash, M-video

**Comment by nurupo** [comment] 2017-02-03 02:58
FFmpeg 3.2.0 includes [the fix](https://github.com/FFmpeg/FFmpeg/commit/18ce63a60e1bffc35b4df5d8a4f9a1ff1a96cb9a), so I have updated FFmpeg on our build server from 3.1.3 to 3.2.2. The patching we did on top of 3.1.3 is obviously removed now, since the commit made it into the release.
