### ISSUE TITLE
How do you deliver updates? What about minisgn and The Update Framework?

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#2841] opened 2016-01-22 22:23 UTC
At first: Does the update procedure prevent downgrade attacks? (if you only take the signing part and ignore that the updates are delivered over HTTPS - consider a threat-model where the attacker can break the HTTPS connection)
Secondly: How do you sign the updates? With an RSA key?

I would suggest:
- **to use [Minisgn](https://jedisct1.github.io/minisign/)** (by @jedisct1)  
  It uses the Ed25519 elliptical curve and is therefore much more secure (and faster) than RSA keys. This also makes sure the security of the whole program is on the "NaCl-level" so that not only the E2E encryption uses such modern elliptic curves, but also 
- maybe **use [The Update Framework](https://theupdateframework.github.io/)** (by @theupdateframework)  
  it mitigates not only downgrade attacks, but much more bad things, which can happen when updating a software. Have a look at their website for more information.

**Comment by tux3** [comment] 2016-01-23 00:12
> At first: Does the update procedure prevent downgrade attacks?

Currently we allow downgrades by design so that people running unstable versions can go back to a stable version.
However we rely on HTTPS to prevent replay attacks, which makes downgrade attacks impossible.

> if you only take the signing part and ignore that the updates are delivered over HTTPS - consider a threat-model where the attacker can break the HTTPS connection

If an attacker can break HTTPS (which is a big IF), then they can run downgrade attacks.
This would be mitigated by the fact that qTox does not do automatic updates, it always asks the users and shows what version is to be installed.

However an attacker that can break HTTPS on the fly would have better opportunities to attack qTox users, for example by MITM'ing qTox developpers and using their credentials to compromise the code, the build system, or pivoting to another system.
If your attacker can break HTTPS, there's not much we can do that will still protect you.

> How do you sign the updates? With an RSA key?

We use Ed25519, as implemented by libsodium. 
If a PQ signing scheme proves to be solid, we could think about transitioning away from ECC in a handful of years.

> to use Minisgn (by @jedisct1)

Since we already use libsodium with Ed25519, this doesn't seem to offer any advantages.

> maybe use The Update Framework (by @theupdateframework)

That's an interesting idea, but it seems like it would add more complexity and attack surface to the system. Our current approach has the advantage of being very simple since it relies on HTTPS. 
Being trivially as secure as HTTPS/TLS is a Good Thing, because if TLS breaks you can be sure a lot of people will be interested in getting it fixed asap.

**Comment by rugk** [comment] 2016-01-23 09:27
Okay, thanks for the answers. Indeed it seems to be quite solid. 
But The Update Framework seems to mitigate [much more](https://github.com/theupdateframework/tuf/blob/develop/SECURITY.md) attacks. 

Maybe someone from @theupdateframework wants to comment on this. Otherwise I think this issue can be closed.

**Comment by tux3** [comment] 2016-01-23 15:48
I believe HTTPS will offer most or all the guarantees of the update framework, but I'll be happy to discuss it if someone wants to.

**Closed as completed by tux3** 2016-01-23 15:48 UTC
Labels: proposal, C-question
