### ISSUE TITLE
How should the auto login checkbox/feature behave on encrypted profiles?

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#1807] opened 2015-06-05 19:08 UTC
Right now it would make the user think that it doesn't work.
Solutions:
- check if the selected profile is encrypted and add a red note under the checkbox that says: "This option is not available for encrypted profiles."
- or the checkbox becomes grayed out, unchecked and unclickable until you select an unencrypted profile

**Comment by ProMcTagonist** [comment] 2015-06-05 19:59
It should work how encrypted profiles worked before the login window merged. You get a popup password dialog.

**Comment by zetok** [comment] 2015-08-29 23:06
> or the checkbox becomes grayed out, unchecked and unclickable until you select an unencrypted profile

It simply shouldn't be visible if encrypted profile is used.

**Comment by bhelm** [comment] 2016-02-02 09:29
yesterday i asked a friend why he is'nt online at tox, and he complained that tox does not store passwords without any reason and therefore does not autologin.

while writing this, i just noticed that the qtox profile creation Dialoge does not require to specify a password, but that is not obvious. if you are a skype user and not familiar with tox, you expect the profile creation dialog to sign you up somewhere on a central server that _requires_ a password specified. the profile creation dialog should make clear that the password is optional and if you specify a passwort, autologin will not be available - and that you are not signing up somewhere, just local.

to the question of this issue: i think the "Load automatically" checkbox should be greyed out on encrypted profiles and there should be a text displayed like "Auto-Login is disabled because you have a password on your profile. If you want to enable the Auto-Login feature, click here to remove the password".

**Comment by zetok** [comment] 2016-02-02 09:49
> (…) qtox profile creation Dialoge does not require to specify a password, but that is not obvious (…)

Yes, it was designed that way - i.e. no one can force user to use a password, but on the other hand, choosing a **not secure** option should be non-obvious.

> to the question of this issue: i think the "Load automatically" checkbox should be greyed out on encrypted profiles and there should be a text displayed like "Auto-Login is disabled because you have a password on your profile. If you want to enable the Auto-Login feature, click here to remove the password".

Right, thanks for reminding to close this issue - it was fixed in #2818.

(also, looks like windows release is outdated)

**Closed as completed by zetok** 2016-02-02 09:49 UTC
Labels: C-bug, proposal, P-low, M-ui
