### ISSUE TITLE
HiDPI - 2 Displays

### ISSUE THREAD

**Issue by nuneze54** [qTox/qTox#4618] opened 2017-09-01 19:38 UTC
##### Brief Description

OS: Windows 10 1703
qTox version: 1.11.0
Commit hash:  66b133c8d4a4d8f60e62475b0b56b509527b1488
toxcore:  0.1.9
Qt:  5.6.2
…

I have two displays, 3840x2160 (primary, 150% scaling) and 1920x1080. This messes with the DPI values.

If I have qTox on the secondary monitor the text in the title bar is too big while everything else is too small. On the primary monitor everything is fine.

[For example like this.](https://i.imgur.com/6YlxE34.png)

**Comment by Diadlo** [comment] 2017-09-02 09:44
Seems, duplicate of #975, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-09-02 09:44 UTC
