### ISSUE TITLE
History is corrupted after encrypting profile

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2142] opened 2015-08-30 11:10 UTC
1. Encrypt profile
2. logout
3. login
4. `[12:06:40.535] src/persistence/db/encrypteddb.cpp:104 : Warning: pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted`
5. no history -.-'

**Comment by zetok** [comment] 2015-08-30 11:13
Is that a duplicate of #1891 ?

**Comment by linux-modder** [comment] 2015-08-30 11:31
@zetok ,  not   quite .   SysD  has  been known to  ' fast  kill '  as in  sending : close  gracefully   >  kill -9 1  (almost  immediately)..  Which  causes  chat  logs to  go  poof.  This  is   more so  apparent  with  encrypted profile / chat logs  ( as the logging  is   synchronous  and  dies  in this  exchange.   Similar  behaviour  but  separate  events.

**Comment by zetok** [comment] 2015-08-30 11:38
@linux-modder that has nothing do to with systemd.

**Comment by linux-modder** [comment] 2015-08-30 11:43
@agilob ,

**Comment by linux-modder** [comment] 2015-08-30 11:43
@zetok ,  I  beg to differ  and  will obtain and  produce logs to that  effect in short order.  namely as it's not a  guaranteed   corruption and  has  only  been  reproduced   locally and  with  friends  on sysD systems  Post  sysD 218.x.   @agilob can you confirm this also  happens on a   unclean  kill of  qTox  >  reload ?

**Comment by agilob** [comment] 2015-08-30 13:23
killing qtox will result in unclosed database, in this case database is easy to recover with manual action. in my case database was cleared, after reading this error message I checked DB manually and it had 0 bytes (no tables, no rows) but was open and locked from modifications. completely different issue.

**Comment by tux3** [comment] 2015-10-23 12:18
Part of the problem is that the way we currently encrypt the database is absolutely insane. Essentially and from what I understood, we keep everything that ever happened as text SQL queries, encrypt/decrypt the resulting text file, and execute everything on startup, if anything unexpected happens it's super easy to corrupt the "database".

I think moving to the SQLite Encryption Extension instead of the current home-made hairball of mud would be a good start.

**Comment by tux3** [comment] 2015-12-19 04:02
Fixed by the new SQLCipher database code in master.

**Closed as completed by tux3** 2015-12-19 04:02 UTC
Labels: C-bug, P-very-high
