### ISSUE TITLE
Not able to start a second instance

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2410] opened 2015-10-17 18:02 UTC
Compared to https://github.com/tux3/qTox/issues/2408 I am not even able to start a second instance (with `./qtox`) when the profile of the first instance is already loaded.

```
./qtox
[19:55:22.225] src/persistence/settings.cpp:119 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
[19:55:22.226] src/ipc.cpp:45 : Debug: Our global IPC ID is  7121812055886993291
[19:55:22.226] src/ipc.cpp:63 : Debug: Attaching to the global shared memory
[19:55:22.226] src/main.cpp:141 : Debug: built on:  20:17:13 Oct 13 2015 ( 1444781660 )
[19:55:22.226] src/main.cpp:142 : Debug: commit:  41cba4ae5293e136a58dc17f4521c575e76e70a1 

[19:55:22.226] src/ipc.cpp:124 : Debug: postEvent  "activate" to 0
```

Only possible with `./qtox -p [profile]`. Formerly, I could use two instances with just `./qtox`.

**Comment by zetok** [comment] 2015-10-17 18:33
Well, this is not a bug - it is supposed to work like that, thus closing.

If it worked like that before, then it was a bug, and it got fixed.

**Closed as completed by zetok** 2015-10-17 18:33 UTC

**Comment by zetok** [comment] 2015-10-17 18:39
> [19:55:22.226] src/main.cpp:141 : Debug: built on:  20:17:13 Oct 13 2015 ( 1444781660 )
> [19:55:22.226] src/main.cpp:142 : Debug: commit:  41cba4ae5293e136a58dc17f4521c575e76e70a1 

Also, you should update, some fixes in regard to that has been merged since that build `:)`
