### ISSUE TITLE
Can't Use Group Calls (Cont.)

### ISSUE THREAD

**Issue by 159PlaysGames** [qTox/qTox#3254] opened 2016-05-05 03:31 UTC
##### Brief Description

OS: Windows 8.1
qTox version: 1.3.0 (It won't let me update)
Commit hash:  b69042ec407c30b27ce3e56bb6daf14300facc8e
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  My PC has a: 
Processor: Intel Core i3-3220 CPU @ 3.30GHz,
Ram: 6 GB
System Type: 64-bit
…

Reproducible: Always
##### Steps to reproduce
1. Call Group. (Fails)
##### Observed Behavior

I can't make group calls. (Normal calls work fine)
It won't let me join the call.
Call button is grayed out.
It won't let me update to 1.4.0
##### Additional Info

https://github.com/tux3/qTox/issues/3251
(Friend's Issue Report)

**Comment by initramfs** [comment] 2016-05-05 04:46
Try downloading and rerunning the installer on the main GitHub page to update to v1.4.0

**Comment by zetok** [comment] 2016-05-09 17:16
@antis81 but it's not an upstream bug?

**Comment by antis81** [comment] 2016-05-10 12:28
@zetok Well, group calls are non-functional in all qTox versions <1.4. The feature actually got implemented in 1.4. The issue is about not being able to upgrade on Windows -> this is what I understand as an "upstream" issue.

**Comment by zetok** [comment] 2016-05-10 12:46
> The issue is about not being able to upgrade on Windows -> this is what I understand as an "upstream" issue.

Um, I thought that the issue is about not being able to use group calls?

As for not being able to update, I think that it would be due to qTox updater – @159PlaysGames didn't really specify what doesn't let them to update :/

In any case, @159PlaysGames needs to re-test with newest version & provide more info.

**Comment by antis81** [comment] 2016-06-04 20:31
@159PlaysGames AFAIK you should be able to upgrade qTox to at least v1.4 now. Can you provide a short feedback please? Closing.

**Closed as completed by antis81** 2016-06-04 20:31 UTC
Labels: OS-windows, O-need-info, M-audio
