### ISSUE TITLE
qTox crashes after clicking the login button

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2541] opened 2015-11-09 12:17 UTC
It doesn't crash always but often.
https://gist.github.com/towlie/cf23cfd75fed707e14fe

bt full:
https://gist.github.com/towlie/0394ba0ba93ac1552ebe

**Comment by towlie** [comment] 2015-11-09 12:25
This also happened to me with qt5.4.2
But I don't have a debug version. 
I can only get this:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000668eb4a9 in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) () from C:\Users\noob\Desktop\qTox\Qt5Core.dll

```

**Comment by towlie** [comment] 2015-11-09 12:36
One of the commits made in the last days must have introduced this.

**Comment by tux3** [comment] 2015-11-09 15:37
Yep, at widget.cpp:138 we connect to 0xBAADFOOD since ProfileForm is only constructed at line 227.

@agilob It's your commit https://github.com/tux3/qTox/commit/7189844b2ad90f21f7b55c78b1b33953306b1636 that caused this, the fix is trivial so either send a PR now or I'll fix it later today when I get home

**Comment by tux3** [comment] 2015-11-09 15:38
Dup of #2540, but keeping this one open since it has more info

**Comment by agilob** [comment] 2015-11-09 15:39
Ah right, windows char escpaing... I right clicked on resource in qtcreator and selected copy resource link and it came with two slashes, so I assumed this is the right way :>

**Comment by tux3** [comment] 2015-11-09 15:43
@agilob Uhm. The problem isn't with the slashes :)
At line 138 you connect something to profileForm, but profileForm is not initialized before line 227. You're using uninitialized data.
Just move the connect after profileForm is constructed!

**Comment by TheNain38** [comment] 2015-11-09 20:33
@tux3 Why is this issue closed? It still crash

**Comment by towlie** [comment] 2015-11-09 20:53
Are you sure you updated? Otherwise we need a new backtrace. For me it looks fine so you may have an other crash?

**Comment by TheNain38** [comment] 2015-11-09 21:11
Yes, my qTox version is a052e3c452470ad97dd9deb1f24032dfbf89bd2c.
I'm on Windows 8.1 64-bits.
I don't know how I can get a backtrace using windows

**Comment by towlie** [comment] 2015-11-09 23:55
@TheNain38 I made a debug version for you so you can make a backtrace with gdb on windows.
Can you download this:
https://build.tox.chat/job/qTox_build_windows_x86-64_debug/lastSuccessfulBuild/artifact/qTox_build_windows_x86-64_debug.zip
And this:
https://www.dropbox.com/s/pz1ommbmfh4c8lp/qtox_gdb.zip?dl=0
1. Extract the folder from the qtox_gdb.zip file and add the qtox.exe to the "qtox_gdb" folder
2. run the "debug-blind-print-bt-and-app-output-on-crash.bat"
3. reproduce the crash
4. post the logfile here (it's inside the "debug-logs" folder)

**Comment by TheNain38** [comment] 2015-11-10 07:08
@towlie Thanks! Also I think debug builds should be built automatically so users could debug qTox without having someone build them.

**Comment by TheNain38** [comment] 2015-11-10 07:19
Sorry! I misread the title of this issue! It all works sorry. You can close this issue.

**Closed as completed** 2015-11-10 07:20 UTC
Labels: C-bug, U-low, OS-windows, C-crash

**Comment by towlie** [comment] 2015-11-10 10:49
@TheNain38 They are now build automatically. You just need to have gdb for windows.

**Comment by TheNain38** [comment] 2015-11-10 11:41
Now, I have it, thank you.
