### ISSUE TITLE
[Bug] Segmentation Fault

### ISSUE THREAD

**Issue by joaovarelas** [qTox/qTox#5070] opened 2018-04-11 16:24 UTC
##### Brief Description

OS: Debian 9
qTox version: 1.14.1 probably
Commit hash:  compiled from source
toxcore:  latest
Qt:  ...
Hardware: Asus K53SJ Laptop 2011 
…

Reproducible: Always

##### Steps to reproduce

1. ./qtox
2. Enter password
3. Segmentation fault

##### LOG

[16:14:03.932 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/r00t/.config/tox/qtox.ini"
[16:14:03.959 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  14847769369658670422
[16:14:03.959 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[16:14:03.959 UTC] ipc.cpp:253 : Debug: Previous owner timed out, taking ownership 4290226400718130511 -> 14847769369658670422
[16:14:03.960 UTC] main.cpp:255 : Debug: commit:  97bc4a9b4a864b0cd35b13cd56e75cb6d3abb4e1
[16:20:58.240 UTC] platform/posixsignalnotifier.cpp:121 : Debug: Signal 2 received
[16:21:00.964 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/r00t/.config/tox/qtox.ini"
[16:21:00.991 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  18110714496508675488
[16:21:00.992 UTC] main.cpp:255 : Debug: commit:  97bc4a9b4a864b0cd35b13cd56e75cb6d3abb4e1
[16:21:22.053 UTC] persistence/profile.cpp:111 : Debug: Loading tox save  "/home/r00t/.config/tox/toxic_profile.tox"
[16:21:22.193 UTC] persistence/settings.cpp:462 : Debug: "Saving global settings at /home/r00t/.config/tox/qtox.ini"
[16:21:22.452 UTC] persistence/settings.cpp:335 : Debug: Loading personal settings from "/home/r00t/.config/tox/toxic_profile.ini"
[16:21:22.453 UTC] nexus.cpp:87 : Debug: Starting up
[16:21:22.696 UTC] core/core.cpp:275 : Debug: Loading user profile
[16:21:22.696 UTC] core/core.cpp:148 : Debug: Core starting with IPv6 enabled
Segmentation fault

Picture:

![Screenshot](https://i.imgur.com/CMx0CjU.png)

**Comment by anthonybilinski** [comment] 2018-04-11 16:26
Duplicate of https://github.com/qTox/qTox/issues/4054. The root cause is a specific sqlcipher package version. There are workarounds you can try in the linked ticket.

**Closed as completed by anthonybilinski** 2018-04-11 16:26 UTC
Labels: U-low

**Comment by joaovarelas** [comment] 2018-04-11 16:46
Thank you @anthonybilinski
