### ISSUE TITLE
Big lag when making call with video activated on linux

### ISSUE THREAD

**Issue by kertase** [qTox/qTox#2963] opened 2016-02-19 18:52 UTC
Hi,

So when I activate a video device when a call gets accepted or ended from either side their is a big lag, the program stops working for about half a minute. Then resumes showing the video after about half a minute later. Or the chat when video is cancelled.

Actually only the interface stops working sound starts normally and works but the program just does not react and interface is frozen.

**Comment by zetok** [comment] 2016-02-21 15:22
Duplicate of #2716, thus closing.

**Closed as completed by zetok** 2016-02-21 15:22 UTC
Labels: C-bug, U-low, M-video
