### ISSUE TITLE
Group chats not saved after logout or quit

### ISSUE THREAD

**Issue by sebasped** [qTox/qTox#4109] opened 2017-01-30 10:00 UTC
##### Brief Description
Groups chats are not saved after logout or quit

OS: Linux (Parabola x64)  
qTox version: 1.7.1.
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment] 2017-01-30 11:20
This is currently a limitation of the Tox protocol, a WIP solution can be found here https://github.com/TokTok/c-toxcore/pull/295

**Comment by zetok** [comment] 2017-01-31 06:29
Duplicate of #896, thus closing.

**Closed as completed by zetok** 2017-01-31 06:29 UTC
Labels: U-low, upstream
