### ISSUE TITLE
Non Latin based Unicode Languages

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2315] opened 2015-09-28 18:33 UTC
Issue:
Unicode based languages does now prints in output window, one can see fine when one type but it sends an empty line to other person. Check following video
https://www.youtube.com/watch?v=8ZJ-qH9t2v0
How to reproduce:
Open any chat window and type any Arabic script language (Arabic, Persian, Urdu, Daari, Pastho etc)
for example you can copy paste my name
امجد شیخ
u can see it correctly where u paste it, but once u send it u just see an empty like. ok but if u add a normal Assci chartar infornt of it, like H or S, and then send it. then it will show it. Please check the video for more details.

**Comment by zetok** [comment] 2015-09-28 19:41
Duplicate of #1887, thus closing.

**Closed as completed by zetok** 2015-09-28 19:41 UTC
Labels: U-low
