### ISSUE TITLE
Symlinked video devices crash application

### ISSUE THREAD

**Issue by alojzjakob** [qTox/qTox#3026] opened 2016-03-21 02:51 UTC
Brief description:

I have a webcam and a tv tuner, which occasionally change device numbers (almost after every system reboot), so i made udev rules to have my webcam always as /dev/video-webcam and tv tuner as /dev/video-tv, instead of /dev/video0, video1...

Choosing symlinked video device crashes application when on settings screen and when clicking on Audio/Video tab.

Operating System: openSUSE Leap 42.1
qTox version: v1.3.0-38-ga48c422.
Hardware: some computer with some webcam and some tv tuner :D

Reproducible: Always

**Steps to reproduce:**  
1.  symlink video devices
2. choose Video device in qTox settings (symlinked one)
3. restart qTox
4. go to settings screen
5. click on Audio/Video tab

**Observed Behavior:**  
app crashes

**Expected Behavior:**  
Audio/Video settings screen shown, allowing me to change settings :)

**Additional info:**  
2016-03-21 03:27:48 qTox file logger starting
[03:27:48.815] src/main.cpp:170 : Debug: built on:  01:49:01 Mar 19 2016 ( 1458366367 )
[03:27:48.815] src/main.cpp:171 : Debug: commit:  a48c4225938834db0d4406cff54a07378e9636f4 

[03:27:48.815] src/nexus.cpp:81 : Debug: Starting up
[03:27:48.871] src/persistence/settings.cpp:1558 : Debug: Creating new profile settings in  ".//alojz.jakob.ini"
[03:27:51.922] src/persistence/profile.cpp:86 : Debug: Loading tox save  "./alojz.jakob.tox"
[03:27:52.020] src/core/coreencryption.cpp:88 : Warning: Decryption failed
[03:27:52.021] src/persistence/profile.cpp:127 : Critical: Failed to decrypt the tox save file
[03:27:55.681] src/persistence/profile.cpp:86 : Debug: Loading tox save  "./alojz.jakob.tox"
[03:27:55.879] src/persistence/settings.cpp:355 : Debug: "Saving global settings at ./qtox.ini"
[03:27:55.975] src/persistence/settings.cpp:296 : Debug: Loading personal settings from "./alojz.jakob.ini"
[03:27:56.774] src/core/core.cpp:236 : Debug: Loading user profile
[03:27:56.774] src/persistence/profile.cpp:249 : Debug: Loading tox save  "./alojz.jakob.tox"
[03:27:56.870] src/core/core.cpp:132 : Debug: Core starting with IPv6 enabled
[03:27:56.975] src/widget/systemtrayicon.cpp:93 : Debug: Using the Qt backend
[03:27:58.460] src/core/core.cpp:407 : Debug: "Connecting to 144.76.60.215:33445 (sonOfRa)"
[03:27:58.461] src/core/core.cpp:407 : Debug: "Connecting to 23.226.230.47:33445 (stal)"
[03:28:00.238] src/audio/audio.cpp:267 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[03:28:00.241] src/audio/audio.cpp:292 : Debug: Opened audio output "Built-in Audio Analog Stereo"
[03:28:00.259] src/audio/audio.cpp:225 : Debug: Opening audio input "Built-in Audio Analog Stereo"
[03:28:00.262] src/audio/audio.cpp:254 : Debug: Opened audio input "Built-in Audio Analog Stereo"
[03:28:00.350] src/video/camerasource.cpp:282 : Debug: Closing device  "none"
[03:28:00.350] src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video-webcam"

**Comment by zetok** [comment] 2016-03-21 11:08
Could you provide udev rules, so that anyone could test with renamed device?
`cd /dev && ln -s video0 video-webcam` works for me with no crash on a48c4225938834db0d4406cff54a07378e9636f4.

Which makes me wonder if it's not a problem with how qTox handles your webcam.

Could you perhaps provide a backtrace?

**Comment by sudden6** [comment] 2016-03-21 12:50
I also can not reproduce on https://github.com/tux3/qTox/commit/a48c4225938834db0d4406cff54a07378e9636f4 with openSUSE Leap 42.1

could you additionally provide the output of `v4l2-ctl -d /dev/video-webcam --list-formats-ext` ?

**Comment by alojzjakob** [comment] 2016-03-21 13:06
udev rules:

```
# Webcam - new
KERNEL=="video[0-9]*", ATTR{name}=="USB2.0 Camera", SYMLINK+="video-webcam"
# TV
KERNEL=="video[0-9]*", ATTR{name}=="cx88*", SYMLINK+="video-tv"

```

![image](https://cloud.githubusercontent.com/assets/17972823/13919460/e1ad1422-ef6d-11e5-802d-882ca37c02c5.png)

**Comment by Sheykhnur** [comment] 2016-03-24 17:38
Confirm, Archlinux x86-64, qtox version: 1.3.0-1, click on Audio/Video settings crash app with message:
[20:34:51.454] ../src/video/camerasource.cpp:282 : Debug: Closing device  "none"
[20:34:51.469] ../src/video/camerasource.cpp:209 : Debug: Opening device  "/dev/video0"
[video4linux2,v4l2 @ 0x2045d60] Cannot find a proper format for codec 'mjpeg' (id 8), pixel format 'none' (id -1)
Assertion *codec_id != AV_CODEC_ID_NONE failed at libavdevice/v4l2.c:809
Аварийный останов (core dumped)

Output list  v4l2-ctl -d /dev/video0 --list-formats-ext:
ioctl: VIDIOC_ENUM_FMT
        Index       : 0
        Type        : Video Capture
        Pixel Format: 'YUYV'
        Name        : YUYV 4:2:2
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 160x120
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 320x240
                        Interval: Discrete 0.033s (30.000 fps)

**Comment by sudden6** [comment] 2016-03-24 18:43
@Sheykhnur I think this problem should be fixed by https://github.com/tux3/qTox/commit/3f89cd95d5399814461f5dae8d7e2a524637988e

If you build the latest master it should work.

**Comment by Sheykhnur** [comment] 2016-03-25 18:57
Yes, it is, building from latest master solved the problem.

**Closed as completed** 2016-04-21 22:20 UTC
Labels: C-bug, OS-linux, O-need-info, C-crash, M-video
