### ISSUE TITLE
qTox crashed when created passwort protected account

### ISSUE THREAD

**Issue by smschumacher** [qTox/qTox#4178] opened 2017-02-15 23:47 UTC
##### Brief Description

OS: Debian 9 Stretch with Gnome, Linux mars 4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux
qTox version:   qTox version v1.6.0-obs.
Commit hash:  5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore: 0.0.0 
Qt: Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu. Obvious rather old for a rather new system stretch. Should I consider updating it? Password creation works on my colleagues ubuntu desktops with out any problems, so I guess the problem is either related to qt or gnome and any of its libs.

qTox crashes always when either trying to create a password protected account. Accounts with Password Protection can be created without problem. What follows is the debug information printed out on the console. 

[23:29:58.611 UTC] nexus.cpp:85 : Debug: Starting up
[23:30:19.548 UTC] persistence/settings.cpp:2383 : Debug: Creating new profile settings in  "/home/stefan/.config/tox//stefan_encrypted.ini"
[23:30:19.794 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/stefan/.config/tox/qtox.ini"
[23:30:19.916 UTC] persistence/settings.cpp:358 : Debug: Loading personal settings from "/home/stefan/.config/tox/stefan_encrypted.ini"
Speicherzugriffsfehler

Trying to set a new password from within the client  also crashes in 100% of the cases.

[23:40:07.662 UTC] persistence/profile.cpp:390 : Debug: Saving tox save to  "/home/stefan/.config/tox/stefan.tox"
Speicherzugriffsfehler

Contact me if you need any additional information. if you provide a debug build I know how to use it with gdb to isolate the problem.

**Comment by tux3** [comment] 2017-02-16 03:23
Please note that qTox is not compatible at all with Qt 4.8.7, you need at least Qt 5.3.0 (although I suspect that if you didn't have Qt 5 qTox wouldn't have started at all).

Edit: This seems to be a duplicate of #4054, this is a bug with the sqlcipher package in Debian. Downgrading to a previous version of sqlcipher fixes the problem in the meantime.

**Closed as completed** 2017-02-16 03:46 UTC
Labels: U-low, OS-linux, P-high, C-crash
