### ISSUE TITLE
Partial public key

### ISSUE THREAD

**Issue by Lionel-Fr-56** [qTox/qTox#4561] opened 2017-08-05 11:19 UTC
##### Brief Description

OS: Mac OS X Sierra 10.12.6 (16G29) Darwin 16.7.0
qTox version: v1.11.0.
Commit hash:  
toxcore:  0.1.0
Qt:  5.9.1
iMac14,1 Intel Core i5 4 cores 2,7 GHz cache 256 Ko level 3 4 Mo memory 8 Go
boot ROM IM141.0118.B47 Version SMC :	2.14f24 system : C02NDAYKF8J2
 
…

Reproducible: Always

Hi all, i'm French, sorry for my language.
I take this opportunity to tell you that I have translated all the chains of the French language. So, if the changes can be included by someone. It may be automatic ... ?

##### Steps to reproduce

1. Right clic on a contact name
2. Choose "Show details"
3. In "Public key" right clic on characters chain
4. Select All
5. Copy
6. Paste

##### Observed Behavior
When we paste the result, the public key is too short and numbers and letters are missed.
We obtain a partial number that we can't share with someone.

##### Expected Behavior
A full characters chain.

##### Additional Info
Maybe it will be cool to have a COPY button.
Just have a clic on the button and then can paste the full result.

**Comment by Diadlo** [comment] 2017-08-05 12:11
Seems, duplicate of #235, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-08-05 12:11 UTC
Labels: U-low
