### ISSUE TITLE
qTox segfault on group audio talk

### ISSUE THREAD

**Issue by quininer** [qTox/qTox#1995] opened 2015-07-12 12:52 UTC
In the group playing music, the qtox user may cause crashed.
This bug can not be reproduced stable, but it does exist.

OS: ArchLinux, Ubuntu, etc..
Reproducible: Sometimes

https://gist.github.com/quininer/b439d760e23575e305bc

tox-git
r3458.7225725-1
qTox 
Git commit: cfeeb03c5ba1da034ebd6b3d04c05972c7a8ad8f

---

Seems uTox also have this problem, so there may be toxcore the bug?

**Comment by zetok** [comment] 2015-07-17 09:02
qTox 965f871d0c88eac6752a9a84833c77d92922715a
backtrace: https://gist.github.com/zetok/8bd1c2386029b0944502

**Comment by quininer** [comment] 2015-07-17 09:05
I have observed, the last contents of the log is always `Group namelist change`.

**Comment by zetok** [comment] 2015-08-30 10:33
Hopefully #2094 will help with it.

**Comment by zetok** [comment] 2015-09-23 18:14
From #2285, thanks to @sudden6 :

My qtox version: a53f6f2adfff59b28fa27fb522ccff235d7a7e58

This was caused by one of the participants closing qtox.

**Comment by zetok** [comment] 2015-10-22 07:08
Should be fixed by #2415, thus closing.

If you still have this issue, please comment for reopen.

**Closed as completed by zetok** 2015-10-22 07:08 UTC
Labels: C-bug, P-medium, C-crash, M-audio
