### ISSUE TITLE
Text between two hyphens shouldn't be underscored. Need tooltip with markup help.

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3407] opened 2016-06-16 20:59 UTC
If this is intended then this isn't a generally expected behavior.

qTox should display an explanation of markup that it supports. I suggest this is done in a tooltip over the edit area.

OS: FreeBSD 10.3
qTox version: 1.4.1
Qt:  5.5.1

**Comment by zetok** [comment] 2016-06-16 21:23
Duplicate of #3404, thus closing.

**Closed as completed by zetok** 2016-06-16 21:23 UTC
Labels: U-low
