### ISSUE TITLE
Playback and capture devices are set to 'None' by default

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2631] opened 2015-12-06 15:54 UTC
Hello,

Reproduce:
1. Download or compile latest qTox
2. Clear your ~/.config/tox directory so that the settings get reset to the default
3. Start qTox
=> Playback and capture devices are set to 'None'

Video device is also set to 'None' by default but that's okay for me and makes sense.

**Edit:** Playback device is done now -> https://github.com/tux3/qTox/pull/2633

**Comment by antis81** [comment] 2015-12-11 12:32
I'll have a look at this after #2509 got merged.

**Comment by tux3** [comment] 2015-12-11 12:34
I think this is fixed by #2633 actually.

**Comment by ovalseven8** [comment] 2015-12-11 12:37
@tux3: Well, capture device not.

**Comment by JacobHenner** [comment] 2015-12-11 18:13
@ovalseven8 I can fix that too, but I believe there were privacy implications of a default capture device mentioned on IRC. If there are no objections, I'll fix it and introduce a PR.

**Comment by TheNain38** [comment] 2015-12-12 07:13
@JacobHenner For capture device? Do you mean: if I disconnect my headphones then it would use my webcam? I don't really like that idea then... because skype is doing that and it's annoying... Sometimes I mute my microphone on hardware, and then I disconnect it, but then it uses my webcam and the sound isn't muted...

**Comment by antis81** [comment] 2015-12-12 08:31
@TheNain38 No, it's related to audio devices only (and to the qTox settings) - not to the webcam or any video devices at all. Even if your webcam has a microphone builtin, it's still a separate audio device in qTox. This is our beloved crazy modern world… :)

**EDIT:** "Capture device" == "microphone" :smile:

**Comment by TheNain38** [comment] 2015-12-12 09:28
Yes, I know this is a separate audio device, but when I disconnect my headphones I don't want my webcam's microphone to be used.

**Comment by JacobHenner** [comment] 2015-12-14 04:06
@antis81 @TheNain38 I think the idea was you might start a video or audio call, and the audio source automatically selected might not be the one you intended (i.e. perhaps a virtual audio device for your system's sound output instead of the microphone).

**Comment by ovalseven8** [comment] 2015-12-31 16:20
Somebody has broken it again...

**Comment by JacobHenner** [comment] 2015-12-31 17:08
I can investigate later.

**Comment by antis81** [comment] 2015-12-31 18:23
@JacobHenner Have a look at #2711 / #2743

**Comment by ovalseven8** [comment] 2016-03-12 10:15
P-high

**Comment by antis81** [comment] 2016-06-04 15:30
This is correct behavior by design. By default (e.g. when qTox is started for the first time), audio (and video) is simply disabled and has to be enabled in settings.

Actually it is not possible to start an audio call without both a configured audio input and output device. Thus, the audio call button in chat window should be disabled in this case and provide a visual hint (probably an overlay icon like an "exclamation mark"  or a "strikethrough" or something); additionally a tooltip should provide the information, that audio input and/or output device is disabled and a call cannot be started.

**Comment by zetok** [comment] 2016-06-04 17:53
> This is correct behavior by design.

No, it isn't correct behaviour. When qTox is started for the first time, it should try to use available video & audio input when user makes a call.

Going into settings is justifiable only when user doesn't want a/v input to be used by qTox, or wants to choose different a/v device for a/v input.

**Comment by antis81** [comment] 2016-07-14 13:34
@ovalseven8 Could you verify, this is fixed?

**Comment by zetok** [comment] 2016-07-14 21:41
Seems to be working for me with

``` bash
cd dir
export HOME=$PWD
export TMPDIR=$PWD
qtox
```

**Comment by zetok** [comment] 2016-09-07 11:18
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.

**Closed as completed by zetok** 2016-09-07 11:18 UTC
Labels: C-bug, proposal, O-need-info, M-audio
