### ISSUE TITLE
Video does not work

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#2245] opened 2015-09-17 11:18 UTC
Win7 32bit + Debian Jessie 32bit.
Black video windows on both sides. Audio ok. Video preview ok on both sides.
After conversation finished, the camera rest active - qTox restart required.

Win version updated today, Debian version updated yesterday.

**Comment by agilob** [comment] 2015-09-17 11:46
duplicate of and #1971 will be closed by #2093

**Closed as completed by agilob** 2015-09-17 11:46 UTC
Labels: C-bug, U-low, M-video

**Comment by ElLamparto** [comment] 2015-09-17 11:54
Ok, but the trick of going to AV settings does not work in my case. Still no video.

**Comment by agilob** [comment] 2015-09-17 12:44
It doesn't work always, for me it worked after 30seconds after visiting a/v settings tab. #2120. The fix is in `work in progress` branch, but apparently work has been suspended :<
