### ISSUE TITLE
Tooltips unreadable

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1936] opened 2015-06-29 14:36 UTC
http://fs2.directupload.net/images/150629/2yponpgz.png

**Comment by agilob** [comment] 2015-06-29 15:16
Duplicate.
Solved in new style.
![snapshot2](https://cloud.githubusercontent.com/assets/2544251/8411126/2b68b3f2-1e7a-11e5-8139-da790b283d7a.png)

**Comment by zetok** [comment] 2015-08-30 09:34
Duplicate of #1583, closing.

**Closed as completed by zetok** 2015-08-30 09:34 UTC
Labels: C-bug, U-low
