### ISSUE TITLE
Drag and Drop should work with text input area

### ISSUE THREAD

**Issue by LittleVulpix** [qTox/qTox#2847] opened 2016-01-23 21:27 UTC
Almost everyone who uses qTox initially tries to drag and drop files into the text input area, because it's considered to be the input area for any kind of input. I agree and when I first tried qTox to understand what's going on, I realized drag and drop only works if you drop atop of the chat history, which doesn't make much sense.

tl;dr - drag and drop should work even if you drop the file atop of the text input area. Currently it gives you the "browser" file path, e.g.

file:///C:/Users/poorperson/Desktop/somefile.txt

appears in the chat instead of the transfer being initiated.

**Comment by zetok** [comment] 2016-01-24 00:52
Kinda a duplicate of #1947.

**Comment by LittleVulpix** [comment] 2016-01-24 01:21
Interesting, yeah I looked over issues but didn't stumble upon this one. Why does the "paste path" behavior exist at all? You only ever drag and drop a file to someone when you intend to send it.

**Comment by sudden6** [comment] 2016-03-27 22:22
The behaviour of drag and drop seems to have been changed. Now the whole chat + text input area act the same. Thus I will close this issue.

**Comment by zetok** [comment] 2016-05-05 07:52
Apparently that works only on Linux – windows still has old behaviour, thus reopening.

```
<LittleVulpix> zetok: Also why the hell does it still only paste the file path when you drag and drop a file into the input box x3 Everyone who ever sends me a file says it is not workin and then I have to explain that you need to drop the file into the "history" i.e. the area where you normally cannot input anything :D
<LittleVulpix> It doesn't work on windows... neither in 1.3 nor in 1.4
```

**Comment by LittleVulpix** [comment] 2016-05-05 08:04
Example of different behavior depending upon where you drop the file.
![Imgur](http://i.imgur.com/et0sjtp.gif)

**Comment by Talkless** [comment] 2016-06-19 16:27
I've tested this behaviour on Kubuntu 14.04 (my OS), Debian 8 GNOME, Debian 8 KDE, Kubuntu 15.10, Kubuntu 16.04, Xubuntu 16.10, Ubuntu 16.10  and Windows 10.

This works only on Kubuntu 15.10 and Kubuntu 16.10 for some reason.

> Now the whole chat + text input area act the same

Maybe event does not fall through to that parent widget somehow.

Is anyone working on a fix? Or should I try that?

**Comment by zetok** [comment] 2016-06-19 16:30
> This works only on Kubuntu 15.10 and Kubuntu 16.10 for some reason.

Most likely Qt version – works for me on 5.5.1

**Comment by Talkless** [comment] 2016-06-19 17:02
All 16.04 *ubuntu systems should have same Qt version, though behaviour is different. Just rechecked again on Ubuntu 16.04, qTox compiled with 5.5.1, and dragging file onto text input produces only file:// link.

@zetok what's your system?

**Comment by zetok** [comment] 2016-06-19 20:02
> @zetok what's your system?

Gentoo, using Thunar as file manager

**Closed as completed** 2016-06-25 15:15 UTC
Labels: OS-windows, M-ui, proposal-accepted
