### ISSUE TITLE
Bug, when receiving an action message, when reloading history, the sender name is displyed twice

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2336] opened 2015-10-04 07:48 UTC
Reproduce:
- Create two profile
- Send an action message to the other
- Close and reopen receiver's qTox
- See that there is the sender's name twice

**Comment by ovalseven8** [comment] 2015-10-04 08:00
Can reproduce.

**Comment by zetok** [comment] 2016-07-12 18:18
Can't reproduce on ef5c094417b15db67b1b8736b5153a3cd221f488, thus closing.

If it's still reproducible with newest qTox, please comment for reopen.

**Closed as completed by zetok** 2016-07-12 18:18 UTC
Labels: C-bug
