### ISSUE TITLE
The character 'U+200C' is not supported!

### ISSUE THREAD

**Issue by Hitaro** [qTox/qTox#3915] opened 2016-11-23 19:29 UTC
`U+200C` is a popular unicode character for Persian, Arabic, Hebrew, etc.

- Without `U+200C`, e.g: آنها
- With `U+200C`, e.g: آن‌ها

More Examples:
![screenshot_20161123_225427](https://cloud.githubusercontent.com/assets/18015032/20575752/dbd1b8e4-b1cf-11e6-8f38-3bf0830b9402.png)

---
OS: Linux (Debian)  
qTox version: v1.6.0
Qt version: 5.7.0

**Comment by zetok** [comment] 2016-11-23 19:55
Can't reproduce the issue on newest qTox, what are the steps and which exactly qTox version are you using (should be shown in Settings→About)?

**Comment by Hitaro** [comment] 2016-11-24 03:51
The version: 1.6.0

![screenshot_20161124_070323](https://cloud.githubusercontent.com/assets/18015032/20585956/d0c8c42a-b214-11e6-82d5-541eea1b1a01.png)

Steps:
1. Using standard persian keyboard layout:, type/copy `آن`
2. `Shift`+`Spacebar` to insert `U+200C` character.
3. Type `ها`

==> It should be `آن‌ها`, but in qtox it is `آنها`, that means the inserted character has been ignored!

    آن = that one
    آن‌ها = those
As you can see, U+200C is supported in GitHub editor.

**Comment by Hitaro** [comment] 2016-11-24 03:54
You can find more details here: https://en.wikipedia.org/wiki/Zero-width_non-joiner

**Comment by Diadlo** [comment] 2017-01-18 06:17
Can't reproduse. Can you test it?
```
You are using qTox version v1.7.0-56-ga4537549.
Commit hash: a4537549c0c53a88a47ca7a06cf276f0430eb43e
Qt version: 5.7.1
```
![image](https://cloud.githubusercontent.com/assets/6306608/22052991/e058e27e-dd5e-11e6-851b-21db54a78e0f.png)

**Comment by Diadlo** [comment] 2017-02-24 08:47
Needed info not provided for over a month, thus closing.

**Closed as completed by Diadlo** 2017-02-24 08:47 UTC
Labels: C-bug, upstream, OS-linux, O-need-info

**Comment by parsedarweb** [comment] 2017-02-27 15:35
It has been a bug within Qt project ([+](https://bugreports.qt.io/browse/QTBUG-42074)) that has been solved and will be released with the next version.
