### ISSUE TITLE
Discussion: Bring qTox forward

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2299] opened 2015-09-25 19:40 UTC
The development of qTox has slowed down for a while now and the issues are growing and growing. I think it's time to speak about how we can improve the current situation and really bring qTox forward. Just waiting for new developers or better times isn't the solution we should trust.
Actually, qTox is probably the most important client for Tox and should be boosted.

We have almost 400 (!) open issues with some really important stuff. Unfortunately, there hasn't been much progress for some time. The most important goal should be - beside working on new ToxAV or/and groupchats - to fix all the issues and cleanup the code.

qTox is a big software project now and needs constant maintenance. Because of time reasons, our main developer, @tux3, doesn't seem to have much time for writing/fixing code. Additionally, the GSoC 2015 is over and @TheSpiritXIII won't work on qTox any longer as far as I know.

Let's discuss how we can improve the situation. I'm of the opinion that we need progress.

**Some suggestions:**
- Create a fundraising campaign like toxcore did and collect money for (full-time?) development.
  - Who could work on qTox constantly or full-time with some monetary support? @tux3 eventually?
- Supporting developers via [Patreon.com](https://www.patreon.com/)?
  - Same question again. Who could work on qTox and how much money is needed?
  - Perhaps contacting companies that are interested in supporting qTox?
- Using platforms like [Bountysource](https://www.bountysource.com/)?
- Writing a blog post on blog.tox.chat with searching for new developers
  - Perhaps, but isn't enough.
- Make a weekly todo-list with items that should be finished after the week.
  - With a specific goal the motivation is perhaps raising and we can work together and divide the efforts.

**Summary:**
We need skilled developers working on qTox.

What do you think?

**Comment by Jeeppler** [comment] 2015-09-25 22:43
@TheSpiritXIII has done a lot of work, still his work is far away from being merged. I guess merging those changes would solve a lot of issues. Then qTox alpha/beta or something like that should be released for testing and after the testing phase as new client.

**Comment by agilob** [comment] 2015-09-26 07:17
I was thinking about cherry-picking some of the commits in his WIP branches. At least some issues would be solved.

**Comment by antis81** [comment] 2015-09-26 07:49
@TheSpiritXIII Is it true you're not contributing any longer to qTox for whatever reasons? Would you help in reviewing the stuff occasionally as required (no coding) until done?

In case TheSpiritXIII is no longer working on qTox, I'd happily go through the outstanding PR's and cherry-pick the good stuff. @agilob If you like, we can divide the work and pick (and separate) the branches onto master (creating new PR's). We can further clear that in qTox chat. :)

**Comment by zetok** [comment] 2015-09-26 08:11
Weird, I thought that I posted comment here, but it would seem that I forgot to press the button..

anyway, posting again.

# 

@Jeeppler

> I guess merging those changes would solve a lot of issues.

Well. First, those PRs conflict against master, which makes them _harder_ to merge.
Additionally, most (all?) of them introduce some regressions, which would be _harder_ to fix without @TheSpiritXIII's help, since he knows the best code he wrote.

Now, since @TheSpiritXIII doesn't have time to work on qTox, it will be slow & hard to get those PRs to merge.

PRs that most likely (for sure?) will be merged are #2013, and (partially?) #2093, #2094.

> Then qTox alpha/beta or something like that should be released for testing and after the testing phase as new client.

qTox is alpha.

Currently there's `testing` branch, to which changes are being pushed and build as `qTox-testing` on jenkins - not available as packages though.

# 

@antis81 yeah, I've talked to @TheSpiritXIII yesterday on IRC, and he apparently doesn't have much free time - he's busy with school, and he soon has exam(s?).

**Closed as completed** 2015-10-14 15:01 UTC
Labels: metabug
