### ISSUE TITLE
Segmentation fault on MX Linux (Debian Stretch)

### ISSUE THREAD

**Issue by TheOuterLinux** [qTox/qTox#5045] opened 2018-04-02 20:08 UTC
##### Brief Description

OS: MX Linux (Debian Stretch)
qTox version: 96ae4284a09df48fda2cdd0868779ec32a9d18de
Commit hash:  96ae4284a09df48fda2cdd0868779ec32a9d18de
toxcore:  https://github.com/toktok/c-toxcore.git
Qt:  5.7.1
Hardware:  Macbook Pro 11,1
…

Reproducible: Always 

##### Steps to reproduce

1. Launch qTox either from menu or Terminal
2. Error is the same if creating a new or using an old profile

##### Observed Behavior
```
[19:49:56.768 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from ~/.config/tox/qtox.ini"
[19:49:56.790 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  13925890465333398094
[19:49:56.790 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[19:49:56.790 UTC] ipc.cpp:253 : Debug: Previous owner timed out, taking ownership 14457243139466015112 -> 13925890465333398094
[19:49:56.790 UTC] main.cpp:255 : Debug: commit:  96ae4284a09df48fda2cdd0868779ec32a9d18de
[19:50:01.495 UTC] persistence/profile.cpp:111 : Debug: Loading tox save  "~/.config/tox/Example.tox"
[19:50:01.556 UTC] persistence/settings.cpp:459 : Debug: "Saving global settings at ~/.config/tox/qtox.ini"
[19:50:01.567 UTC] persistence/settings.cpp:332 : Debug: Loading personal settings from "~/.config/tox/Example.ini"
[19:50:01.567 UTC] nexus.cpp:87 : Debug: Starting up
[19:50:01.796 UTC] core/core.cpp:269 : Debug: Loading user profile
[19:50:01.796 UTC] core/core.cpp:143 : Debug: Core starting with IPv6 enabled
[19:50:01.798 UTC] core/core.cpp:213 : Warning: Core failed to start with IPv6, falling back to IPv4. LAN discovery may not work properly.
[19:50:01.866 UTC] persistence/profile.cpp:76 : Debug: Self avatar not found, will broadcast empty avatar to friends
Segmentation fault
```

##### Expected Behavior
No errors

##### Additional Info
I completely blocked ipv6, but that shouldn't cause any issues, especially when toxic runs fine without it.

**Comment by TheOuterLinux** [comment] 2018-04-02 20:11
Apparently, "~" means lineout in GitHub speak. I tried clicking "Edit comment," but it wont let me.

**Comment by tox-user** [comment] 2018-04-02 21:35
Can you see if a profile without a password will work?

**Comment by TheOuterLinux** [comment] 2018-04-02 22:07
It works when I create a profile without a password. That's weird. And, the profile I made a long time ago that I'd like to use has one too :/

**Comment by anthonybilinski** [comment] 2018-04-02 23:11
Looks like a duplicate of https://github.com/qTox/qTox/issues/4054, upstream issue with sqlcipher packaging. There are a couple workarounds mentioned in that ticket (i.e. downgrading or upgrading from the version specifically) as well as links to the upstream ticket.

Your encrypted profile should still be safe and accessible once you have access to a different sqlcipher version, either by copying your profile onto another machine or changing the version you have installed.

**Closed as completed by anthonybilinski** 2018-04-02 23:11 UTC
Labels: U-low
