### ISSUE TITLE
logs error at login

### ISSUE THREAD

**Issue by adrian-purism** [qTox/qTox#2765] opened 2016-01-02 19:22 UTC
got this msg error and i cannot see any previous  chat log
![qtox-error](https://cloud.githubusercontent.com/assets/16197525/12075837/f1acab1a-b16c-11e5-8116-f53a044d67e6.png)

Adrian.-

**Comment by zetok** [comment] 2016-01-02 19:28
Could you provide more info?

https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports

**Comment by adrian-purism** [comment] 2016-01-02 19:32
am using the debian package of qtox version:
ii  qtox                                  406-7f34290                          amd64        The best Tox client.

what else you need am starting the app and after that i got that error not sure what else details i can provide, let me know

Cheers Adrian.-

**Comment by adrian-purism** [comment] 2016-01-02 19:37
gdb output:
(gdb) run 
Starting program: /usr/bin/qtox 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0136700 (LWP 4649)]
[New Thread 0x7fffef72a700 (LWP 4650)]
[16:36:32.104] src/persistence/settings.cpp:119 : Debug: "Loading settings from /home/adrian/.config/tox/qtox.ini"
[16:36:32.104] src/ipc.cpp:46 : Debug: Our global IPC ID is  9191447625833715715
[16:36:32.104] src/main.cpp:143 : Debug: built on:  15:45:13 Dec 30 2015 ( 1451508130 )
[16:36:32.104] src/main.cpp:144 : Debug: commit:  7f34290129b99eafeac226ba2e908476fa209802 

[16:36:32.105] src/nexus.cpp:82 : Debug: Starting up
[16:36:39.053] src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/adrian/.config/tox/alvesadrian.tox"
[16:36:39.262] src/persistence/settings.cpp:345 : Debug: "Saving global settings at /home/adrian/.config/tox/qtox.ini"
[New Thread 0x7fffed374700 (LWP 4651)]
[16:36:39.345] src/persistence/db/rawdatabase.cpp:374 : Warning: Failed to prepare statement "SELECT count(*) FROM sqlite_master" with error 26
[16:36:39.345] src/persistence/db/rawdatabase.cpp:70 : Warning: Database is unusable, check that the password is correct
[16:36:39.345] src/persistence/history.cpp:191 : Warning: Database not open, init failed
[16:36:39.345] src/persistence/profile.cpp:56 : Warning: Failed to open history for profile "alvesadrian"

[qtoxlog.txt](https://github.com/tux3/qTox/files/76370/qtoxlog.txt)

**Comment by adrian-purism** [comment] 2016-01-11 14:06
do you need more info about this issue?

**Comment by tux3** [comment] 2016-01-14 13:06
@adrian-purism Do you have the package "libsqlcipher0" installed?

The error message could mean 3 possible things:
- The SQLCipher library is not working correctly on your system
- The database is somehow encrypted with a different password than your profile password
- The database is corrupt and can't be decrypted at all (unlikely)

**Comment by adrian-purism** [comment] 2016-01-14 14:11
yes i have libsqlcipher0 installed, how can i fix this? beacuse if i remove all my profile i will lose everything and i cannot login again after reinstall it because qtox only shows new profile and i cannot loging with my previous user and pass

**Comment by adrian-purism** [comment] 2016-01-14 14:18
in a fresh install "load profile" is not available and also i cannot type my username because i need to pick it from a list

**Comment by adrian-purism** [comment] 2016-01-31 13:22
any update on this issue? yes i have libsqlcipher0 installed,

**Comment by tux3** [comment] 2016-03-11 23:22
It looks like your database is corrupt, unfortunately there's no way to recover it since it's strongly encrypted.
If you or anyone runs into this issue again, or if you find a way to reproduce the issue reliably, **please** leave a comment. 
But without any way to reproduce, this bug seems to have been an unfortunate isolated corruption, so I don't think there's much we can do. Closing for now.

**Closed as completed by tux3** 2016-03-11 23:22 UTC
Labels: C-bug, P-very-high, O-need-info
