### ISSUE TITLE
Add ability to change background color of chat window, or just Dark Mode

### ISSUE THREAD

**Issue by UralZima** [qTox/qTox#4293] opened 2017-03-26 11:46 UTC
Hello. About 5 years I use only White on Black scheme everywhere. I have 4 monitors, everything is black by default. Also I use browser extension to do this for web.
The reason is one: LED destroys your eyes, because white is blue led + phosphoric luminofor that makes white. Too much ultraviolet hurts your eyes. I feel much more comfortable as I do.

I don't use qTox only for that reason, I don't like white background. I use Toxic now, but want to use qTox. 

Please make an option 'Dark Mode' or color selection for messaging window.

Thank you very much.

**Comment by zetok** [comment] 2017-03-26 12:01
Duplicate of #1639, thus closing.

**Closed as completed by zetok** 2017-03-26 12:01 UTC
Labels: U-low, M-ui
