### ISSUE TITLE
'\u2028' illegal character comes with copied messages when there is a line space

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3016] opened 2016-03-15 13:12 UTC
When I copy messages (code) from qTox into NetBeans IDE, I find that if the messages has a line space in it, so a message like this for example:

```
int i = 0;

System.out.println(i);
```

That NetBeans throws an error saying `illegal character '\u2028'`, however this does not happen if I copy and paste the same message from another program, so it seems as though that line space is being written out as a unicode character instead of just a blank line.

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and qTox version `1.3.0-38-ga48c422-1`.

**Comment by Aerolivier** [comment] 2016-04-23 09:22
Indeed, I have noticed this too. It puts in a character described as:
 U+2028 LINE SEPARATOR, decimal: 8232, HTML: &#8232;, UTF-8: 0xE2 0x80 0xA8, block: General Punctuation
instead of a normal line feed (\n or \r\n on Windows).

In pluma (gedit) the multiple lines copied show up as a single line number.

**Comment by ezavod** [comment] 2017-05-12 05:57
Duplicate of #4214.
I think this could be closed.

**Comment by Diadlo** [comment] 2017-05-12 06:44
@ezavod Thanks

**Closed as completed by Diadlo** 2017-05-12 06:44 UTC
Labels: C-bug, P-medium
