### ISSUE TITLE
sent message still indicates "sending"

### ISSUE THREAD

**Issue by LER0ever** [qTox/qTox#3518] opened 2016-07-16 10:16 UTC
##### Brief Description

Message status is always "Sending". The circle beside the message is always spinning instead of showing sent time. **And actually message is already sent.**

OS: Linux (Manjaro 16.06 KDE Plasma 5.6)
qTox version: 1.4.1.1
Commit hash:  built without git (installed from AUR)
toxcore:  3747-1
Qt:  5.6.0
Hardware:  Samsung 450r5j
…

Reproducible: Always
##### Steps to reproduce
1. Send a direct message to a friends
##### Observed Behavior

circle progress bar always spinning
##### Expected Behavior

show message sent time
##### Additional Info

![image](https://cloud.githubusercontent.com/assets/10568668/16894160/02ab7e4c-4b81-11e6-9915-1df8d3d76770.png)

**Comment by zetok** [comment] 2016-07-16 10:35
> qTox version: 1.4.1.1

This shouldn't be the case, since that version doesn't have https://github.com/tux3/qTox/pull/3316/commits/a77afca1ec8f86cda68fe7ba853f7e4d854c346f – this commit most likely caused this regression.

It would be good to know which version you have, and whether with this commit reverted you wouldn't have the issue.

**Comment by LER0ever** [comment] 2016-07-16 11:05
![image](https://cloud.githubusercontent.com/assets/10568668/16894392/83e292a6-4b87-11e6-973e-d642ad13e8c3.png)
This is how I installed the qTox.
Besides, I've got this problem for several weeks.

**Comment by zetok** [comment] 2016-07-16 14:37
Related: #1098 – in other issue messages weren't delivered.

**Comment by networkjanitor** [comment] 2016-10-31 21:14
Happens on qTox v1.5.2-obs on Fedora 24 too (installed via "official" repository)

**Comment by anthonybilinski** [comment] 2022-03-17 09:34
This was probably fixed by e9d63397e1008e57a23c763aaa418fc65f57577b, but is fixed on master regardless. Closing.

**Closed as completed by anthonybilinski** 2022-03-17 09:34 UTC
Labels: C-bug
