### ISSUE TITLE
Segfault while group audiochatting

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#2285] opened 2015-09-23 16:51 UTC
I and my friends got a segfault (linux) / crash (windows)

The following was the last output of qtox:

```
[18:44:22.300] src/audio/audio.cpp:326 : Debug: Dropped frame
[18:44:22.300] src/audio/audio.cpp:326 : Debug: Dropped frame
[18:44:24.850] src/audio/audio.cpp:326 : Debug: Dropped frame
[18:44:24.850] src/audio/audio.cpp:326 : Debug: Dropped frame
[18:46:45.999] src/core/core.cpp:558 : Debug: "Group namelist change 0:2 1"
[18:46:46.000] src/core/core.cpp:976 : Warning: getGroupPeerName: Unknown error
```

I'm running with gdb right now and wait for it to happen again.

My qtox version: a53f6f2adfff59b28fa27fb522ccff235d7a7e58

This was caused by one of the participants closing qtox.

**Comment by sudden6** [comment] 2015-09-23 17:29
backtrace, while it happened the second time:

```
(gdb) bt
#0  0x00007ffff240bec0 in QWidget::setStyleSheet(QString const&) () at /usr/lib64/libQt5Widgets.so.5
#1  0x000000000048a33c in QtPrivate::QFunctorSlotObject<GroupChatForm::peerAudioPlaying(int)::{lambda()#1}, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#2  0x00007ffff0f7856f in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#3  0x00007ffff0f85e42 in QTimer::timerEvent(QTimerEvent*) () at /usr/lib64/libQt5Core.so.5
#4  0x00007ffff0f7973c in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#5  0x00007ffff23d8bac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#6  0x00007ffff23dda00 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff0f492b5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#8  0x00007ffff0f9fffd in QTimerInfoList::activateTimers() () at /usr/lib64/libQt5Core.so.5
#9  0x00007ffff0fa0359 in  () at /usr/lib64/libQt5Core.so.5
#10 0x00007ffff43e5a04 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#11 0x00007ffff43e5c48 in  () at /usr/lib64/libglib-2.0.so.0
#12 0x00007ffff43e5cec in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#13 0x00007ffff0fa05ec in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#14 0x00007ffff0f4721b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#15 0x00007ffff0f4e886 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#16 0x0000000000438e27 in main ()
```

**Comment by zetok** [comment] 2015-09-23 18:13
Looks like a duplicate of #1995, closing.

**Closed as completed by zetok** 2015-09-23 18:13 UTC
Labels: U-low
