### ISSUE TITLE
voice impressively altered with qtox in Bionic Beaver (beta 2)

### ISSUE THREAD

**Issue by DoctorSubtilis** [qTox/qTox#5088] opened 2018-04-18 18:55 UTC
##### Brief Description

OS: Linux Kubuntu Bionic Beaver
qTox version: v1.14.0-44-g97bc4a9b.
Commit hash:  97bc4a9b4a864b0cd35b13cd56e75cb6d3abb4e1
toxcore:  0.1.2
Qt: 5.9.4
Hardware:  Kernel: 4.15.0-13-generic x86_64 bits: 64
           Desktop: KDE Plasma 5.12.4
Machine:   Device: desktop Mobo: MSI model: B250M PRO-VD (MS-7A74) v: 1.0 serial: N/A
           UEFI [Legacy]: American Megatrends v: 1.20 date: 12/02/2016
CPU:       Dual core Intel Core i3-7100 (-MCP-) cache: 3072 KB
           clock speeds: max: 3900 MHz 1: 800 MHz 2: 800 MHz
Graphics:  Card: Intel HD Graphics 630
            (...)
Audio:     Card Intel 200 Series PCH HD Audio driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.15.0-13-generic
Network:   Card: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169
           IF: enp1s0 state: up speed: 100 Mbps duplex: full mac: 4c:cc:6a:d8:70:9f
…

Reproducible: Always

##### Steps to reproduce

1. start a call with qtox
2. the listener hears my severely altered voice
3. I hear the other voice normally

##### Observed Behavior
the voice is almost unrecognizable with qtox under Bionic Beaver

##### Expected Behavior
the voice should be the familiar one

**Comment by anthonybilinski** [comment] 2018-04-18 18:57
This sounds like a duplicate of https://github.com/qTox/qTox/issues/5039. This issue is fixed for v1.15.0 which is about to be released. In the meantime, a workaround is to set your mic gain in qTox to the absolute middle, and then adjust your mic levels in OS settings instead.

Can you confirm that setting gain to 0dB in the middle of the bar fixes the issue?

**Comment by DoctorSubtilis** [comment] 2018-04-18 18:59
With the mic gain to the absolute middle the problem is fixed!!! Thank you very much!!!

**Comment by anthonybilinski** [comment] 2018-04-18 19:02
Great, mic gain will be back to working as soon as v1.15.0 is released today or tomorrow :)

**Closed as completed by anthonybilinski** 2018-04-18 19:02 UTC
Labels: U-low
