### ISSUE TITLE
Group chat user participation needs to be persistent

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2997] opened 2016-03-11 19:58 UTC
Currently user that goes offline (often only temporarily offline) is dropped from the group chat. This doesn't look like a good way to handle user-offline situation because on poor connections users might go off and on again frequently.

In general I think group chat should be as persistent as possible.

User list should be able to show the online status of all group chat participants.

**Comment by ProMcTagonist** [comment] 2016-03-11 20:03
https://github.com/tux3/qTox/issues/1567#issuecomment-195384513

**Comment by Deleetdk** [comment] 2016-03-11 20:32
Yes. This is the primary reason I don't use qTox for group conversations. Have to use Skype.

**Comment by yurivict** [comment] 2016-03-11 20:37
Group chats in tox have a lot of space for improvement.

**Comment by zetok** [comment] 2016-03-12 09:24
Duplicate of #1567, thus closing.

**Closed as completed by zetok** 2016-03-12 09:24 UTC
Labels: U-low, proposal
