### ISSUE TITLE
link like "tox:...." don't work

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2271] opened 2015-09-20 21:41 UTC
in windows link like tox:1233123131321321312 don't work
start a new process and all

**Comment by zetok** [comment] 2015-09-20 21:47
Duplicate of #1926, thus closing.

**Closed as completed by zetok** 2015-09-20 21:47 UTC
Labels: U-low

**Comment by zetok** [comment] 2015-09-20 21:49
Also, given by you link is not supposed to work, since it should have 76 hexadecimal characters in order to be an ID.
