### ISSUE TITLE
qTox is keeping chat history even I uncheck "Keep Chat History"

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3221] opened 2016-04-28 13:23 UTC
##### Brief Description

OS: Windows 7
qTox version:v1.4.0-2-g24a7f4d.
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. In Settings > Privacy, uncheck "Keep chat history".
2. Open a chat window by clicking a friend from a list.
3. Send some messages and close chat window.
4. Open chat window again.
##### Observed Behavior

Previous chat records are still there.
##### Expected Behavior

Clean window with no previous conversation.

**Comment by zetok** [comment] 2016-04-28 16:17
~~Right. Previous history should be kept, but not offering a way to delete it is a bug.~~

Edit: look at the comment below ↓

**Comment by zetok** [comment] 2016-04-28 16:21
Actually, the behaviour you're describing is not a bug. It is supposed to work like that.

And no, once `Keep chat history` is unchecked qTox doesn't keep the history.

Thus closing.

**Closed as completed by zetok** 2016-04-28 16:21 UTC
