### ISSUE TITLE
Buggy profile (switching to a new API version of qTox)

### ISSUE THREAD

**Issue by Draako** [qTox/qTox#1547] opened 2015-04-28 00:05 UTC
Upon switching to a new version, qTox created tox_save profile file containing ID used by me yet voided of anything except some ID in my contacts list that I don't recognize. Selecting a backup profile of the same ID does the trick, meaning all the contacts are back.

Windows 7 64-bit.

**Comment by zetok** [comment] 2015-08-28 14:35
Are you really sure that it was qTox that created it?

Also, could you provide more info and see if problem is reproducible on newest qTox builds?
You probably will want to read https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports

**Comment by agilob** [comment] 2015-08-29 16:10
I'm closing this because it was related to migration to new toxcore api and no one else reported it.

**Closed as completed by agilob** 2015-08-29 16:10 UTC
Labels: C-bug, O-need-info
