### ISSUE TITLE
qTox resends part of history

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1006] opened 2015-01-11 13:55 UTC
qTox is resending part of my history. After I close my client (by shutting down my PC normally through KDE), qTox tends to resend a fair part of the history to contacts upon coming online. I assume it doesn't correctly write to the database that those messages were sent succesfully? Purely guessing here, though.

**Comment by dubslow** [comment] 2015-01-11 16:46
@apprb

**Comment by apprb** [comment] 2015-01-11 17:35
DB corruption, may be. 
In your case qTox resends only your messages?

**Comment by TheLastProject** [comment] 2015-01-11 17:38
Yes, and only to the contact they were initially sent to.

**Comment by zetok** [comment] 2015-01-11 17:39
so duplicate of #813?

**Comment by TheLastProject** [comment] 2015-01-11 17:44
@zetok Explicitly NOT a duplicate of #813, because in #813, messages from your contact get resent by you, not your own.

**Comment by apprb** [comment] 2015-01-11 17:56
Can you recreate your history db file:
`echo '.dump' | sqlite3 [filename.old] | sqlite3 [filename.new]`
and check for this bug again.

**Comment by TheLastProject** [comment] 2015-01-11 19:16
I don't quite understand the command. Does the echo give sqlite3 a special command? Also, [filename.old] and [filename.new]? My history only has one filename? Should I make a backup, enter that as filename.old and the original as filename.new?

**Comment by zetok** [comment] 2015-02-05 07:00
I've just run into that issue too.

**Comment by apprb** [comment] 2015-02-08 11:21
I assume it is for unencrypted history. As I guessed before it may be connected with DB corruption (don't have any clue about the reason of it). So try to encrypt history and then unencrypt, it recreates history db file.

**Comment by dubslow** [comment] 2015-02-17 08:16
Fixed? By the new OfflineMsgEngine?

**Comment by zetok** [comment] 2015-02-21 08:12
Still happens on 244d6daca88f0d79f29d9999dd74bd27ebd65780

**Comment by TheLastProject** [comment] 2015-02-28 13:07
@apprb I encrypted and unencrypted it, but to no avail. You still didn't explain the sql command so I haven't been able to run that. Anyway, I got told today that my qTox was sending old messages again.

**Comment by apprb** [comment] 2015-03-29 15:52
@TheLastProject 
Yes this `echo` passes into sqlite command to store DB in the plain text format, then this plain text content goes to sqlite again in order to create DB with the same content as original one but in the new file. Now enabling and then disabling encryption recreates DB history file. In the case of DB corruption this trick should help. But what the origin of your problem with history I don't know currently.

**Comment by zetok** [comment] 2015-08-03 09:15
Still happens on 74b771373d9f367a48f8cf7d175dd34cd10e0b67

**Comment by gmscs** [comment] 2015-09-02 08:33
I've just experienced this issue as well, the client resends history but unlike OP, it only happens sometimes in my case.

**Comment by subliun** [comment] 2015-09-04 08:57
This happened to me.

**Comment by zetok** [comment] 2015-09-15 17:45
Still happens on 54fc35e714bdf03e13d21e3d2d6c2bddfd37baca

**Comment by tox-user** [comment] 2018-06-02 19:28
Can this issue still be reproduced in 1.15.0?

**Comment by sudden6** [comment] 2019-08-12 21:10
This issue has not been seen in current builds.

**Closed as completed by sudden6** 2019-08-12 21:10 UTC
Labels: C-bug, P-medium, D-easy
