### ISSUE TITLE
toxme.se support

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#1046] opened 2015-01-25 23:15 UTC

**Comment by agilob** [comment] 2015-01-25 23:42
isn't it supported already?

**Comment by TheLastProject** [comment] 2015-01-26 00:01
@agilob Support in the sense of registering on it and so.

**Comment by suhr** [comment] 2015-01-26 01:26
Sounds like too much centralization.

**Comment by tux3** [comment] 2015-01-26 01:43
Well, until we get a tox4 protocol with names in the DHT or something like that, I think it's a nice thing to have. Raw tox IDs aren't very user friendly.

**Comment by ProMcTagonist** [comment] 2015-01-26 01:48
Users should be able to register from inside the client. But they should be able to choose from as many services as we know of, to prevent toxme monopoly. They should also be told what they're doing during the process: "Registering will store your ID and chosen <shortname? address?> on a remote server so that friends can add you more easily. This will allow anyone to look up your ID."

**Comment by tux3** [comment] 2015-01-26 01:50
Yes, that's a good idea. What else is there, utox.org and toxme.se ?

**Comment by stqism** [comment] 2015-01-26 02:05
I think you're forgetting the lack of actual support outside of those services, and even when you go to utox.org you lack an actual api and other things. We've had things designed to make a bit of coperstion between services go in to the STS, but so far the only non-toxme service refuses to implement even things like server key lookups making it impossible to use the software and host your own without modifying clients.

**Comment by ProMcTagonist** [comment] 2015-01-26 02:26
Isn't that because it's difficult to deploy a ToxDNS service? Maybe any issues on that front should be resolved before clients move to prompt users to register.

**Comment by stqism** [comment] 2015-01-26 04:01
Well, here's the thing. 

I've spent a good deal of time working out potential APIs and standards that could be adopted and deployed between services. When I went to implement these as standards I ran them by the utox.org maintainer to see he'd be able to implement something like it too so we could have a single cross-service interface for editing, adding, and managing entries.

He responded with a sharp **no**, citing the immense complexities of writing common REST APIs in C.

Not disheartened, I went on and pushed horribly reduced versions of ideas that would allow you to do things like get the server key in a simple and standard way without ever implementing anything like json or xml and adopted it in toxme. This was well documented, easy to implement, and was often thrown at the utox.org maintainer, asking him to implement it. He outright ignored any requests to do so, giving no reasons to his refusal. For readers who do not know, tox3 requires you to have a servers public key to do the encrypted requests using libtoxdns but provides no method of getting the key. This means all keys have to be preloaded in browsers or the domain won't be resolvable ever. (Something I personally fixed with the simple standard I mentioned earlier)

When Tox3 was created it was designed at the exact same time as utox.org and its lookup stuff by the same person. The client library written for it was fully documented and described, but requests for how the server-end worked and some documentation on that were ignored as well. Despite efforts to make our work updated and more secure, we were able to successfully reverse engineer the utox.org's server using its poorly documented codebase a week later.

We, the maintainers of toxme, have always been about openness and designing things in ways that are federated, standardised, and easily deployed. We've always done what we could to make it possible for anyone to run a server or service and get started without trusting us or anyone else, but some of our best efforts are getting hindered by utox.org. We actually created Quickdns, a fork of toxme without the API or web UI so people could get started running servers for their own personal domains, but it has seen limited use.

A funny story, we actually wrote https://github.com/Tox/PyToxme in a service-agnostic way that if needed could be easily used on another domain that followed our standard API we attempted to implement as a commitment to openness and making our work accessible, though we've seen no other implementations of this API outside of toxme.

**Comment by dubslow** [comment] 2015-01-26 04:19
There is at least three third party domains that run the tox1 dns service, it was mentioned in the tox3->tox1 fallback issues around here.

https://github.com/tux3/qTox/issues/907
https://github.com/tux3/qTox/issues/886

cronfire.ru, tox.moe, and coldron.com

**Comment by stqism** [comment] 2015-01-26 04:23
@dubslow Quickdns or implementing the STS standard to lookup server public keys would have made tox3 records resolve on those domains in qTox.

Quite funny actually.

**Comment by zetok** [comment] 2015-01-26 05:45
@stqism no it's not funny. All you've said is that even though there is API, µTox-related things cannot into standard. That's hardly a new thing, and as such can and should be ignored. If utox.org doesn't want to have support from Tox clients, it doesn't have to have it.

But lets look and focus on the reality..
![dns](https://cloud.githubusercontent.com/assets/3148759/5895625/0a3b8b36-a51d-11e4-8578-ef20c08ed01f.png)
Can you tell me, where exactly do you see your API listed?

In 3rd(**!**) link one can actually find some toxcore documentation(?) of tox3 standard, but in regard to this issue it's an irrelevant bullshit.

Considering that, what have you done to make ToxDNS standard API that clients could use widely and easily accessible? Or, since you can't do every single thing, is there anyone else who could have done it, or at least part of it?

Please, don't cry that no one wants to use it, if you (or someone else) fail to promote and encourage usage of it sufficiently.

# 

I for one haven't **ever** (IIRC) seen Standard ToxDNS API.
(Disclaimer: I think that I saw part of toxme.se API, but in my eyes it does not qualify as **Standard API**)

**Comment by ProMcTagonist** [comment] 2015-01-26 05:51
There are definitely issues with toxdns, and its usage, that need resolving before client integration is put on the table. It's pretty pathetic to show the user all options but one are dangerous and insecure (moreso than usual).

It's not a conscionable action to pressure users into registering with webservices until we can be sure there are a variety of available hosts that we can deem relatively secure, as far as you can say that about any webservice.

**Comment by srkunze** [comment] 2015-01-27 00:12
Looks like we need an implementation for this https://github.com/irungentoo/toxcore/issues/1222 and that https://github.com/irungentoo/toxcore/issues/1180 as soon as possible.

**Comment by strk** [comment] 2015-01-27 17:56
+1 for leaving user the possibility to specify which lookups to make (including none, for privacy reasons)

**Comment by tux3** [comment] 2015-02-20 02:35
API support is implemented in the "toxme" branch as of today, but there's still no GUI for it.

**Comment by suhr** [comment] 2015-07-16 08:02
Time to close this.

**Comment by suhr** [comment] 2015-08-21 07:07
^

**Comment by ovalseven8** [comment] 2015-09-04 16:49
Personally, I think it's not a good idea to implement the registration for services like toxme.se in the qTox client. That should be separated.
Everybody who would like to use such services can go to the website with a browser and do it.

**Comment by ProMcTagonist** [comment] 2015-09-07 05:53
Toxme.se is malware, change to toxme.io + tox.party + toxing.me + utox.org + sr.ht + whatever else

**Comment by Diadlo** [comment] 2016-08-25 20:23
Added toxme support #3127

**Closed as completed by Diadlo** 2016-08-25 20:23 UTC
Labels: proposal, P-low, M-ui
