### ISSUE TITLE
Focus-on-typing-start takes too long and loses the beginning of what the user types

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#2084] opened 2015-08-21 06:49 UTC
The only problem I've found with it, @zetok.

Observed behavior: When I start typing, it may take up to two or three letters for qTox to actually start putting my characters in the text field. Pretty annoying. After more observing it looks like when I hit one character at normal speed the text box focuses, empty, always losing the first character regardless of speed.

Desired behavior: qTox puts all typed characters in the text box

Environment: qTox latest from git with Qt 5.3.2+dfsg-5 using Openbox as my window manager.

(https://github.com/tux3/qTox/issues/491#issuecomment-133297778)

**Comment by sudden6** [comment] 2016-09-02 22:18
Not reproducible on 76c4cf7d390ece3d0ec57b771fb9aaa21f7337f7 with Qt 5.6.1 on plasmashell 5.7.3

Closing because no update since > 1 year, feel free to reopen if the issue persists.

**Comment by zetok** [comment] 2016-09-03 01:19
Still reproducible on 4a5f89bb98fc8657514e35c5022713358a453d49 with Qt 5.6.1.

**Comment by sudden6** [comment] 2016-09-03 08:22
@zetok can you give more details about how to reproduce? Also the environment needed to reproduce?

**Comment by zetok** [comment] 2016-09-03 11:17
Env:
i3wm, I doubt whether it's related though.

Might need `xset r rate 220 70` – some stuff tends to break with that, but it usually happens with repeated input, not when just typing. It changes wait time for key repetition to 220ms and pressed key is repeated 70 times per second.

Steps to reproduce:
1. Select contact
2. input field has focus, click in the chat to remove focus from it
3. **_Quickly**_ type something, e.g. `asdf` – if you're doing it fast enough, whole `asdf` won't appear in the input field.

**Comment by tox-user** [comment] 2018-06-02 19:02
Is this still relevant? I can't reproduce in 1.15.0.

**Closed as completed** 2018-06-02 19:15 UTC
Labels: C-bug, P-medium
