### ISSUE TITLE
Proxy issues

### ISSUE THREAD

**Issue by albesp77** [qTox/qTox#4390] opened 2017-05-11 11:25 UTC
OS: Windows 7 x64
qTox version: 1.9.0 and 1.10.0  

unable to use both http and socks5 proxy settings, receiving error on proxy settings and client crash
just to better clarify, with build 1.8.1 all works good, with 1.9.0 and 1.10.0 i don't see any type of traffic outgoing from my pc to web proxy, both http and socks5!

**Comment by zetok** [comment] 2017-05-12 21:09
Duplicate of #4324, thus closing.

**Closed as completed by zetok** 2017-05-12 21:09 UTC
Labels: U-low
