### ISSUE TITLE
Autoaccept groupinvites

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#4241] opened 2017-03-08 16:48 UTC
Similar to "auto-accept filetransfers" and "autoaccept call" there should be an option to automatically join groups if invited by a specific contact.

This feature, in combination with groupbots that invite automatically when a user comes online should allow for nearly permanent groupchats.

**Comment by zetok** [comment] 2017-03-08 18:14
Duplicate of #1197, thus closing.

**Closed as completed by zetok** 2017-03-08 18:14 UTC
Labels: U-low, proposal
