### ISSUE TITLE
Qtox Cannot select any video device while none are detected

### ISSUE THREAD

**Issue by 678zinner** [qTox/qTox#6063] opened 2020-04-03 13:08 UTC
I am using Linux Mint Cinnamon 19.3.
The menu video settings doesn't preset any internal oder external connetced video device, although in Audio settings I can select the microphone of the connetd Logitech USB-Webcam C920 and it works.

OS: KDE Flatpak runtime
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.10
Qt: 5.12.6
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by Piraty** [comment] 2020-04-03 14:15
Duplicate of #6059 ?

**Comment by sudden6** [comment] 2020-04-04 17:47
Yes, duplicate of #6059

**Closed as completed by sudden6** 2020-04-04 17:47 UTC
