### ISSUE TITLE
qTox; "4.00GiB Accept to receive this file [close button] [accept button]" appears

### ISSUE THREAD

**Issue by DmitriyMendeleev** [qTox/qTox#1516] opened 2015-04-10 09:19 UTC
When I (re)connect, or my friend (re)connects, this (see screenshot) appears.
Windows 7 (6.1; 7600) Professional is on my PC, and FreeBSD is on my friend's PC.
![2015040901_qtox_bug](https://cloud.githubusercontent.com/assets/11884614/7085044/3f57fca8-df62-11e4-828b-46f92394f355.jpg)
No file transfers initiated by me of by my friend.
Accepting the file transfer, I can choose where I want to save the "file" on my PC.
And nothing more happens (file marked as downloaded; no file appears on my PC in pointed location).

**Comment by zetok** [comment] 2015-04-10 10:01
It's due to difference between APIs that clients use.

Your fiend uses client on new API.. until qTox gets ported, it's an expected behaviour.

**Comment by TheLastProject** [comment] 2015-04-11 10:20
Indeed, it's an API incompatibility issue. See #1520.

**Comment by tux3** [comment] 2015-04-25 17:45
Fixed in the new API branch.

**Closed as completed by tux3** 2015-04-25 17:45 UTC
Labels: C-bug
