### ISSUE TITLE
Changing input/output devices during call don't have any effect

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2445] opened 2015-10-22 15:36 UTC
I can't change (input/output) devices during a call. Well, of course I can - but it doesn't have any effects. Don't think that it's desired behaviour.

**Comment by tux3** [comment] 2015-10-24 01:09
Should be fixed by new AV #2456

**Comment by zetok** [comment] 2015-11-06 08:19
Since it should be fixed now, closing.

If you can still reproduce it on new AV, please comment for reopen.

**Closed as completed by zetok** 2015-11-06 08:19 UTC
Labels: C-bug, M-audio

**Comment by ovalseven8** [comment] 2015-11-06 08:52
Works. :+1:
