### ISSUE TITLE
uninformative taskbar button icon

### ISSUE THREAD

**Issue by koshakm5** [qTox/qTox#4862] opened 2017-12-12 16:34 UTC
##### Brief Description

OS: Windows 7 x64  
qTox version:  v1.13.0
Commit hash:  8de8c14
toxcore:  0.1.10
Qt:  5.9.3

Reproducible: Always 

cant see my own status and message alert in taskbar button when "combine" view activated
it's a terrible thing, because it's a default state in windows, and people unable to see new messages alert(flashing orange icon), except in a tray - icon of taskbar button always static, black

![1](https://user-images.githubusercontent.com/34250813/33891871-547bca66-df68-11e7-825c-8ee7a7d648e9.PNG)

uncombined view works fine

![2](https://user-images.githubusercontent.com/34250813/33891872-54aaf2aa-df68-11e7-88e5-1162ff64b3f2.PNG)

and the most strange thing - after deleting desktop shortcut in "combined" view taskbar button icon will change to useful view 

![3](https://user-images.githubusercontent.com/34250813/33891873-54e14bf2-df68-11e7-83a5-98f3ad964a8a.PNG)
![4](https://user-images.githubusercontent.com/34250813/33891875-554ac2d0-df68-11e7-8587-e9395422b431.PNG)

but if I  choose "pin this program to taskbar" then icon changes back to unuseful view

![5](https://user-images.githubusercontent.com/34250813/33895212-0c449558-df71-11e7-8894-2fe61572810e.png)
![6](https://user-images.githubusercontent.com/34250813/33895213-0c7f1656-df71-11e7-98f8-2fb4fa7ec742.png)

**Comment by Hasshu** [comment] 2017-12-13 09:54
Duplicate of #1778?

**Closed as completed** 2017-12-13 12:28 UTC
Labels: U-low, OS-windows
