### ISSUE TITLE
qTox doesn't reconnect to group chat after connection loss

### ISSUE THREAD

**Issue by tox-user** [qTox/qTox#4842] opened 2017-11-27 17:21 UTC
##### Brief Description

OS: Debian 9
qTox version: v1.11.0-391-g531defd0  
Commit hash: 531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore: 0.1.10
Qt: 5.7.1
…

Reproducible: Almost Always

##### Steps to reproduce
1. Join a groupchat.
2. Disconnect from the internet.
3. Connect to the internet.

##### Observed Behavior
qTox not only doesn't rejoin the group after the connection is back, but also doesn't give the user any hints that they are no longer in the group. Everything looks normal, except that sometimes it shows that we are the only user in the chat.

##### Expected Behavior
Rejoin groupchat after connection loss. Give user some indication when they lose connection. Give user some indication when their connection is restored.

**Comment by sudden6** [comment] 2017-11-27 19:16
duplicate of https://github.com/qTox/qTox/issues/896

upstream solution currently WIP

**Closed as completed by sudden6** 2017-11-27 19:16 UTC
