### ISSUE TITLE
Improved webcam and desktop share interface

### ISSUE THREAD

**Issue by tantrus332** [qTox/qTox#4528] opened 2017-07-23 11:04 UTC
I do not understand why in qTox you can not display images from the webcam or "Desktop share" in full screen as it is implemented in Skype. It is impossible to use this "Desktop share" if there is nothing to see in this size, so you need to add the feature to include the web-camera (desktop share) of the interlocutor to the full screen. Also, it would be nice to bring a button like "Turn on the desktop share" directly into the interface of the conversation (at least in the context menu), and not go to the settings and there to change something. And yet, when you use Desktop share, very often the image becomes pixelated and gray is very similar to a bug.

**Comment by Diadlo** [comment] 2017-07-23 11:09
Seems, duplicate of #2529, duplicate of #2922 and duplicate of #2102, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-07-23 11:09 UTC
Labels: U-low

**Comment by tantrus332** [comment] 2017-07-25 11:00
Did add these features?

**Comment by Diadlo** [comment] 2017-07-25 11:44
All issues are opened => not

**Comment by Diadlo** [comment] 2017-07-25 11:44
@tantrus332 All issues are opened => not

**Comment by Diadlo** [comment] 2017-07-25 11:45
duplicate #2922 and duplicate #2102
