### ISSUE TITLE
filetransfers and timestamps overlap

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#2268] opened 2015-09-19 16:11 UTC
If I use a small window, the filetransfer bubbles overlap with timestamps.
![qtox-screenshot-ojk13983](https://cloud.githubusercontent.com/assets/4164816/9977040/fa9c26dc-5ee8-11e5-9751-1a7e1a2d8efe.png)

**Comment by ProMcTagonist** [comment] 2015-09-20 01:24
Me too.

![qtox file transfer overflowing bounds](https://cloud.githubusercontent.com/assets/4358079/9978754/a1928780-5efb-11e5-986e-1939707de78d.png)

**Comment by agilob** [comment] 2015-09-20 06:36
It's a known issue and was reported before.

**Comment by zetok** [comment] 2015-09-21 22:34
Right, a duplicate of #2227, thus closing.

**Closed as completed by zetok** 2015-09-21 22:34 UTC
Labels: C-bug, U-low, P-low, M-ui
