### ISSUE TITLE
qTox shows metadata-only /dev/videoN devices as real video devices

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6058] opened 2020-04-01 19:15 UTC
The V4L interface sometimes creates two /dev/videoN devices for one physical webcam. The second device is with meta-data.

qTox shows two webcams in the list for such devices.

```
commit 088ead25524583e2200aa99111bea2f66a86545a
Author: Guennadi Liakhovetski <guennadi.liakhovetski@intel.com>
Date:   Wed Dec 6 10:15:40 2017 -0500

    media: uvcvideo: Add a metadata device node
        Some UVC video cameras contain metadata in their payload headers. This
    patch extracts that data, adding more clock synchronisation information,
    on both bulk and isochronous endpoints and makes it available to the user
    space on a separate video node, using the V4L2_CAP_META_CAPTURE capability
    and the V4L2_BUF_TYPE_META_CAPTURE buffer queue type. By default, only the
    V4L2_META_FMT_UVC pixel format is available from those nodes. However,
    cameras can be added to the device ID table to additionally specify their
    own metadata format, in which case that format will also become available
    from the metadata node. 
```

**Comment by anthonybilinski** [comment] 2021-06-18 07:25
Duplicate of https://github.com/qTox/qTox/issues/6276, was fixed by https://github.com/qTox/qTox/pull/6309.

**Closed as completed by anthonybilinski** 2021-06-18 07:25 UTC
