### ISSUE TITLE
Update qTox Windows version building manual

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#3372] opened 2016-06-10 05:55 UTC
But CMake adding exists in **Setting up PATH**.
https://github.com/tux3/qTox/blob/master/INSTALL.md#setting-up-path

**Comment by zetok** [comment] 2016-06-10 06:42
> Select mingw-developer-toolkit, mingw32-base, mingw32-gcc-g++, msys-base and mingw32-pthreads-w32

It's not provided with one of those? Or Qt toolchain that is supposed to be optional?

**Comment by DX37** [comment] 2016-06-10 06:53
> It's not provided with one of those? Or Qt toolchain that is supposed to be optional?

It's not exists in MinGW or Qt basic installation. But I deselect MinGW 4.9.2 in Tools, as described in docs.

**Comment by DX37** [comment] 2016-06-10 07:15
Well... OpenAL got updated from 1.16.0 to 1.17.2 and FFmpeg from 2.7 to 3.0.2.
Maybe it's time to update Windows building manual? And I notice, what after [Getting dependencies](https://github.com/tux3/qTox/blob/master/INSTALL.md#getting-dependencies) nothing listed what to do after it. Exactly what you should run to build qTox.

**Comment by DX37** [comment] 2016-06-10 07:28
Found gcc in _Qt for Desktop 5.6 (MinGW 4.9.2)_, WTF.

**Comment by DX37** [comment] 2016-06-10 07:53
Well... It's getting errors when I try to get and compile dependencies with original manual. Now I try to install MSYS2 and MinGW64.

**Comment by zetok** [comment] 2016-06-10 08:23
> Well... OpenAL got updated from 1.16.0 to 1.17.2 and FFmpeg from 2.7 to 3.0.2.
> Maybe it's time to update Windows building manual?

Sure. Instructions in there are supposed to be for something that worked. With that in mind, there has to be someone who would write & test newer instructions – note that out of qTox maintainers currently only @tux3 uses windows to test qTox. Dunno though if he even compiles qTox on windows..

If instructions for windows need to be updated, PRs would be very welcome.

**Comment by DX37** [comment] 2016-06-10 08:28
> If instructions for windows need to be updated, PRs would be very welcome.

Maybe I will do this...
At this moment I downloading Qt 5.6.0 in MSYS2. It's already have compiled openal and ffmpeg in it's repos. I will test that.

**Comment by DX37** [comment] 2016-06-10 13:33
I give up for now. I've got fully generated dependencies from manual, but I can't compile qTox. `qmake` behavior is strange, `make -j4` fails with error: 

> src/persistence/db/rawdatabase.cpp:15:31: fatal error: sqlcipher/sqlite3.h: No such file or directory

![2016-06-10_19-32-06](https://cloud.githubusercontent.com/assets/12829428/15965874/312d6498-2f42-11e6-8a32-e05463493b4b.png)

SQLCipher is not exist in MSYS2 repos.
**How do you building qTox for Windows from [build.tox.chat](https://build.tox.chat)?**

**Comment by zetok** [comment] 2016-06-10 13:58
From a better OS, cross-compiling.

**Comment by DX37** [comment] 2016-06-10 15:18
> From a better OS, cross-compiling.

Well, I have Linux too. And I compiling `qtox-git` on it and it works well.

**Comment by DX37** [comment] 2016-06-10 15:54
Just tested MinGW toolchain from Qt 5.6.0 - sometimes it pauses at compiling and not continue before.

**Comment by Talkless** [comment] 2016-06-11 13:58
I am too struggling to build on Windows. After some addition to INSTALL.md, still something is missing.

Here's bootstrap.bat output: https://gist.github.com/Talkless/a78b687d9492fe99be39541ff46a31a3

Some interesting parts:

```
/cygdrive/c/MinGW/bin/autoheader: /cygdrive/c/MinGW/bin/autoheader-2.68: /bin/perl: bad interpreter: Permission denied
```

at line [162](https://gist.github.com/Talkless/a78b687d9492fe99be39541ff46a31a3#file-bootstrap_bat_output-txt-L162)

Also this compilation error:

```
C:/myqTox/libs/openal-soft-1.16.0/include/threads.h:38:8: error: redefinition of 'struct timespec'
```

at line [528](https://gist.github.com/Talkless/a78b687d9492fe99be39541ff46a31a3#file-bootstrap_bat_output-txt-L528)

More, not sure if critical:

```
/usr/bin/sed: -e expression #1, char 6: unterminated `s' command
```

at line [5842](https://gist.github.com/Talkless/a78b687d9492fe99be39541ff46a31a3#file-bootstrap_bat_output-txt-L5842)

More:

```
/usr/bin/mktemp: cannot create temp file /cygdrive/c/Users/IEUser/AppData/Local/Temp/ffconf.IqbHrgeU: No such file or directory
```

at line [5866](https://gist.github.com/Talkless/a78b687d9492fe99be39541ff46a31a3#file-bootstrap_bat_output-txt-L5866)

And finally, at the end of file:

```
Makefile:2: config.mak: No such file or directory
Makefile:59: /common.mak: No such file or directory
Makefile:100: /libavutil/Makefile: No such file or directory
Makefile:100: /library.mak: No such file or directory
Makefile:102: /doc/Makefile: No such file or directory
Makefile:185: /tests/Makefile: No such file or directory
make: *** No rule to make target `/tests/Makefile'.  Stop.
Makefile:2: config.mak: No such file or directory
Makefile:59: /common.mak: No such file or directory
Makefile:100: /libavutil/Makefile: No such file or directory
Makefile:100: /library.mak: No such file or directory
Makefile:102: /doc/Makefile: No such file or directory
Makefile:185: /tests/Makefile: No such file or directory
make: *** No rule to make target `/tests/Makefile'. Stop.
```

So.. basically nothing gets build during bootstrap.

**Comment by DX37** [comment] 2016-06-11 14:31
> Here's bootstrap.bat output: https://gist.github.com/Talkless/a78b687d9492fe99be39541ff46a31a3

I have exactly the same output while build.

**Comment by Talkless** [comment] 2016-06-25 16:33
@tux3 Could you comment on this issue? Do you actually build with MinGW? I am still struggling with build errors as posted in my comment above.

**Comment by Talkless** [comment] 2016-06-26 12:55
There is effort to make libqrencode buildable with CMake, which is very nice, though actual implementation is not quite enough so far: https://github.com/fukuchi/libqrencode/pull/83 .

**Comment by Talkless** [comment] 2016-09-18 13:15
`windows/bootstrap.sh` is successfull only and only if it's launched from `C:\MinGW\msys\1.0\msys.bat` shell. Then:
- `cd /cygdrives/c/qTox/windows`
- `./bootstrap.sh`

I yet failed to make it work from `bootstrap.bat`. Seems like environment is "wrong" if `sh` is launched from `.bat`.

Also, `windows/bootstrap.sh` does not build `libsodium`, so there's need to fix that also.

**Comment by DX37** [comment] 2016-09-18 13:24
We will build by using MinGW64 Win32 Shell from MSYS2. qTox works, but I've got it not portable. It runs only from Shell.
And one more problem - I can't build sqlcipher. Other libs, which is not exist in MSYS2 repo, compiles fine.

**Comment by Talkless** [comment] 2016-09-18 13:35
@DX37 I've believe I have found problem - I had `C:\Program Files\OpenSSH\bin` _before_ MinGW/MSYS paths in Windows `%PATH%`! 

After moving it to the end of `%PATH%` I see that `windows/bootstrap.sh` builds what was intended without errors I've mentioned above.

**Comment by DX37** [comment] 2016-09-18 13:39
In new MSYS2 it's not needed to have it paths in Windows PATH. It works in its own console.

Building sqlcipher says 

```
libtool: warning: undefined symbols not allowed in i686-w64-mingw32 shared libraries; building static only
libtool: link: ar cru .libs/libsqlcipher.a  sqlite3.o
libtool: link: ranlib .libs/libsqlcipher.a
libtool: link: ( cd ".libs" && rm -f "libsqlcipher.la" && cp -pR "../libsqlcipher.la" "libsqlcipher.la" )
./libtool --mode=link gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_WIN=1 -I. -I/c/Users/asusx/Desktop/sqlcipher/src -I/c/Users/asusx/Desktop/sqlcipher/ext/rtree -I/c/Users/asusx/Desktop/sqlcipher/ext/fts3 -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/mingw32/include/tcl8.6 -DSQLITE_THREADSAFE=1    -lcrypto  -DHAVE_READLINE=0  -DHAVE_EDITLINE=1 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
        -o sqlcipher.exe /c/Users/asusx/Desktop/sqlcipher/src/shell.c libsqlcipher.la \
        -ledit  -lcrypto   -rpath "/mingw32/lib"
libtool: link: gcc -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_WIN=1 -I. -I/c/Users/asusx/Desktop/sqlcipher/src -I/c/Users/asusx/Desktop/sqlcipher/ext/rtree -I/c/Users/asusx/Desktop/sqlcipher/ext/fts3 -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I/mingw32/include/tcl8.6 -DSQLITE_THREADSAFE=1 -DHAVE_READLINE=0 -DHAVE_EDITLINE=1 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_EXPLAIN_COMMENTS -o .libs/sqlcipher.exe /c/Users/asusx/Desktop/sqlcipher/src/shell.c  ./.libs/libsqlcipher.a -ledit -lcrypto -L/mingw32/lib
C:/Users/asusx/Desktop/sqlcipher/src/shell.c: In function 'main':
C:/Users/asusx/Desktop/sqlcipher/src/shell.c:79:34: warning: implicit declaration of function 'stifle_history' [-Wimplicit-function-declaration]
 # define shell_stifle_history(X) stifle_history(X)
                                  ^
C:/Users/asusx/Desktop/sqlcipher/src/shell.c:79:34: note: in definition of macro 'shell_stifle_history'
 # define shell_stifle_history(X) stifle_history(X)
                                  ^~~~~~~~~~~~~~
D:\msys32\tmp\ccIY4yYc.o:shell.c:(.text+0xc66d): undefined reference to `stifle_history'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:600: sqlcipher.exe] Error 1
```

and fails. However, if I taking sqlcipher from [build.tox.chat](https://build.tox.chat/view/qtox/job/libsqlcipher_build_windows_x86_static_release/) and putting into `libs` folder for compiling, it fully works. I don't know how to got working compiling of sqlcipher

**Comment by Talkless** [comment] 2016-09-18 13:50
With `bootstrap.bat` it's kinda simpler just to click on it in Windows Explorer as opposed to entering commands into msys.bat shell.

> Other libs, which is not exist in MSYS2 repo, compiles fine

Do you have instructions to build libsodium? Could you add it to `windows/boostrap.bat` ?

**Comment by DX37** [comment] 2016-09-18 14:04
> With bootstrap.bat it's kinda simpler just to click on it in Windows Explorer as opposed to entering commands into msys.bat shell.

Well... we can create new bootstrap.bat 😄

> Do you have instructions to build libsodium? Could you add it to windows/boostrap.bat ?

In MSYS2 Shell I just installed it using `pacman -S mingw-w64-i686-libsodium`. For building you should read [this](https://download.libsodium.org/libsodium/content/installation/), I guess.
And I thinking what I will change current instructions, not just bootstrap.bat. But I don't have much time since I study. If nobody will update this intructions, then I will.

**Comment by Talkless** [comment] 2016-09-18 14:44
> For building you should read this, I guess.

What I had in mind maybe you have updated `windows/bootstrap.sh script` that builds/downloads/whatever libsodium and other stuff, with pacman or not.

So decision is to use MSYS2 instead? Wouldn't using pacman restrict versions we would like to use, etc?

@zetok do you have ideas in this regard?

**Comment by DX37** [comment] 2016-09-18 15:09
> What I had in mind maybe you have updated windows/bootstrap.sh script that builds/downloads/whatever libsodium and other stuff, with pacman or not.

If I had a new script, I would have tried to create a pull request. I just today was able to get compiled qTox on Windows.

> So decision is to use MSYS2 instead? 

Yeah, because it have new and updated toolchains.

**Comment by zetok** [comment] 2016-09-18 17:17
@Talkless is building libsodium required in the first place, since there there are compiled libs available that libsodium docs link to?

**Comment by Talkless** [comment] 2016-09-18 17:58
@zetok maybe `windows/bootstrap.sh` could download them as it downloads toxcore then?

**Comment by zetok** [comment] 2016-09-18 18:13
@Talkless yep, why not.

**Comment by AliceGrey** [comment] 2016-10-16 23:40
After doing some test builds in a windows vm and asking lots of questions in the IRC I've come to a few conclusions.
1. ddraw.h: This library is not included in MinGW32 only MinGW64
2. QT doesn't distribute a version of QT for windows that is built with MinGW64 which causes complications
3. Building your own version for windows is difficult but possible. https://wiki.qt.io/MinGW-64-bit
4. rtti: When building on windows I needed to turn rtti on. It's currently set to `rtti_off` in qtox.pro. Reference: https://bugzilla.redhat.com/show_bug.cgi?id=725079#c3

There is hope though. A user seems to have gotten it compiled on windows using MSYS2 #3716

**Comment by Talkless** [comment] 2016-10-29 14:24
@AliceGrey I'm also experimenting with building on Windows. 

First, I've built required libraries and qTox using msys1, qTox launches but crashes.

Then I've made sure that I build qTox and other dependencies using gcc from Qt installation directory, so Qt's and qTox's compiler was the same, and MSYS1 was only use for other build tools. qTox launches and works, though there is strange hardcoded path to Qt's compiler, and I assume there's idea to upgrade to MSYS2.

Now, I'm experimenting with MSYS2, looks like there's no need to build ffmpeg and stuff, but I got stuck on nonsense as `error: required library rt was not found on your system` because of `undefined reference to 'clock_gettime'`...  Oh come on, this Windoz task takes too much time...

**Comment by DX37** [comment] 2016-10-29 14:30
@Talkless Hmm... Did you remove -fno-rttio option or something?
In my case I didn't saw this error.

**Comment by initramfs** [comment] 2016-10-29 14:42
@AliceGrey @DX37 The latest version from master should no longer need RTTI as all instances of `std::dynamic_cast` and `std::dynamic_pointer_cast` has been removed as per #3830.

**Comment by Talkless** [comment] 2016-10-29 14:57
@DX37 in my case, toxcore's `configure.ac` does not detect OS as Windows, because `$host_os` is `msys`, not `mingw`. OK workarounded that, but now it does not find `pthread-config` nowhere in path...

Enought for today. 

I think that I'll just try to PR that version where gcc from Qt directory is used and all (except OpenSSL IIRC) libs are built manually...

**Comment by Talkless** [comment] 2016-12-11 13:30
@AliceGrey @DX37 could you please try to build qTox using my [bootstrap branch](https://github.com/Talkless/qTox/tree/bootstrap)? Please read updated INSTALL.md for setting things up.

qTox now can be built and debugged on Windows (which I need), though ffmpeg DX9/DX11 acceleration is disabled during compilation due to missing DX in Qt-bundled compiler (not sure how this affects video calls though). Using standalone MinGW for qTox with prebuilt-Qt causes crash, so this is the price to pay, at least for now.

**Comment by DX37** [comment] 2016-12-11 14:14
> could you please try to build qTox using my bootstrap branch? Please read updated INSTALL.md for setting things up.

I run `bootstrap.bat` and it still downloading old versions of ffmpeg and OpenAL. Building OpenAL failes on some moment and script continues to work.
Maybe you should update links.
I building this, again, on MSYS2. It also can download `yasm` as a package.

**Comment by Talkless** [comment] 2016-12-12 06:41
> Building OpenAL failes on some moment and script continues to work.

Are you sure you checkouted right branch? Script should not continue after error [because there is a flag for that](https://github.com/Talkless/qTox/blob/bootstrap/windows/bootstrap.sh#L3).

Concerning versions, yeah, I should update them. At first all I wanted for it is just to build.

**Comment by DX37** [comment] 2016-12-12 07:05
I got it... I forgot to checkout bootstrap branch. Sorry. Will test script later.

**Comment by DX37** [comment] 2016-12-12 10:01
Can't `autoreconf -i` from script for toxcore. It says `aclocal-1.15: error: aclocal: file '/msys32/usr/share/aclocal/xsize.m4' does not exist`, when I run it from qTox root directory. But when I run it from `toxcore-master` dir, it works.

And, in some cases, we should use `make -j$(nproc)`, for better speed.

**Comment by DX37** [comment] 2016-12-12 10:36
Also in `QTOX_DIR` variable you should remove slash and two points, because of toxcore, that can't find vpx and opus in `libs` directory (QTOX_DIR shows directory, where qTox directory lies).

**Comment by DX37** [comment] 2016-12-12 10:44
@Talkless I have one question - can you install MSYS2?

**Comment by DX37** [comment] 2016-12-12 10:49
I still have that dumb error...

> D:/msys32/home/asusx/qTox/libs/sqlcipher-3.4.0/src/shell.c: In function 'main':
> D:/msys32/home/asusx/qTox/libs/sqlcipher-3.4.0/src/shell.c:79:34: warning: implicit declaration of function 'stifle_history' [-Wimplicit-function-declaration]
>  #define shell_stifle_history(X) stifle_history(X)
>                                   ^
> D:/msys32/home/asusx/qTox/libs/sqlcipher-3.4.0/src/shell.c:79:34: note: in definition of macro 'shell_stifle_history'
>  #define shell_stifle_history(X) stifle_history(X)
>                                   ^~~~~~~~~~~~~~
> C:\Users\asusx\AppData\Local\Temp\ccyr0p1k.o:shell.c:(.text+0xc66d): undefined reference to `stifle_history'
> collect2.exe: error: ld returned 1 exit status

**Comment by Talkless** [comment] 2016-12-12 17:21
> /msys32/usr/share/aclocal/xsize.m4

You are using MSYS? It's still designed to be used with old MinGW, as original script did. Please move MSYS2 PATH's below MinGW.

> Also in QTOX_DIR variable you should remove slash and two points, because of toxcore, that can't find vpx 

Strange, I get 
```
checking for OPUS... yes
checking for VPX... yes
```
toxcore has flag `--with-dependency-search="${QTOX_DIR}/libs"` and `configure` documents:
```
  --with-dependency-search=DIR
                          search for dependencies in DIR, i.e., look for
                          libraries in DIR/lib and for headers in DIR/include
```

So it should find `${QTOX_DIR}/libs/lib/libvpx.a`, at least it does *on my machine* (heh)

Anyway, long story short, I would suggest:
* Make msys2 inaccessible by renaming `D:\msys32` -> `D:\msys32_`, for example.
* Make sure MinGW has packages required (msys-base, tcl, libz, whatever mentioned in INSTALL.md). I would delete `C:/MinGW` and reinstall it clean.
* Delete `QTOX_DIR/libs/` contents clean.
* Execute `bootstrap.bat`.

I agree that `QTOX_DIR` could be resolved in less error-prone way (using currently running scripts actual path, not process working dir), I'll improve that.

**Comment by Talkless** [comment] 2016-12-12 18:45
By the way, please PULL some [some minor change](https://github.com/Talkless/qTox/commit/a9c844ab01769c70db5ad3c6ba455dd0cfecb11e).

**Comment by Talkless** [comment] 2017-02-11 18:21
With new CMake build setup, new issues. Yay!
```
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  C:/MinGW/msys/1.0/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.
```

If I remove `C:/MinGW/msys/1.0/bin` from PATH (which is nonsense, how will `bootstrap.bat` will execute `windows/bootstrap.sh` then?), I get missing PKG_CONFIG_EXECUTABLE:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```

@DX37 Do you have any progress on building on Windows with MSYS2?

@zetok Seems like making qTox build on Windows "natively" is not only missing feature, but it's becomming harder to implement :-)  ([this smile is more accurate](http://i0.kym-cdn.com/photos/images/newsfeed/000/839/199/8a9.jpg)).

**Comment by DX37** [comment] 2017-02-12 06:02
> With new CMake build setup, new issues. Yay!

Please, try it with MSYS2. Original MSYS is too old for using :/
And... I don't have any progress. But I didn't try to compile with cmake, so... Testing!

**Comment by DX37** [comment] 2017-02-12 09:10
I can't compile sqlcipher!... There's a [pastebin](http://pastebin.com/qHVNwKgV).

**Comment by sudden6** [comment] 2019-08-11 14:58
Windows builds are now based on Docker, this is not longer relevant.

**Closed as completed by sudden6** 2019-08-11 14:58 UTC
Labels: OS-windows, M-docs
