### ISSUE TITLE
SIGABRT when trying to run two QTox instances

### ISSUE THREAD

**Issue by d33tah** [qTox/qTox#1257] opened 2015-02-22 20:24 UTC
This is on Fedora 21 64bit, repo built from 21:30:26 Feb 19 2015.

```
$ gdb core.4775 -ex "bt" </dev/null
GNU gdb (GDB) Fedora 7.8.2-38.fc21
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
[New LWP 4787]
[New LWP 4779]
[New LWP 4780]
[New LWP 4777]
[New LWP 4776]
[New LWP 4783]
[New LWP 4784]
[New LWP 4786]
[New LWP 4775]
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/e9/959c53e6149d11d7c40c09c4e86c635bd90c36
Core was generated by `qtox'.
Program terminated with signal SIGABRT, Aborted.
#0  0x000000311be348c7 in ?? ()
"/home/d/workspace/metatorrent/core.4775" is a core file.
Please specify an executable to debug.
#0  0x000000311be348c7 in ?? ()
#1  0x000000311be3652a in ?? ()
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb) quit
```

**Comment by d33tah** [comment] 2015-02-22 20:29
Also a segmentation fault in the same case:

```
$ gdb core.6555 -ex "bt" </dev/null
GNU gdb (GDB) Fedora 7.8.2-38.fc21
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
[New LWP 6570]
[New LWP 6562]
[New LWP 6569]
[New LWP 6558]
[New LWP 6566]
[New LWP 6567]
[New LWP 6555]
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/e9/959c53e6149d11d7c40c09c4e86c635bd90c36
Core was generated by `qtox'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000024a8401 in ?? ()
"/home/d/workspace/core.6555" is a core file.
Please specify an executable to debug.
#0  0x00000000024a8401 in ?? ()
#1  0x0000003cb85c64e5 in ?? ()
#2  0x00007fccdc003440 in ?? ()
#3  0x75aa99b602b37700 in ?? ()
#4  0x0000000000000000 in ?? ()
(gdb) quit
```

**Comment by d33tah** [comment] 2015-02-22 20:36
Core dumps available here: http://a.pomf.se/ugdacp.lzma http://a.pomf.se/cmegdy.lzma

**Comment by dubslow** [comment] 2015-02-23 18:33
Technically qTox doesn't support two instances at once, but we seem to be moving in that direction anyways...

**Comment by d33tah** [comment] 2015-02-23 20:07
Yeah, but a crash like this doesn't look nice.

**Comment by zetok** [comment] 2015-03-04 07:50
@d33tah I couldn't reproduce on hardened Gentoo. Mind providing steps?

**Comment by zetok** [comment] 2015-04-28 15:01
I think that this issue should be closed.. @tux3 ?

**Comment by tux3** [comment] 2015-05-07 20:14
Yes, this should be fixed.

**Closed as completed by tux3** 2015-05-07 20:14 UTC
Labels: C-bug
