### ISSUE TITLE
Disable qtox.log - HOW?

### ISSUE THREAD

**Issue by nakadashi** [qTox/qTox#3240] opened 2016-05-01 23:20 UTC
How can I stop "qtox.log" logging?
I'm no Linux, so linking it to /dev/null is not the answer

**Comment by nakadashi** [comment] 2016-05-01 23:22
Close qTox, set it to read-only, start qTox does prevent logging, but it would be nice
if you just disable this logging. (and don't patch "read-only-counter" because I really hate loggin)

**Comment by zetok** [comment] 2016-05-02 05:27
Duplicate of #3196, thus closing.

**Closed as completed by zetok** 2016-05-02 05:27 UTC
Labels: U-low
