### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by camrodgers** [qTox/qTox#4211] opened 2017-02-26 22:13 UTC
Given that the distribution methods for tox and qtox are pretty fragmented, have you considered putting out a flatpak? It's getting support in the KDE and GNOME3 package manager GUIs.

**Comment by Diadlo** [comment] 2017-02-26 22:33
Seems, duplicate of #3879, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-02-26 22:33 UTC
