### ISSUE TITLE
Glitch receiving screenshot from uTox

### ISSUE THREAD

**Issue by Zer0-One** [qTox/qTox#2215] opened 2015-09-13 02:56 UTC
@GrayHatter sent me a screenshot from uTox, and upon clicking the Accept button I ended up with this:

![2015-09-12-222549_1366x768_scrot](https://cloud.githubusercontent.com/assets/1117820/9834950/d8283828-5986-11e5-9db8-7652a3d9a0f4.png)

It's the file-save dialog, but it's minimum size, blacked-out, and I can't click anything; the UI appears to become totally non-responsive until I exit the window with the Esc key.

I'm on Gentoo with a 4.1.6-hardened kernel. The log doesn't mention anything obvious except for a few chunks matching the following:

[22:50:10.236] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[22:50:10.236] :0 : Warning: libpng warning: iCCP: cHRM chunk does not match sRGB
[22:50:10.330] :0 : Warning: libpng warning: iCCP: known incorrect sRGB profile
[22:50:10.330] :0 : Warning: libpng warning: iCCP: cHRM chunk does not match sRGB

**Comment by zetok** [comment] 2015-09-13 05:45
Duplicate of #2205, thus closing.

**Closed as completed by zetok** 2015-09-13 05:45 UTC
Labels: U-low
