### ISSUE TITLE
file transfer window

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1318] opened 2015-03-01 12:33 UTC
i would like to propose to add a window with file transfer history and state like pidgin or skype.

![istantanea - 01032015 - 13 29 16](https://cloud.githubusercontent.com/assets/11056930/6430744/896d9678-c017-11e4-845f-4815f065a416.png)

i think that this addition will make order into chatlog and will can show us who're sending what and when! :+1:

**Comment by TheLastProject** [comment] 2015-03-01 15:01
That already partially exists, look for the two-arrows in the bottom left.

It should be improved to show progress of all transfers, though, instead of only show completed transfers.

**Comment by bitchecker** [comment] 2015-03-01 15:12
@TheLastProject yes but i think that must be redesigned completely...also removing "sent" and "received" but only one window with more information! now is only history log!

for example for distinguish from sent and received it can be use arrows, is important to have more information about user and timestamp!

i think that also an alert near the chatbox textfield, or contact name, can be useful if you enable auto-accept option and you're afk!

**Comment by zetok** [comment] 2015-08-26 10:21
Duplicate of #1300, closing.

**Closed as completed by zetok** 2015-08-26 10:21 UTC
Labels: U-low, proposal
