### ISSUE TITLE
In file transfer, please reproduce the original time stamp in that file in the destination PC.

### ISSUE THREAD

**Issue by ua7** [qTox/qTox#4792] opened 2017-11-07 04:53 UTC
##### Brief Description

OS: Windows 7 x64
qTox version: 1.12.1
Commit hash:  
toxcore:  0.1.10
Qt:  5.6.3
Hardware: 
…
In file transfer, please completely reproduce the original time stamp in that file in the destination PC.
For me,Sometimes this is a very important to manage the file version.
I want an option to select that mode.

##### Steps to reproduce

1. send any file in qTox
2. check the timestamp of that file in destination PC

##### Observed Behavior

The timestamp of that file is newest time.

##### Expected Behavior

The timestamp of that file (Last Modified , Creation , and Last Accessed) is kept originals.

**Comment by Diadlo** [comment] 2017-11-23 12:58
I'm not sure, that it's adequate behavior. IMO the expected behavior is set current time.

**Comment by ua7** [comment] 2017-12-01 05:34
I think that it is not necessary that this is the default.
But, I propose that the user can choose both by setting or toggle button.

**Comment by anthonybilinski** [comment] 2017-12-01 06:57
IMO updating time/user of the downloaded file is expected behaviour across almost any program, except explicit backup or versioning software. I think even adding the option to preserve file metadata is adding clutter to the settings menus that isn't important to the vast majority of people using a chat app.

Using tar or some other container can keep the contained files metadata, and then you could transfer the tar. Alternatively using versioning software like git to keep track of history instead of timestamps.

**Comment by sudden6** [comment] 2019-08-11 12:46
The majority of comments seems to be against this, closing.

**Closed as completed by sudden6** 2019-08-11 12:46 UTC
Labels: proposal
