### ISSUE TITLE
Video in video call was started after ~30seconds of call

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2120] opened 2015-08-26 19:26 UTC
I just had a call video-desktop sharing, as video from desktop was started automatically, my video from webcam started after 25-30 seconds of call. I am not sure about the cause of starting the video, but it could be started just after I opened settings Audio/Video tab. 

I doesn't start automatically without "help". Call was between windows and arch linux, problem is on linux.

**Comment by agilob** [comment] 2015-08-26 19:31
will be fixed by #2093

**Comment by zetok** [comment] 2015-09-17 12:47
Since it seem to be a duplicate of #1971, should be closed?

**Closed as completed** 2015-09-17 17:31 UTC
Labels: C-bug, U-low, P-high
