### ISSUE TITLE
No information when message cannot be delivered

### ISSUE THREAD

**Issue by NicoHood** [qTox/qTox#3905] opened 2016-11-21 22:05 UTC
In 1.5.1 for linux (archlinux) there is no way to determine if a message was delivered successfully or not. On antox for example there is. I have a lot of message loss with one contact and we never know which messages the othe rperson got and which not (qtox chatting with antox).

**Comment by zetok** [comment] 2016-11-21 22:26
>In 1.5.1 for linux (archlinux) there is no way to determine if a message was delivered successfully or not.

There is. If there is no spinning circle instead of message date, it was delivered successfully. Note that if you don't have enabled history that doesn't apply to client restarts.

If Antox doesn't display messages that it confirmed as received, it's a bug in Antox.

**Comment by NicoHood** [comment] 2016-11-21 22:38
antox does, but qtox doesnt.
I never see any circle at all. Even if i write to offline contacts. It just displays the date on the right.

**Comment by zetok** [comment] 2016-11-21 22:44
Do you have history enabled?

**Comment by NicoHood** [comment] 2016-11-21 22:45
no. not at all.

**Comment by zetok** [comment] 2016-11-21 22:45
Then it's not a bug.

**Comment by NicoHood** [comment] 2016-11-21 22:45
but why? its totally confusing if i dont see if the message was received or not

**Comment by zetok** [comment] 2016-11-21 22:55
>but why? its totally confusing if i dont see if the message was received or not

I've made a PR with added docs, hopefully they make things more clear: https://github.com/qTox/qTox/pull/3908 . Would be nice if you checked.

**Comment by NicoHood** [comment] 2016-11-21 22:59
This does not solve the problem. a) it does not even need to resend them. just give a notification if the message was not yet received. and b) the message is still in the ram, as its displayed on the screen. so there is still a way to resend it as long as the client is opened.

If i' at least know the sending failed, that'd extremely help.  automatic resending is something to still aim for though.

**Comment by NicoHood** [comment] 2016-11-21 23:06
You should possibly reopen it then. Thanks for taking the time ;)

**Comment by zetok** [comment] 2016-11-21 23:18
Oh, right, I forgot the press the button. Thanks for reminding. >.<"

**Comment by Diadlo** [comment] 2016-11-22 06:15
@NicoHood 
> the message is still in the ram

Just to describe situation: Problem is place, where it's stored. Now it's placed in chatform view. And it's really hard go get message from it. Trying to get the data from the `view` breaks design. qTox should be redesigned, we are working on it

**Comment by anthonybilinski** [comment] 2022-03-17 09:31
Pending messages work without history enabled since 2283d0c1b0221303197714cc2b6d90b3f0bb8144. Closing.

**Closed as completed by anthonybilinski** 2022-03-17 09:31 UTC
Labels: C-bug, M-ui
