### ISSUE TITLE
Bug: Audio call button is disabled for group on Linux

### ISSUE THREAD

**Issue by 1KoT1** [qTox/qTox#2989] opened 2016-03-05 17:59 UTC
1) Create group.
2) Add some people to group.
Actual: Audio call button is disabled
Expectation: Audio call button is enabled and I can call to gruop.

Additional info:
1) Audio call of one person is valid.
2) Audio call of group on Windows is valid.
3) When star qTox from QtCreator I see in output: [22:09:05.287] :0 : Warning: QMetaObject::invokeMethod: No such method Audio::playGroupAudio(int,int,const int16_t*,unsigned,uint8_t,unsigned)
I check Audio class. It actually hasn't method playGroupAudio

**Comment by anoadragon453** [comment] 2016-03-07 08:43
Looks like Audio::playGroupAudio was removed in ce2f8fd1d5948b6df6769ece4568d52040ce36fb. Correct me if I'm wrong, but it looks like [this line](https://github.com/tux3/qTox/blob/c82e41ff6f029dacb92ca32e8eac144505339082/src/audio/audio.cpp#L365) is still trying to call it.

**Comment by 1KoT1** [comment] 2016-03-07 12:53
> Correct me if I'm wrong, but it looks like [this line](https://github.com/tux3/qTox/blob/c82e41ff6f029dacb92ca32e8eac144505339082/src/audio/audio.cpp#L365) is still trying to call it.

You are right. I debug qTox. And I get Warning on this line.

> Looks like Audio::playGroupAudio was removed in ce2f8fd

Thank you for information.

**Comment by feeef** [comment] 2016-03-21 13:16
I confirm this bug. It was working on a previous release but after a recent upgrade of qtox it stopped working for me as well.

This is a feature that I really need as I use tox to do audio conferencing with my collaborators.

thanks for your help!

**Comment by gustavklopp** [comment] 2016-03-26 08:51
+1
@anoadragon453  How come it's working for windows and not linux since this function was deleted also for Windows code?

**Comment by anoadragon453** [comment] 2016-03-28 19:46
@gustavklopp You sure you're running the latest nightly build on Windows?

**Comment by gustavklopp** [comment] 2016-03-29 15:35
@anoadragon453  So it's disabled for Windows too? Because No, I don't have qtox installed on Windows platform, only Linux

**Comment by anoadragon453** [comment] 2016-03-29 15:36
I've got a windows partition, I'll test it when I get home.

**Comment by anoadragon453** [comment] 2016-03-29 22:22
I'm getting some odd behavior. Here's my setup: 
- qTox 791d871 Win8.1
- qTox 49b8a48 Arch Linux
- qTox db812fe Arch Linux

Putting them all into a groupchat together, I get the following:

Windows has the call button  active while it is not on either of the Linux clients. Calling and hanging up on the group from Windows crashes the clients (Group never receives call notification). One member of the group leaving and returning removes Windows' ability to call the group unless the Windows client is relaunched.

Here's the sequence of steps I used:
- Launch qTox on all three platforms
- Create Groupchat with 49b8a48 client
- Invite Windows and db812fe Linux to Groupchat with 49b8a48 client
- Call group from Windows AND end call from Windows (Windows client crashes, other clients don't receive call)
- Restart Windows client
- Re-add Windows client to groupchat
- Remove db812fe Linux from groupchat (Windows client can no longer call)

Here's the Logs from each machine:

Windows
https://gist.github.com/anoadragon453/7695bf09561c417ad2dfefb39af07015

49b8a48 Arch Linux
https://gist.github.com/anoadragon453/6fa4d317314f4ba769764d021b2ab6e6

db812fe Arch Linux
https://gist.github.com/anoadragon453/c443e8ac2b275d08678aee8c3697fc8d

Additionally, at one point during testing I found the members of the groupchat to just leave on their own, with the Windows client none the wiser. It sat there thinking there were three clients when the rest had already left. No messages would go through to any client.

Overall there's definitely a need to revise some of this code.

**Comment by sudden6** [comment] 2016-03-30 15:15
This PR should fix the audiocall buttons behavior on Linux and Windows:
- Remove db812fe Linux from groupchat (Windows client can no longer call)
- Call button inactive on Linux

Please test if there is actual Audio transmitted. (Probably not, but I don't fully understand the code yet)

Please report the crash of the windows client in a new issue, if possible with a backtrace and logs.

**Comment by feeef** [comment] 2016-03-30 16:20
Thank you so much @sudden6  !

**Comment by anoadragon453** [comment] 2016-03-31 04:29
Will test in a bit, thanks @sudden6.

**Comment by mhow2** [comment] 2016-04-22 10:12
Audio call button is greyed out. I running qTox built on:  23:12:40 Apr 21 2016 ( 1461280109 ), Ubuntu Wily.

**Comment by sudden6** [comment] 2016-04-22 10:23
@mhow2 you have to build from my PR as this isn't yet merged.

**Comment by mhow2** [comment] 2016-04-22 10:48
@sudden6 : well, thanks. I'm not going to ask this to my colleagues who are currently using Skype :)

**Comment by zetok** [comment] 2016-04-24 15:34
Should be fixed on newest master / 1.4.0 release, thus closing.

If you still can reproduce, please comment for reopen.

**Closed as completed by zetok** 2016-04-24 15:34 UTC
Labels: C-bug, P-high, M-audio
