### ISSUE TITLE
Message not highlighted when your nick contains emoticons/emojis

### ISSUE THREAD

**Issue by Ansa89** [qTox/qTox#1844] opened 2015-06-09 09:55 UTC
If your nickname contains at least one emoticon/emoji and someone write your nickname in chat, then the message isn't highlighted.

Tested with tux3/qTox@f0f2776050622982883925bdaad620a20f8eaad3.

**Comment by zetok** [comment] 2015-06-16 16:52
also doesn't work when name is set to `:3`
qTox ce2c8309a28dc49ec005610791062ee55633ef80

**Comment by zetok** [comment] 2016-09-24 12:46
Actually, it's a duplicate of #1167, thus closing.

**Closed as completed by zetok** 2016-09-24 12:46 UTC
Labels: U-low
