### ISSUE TITLE
Arabic language mirror window horizontal

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#3542] opened 2016-07-24 09:17 UTC
##### Brief Description

OS: Arch Linux
qTox version: v1.4.0-2-g24a7f4d.
Commit hash: 24a7f4d51960a73cb7234cec9a4a2811e9175c6c
Qt: 5.7.0

Reproducible: Always
##### Steps to reproduce
1. Change language on Arabic
2. Change language on English
##### Observed Behavior

Window won't reset state
##### Expected Behavior

Resetting window state
##### Additional Info

Some languages reset state.
![spectacle m15389](https://cloud.githubusercontent.com/assets/6306608/17083063/680e6456-51a4-11e6-93d5-8c07b261cba2.png)

**Comment by zetok** [comment] 2016-07-24 09:41
Can't reproduce on ff92a5595002a4156bada85eeffe4bdb3cdd7f8e under i3wm

Also, the screenshot looks like #3457 ?

**Comment by Diadlo** [comment] 2016-07-24 09:42
@zetok Sorry. Screenshot changed

**Comment by zetok** [comment] 2016-07-24 11:17
I'm using Qt 5.5.1 – could it be an upstream issue?

**Comment by Diadlo** [comment] 2016-07-24 11:42
@zetok Yes, I think about it. May be

**Comment by zetok** [comment] 2016-08-23 00:48
Reopening, since it's still not fixed on 54350fd24feb68750c0808eea708cbe0543c55b3 with Qt 5.6.1.

**Comment by Diadlo** [comment] 2016-08-23 08:28
Can't reproduse on 54350fd24feb68750c0808eea708cbe0543c55b3 with Qt 5.7.0

**Comment by ezavod** [comment] 2017-03-16 11:36
Can not reproduce in qTox version 1.8.1 neither on Windows 10 (64bit, qTox 1.8.1, Qt 5.5.1, toxcore 0.1.5) nor on Linux (openSuse Tumbleweed 64bit, KDE 5.9.2, qTox 1.8.1, Qt 5.7.1, toxcore 0.1.2).
Also not reproducible in qTox version 1.6.0 on Linux (openSuse Tumbleweed 64bit, KDE 5.9.2, qTox 1.6.0-91-gb392e2c-obs, Qt 5.7.1, toxcore 0.0.0, commit hash: [b392e2c320800c38f44370dd7deee53e7497b167](https://github.com/qTox/qTox/commit/b392e2c320800c38f44370dd7deee53e7497b167)).

This seems to be fixed.

**Comment by zetok** [comment] 2017-03-16 14:13
Still reproducible on 2923697b5ce1ed4f28d6aa10c4621470ffee3a62 , Qt 5.6.2

**Comment by Diadlo** [comment] 2017-03-16 17:05
Can't reproduce on 2923697b5ce1ed4f28d6aa10c4621470ffee3a62
with Qt 5.8.0, i3wm
@zetok, still under i3?

**Comment by zetok** [comment] 2017-03-16 19:14
Yep.

**Comment by ezavod** [comment] 2017-03-18 12:11
Still not reproducible for me (tried Ubuntu 16.04.1, X.org 1.18.4, i3wm 4.11, Qt 5.5.1 qTox 1.6.0).
@zetok Which system are you on (OS version, X.org version, i3 version)?
> I'm using Qt 5.5.1 – could it be an upstream issue?

I would speculate that this might be a problem of the window manager. This issue does not seem do be tied to a specific Qt version.

**Comment by Diadlo** [comment] 2017-03-18 15:00
@ezavod I created this issue under KDE (with kwindow)

**Comment by zetok** [comment] 2017-03-18 21:40
@ezavod 

Gentoo amd64
X: `1.18.4`, then it derped out due to buggy drivers and I had to restart it, so now I'm on `1.19.2`.
i3: `4.13`

**Comment by Diadlo** [comment] 2017-07-24 08:07
@zetok Can't reproduce under i3. Can you retest it?

**Comment by zetok** [comment] 2017-07-27 07:41
Still reproducible on d59c7223895b9cca09fd98081657541976d0.

**Comment by Diadlo** [comment] 2017-07-27 07:45
@zetok Qt version?

**Comment by zetok** [comment] 2017-07-27 07:55
Qt 5.7.1

**Comment by zetok** [comment] 2017-07-27 08:49
Sorry, it looks like I've forgotten issue description, and just based on issue title and the screenshot I thought that there is still an issue.

At some point in time language change in qTox started to change qTox's layout to RTL, and since the change wasn't listed, I've perceived it as a regression, and got it mixed up with this issue.

Since the original issue is fixed, closing.

Sorry for the confusion.

**Closed as completed by zetok** 2017-07-27 08:49 UTC
Labels: C-bug, M-ui
