### ISSUE TITLE
4k support

### ISSUE THREAD

**Issue by geeteshtabjul** [qTox/qTox#4192] opened 2017-02-22 10:41 UTC
OS: Windows
qTox version: v1.8.1.
Qt:  5.5.1
Hardware:  Dell XPS 15 (9550) with a 4k display

Reproducible: Always

The application doesn't look proper with 4k resolution, especially the icons, they are really tiny. I have attached screenshots for better understanding. The settings page looks perfectly fine. The text size and the emoji size were changed in the settings.

![login_screen](https://cloud.githubusercontent.com/assets/15844565/23207935/29a0fb9e-f919-11e6-8d42-56e1f3c92821.png)
![main_screen](https://cloud.githubusercontent.com/assets/15844565/23207936/29a716d2-f919-11e6-9556-b1f837e00deb.png)

**Comment by Diadlo** [comment] 2017-02-22 16:14
Seems, duplicate of #2995, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-02-22 16:14 UTC
Labels: U-low
