### ISSUE TITLE
qTox will not open in macOS Sierra (10.12)

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3789] opened 2016-10-06 11:30 UTC
##### Brief Description

OS: macOS Sierra 10.12 (16A323)
qTox version: 1.5.1
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always
##### Steps to reproduce
1. Launch the application
##### Observed Behavior
1. macOS Problem Reporter launces, stating that the application "could not open because of an error"
##### Expected Behavior
1. Application should launch as expected
##### Additional Info

Paste from macOS Problem Reporter:

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/ffmpeg/3.1.2/lib/libavcodec.57.dylib
  Referenced from: /Applications/qTox.app/Contents/Frameworks/libavformat.57.dylib
  Reason: image not found

---

Could not locate error log in macOS, please advice.

Also, this my first issue report on GitHub. For any screw-ups on my part, I apologize in advance.

**Comment by zetok** [comment] 2016-10-06 11:41
Duplicate of #3747, closing.

**Closed as completed by zetok** 2016-10-06 11:41 UTC
Labels: U-low
