### ISSUE TITLE
Video calls crashes (with Antox)

### ISSUE THREAD

**Issue by freddi301** [qTox/qTox#6329] opened 2021-04-13 10:23 UTC
##### Brief Description

OS: Win10
qTox version:  v1.17.3.
Commit hash:  c0e9a3b79609681e5b9f6bbf8f9a36cb1993dc5f
toxcore:   0.2.12
Qt:  5.12.9

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. videocall from Antox android app

##### Observed Behavior

qtox crashes few seconds after

##### Expected Behavior

can videocall indefinitely

**Comment by pboettcher** [comment] 2022-03-13 15:41
Сan confirm with 1.17.6 on Win7 SP1 64 bit. The application transfers video, then crashes a few seconds after the video shatters into squares.
Is always reproducible.

qTox settings:
Enable IPv6 = true
Enable UDP = true
Enable LAN discovery = true

UDP in Antox is disabled.
When I enable UDP in Antox, qTox can transfer video indefinitely and doesn't crash.

**Comment by anthonybilinski** [comment] 2022-03-16 13:35
Checking with gdb on version v1.17.6 on Windows 11, there's a segfault happening on libvpx.

I don't see this on Linux with v1.17.6, and don't see it on Windows 11 with a nightly build. I see tons of logs about corrupt frames which makes sense with all the video corruption that qTox is receiving. Probably a toxcore libvpx update since qTox v1.17.6 handles the corruption better causing it to not segfault.

So this should be fixed for free once v1.18.0 is out. Optionally you could use a nightly build until then: https://github.com/qTox/qTox/releases/tag/nightly, though pay attention to the warning in the release notes.

**Closed as completed by anthonybilinski** 2022-03-16 13:35 UTC
