### ISSUE TITLE
Update popup even after update to 1.3.0

### ISSUE THREAD

**Issue by suchpool** [qTox/qTox#3062] opened 2016-03-27 03:46 UTC
I updated to qtox 1.3.0 manually since I tought the updater wasn't working well cause the popup about an update kept coming. But even after updating (using the 64 bit installer) manually and seeing 1.3.0 in the about page I keep getting the popup that ask me to update. Every time I login the popup appear. 

qTox version: 1.3.0 
From the about page:
You are using qTox version v1.3.0. 
Commit hash: b69042ec407c30b27ce3e56bb6daf14300facc8e 
toxcore version: 0.0.0

Hardware:  Windows 10 Enterprise 64 bit

**Steps to reproduce:**  
1.  Install the version prior to 1.3.0 (installer not portable)
2.  start it, login, it'll ask to update 
3. Update 
4. Restart with 1.3.0 (confirm the update really worked by checking the about page)
5. Popup still appear even after update

**Comment by TON14** [comment] 2016-03-27 09:22
I have same problem!

**Comment by LittleVulpix** [comment] 2016-04-30 09:59
Yep, same on my dad's PC. except there it actually _crashes_ during the update. But the rest is the same.

**Comment by CryptoSiD** [comment] 2016-05-04 10:57
Still happening with 1.4.0
tux3 told me yesterday on freenode that  it should be fixed but it's not!

**Comment by LittleVulpix** [comment] 2016-05-04 12:04
@CryptoSiD Not happening with 1.4.0 for me. What's your OS/UAC setting ? And did you update or downloaded the binary directly and then it started asking you to update?

**Comment by zetok** [comment] 2016-05-09 17:13
Should be fixed with newest 1.4.1 release, released today. Could you see if after updating problem is gone?

**Comment by CryptoSiD** [comment] 2016-05-09 20:22
I confirm that the problem is fixed with 1.4.1

**Comment by zetok** [comment] 2016-05-09 20:55
Since it's fixed, closing.

**Closed as completed by zetok** 2016-05-09 20:55 UTC
Labels: C-bug, M-packaging, OS-windows, P-medium
