### ISSUE TITLE
problem to swith to the last 1.11.0 version (infinite download loop)

### ISSUE THREAD

**Issue by user67x** [qTox/qTox#4557] opened 2017-08-03 10:46 UTC
##### Brief Description

OS: Windows 8.1
qTox version: v1.10.2
Commit hash: b73603b45a32e63a649294537a62a9f11176c73d
toxcore: 0.1.8
Qt: 5.6.2
Hardware: 
…

Reproducible: Always 

##### Steps to reproduce

1. In "about" tab, I notice there is a new version for qTox : the 1.11.0
2. It's demander to relaunch the client for switch to this version
3. The qTox 1.11.0 is always relaunched to download and never installe it self.

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by user67x** [comment] 2017-08-03 11:58
Ok, I have launch manually the : qtox-updater.exe
The update is now ok.

**Comment by sudden6** [comment] 2017-08-05 21:41
Lets see if others have this problem too before we close this.

**Comment by HarleyLorenzo** [comment] 2017-08-17 13:50
I definitely have this problem on Windows (64-bit). I'm going to try the solution and confirm if it works for me.

Edit: Yes, @user67x 's solution worked for me and it stopped the infinite update loop. By the looks of what happens, it seems the application itself does not actually trigger the update executable even if you click the update button in the application. Also, it's worth noting that it was asking me to update even though I was already running the latest version (maybe not the latest build, not sure.)

**Comment by sudden6** [comment] 2017-08-18 19:03
@tux3 If you find time, please look at this.

**Comment by anthonybilinski** [comment] 2017-09-10 07:36
confirmed on v1.11.0 66b133c8d4, windows 10 64-bit, fresh download

**Comment by user67x** [comment] 2017-11-15 16:45
The problem still exist with 1.12.1

**Comment by Diadlo** [comment] 2017-11-15 18:27
Can anyone post qTox log here? After update click and after restart

**Comment by sudden6** [comment] 2018-04-01 12:42
Auto update is now disabled, thus closing.

**Closed as completed by sudden6** 2018-04-01 12:42 UTC
Labels: C-bug, M-packaging, OS-windows
