### ISSUE TITLE
qTox opens /dev/video0 twice every time the tab is clicked

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5743] opened 2019-07-07 05:56 UTC
Every time Audio/Video tab is clicked /dev/video0 is opened twice. When some other tab is clicked one of the file handles is closed, but the other one isn't, then when the Audio/Video tab is clicked again - another 2 file handles are opened, so on, so forth.

```
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   45u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   45u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   47u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   47u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   45u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   47u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   51u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   47u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   51u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
[yuri@yv ~]$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    24624 yuri   42u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   45u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   47u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   51u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   52u  VCHR  0,150      0t0  150 /dev/video0
qtox    24624 yuri   54u  VCHR  0,150      0t0  150 /dev/video0
```

qTox-1.16.3-529-gb4450319 (from the port)
FreeBSD 12.0 amd64

**Comment by Diadlo** [comment] 2019-07-07 11:16
Does this happen on video call too?

**Comment by yurivict** [comment] 2019-07-07 17:26
I only tried without making calls.

**Comment by anthonybilinski** [comment] 2021-06-18 15:37
Leaking of one device is caused by https://github.com/qTox/qTox/issues/6346 and fixed by https://github.com/qTox/qTox/pull/6348. The part where we open two file descriptors while using the camera seems to come straight from `avformat_open_input`. We have 0 open right before it, and 2 right after it. https://github.com/qTox/qTox/blob/55fb28b08b7eeb60fc2698ad9cb8e36e9db93e19/src/video/cameradevice.cpp#L107.

On my system I see lsof show one entry as type "mem" and one regular file descriptor, and both are closed when clicking away from the A/V tab (after https://github.com/qTox/qTox/pull/6348).

I'm not sure that this is actually a bug, rather than `avformat_open_input` just choosing to open the device in two ways at once while using it.

**Comment by anthonybilinski** [comment] 2021-06-18 15:42
Checking with OBS, opening the same webcam I also see one "mem" type and one file descriptor type entry under lsof. I'm happy to close this, unless there's objection.

```
qtox    mem    CHR   81,0           582 /dev/video0
qtox     56u   CHR   81,0      0t0  582 /dev/video0
```

```
obs     mem    CHR   81,0           582 /dev/video0
obs      39u   CHR   81,0      0t0  582 /dev/video0
```

**Closed as completed** 2021-06-18 18:49 UTC
Labels: C-bug, M-perf
