### ISSUE TITLE
Profile not loaded, qtox crashes

### ISSUE THREAD

**Issue by meaz** [qTox/qTox#4352] opened 2017-04-27 19:21 UTC
Hi,

I'm on Debian stretch 64, so I installed qtox using the provided link [https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox](url)
The installation worked perfectly: no error messages.
However, when I create a new profile, qtox crashes. But some files are created in `~/.config/tox` (here a profile with the username "test"):
qtox.ini.lock
qtox.ini.T24284
test.db
test.db-journal
test.ini
test.lock

I installed utox, created a profile, closed utox: I can open qtox with the profile and that works!

Thanks

**Comment by sudden6** [comment] 2017-04-28 10:47
Can you check if it's a duplicate of https://github.com/qTox/qTox/issues/4054 ?

**Comment by meaz** [comment] 2017-04-28 15:48
Hi,

yes you're right, it is a duplicate...

**Comment by sudden6** [comment] 2017-04-28 18:30
Thx for checking, I'll close this one then.

**Closed as completed by sudden6** 2017-04-28 18:30 UTC
Labels: U-low
