### ISSUE TITLE
Optional ability to get desktop-notifications when contacts go online, offline, change status, etc...

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2885] opened 2016-01-28 16:09 UTC
In many IM programs such as Skype and Steam (though that is not its main functionality, it has it, so I thought I would mention it) you have the ability to change what you get alerted for and you can also choose to be alerted (though not usually on by default) and have desktop-notifications for activity such as your friends' statuses changing, them going going online, offline, and any of the other states, etc... So I think it would be nice if qTox at least allowed you to get notifications about when your friends come online and go offline if not some other activity.

**Comment by zetok** [comment] 2016-01-28 17:19
Duplicate of https://github.com/tux3/qTox/issues/483#issuecomment-59968354, thus closing.

**Closed as completed by zetok** 2016-01-28 17:19 UTC
Labels: U-low
