### ISSUE TITLE
Resize username column

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#1974] opened 2015-07-08 10:48 UTC
Hello,

only a suggestion:
For some people it would be great, I think, if they could resize the username column. Especially, if people in Groupchats are using long usernames, it really could make sense if there would be more place for the names.

Screenshot: http://oi58.tinypic.com/984pba.jpg
(I shaded the column I am speaking about in yellow)

**Comment by TheSpiritXIII** [comment] 2015-07-08 11:33
It's already possible in my chatform branch. This will come soon.

**Comment by Diadlo** [comment] 2018-11-16 03:49
Seems, duplicate of #1190, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2018-11-16 03:49 UTC
Labels: M-ui, proposal-accepted
