### ISSUE TITLE
Adding Repo: gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by simonkrausgit** [qTox/qTox#2117] opened 2015-08-26 08:50 UTC
When trying to add the repo using the explanation from the Tox Wiki or from the INSTALL File (which seem to be the same except for the Key deletion I'm getting gpg error.
Here is the script I executed:

``` bash
#remove old key
sudo apt-key del 0C2E03A0
sudo sh -c 'echo "deb https://pkg.tox.chat/ nightly main" > /etc/apt/sources.list.d/tox.list'
wget -q O - https://pkg.tox.chat/pubkey.gpg | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update -qq
echo "Tox Repository Installed."
echo "You can now install qtox"
```

**Comment by zetok** [comment] 2015-08-26 09:54
Duplicate of  #2111.

Right, for time being until it will be maintained again, it should be removed from ISNTALL.md

**Comment by zetok** [comment] 2015-08-26 10:05
Done in f5c02def6d8c8872b7dcf26f2c24e1c3e86655f5

**Closed as completed by zetok** 2015-08-26 10:05 UTC
Labels: U-low
