### ISSUE TITLE
tox drops call after 15 min

### ISSUE THREAD

**Issue by katamari1992** [qTox/qTox#3150] opened 2016-04-16 07:22 UTC
##### Brief Description

OS: Linuxmint 17.3
qTox version: v1.3.0-138-g32ed2ac.
Commit hash:  
toxcore:  most recent
Qt:  unsure python-qt4          4.10.4+dfsg-1ubuntu1 

Reproducible: Always
##### Observed Behavior

I'm having a call between tox and antox the call drops off after 15 minutes like clockwork
I'd like to know what's causing this (I believe I know) 
I believe the sip (re-call?) isn't being responded to but I don't know as I haven't done extensive testing 
merely idle chatting over the call
##### Expected Behavior

not to drop the call

**Comment by zetok** [comment] 2016-04-16 07:24
Could it be a duplicate of #2926?

**Comment by katamari1992** [comment] 2016-04-16 07:32
very possible

**Comment by zetok** [comment] 2016-04-16 07:50
Duplicate, thus closing.

**Closed as completed by zetok** 2016-04-16 07:50 UTC
Labels: C-bug, U-low, M-audio
