### ISSUE TITLE
Question or Request - adjustable text entry window?

### ISSUE THREAD

**Issue by phd21** [qTox/qTox#5557] opened 2019-02-18 18:48 UTC
Hi qTox developers and maintainers, 

I hope you are all doing well.

using qTox version v1.16.3-207-gea9f4298 in Linux Mint 19 (Ubuntu 18.04).

It would be very nice to have an adjustable text entry window? Is there a way to make that larger like 4 lines or to automatically resize itself based on what's being entered?

Best regards,
Phil (phd21)

**Comment by sudden6** [comment] 2019-02-23 19:10
duplicate of https://github.com/qTox/qTox/issues/1316

**Closed as completed by sudden6** 2019-02-23 19:10 UTC
