### ISSUE TITLE
Automatically adjusts the microphone level

### ISSUE THREAD

**Issue by alexeysvrv** [qTox/qTox#2469] opened 2015-10-25 17:31 UTC
In the main branch in the program setting level microphone is not connected to a level in the microphone system. I would like to automatically adjust the level of the microphone, depending on the volume of your voice. This can be done?

**Comment by antis81** [comment] 2016-01-09 20:53
I'll see what I can do. Working on volume control currently in #2768.

**Comment by antis81** [comment] 2016-06-04 21:14
Duplicate of #2422. @alexeysvrv Btw. input gain can now manually be controlled via digital amplifier from -30 to 30dB in latest qTox version - no automatic normalization, but far better than before.

**Closed as completed by antis81** 2016-06-04 21:14 UTC
Labels: U-low, proposal, M-audio
