### ISSUE TITLE
RTL text is not showing correctly in chat box.

### ISSUE THREAD

**Issue by banx** [qTox/qTox#1465] opened 2015-03-24 21:35 UTC
When writing Arabic text, the conversation text box does not show the sent text correctly. It is hiding some part of the Arabic text (and entirely hides short lines) behind a white rectangle (as it appears). Ir seems that this might be generalized for all RTL text, but testing is needed to confirm.
Refer to the attached screenshot for a visual proof.

![qtox-rtl-bug](https://cloud.githubusercontent.com/assets/345006/6813489/3b9cde44-d27e-11e4-96d0-c8a36549e279.png)

The text shown in the typing text box is what is expected to appear in the conversation box. However it appears to be cropped.

**Comment by dubslow** [comment] 2015-03-25 00:35
Could this be an isssue with protocol breakage? If your friend is using uTox on the new_api, the first four bytes of the message are swallowed due to incompatible protocols.

**Comment by tux3** [comment] 2015-03-26 09:21
Does it happen if you send a message to yourself in an empty groupchat ?

**Comment by banx** [comment] 2015-03-28 15:08
@tux3 Yes it does
![rtl bug - group chat](https://cloud.githubusercontent.com/assets/345006/6881556/c6516672-d56c-11e4-9bd6-d4043842de7d.png)
@dubslow I don't think it's related to the other user client (Check screenshot). It seems it's related to the GUI handling of RTL text in qtox.

**Comment by zetok** [comment] 2015-08-27 08:40
Perhaps #2013 would help with it.

**Comment by zetok** [comment] 2015-09-28 19:43
#1887 is actually a duplicate of this one, but this gets closed in favour of the other issue having more useful info.

**Closed as completed by zetok** 2015-09-28 19:43 UTC
Labels: C-bug, U-low, P-low, M-ui
