### ISSUE TITLE
[FR]  Contact Layout Persistance, including a better sort feature /layout 

### ISSUE THREAD

**Issue by linux-modder** [qTox/qTox#2009] opened 2015-07-16 12:46 UTC
Persistence of  contact layout..

Say you prefer layout per  "activity" aka  most contacted folks at  top,  but have to reset on reload, can seem trivial but for those with longer contact lists it is a feature that makes sense

**Comment by ProMcTagonist** [comment] 2015-07-16 17:24
+1

**Comment by agilob** [comment] 2015-07-16 17:41
come on, name your issues properly or close.

**Comment by An-dy** [comment] 2015-07-17 03:17
+1
Btw. I not even detected the "sort by" feature by my own.
I assumed "By name" means SEARCH by name / SEARCH all and "all" means search in the name line AND the status line. A arrow (↑ or ↓) instead of "By" had prevented this misunderstanding and added extra functionality  ↑=cba ↓=abc.
Another thought: why not searching in the status line as second criteria? 
h find "Hank" in the name field and "Hello" in the status field. Display order: all names first followed by status lines with "h".
?
The user who "searches" is looking for a string in a contact record and not really care where this string is.
OK lets take search a step further.
I have unlimited storage of chat history on (my pc is save).
This is a great feature! 
(my email archive has 28,000+ emails (starting from 1994) is qtox ready for a chat history in this dimension ?)
But I can't search the growing "archive" of chat history for a string.
The chat archive would gain a lot of value if I could search in it.
Where would a user _expect_ a chat archive search ?

**Comment by TheSpiritXIII** [comment] 2015-07-17 14:56
@An-dy Perhaps you should make a separate feature request for your ideas as they "take a step further" from what is actually being requested here and, in my opinion, going out of scope.

**Comment by linux-modder** [comment] 2015-07-17 15:17
@TheSpiritXIII, not sure I see the out of scope part.

**Comment by zetok** [comment] 2015-08-30 11:06
This issue looks like a duplicate of #645, closing.

**Closed as completed by zetok** 2015-08-30 11:06 UTC
Labels: U-low
