### ISSUE TITLE
Segfault on send/receive file 

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1978] opened 2015-07-08 17:56 UTC
I sent a file to my friend, he acceptés ans both of us segault'ed without reason.

**Comment by suhr** [comment] 2015-07-08 18:10
Logs and backtrace would be nice to have.

**Comment by agilob** [comment] 2015-08-20 21:44
please tell how to reproduce or/and provide backtrace. I can't reproduce.

**Comment by zetok** [comment] 2015-09-10 13:59
Closing, since no usable info was provided.

**Closed as completed by zetok** 2015-09-10 13:59 UTC
Labels: O-need-info
