### ISSUE TITLE
Need more installation options for Windows

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3730] opened 2016-09-20 21:08 UTC
When I recommended qTox to someone and they tried to download it from here https://build.tox.chat/view/qtox/job/qTox_pkg_windows_x86-64_stable_release/lastSuccessfulBuild/artifact/setup-qtox.exe , they said that the browser page comes up blank. They tried many times - same result.

It is possible that this site is blocked in the country this person is in or it is also possible there is some other technical difficulty. qTox needs more installation options for simple windows users. You probably should also host windows binaries (like you do with OSX binaties) on github, and maybe some other places.

**Comment by zetok** [comment] 2016-09-21 03:23
> (…) they said that the browser page comes up blank. They tried many times - same result.

Couldn't reproduce. (with wget)

> It is possible that this site is blocked in the country this person is in or it is also possible there is some other technical difficulty.

Which country/ISP? (perhaps that could be added to FAQ somewhere)
Did your friend try to use some alternative DNS servers, e.g. from ~~googl~~ botnet? It's `8.8.8.8`, `8.8.4.4`.

> You probably should also host windows binaries (like you do with OSX binaties) on github, and maybe some other places.

I've mirrored stable `setup-qtox.exe`, both 32 and 64 bit versions along with their signatures under [v1.5.1](https://github.com/qTox/qTox/releases/tag/v1.5.1) release, hopefully that will work for your friend.

**Comment by yurivict** [comment] 2016-09-21 04:38
> Which country/ISP? (perhaps that could be added to FAQ somewhere)
> Did your friend try to use some alternative DNS servers, e.g. from googl botnet? It's 8.8.8.8, 8.8.4.4.

This is Belarus, the BelTeleComm provider. Many websites are blocked in this part of the world, so I won't be amazed if qTox is blocked too. It is also one of only two countries in the world where Tor is illegal.

**Comment by sudden6** [comment] 2016-09-22 16:33
In my Firefox the page comes up blank, but it prompts me to save the file. Maybe your contact mistook this for the page not working?

EDIT: For windows you can also point them to https://tox.chat/download.html which offers all options

**Comment by yurivict** [comment] 2016-09-22 16:48
This is possible. I just tried, in my firefox it offers choices download/choose a program to open with.

**Comment by zetok** [comment] 2016-10-28 16:53
Since it doesn't look like a problem anymore, closing.

**Closed as completed by zetok** 2016-10-28 16:53 UTC
Labels: M-packaging, OS-windows
