### ISSUE TITLE
Feature request: "faux offline file-sending"

### ISSUE THREAD

**Issue by Geremia** [qTox/qTox#4411] opened 2017-05-19 00:00 UTC
Currently, when I try sending a file to an offline friend, qTox immediately returns "Failed to send file". Instead, it could emulate the behavior of "faux offline messaging" and send the file when the user comes online.

**Comment by zetok** [comment] 2017-05-19 21:13
Duplicate of #1293, thus closing.

**Closed as completed by zetok** 2017-05-19 21:13 UTC
Labels: U-low
