### ISSUE TITLE
'Circles' settings wiped out  from -243 to -314

### ISSUE THREAD

**Issue by linux-modder** [qTox/qTox#2892] opened 2016-01-29 12:17 UTC
Noticed the other day that when going to -243 that all my  settings EXCEPT circles were saved,  on a recompile to -314  this was not the case all circles I had  manually  regenerated were honored on the -314 compile... Stands to reason while likely  trivial for most that  your circles should be honored and not  nixed during a re-compile or  not api breaking version bump.

**Comment by tux3** [comment] 2016-01-29 12:26
So the bug was when going to 243, but it's fixed in 314?

**Comment by zetok** [comment] 2016-01-29 12:33
Actually, on IRC @linux-modder wrote:

```
<linuxmodder> anyone able to explain why -243 -> 314 reverted all 'circles' to non existent ?
```

**Comment by linux-modder** [comment] 2016-01-29 12:38
@tux3 This has happened in the past as well but  I thought it was just some locally  buggered up setting I recently confirmed with a friend it was not.  Odd more still, is that if you don't reset your circles on 243 314 does not  notify you or attempt to regenerate them (even if it is in an older config)   however some sanity check in 314  DOES maintain them if  set manually  before the ver bump.

243 -- no circles  regenerated (previous configs ignored) >  314  -- still no circles but  config there for it

243 -- regenerate circles >  314 -- all is as would be expected 

In both cases ALL other settings honored as expected

**Comment by tux3** [comment] 2016-01-29 13:28
What do you mean by regenerate?

**Comment by linux-modder** [comment] 2016-01-29 14:01
No circles >  make new circle; repeat for all circles desired and re-shuffle folks to respective circles

**Comment by tux3** [comment] 2016-01-29 14:04
Okay. That's weird. Do you use an encrypted profile?
It could be a problem with password management that made the circles settings fail to decrypt.

You didn't lose the chat history at the same time, did you?

**Comment by linux-modder** [comment] 2016-01-29 14:20
no kidding.

Seems like the  default in 243 did NOT have a sanity check for existing
contact list formatting

**Comment by tux3** [comment] 2016-01-29 14:22
Thanks, but please stop spamming your 2 pages long signature or I'll edit it out...

**Comment by linux-modder** [comment] 2016-01-29 15:05
sorry was from email not  github my bad

**Comment by Diadlo** [comment] 2016-09-12 21:23
Can anyone describe, what is the magic numbers `-243` and `-314`?)

**Comment by zetok** [comment] 2016-09-13 01:54
@Diadlo it's a suffix denoting number of commits since tagged version[1], IIRC in this case since 1.4.0.

So, somewhere in between those commits there was a regression that wiped out @linux-modder's circles.

[1] this thing:![qtox version](https://cloud.githubusercontent.com/assets/3148759/18458865/d0a630cc-795c-11e6-94fd-08d107c6517e.png)

**Comment by zetok** [comment] 2016-12-28 14:09
Is this reproducible on newer qTox versions?

**Comment by Diadlo** [comment] 2017-02-24 08:26
Needed info not provided for over a month, thus closing.

**Closed as completed by Diadlo** 2017-02-24 08:26 UTC
Labels: C-bug, P-high, O-need-info
