### ISSUE TITLE
Have the ability to be able to search for strings in chat history

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2954] opened 2016-02-14 18:31 UTC
Perhaps in the "Load History Dialog" there should be the option to search through your chat history for strings (certain keywords to phrases - and you could specify if you only want it to show results where those words go after each other in that exact order, or if you just want any places with those keywords mentioned even if only one of them is), and of course also the ability to choose the time frame that you want to search for them in (you could select a day, dates between two dates, or your entire history).

Because sometimes I know I have said something in the past, but unless I go through all of my chat history, I will probably never find it, and I have a lot of chat history... Plus it doesn't even tell me which days I have chatted on yet (I made another feature request on this)...

**Comment by ovalseven8** [comment] 2016-02-14 19:00
At least https://github.com/tux3/qTox/pull/2013 would include:

> - You can now search and find text in the chat form using Ctrl+F.

Unfortunately, the PR is outdated. :/

**Comment by ProMcTagonist** [comment] 2016-02-14 22:30
dup

https://github.com/tux3/qTox/issues/1734

https://github.com/tux3/qTox/issues/2377

**Comment by zetok** [comment] 2016-02-14 22:34
Since it's a duplicate of #1734, closing.

**Closed as completed by zetok** 2016-02-14 22:34 UTC
Labels: U-low, proposal, M-ui
