### ISSUE TITLE
Offline file sending should pile up and send when next possible like with offline messaging rather than just failing

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2904] opened 2016-01-31 16:40 UTC
If one sends a message when the other user is offline, the message is stored until both users are online and then the message is sent, this is the basic offline messaging system currently in use in qTox. However if one is to try and send a file to another user who is currently offline, one just gets something like this:

![failed_to_send_file_qtox](https://cloud.githubusercontent.com/assets/11575271/12703349/d9f7d0ac-c838-11e5-8ad8-b79a3ef93c0a.png)

Instead I think that it should be the same as it is for messaging, so that when the other user is online at the same time as you are, then the file should attempt to send (or rather they should be prompt if they want it as usual, and then if they accept it it will be sent to them, and if they decline then obviously not - though of course it will always check before asking them if the file has moved location, if so, it will fail to send and probably put the error one currently gets).

**Comment by zetok** [comment] 2016-01-31 16:55
Duplicate of #1293, thus closing.

**Closed as completed by zetok** 2016-01-31 16:55 UTC
Labels: U-low, proposal
