### ISSUE TITLE
Sync Combobox in Fusion style

### ISSUE THREAD

**Issue by Bargest** [qTox/qTox#1941] opened 2015-06-29 22:07 UTC
It looks very strange: items are half at height.
![image](https://cloud.githubusercontent.com/assets/13108544/8419638/e646ad5c-1ec3-11e5-9287-38e9888b40b4.png)
When switching from Fusion to Vista, an opposite bug appears: items become twice at height.
![image](https://cloud.githubusercontent.com/assets/13108544/8419690/4afccf38-1ec4-11e5-8e1a-d71b2c8b622e.png)
But when changin to Vista style from any other, combobox looks fine.

**Comment by agilob** [comment] 2015-06-30 09:22
I never could reproduce it, but I think it's because of fault in CSS not QtFusion, this **might** be fixed in https://github.com/tux3/qTox/pull/1882

**Comment by zetok** [comment] 2015-08-30 09:57
Closing, since other issue with that problem was said to be fixed.

**Closed as completed by zetok** 2015-08-30 09:57 UTC
Labels: C-bug, U-low
