### ISSUE TITLE
can't use private proxies with qtox...

### ISSUE THREAD

**Issue by brightersun99** [qTox/qTox#6300] opened 2021-02-09 12:22 UTC
##### Brief Description

OS: 5.10.11-arch1-1 #1 SMP archlinux x64
qTox version: (version numbers in menu `Settings → About`)  
Commit hash: c0e9a3b79609681e5b9f6bbf8f9a36cb1993dc5f
toxcore:  0.2.12
Qt:  : 5.15.2
…

Reproducible: Always

We are unable to use private proxies with qtox. there is no username or password field for them... it almost seemed common sense, that p2p programs would have this functionality, that this does not truly surprises me. 

Proxies are a stable of p2p, please fix this.

Again, there are no way to use private proxies with qtox, only public proxies which are essentially useless

**Comment by brightersun99** [comment] 2021-02-09 12:26
Im assuming since, it wasn't here already that this software has some really weird opinion that defies common sense and I will probably never see it added. 

I guess I will just not use qtox, or tox in general.

**Comment by anthonybilinski** [comment] 2021-02-09 20:15
Duplicate of https://github.com/qTox/qTox/issues/1286. Toxcore, the network library that qTox uses, would need to add support.

**Closed as completed by anthonybilinski** 2021-02-09 20:15 UTC

**Comment by anthonybilinski** [comment] 2021-02-09 22:53
https://github.com/TokTok/c-toxcore/issues/1682 created.
