### ISSUE TITLE
Allow full importation of profiles through the GUI

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2791] opened 2016-01-11 18:27 UTC
I understand that in the past it was possible to import through the GUI, however now it is not possible, so one has to manually move the `.tox` file into the correct Tox folder.

But I think it would be a rather simple feature to just have an import button in the GUI which just allows you to move the `.tox` file into the right place automatically, and then just set the pull-down menu of the profile you want to log into to that one.

Or is there a specific reason why it would be difficult to do this?

**Comment by zetok** [comment] 2016-01-11 19:36
Duplicate of #1872, thus closing.

There's also #2050.

**Closed as completed by zetok** 2016-01-11 19:36 UTC
Labels: U-low
