### ISSUE TITLE
File transfer issue

### ISSUE THREAD

**Issue by Madotsukii** [qTox/qTox#2017] opened 2015-07-18 15:54 UTC
It seems like if client A sends 2 or more files (video?) and client B accepts while downloading one, client A crashes.

**Comment by agilob** [comment] 2015-08-03 21:01
both users use qtox? how big the files are?

**Comment by zetok** [comment] 2015-08-30 11:10
Looks like it's related to #1875

**Comment by tox-user** [comment] 2018-06-02 19:07
Can't reproduce in 1.15.0, so I will close this.

**Closed by tox-user** 2018-06-02 19:07 UTC
Labels: I-bug, I-crash, P-medium, up for grabs
