### ISSUE TITLE
Icon stays green even after internet connection went down for over 1 hour

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#1660] opened 2015-05-16 08:21 UTC
I noticed that qTox doesn't notice that connection is down. It should go yellow once it doesn't get any response for over certain short period of time.

**Comment by ProMcTagonist** [comment] 2015-05-16 08:35
Why would it mark you as away?

**Comment by yurivict** [comment] 2015-05-16 09:21
Actually, window says "Offline", and the light is green. Maybe it shouldn't mark me as away, but I am de-facto offline for others though, if there is no connection.

I suggest, qTox icon should reflect the actual network connection state. Skype does indicate that you are disconnected, and this is very helpful, and I believe many people will appreciate this. Maybe there should be two values: Online status, and connection status, both reflected in the icon.

**Comment by agilob** [comment] 2015-05-16 09:25
Duplicate of issues https://github.com/tux3/qTox/issues/1560 https://github.com/tux3/qTox/issues/1369

**Comment by yurivict** [comment] 2015-05-16 09:31
Duplicate of #1369

**Comment by agilob** [comment] 2015-05-16 10:00
Why did you close it? Please reopen, this issue is not solved.

**Comment by yurivict** [comment] 2015-05-16 10:44
But this is a duplicate of #1369 ?

**Comment by tux3** [comment] 2015-05-16 11:18
Historically, we tend to leave duplicates open until they are fully resolved, but either ways are fine.

**Comment by zetok** [comment] 2015-08-28 07:25
Closing, since it's a duplicate.

**Closed as completed by zetok** 2015-08-28 07:25 UTC
Labels: C-bug, U-low, proposal
