### ISSUE TITLE
Clang compile warnings

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4248] opened 2017-03-11 20:29 UTC
```
src/chatlog/chatlinecontent.cpp:73:48: warning: unused parameter 'font' [-Wunused-parameter]
void ChatLineContent::fontChanged(const QFont& font)
src/chatlog/textformatter.cpp:206:5: warning: ignoring return value of function declared with warn_unused_result attribute [-Wunused-result]
    message.toHtmlEscaped();
    ^~~~~~~~~~~~~~~~~~~~~
src/video/camerasource.cpp:286:42: warning: 'codec' is deprecated [-Wdeprecated-declarations]
        if (device->context->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
                                         ^
../../../../local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
src/video/camerasource.cpp:298:60: warning: 'codec' is deprecated [-Wdeprecated-declarations]
    cctxOrig = device->context->streams[videoStreamIndex]->codec;
                                                           ^
../../../../local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
src/video/camerasource.cpp:307:9: warning: 'avcodec_copy_context' is deprecated [-Wdeprecated-declarations]
    if (avcodec_copy_context(cctx, cctxOrig) != 0) {
        ^
../../../../local/include/libavcodec/avcodec.h:4241:5: note: 'avcodec_copy_context' has been explicitly marked deprecated here
int avcodec_copy_context(AVCodecContext *dest, const AVCodecContext *src);
    ^
src/video/camerasource.cpp:375:13: warning: 'avcodec_decode_video2' is deprecated [-Wdeprecated-declarations]
            avcodec_decode_video2(cctx, frame, &frameFinished, &packet);
            ^
../../../../local/include/libavcodec/avcodec.h:4812:5: note: 'avcodec_decode_video2' has been explicitly marked deprecated here
int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
    ^
src/widget/form/groupinviteform.cpp:51:7: warning: field 'scroll' will be initialized after field 'headLabel' [-Wreorder]
    , scroll(new QScrollArea(this))
      ^
src/widget/form/groupinviteform.cpp:52:7: warning: field 'headLabel' will be initialized after field 'headWidget' [-Wreorder]
    , headLabel(new QLabel(this))
      ^
src/widget/form/groupinvitewidget.cpp:40:7: warning: field 'widgetLayout' will be initialized after field 'acceptButton' [-Wreorder]
    , widgetLayout(new QHBoxLayout(this))
      ^
src/widget/widget.cpp:2069:52: warning: unused parameter 'w' [-Wunused-parameter]
inline QIcon Widget::prepareIcon(QString path, int w, int h)
                                                   ^
src/widget/widget.cpp:2069:59: warning: unused parameter 'h' [-Wunused-parameter]
inline QIcon Widget::prepareIcon(QString path, int w, int h)
                                                          ^
```

**Comment by Diadlo** [comment] 2017-03-12 07:42
> 'codec' is deprecated
> 'avcodec_decode_video2' is deprecated

Duplicate of #3727 and fixed in #4180

**Comment by sudden6** [comment] 2017-03-12 14:54
```
src/chatlog/textformatter.cpp:206:5: warning: ignoring return value of function declared with warn_unused_result attribute [-Wunused-result]
    message.toHtmlEscaped();
    ^~~~~~~~~~~~~~~~~~~~~
```

cc @noavarice

**Comment by yurivict** [comment] 2017-04-01 17:42
There's the new one now:
```
src/widget/contentdialog.cppcompiling src/widget/form/settings/privacyform.cpp
:355:56: warning: '&&' within '||' [-Wlogical-op-parentheses]
        bool nextIsEmpty = isCurOnline && offlineEmpty && (groupsEmpty || groupsOnTop) ||
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~
src/widget/contentdialog.cpp:355:56: note: place parentheses around the '&&' expression to silence this warning
        bool nextIsEmpty = isCurOnline && offlineEmpty && (groupsEmpty || groupsOnTop) ||
                                                       ^
                           (                                                          )
src/widget/contentdialog.cpp:356:56: warning: '&&' within '||' [-Wlogical-op-parentheses]
                           isCurGroup  && offlineEmpty && (onlineEmpty || !groupsOnTop) ||
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/widget/contentdialog.cpp:356:56: note: place parentheses around the '&&' expression to silence this warning
                           isCurGroup  && offlineEmpty && (onlineEmpty || !groupsOnTop) ||
                                                       ^
                           (                                                           )
```

**Comment by Diadlo** [comment] 2017-05-12 05:32
Moved to #4393

**Closed as completed by Diadlo** 2017-05-12 05:32 UTC
Labels: C-bug
