### ISSUE TITLE
Improved update UI

### ISSUE THREAD

**Issue by borrougagnou** [qTox/qTox#1080] opened 2015-02-01 12:43 UTC
Bonjour,
j'ai une idée d'amélioration pour qTox,
au lieu de mettre "Une mise à jour est disponible, [...] elle sera installée au prochain démarrage de qTox"
pourquoi ne pas mettre:

"Une mise à jour est disponible, Voulez-vous la télécharger maintenant? (Oui) (Non)"
ou bien:
"La version xxx est disponible, Voulez-vous la télécharger maintenant? (Oui) (Non)"

Si l'utilisateur fait Oui:
Affiche une fenêtre de progression et une fois fini, un bouton (Redémarrer qTox)

Si l'utilisateur fait Non:
Aucune fenêtre, lance le logiciel comme si de rien étais.

Je pense que ça sera plus pratique parce que là, on ne voit aucun avancement rien :/ on se demande s'il s'est mis à jour ou autre :/ et ce qui est dommage, la version se trouve uniquement dans le log et pas ailleur :/

Voilà :)

**Comment by zetok** [comment] 2015-02-01 14:32
@borrougagnou Could you please write in English, so that everyone interested in evaluating what you wrote could do so?

**Comment by borrougagnou** [comment] 2015-02-01 16:20
@zetok>
Okay,
Hello,
I have an idea for improvement qTox,
instead of putting "An update is available [...] it will be installed when qTox restarts"
why not add:

"An update is available, Want to download now (Yes) (No)"
or:
"The xxx version is available, Want to download now (Yes) (No)"

If user click Yes:
Displays a progress window and once finished: a button (Restart qTox)

If user click No:
No window, launch the software not update.

I think it will be more convenient, because here we see no progression, :/  we do not know if software is updated or not. the version is only found in the log :/ it is not simple :/

**Comment by zetok** [comment] 2015-08-23 06:43
Rather, qTox should download updates in the background, and then ask user whether update should be applied now - just like Firefox does it.

**Comment by zetok** [comment] 2016-03-21 22:48
Hmm, how does current update mechanism work?

I.e. are changes proposed here still applicable?

**Comment by SkyzohKey** [comment] 2016-03-22 00:05
Would be a nice idea. ;)
@borrougagnou Cool, un français dans le monde de Tox :)

**Comment by borrougagnou** [comment] 2016-03-29 01:12
Sorry for long time I have work my project.
@zetok > Yes but, Firefox Update is not cool, If I check "Check for Update, but let me choose whether to install them" or check Automatically Update, Firefox Download okay but
each launch Firefox, I have a Message for Install a new Firefox version, Is not cool, I don't have a Buttons for skip version... ><""
and refuse install each firefox launch...
we must let the user choose whether he wants to install the latest version or not.
example a changelog:
![qtox_update](https://cloud.githubusercontent.com/assets/10796546/14094996/c3e226f0-f55b-11e5-8a1d-46df6122cfd1.png)

and the update is simple:
![wget](https://cloud.githubusercontent.com/assets/10796546/14094909/ea12fb16-f55a-11e5-93dd-79a64f5a7a72.png)
or
![capture d ecran 2016-03-29 a 03 06 18](https://cloud.githubusercontent.com/assets/10796546/14094984/99545e58-f55b-11e5-99df-883eaa07f8c0.png)

@SkyzohKey > Yeah :D

**Comment by borrougagnou** [comment] 2016-04-04 12:55
this is an example.

**Comment by zetok** [comment] 2016-04-04 20:29
I guess that proposed changes are still applicable.

**Comment by borrougagnou** [comment] 2016-04-11 20:33
thanks for add "You are using qTox version v1.3.0-38-ga48c422"
I wait the next updates to see if there has been change on "update"

**Comment by jessica181920** [comment] 2019-03-14 18:27
I wouldn't say this is applicable anymore because it would appear automatic updating is gone. If it's not gone I think it's seriously broken.

**Comment by anthonybilinski** [comment] 2019-03-16 06:20
Confirmed. Auto-update has been broken for a while and was removed. A new update check pointing to a download link on github was added in its place, with new UI, as part of https://github.com/qTox/qTox/pull/5346.

Proposed improvements are not applicable to the update check, closing.

**Closed as completed by anthonybilinski** 2019-03-16 06:20 UTC
Labels: proposal, P-low, M-ui
