### ISSUE TITLE
Can't invite contact in group

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2520] opened 2015-11-07 15:08 UTC
Hello,

at the moment, I can't invite my contact into my created group.
The contact doesn't get an invitation.

Can you reproduce?

**Comment by tux3** [comment] 2015-11-07 17:55
I can't repro here.

**Comment by ovalseven8** [comment] 2015-11-07 18:47
Well, I think I've got it now.

@tux3:
Invite an offline contact to a group.
So, when the contact is coming online:
- He don't get an invitation
- => You're not able to invite the contact anymore

Can you reproduce?

**Comment by agilob** [comment] 2015-11-07 19:21
> Invite an offline contact to a group.
1. You can't call offline contact.
2. You can't invite offline contact to a group.

seems pretty obvious

**Comment by tux3** [comment] 2015-11-07 19:23
That's "not a bug", but maybe we should gray out the invite option for offline people.

**Comment by agilob** [comment] 2015-11-07 19:24
Or just show popup, but popups are so '90s

**Comment by ovalseven8** [comment] 2015-11-07 19:24
Why isn't that a bug?

I cannot invite a contact when the contact is ONLINE! Only because I tried to invite the contact when he was offline.

**Comment by tux3** [comment] 2015-11-07 19:25
Let's turn this into a "make the UI not completely stupid" bug then.

**Comment by ovalseven8** [comment] 2015-11-07 19:27
Yeah, that the invite option isn't grayed out when the contact is offline, is bad UI.
But that I am not able to invite the contact anymore when he comes online is simply a bug.

**Comment by tux3** [comment] 2015-11-07 19:28
Toxcore doesn't let us send the same invite to the same group twice, if you invite someone offline to a group, the invite is lost because your friend is offline, and you can't send the invite again later because you already failed to send it (you could say that's a toxcore bug, but we can fix that in the UI).

You can always invite your friend to another group thought. It's a different bug because we shouldn't let you send invites to offline friends in the first place.

**Comment by ProMcTagonist** [comment] 2015-11-07 19:29
If group invitations showed in the chatform, and queued like messages if users were offline, it would help.

**Comment by tux3** [comment] 2015-11-07 19:30
The problem is we can't resend group invites when the friend comes back online, toxcore won't let us. You could call that a toxcore bug, but it's a non issue if we just don't send invites to offline friends in the first place.

**Comment by ProMcTagonist** [comment] 2015-11-07 19:33
qTox would ideally not send the invite until the friend comes back online, as with normal queued messages.

**Comment by tux3** [comment] 2015-11-07 19:34
You're right, didn't think of that somehow :)

**Comment by agilob** [comment] 2015-11-07 19:46
> qTox would ideally not send the invite until the friend comes back online, as with normal queued messages.

I don't agree. qTox should not queue invitation for offline contacts. I can invite you to a group when you're offline, which doesn't exist when you come online.

**Comment by TheNain38** [comment] 2015-11-07 21:26
I'm with @agilob's opinion, I think it should just not let the user be able to send an invite to an offline friend. For example, if you invite an offline contact, then this contact comes online 8 hours later, he would join the group, and you at that moment you will not want him to join the group anymore

**Comment by tux3** [comment] 2015-11-07 22:53
@TheNain38 Let's just change the UI and grey out the invite button for offline friends then

**Comment by ovalseven8** [comment] 2015-11-09 18:08
@tux3: Or perhaps a even better solution would be just not to display the invite button when the contact is offline.

**Comment by TheNain38** [comment] 2015-11-09 18:43
@ovalseven8 I don't know if this is really a better solution because the user could then think qTox can't invite people to a group chat

**Comment by Diadlo** [comment] 2017-02-25 23:00
Seems, duplicate of #4018, so it will be closed. Please comment if it isn't
Also, fixed

**Closed as completed by Diadlo** 2017-02-25 23:00 UTC
Labels: C-bug, proposal, upstream, M-ui
