### ISSUE TITLE
P2P offline messaging feature?

### ISSUE THREAD

**Issue by icmtfk** [qTox/qTox#4157] opened 2017-02-08 05:07 UTC
Let's say Alice(online) sent a message to Bob(offline), but Alice has to stay online in order to deliver that message until they are both online, which is the Pseudo-Offline messaging method. And that is very inconvenient. But what if the message Alice(online) sent to Bob(offline) was forwarded to Carl(online), and when Bob was online again, Carl will send the message to Bob, as a relay. Therefore the sender don't have to stay online to deliver the offline message if there are online friends.
It would be really great if you can add this feature.

**Comment by sudden6** [comment] 2017-02-08 10:39
duplicate of  #3361 closing

**Closed as completed by sudden6** 2017-02-08 10:39 UTC
Labels: U-low

**Comment by icmtfk** [comment] 2017-02-09 01:32
Forgive my ignorance, but what does "upstream issue" mean? I'm new to git.

**Comment by Diadlo** [comment] 2017-02-09 05:41
@icmtfk qTox use [c-toxcore](https://github.com/TokTok/c-toxcore) to work with Tox network. And we don't implement protocol stuff directly. We just use API of toxcore library. Upstream means, that offline messaging should be added to the protocol and then to the clients
