### ISSUE TITLE
Crash on setting profile password

### ISSUE THREAD

**Issue by martin21** [qTox/qTox#4056] opened 2017-01-05 22:25 UTC
Possible duplicate:

segmentation fault on startup #4054

##### Brief Description
toxcore + qTox compiled from git, toxcore from tag v0.1.2

OS: Debian GNU/Linux Sid
qTox version: v1.7.0-43-g6b513819.
Commit-Hash: 6b51381980e4d742efff0905a697040efbcce049
Toxcore-Version: 0.1.2
Qt:  5.7.1-1

Plasma 5.8.4 LTS + KF 5.29

Hardware:  ThinkPad T520

```
~> phoronix-test-suite system-info
Phoronix Test Suite v5.2.1
System Information

Hardware:
Processor: Intel Core i5-2520M @ 3.20GHz (4 Cores), Motherboard: LENOVO 42433WG, Chipset: Intel 2nd Generation Core Family DRAM, Memory: 16384MB, Disk: 300GB INTEL SSDSA2CW30 + 480GB Crucial_CT480M50, Graphics: Intel 2nd Generation Core Family IGP, Audio: Conexant CX20590, Network: Intel 82579LM Gigabit Connection + Intel Centrino Advanced-N 6205

Software:
OS: Debian unstable, Kernel: 4.8.15-tp520-btrfstrim+ (x86_64), Desktop: KDE Frameworks 5, Display Server: X Server 1.19.0, Display Driver: modesetting 1.19.0, OpenGL: 3.3 Mesa 13.0.2, Compiler: GCC 6.3.0 20161229, File-System: btrfs, Screen Resolution: 3840x1080
```

Reproducible: Always

OS: Windows / OS X / Linux (include version and/or distro)  

##### Steps to reproduce

1. Start qTox with a profile without password (for example one created with uTox)
2. Set profile password

##### Observed Behavior
qTox crashes on setting profile password:

```
~#130> gdb qtox
[…]
(gdb) run
Starting program: /usr/bin/qtox 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd321c700 (LWP 15284)]
[New Thread 0x7fffc8b4c700 (LWP 15285)]
[New Thread 0x7fffc3fff700 (LWP 15286)]
[22:14:32.690 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from /home/martin/.config/tox/qtox.ini"
[22:14:32.718 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:14:32.718 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[22:14:32.718 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  14448200687225519303
[22:14:32.719 UTC] ipc.cpp:77 : Debug: Attaching to the global shared memory
[22:14:32.719 UTC] ipc.cpp:279 : Debug: Previous owner timed out, taking ownership 16877725455620350061 -> 14448200687225519303
[22:14:32.719 UTC] main.cpp:210 : Debug: built on:  22:47:41 Jan  5 2017 ( 1483652845 )
[22:14:32.719 UTC] main.cpp:211 : Debug: commit:  6b51381980e4d742efff0905a697040efbcce049 

[22:14:32.739 UTC] persistence/profile.cpp:100 : Debug: Loading tox save  "/home/martin/.config/tox/tox_save.tox"
[22:14:32.740 UTC] persistence/settings.cpp:493 : Debug: "Saving global settings at /home/martin/.config/tox/qtox.ini"
[22:14:32.762 UTC] persistence/settings.cpp:358 : Debug: Loading personal settings from "/home/martin/.config/tox/tox_save.ini"
[22:14:32.762 UTC] nexus.cpp:85 : Debug: Starting up
[22:14:32.834 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:14:32.835 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[New Thread 0x7fffbbbeb700 (LWP 15287)]
[22:14:33.897 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:14:33.897 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[22:14:33.900 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:14:33.900 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[New Thread 0x7fffbb3ea700 (LWP 15288)]
[22:14:33.909 UTC] :0 : Warning: QString::arg: Argument missing: Wenn du <b>wirklich</b> nicht weißt, was du tust, solltest du hier nichts ändern. Änderungen, die du hier machst, könnten zu Problemen mit qTox und sogar dem Verlust deiner Daten, z.B. dem Verlauf, führen., <b>nicht</b>
[22:14:33.928 UTC] :0 : Warning: QString::arg: Argument missing: Originalauthor, <a href="https://github.com/tux3" style="text-decoration: underline; color:#0000ff;">tux3</a>
[New Thread 0x7fffbab30700 (LWP 15289)]
[22:14:34.104 UTC] core/core.cpp:251 : Debug: Loading user profile
[22:14:34.104 UTC] persistence/profile.cpp:295 : Debug: Loading tox save  "/home/martin/.config/tox/tox_save.tox"
[22:14:34.104 UTC] core/core.cpp:135 : Debug: Core starting with IPv6 enabled
[New Thread 0x7fffba22b700 (LWP 15292)]
[22:14:34.106 UTC] core/core.cpp:319 : Debug: Self avatar not found, will broadcast empty avatar to friends
[New Thread 0x7fffabfff700 (LWP 15293)]
[22:14:34.239 UTC] widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
[22:14:34.241 UTC] widget/widget.cpp:481 : Debug: Detected buggy QIcon::hasThemeIcon. Icon overrides from theme will be ignored.
[22:14:35.677 UTC] core/core.cpp:423 : Debug: "Connecting to 148.251.23.146:2306 (pucetox)"
[22:14:35.678 UTC] core/core.cpp:423 : Debug: "Connecting to 108.61.165.198:33445 (ray65536)"
[22:14:40.178 UTC] core/core.cpp:423 : Debug: "Connecting to 2001:19f0:5000:8121:5054:ff:fe1c:9ded:33445 (ray65536)"
[22:14:40.178 UTC] core/core.cpp:423 : Debug: "Connecting to srv1.ricin.im:1337 (Ricin.im)"
[22:14:44.877 UTC] core/core.cpp:423 : Debug: "Connecting to 2a02:7aa0:1619::bdbd:17b8:33445 (Rotkaermota)"
[22:14:44.878 UTC] core/core.cpp:423 : Debug: "Connecting to 95.215.46.114:33445 (Rotkaermota)"
[22:14:45.827 UTC] core/core.cpp:387 : Debug: Connected to the DHT
[22:14:45.828 UTC] persistence/profile.cpp:373 : Debug: Saving tox save to  "/home/martin/.config/tox/tox_save.tox"
[22:15:01.652 UTC] persistence/profile.cpp:373 : Debug: Saving tox save to  "/home/martin/.config/tox/tox_save.tox"
[22:15:01.742 UTC] persistence/db/rawdatabase.cpp:350 : Warning: Found old temporary export file while rekeying, deleting it

Thread 9 "qTox Database" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffabfff700 (LWP 15293)]
0x00007fffeeff675d in EVP_EncryptUpdate () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) bt full
#0  0x00007fffeeff675d in EVP_EncryptUpdate () at /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007ffff6992e3b in sqlcipher_openssl_cipher (ctx=0x7fffa001e098, mode=<optimized out>, key=0x7fffa001e0b8 "h\f\352\016z\362\211\353\022E\203\005\330\034\270\236h}\265\221gϖ\220~o\354\367\251\226J\033", key_sz=<optimized out>, iv=0x7fffa0019128 "\232\247\027\355\304:k M@v9h\036;\231\372\071", in=0x7fffa001eaa8 "\004", in_sz=960, out=0x7fffa0018d68 "") at sqlite3.c:16517
        tmp_csz = 0
        csz = <optimized out>
        ectx = 0x7fffa001fa20
#2  0x00007ffff69a347e in sqlcipher_page_cipher (ctx=ctx@entry=0x7fffa0014f78, for_ctx=<optimized out>, pgno=1, mode=1, page_sz=<optimized out>, in=0x7fffa001eaa8 "\004", out=0x7fffa0018d68 "") at sqlite3.c:15696
        c_ctx = 0x7fffa001df88
        iv_in = 0x7fffa001ee68 ""
        iv_out = 0x7fffa0019128 "\232\247\027\355\304:k M@v9h\036;\231\372\071"
        hmac_in = <optimized out>
        hmac_out = 0x7fffa0019138 "\372\071"
        out_start = 0x7fffa0018d68 ""
        size = 960
#3  0x00007ffff69b5104 in sqlite3Codec (iCtx=0x7fffa0014f78, data=0x7fffa001ea98, pgno=1, mode=6) at sqlite3.c:14389
        ctx = 0x7fffa0014f78
        offset = <optimized out>
        rc = <optimized out>
        page_sz = 1024
        pData = 0x7fffa001ea98 "SQLite format 3"
        buffer = 0x7fffa0018d58
        kdf_salt = 0x7fffa0014fc8
#4  0x00007ffff69c3799 in pager_write_pagelist (pPager=pPager@entry=0x7fffa00189c8, pList=0x7fffa001eed0) at sqlite3.c:48086
        offset = 0
        pData = <optimized out>
        pgno = 1
        rc = 0
#5  0x00007ffff69cb5fa in sqlite3PagerCommitPhaseOne (pPager=0x7fffa00189c8, zMaster=zMaster@entry=0x0, noSync=noSync@entry=0) at sqlite3.c:50033
        rc = <optimized out>
#6  0x00007ffff69cb7cf in sqlite3PagerCommitPhaseOne (noSync=0, zMaster=0x0, pPager=<optimized out>) at sqlite3.c:49932
        rc = 0
        pBt = 0x7fffa0015578
#7  0x00007ffff69cb7cf in sqlite3BtreeCommitPhaseOne (p=0x7fffa0017f48, zMaster=zMaster@entry=0x0) at sqlite3.c:57764
        pBt = 0x7fffa0015578
#8  0x00007ffff69cf421 in sqlite3BtreeCommitPhaseOne (zMaster=0x0, p=<optimized out>) at sqlite3.c:89551
        rc = 0
        pBt = <optimized out>
        i = 2
        nTrans = <optimized out>
---Type <return> to continue, or q <return> to quit---
        rc = 0
        needXcommit = <optimized out>
        mrc = <optimized out>
        eStatementOp = <optimized out>
        isSpecialError = <optimized out>
        rc = <optimized out>
        db = 0x7fffa0002fb8
#9  0x00007ffff69cf421 in vdbeCommit (p=0x7fffa0020b88, db=0x7fffa0002fb8) at sqlite3.c:1586
        pBt = <optimized out>
        i = 2
        nTrans = <optimized out>
        rc = 0
        needXcommit = <optimized out>
        mrc = <optimized out>
        eStatementOp = <optimized out>
        isSpecialError = <optimized out>
        rc = <optimized out>
        db = 0x7fffa0002fb8
#10 0x00007ffff69cf421 in sqlite3VdbeHalt (p=p@entry=0x7fffa0020b88) at sqlite3.c:1993
        mrc = <optimized out>
        eStatementOp = <optimized out>
        isSpecialError = <optimized out>
        rc = <optimized out>
        db = 0x7fffa0002fb8
#11 0x00007ffff69fe926 in sqlite3VdbeExec (p=p@entry=0x7fffa0020b88) at sqlite3.c:71867
        zType = <optimized out>
        zLogFmt = <optimized out>
        pc = 42
        aOp = <optimized out>
        pOp = 0x7fffa0022a48
        rc = 0
        db = <optimized out>
        resetSchemaOnFault = 0 '\000'
        encoding = <optimized out>
        iCompare = <optimized out>
        nVmStep = <optimized out>
        nProgressLimit = <optimized out>
        aMem = <optimized out>
        pIn1 = <optimized out>
        pIn2 = <optimized out>
        pIn3 = <optimized out>
---Type <return> to continue, or q <return> to quit---
        pOut = <optimized out>
        aPermute = <optimized out>
        lastRowid = 0
#12 0x00007ffff69ff8cf in sqlite3Step (p=0x7fffa0020b88) at sqlite3.c:69631
        db = 0x7fffa0002fb8
        rc = <optimized out>
        db = <optimized out>
        v = <optimized out>
        pStmt = <optimized out>
        v = <optimized out>
#13 0x00007ffff69ff8cf in sqlite3_step (pStmt=<optimized out>) at sqlite3.c:4161
        db = <optimized out>
        v = <optimized out>
        pStmt = <optimized out>
        v = <optimized out>
#14 0x00007ffff6a00459 in sqlcipher_execSql (db=0x7fffa0002fb8, pzErrMsg=0x7fffabffd5d0, zSql=<optimized out>) at sqlite3.c:14626
        pStmt = 0x7fffa0020b88
#15 0x00007ffff6a00539 in sqlcipher_execExecSql (db=db@entry=0x7fffa0002fb8, pzErrMsg=pzErrMsg@entry=0x7fffabffd5d0, zSql=zSql@entry=0x7fffa0020d18 "SELECT 'CREATE TABLE encrypted.' || substr(sql,14)   FROM sqlite_master WHERE type='table' AND name!='sqlite_sequence'   AND rootpage>0") at sqlite3.c:14645
        pStmt = 0x7fffa0020888
        rc = <optimized out>
#16 0x00007ffff6a0064a in sqlcipher_exportFunc (context=0x7fffabffd750, argc=<optimized out>, argv=<optimized out>) at sqlite3.c:14687
        db = 0x7fffa0002fb8
        attachedDb = 0x7fffa0017e88 "encrypted"
        saved_flags = 9437264
        saved_nChange = 0
        saved_nTotalChange = 0
        saved_xTrace = 0x0
        rc = 0
        zSql = 0x7fffa0020d18 "SELECT 'CREATE TABLE encrypted.' || substr(sql,14)   FROM sqlite_master WHERE type='table' AND name!='sqlite_sequence'   AND rootpage>0"
        pzErrMsg = 0x0
#17 0x00007ffff69fb00a in sqlite3VdbeExec (p=p@entry=0x7fffa00192d8) at sqlite3.c:72490
        i = <optimized out>
        pArg = <optimized out>
        ctx = 
          {pFunc = 0x7fffa0003868, s = {db = 0x7fffa0002fb8, z = 0x0, r = 0, u = {i = 0, nZero = 0, pDef = 0x0, pRowSet = 0x0, pFrame = 0x0}, n = 0, flags = 1, enc = 0 '\000', xDel = 0x0, zMalloc = 0x0}, pMem = 0x7fffa0016cb1, pColl = 0x1, pVdbe = 0x7fffa00192d8, iOp = 1, isError = 32767, skipFlag = 0 '\000', fErrorOrAux = 0 '\000'}
        apVal = 0x7fffa0019518
        n = 1
        pc = 1
        aOp = <optimized out>
---Type <return> to continue, or q <return> to quit---
        pOp = 0x7fffa0019430
        rc = 0
        db = <optimized out>
        resetSchemaOnFault = 0 '\000'
        encoding = <optimized out>
        iCompare = <optimized out>
        nVmStep = <optimized out>
        nProgressLimit = <optimized out>
        aMem = <optimized out>
        pIn1 = <optimized out>
        pIn2 = <optimized out>
        pIn3 = <optimized out>
        pOut = 0x7fffa00194a8
        aPermute = <optimized out>
        lastRowid = 0
#18 0x00007ffff69ff8cf in sqlite3Step (p=0x7fffa00192d8) at sqlite3.c:69631
        db = 0x7fffa0002fb8
        rc = <optimized out>
        db = <optimized out>
        v = <optimized out>
        pStmt = <optimized out>
        v = <optimized out>
#19 0x00007ffff69ff8cf in sqlite3_step (pStmt=<optimized out>) at sqlite3.c:4161
        db = <optimized out>
        v = <optimized out>
        pStmt = <optimized out>
        v = <optimized out>
#20 0x0000555555609b10 in  ()
#21 0x00005555556de035 in  ()
#22 0x00007ffff0ee6ade in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff0eec53a in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x0000555555606d41 in  ()
#25 0x0000555555607058 in  ()
#26 0x0000555555607531 in  ()
#27 0x000055555560b168 in  ()
#28 0x00005555556de049 in  ()
#29 0x00007ffff0f08449 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff192eb2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#31 0x00007ffff19362e1 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff0edb990 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff0ede11d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff0f2fbf3 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff3fd07f7 in g_main_dispatch (context=0x7fffa0000990) at ././glib/gmain.c:3203
        dispatch = 0x7ffff0f2fbe0
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0x7fffa00012d0
        current = 0x7fffa4002770
        i = 0
#36 0x00007ffff3fd07f7 in g_main_context_dispatch (context=context@entry=0x7fffa0000990) at ././glib/gmain.c:3856
#37 0x00007ffff3fd0a60 in g_main_context_iterate (context=context@entry=0x7fffa0000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ././glib/gmain.c:3929
        max_priority = 2147483647
        timeout = -1
        some_ready = 1
        nfds = 1
        allocated_nfds = 1
        fds = <optimized out>
#38 0x00007ffff3fd0b0c in g_main_context_iteration (context=0x7fffa0000990, may_block=1) at ././glib/gmain.c:3990
        retval = <optimized out>
#39 0x00007ffff0f2ffff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007ffff0ed997a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff0d070f3 in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ffff0d0bda8 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007ffff07d5464 in start_thread (arg=0x7fffabfff700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffabfff700
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140736079066880, -5894639534786212144, 0, 140737488345423, 0, 140737354125376, 5894472408380214992, 5894623027823513296}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
---Type <return> to continue, or q <return> to quit---
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#44 0x00007fffefc7b9df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb) quit
A debugging session is active.

        Inferior 1 [process 15272] will be killed.

Quit anyway? (y or n) y
```

##### Expected Behavior
qTox just sets profile password

##### Additional Info

On subsequent start qTox demands password, but on entering right password I still get an error that it cannot load chat history.

```
~> LANG=C qtox
[22:18:13.979 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from /home/martin/.config/tox/qtox.ini"
[22:18:14.008 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:18:14.009 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[22:18:14.009 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  8519042380258420189
[22:18:14.009 UTC] ipc.cpp:77 : Debug: Attaching to the global shared memory
[22:18:14.009 UTC] ipc.cpp:279 : Debug: Previous owner timed out, taking ownership 8102220773674828224 -> 8519042380258420189
[22:18:14.009 UTC] main.cpp:210 : Debug: built on:  22:47:41 Jan  5 2017 ( 1483652845 )
[22:18:14.009 UTC] main.cpp:211 : Debug: commit:  6b51381980e4d742efff0905a697040efbcce049 

[22:18:14.009 UTC] nexus.cpp:85 : Debug: Starting up
[22:18:19.329 UTC] persistence/profile.cpp:100 : Debug: Loading tox save  "/home/martin/.config/tox/tox_save.tox"
[22:18:19.535 UTC] persistence/settings.cpp:358 : Debug: Loading personal settings from "/home/martin/.config/tox/tox_save.ini"
[22:18:19.535 UTC] persistence/settingsserializer.cpp:386 : Warning: We have a password, but the settings file is not encrypted
[22:18:19.535 UTC] persistence/settings.cpp:493 : Debug: "Saving global settings at /home/martin/.config/tox/qtox.ini"
[22:18:19.560 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:18:19.560 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[22:18:20.349 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:18:20.349 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[22:18:20.351 UTC] widget/translator.cpp:56 : Debug: Loaded translation "de"
[22:18:20.352 UTC] widget/translator.cpp:65 : Debug: System translation loaded "de"
[22:18:20.368 UTC] :0 : Warning: QString::arg: Argument missing: Wenn du <b>wirklich</b> nicht wei?t, was du tust, solltest du hier nichts ?ndern. ?nderungen, die du hier machst, k?nnten zu Problemen mit qTox und sogar dem Verlust deiner Daten, z.B. dem Verlauf, f?hren., <b>nicht</b>
[22:18:20.394 UTC] :0 : Warning: QString::arg: Argument missing: Originalauthor, <a href="https://github.com/tux3" style="text-decoration: underline; color:#0000ff;">tux3</a>
[22:18:20.584 UTC] core/core.cpp:251 : Debug: Loading user profile
[22:18:20.584 UTC] persistence/profile.cpp:295 : Debug: Loading tox save  "/home/martin/.config/tox/tox_save.tox"
[22:18:20.601 UTC] widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
[22:18:20.605 UTC] widget/widget.cpp:481 : Debug: Detected buggy QIcon::hasThemeIcon. Icon overrides from theme will be ignored.
[22:18:20.721 UTC] core/core.cpp:135 : Debug: Core starting with IPv6 enabled
[22:18:20.722 UTC] core/core.cpp:319 : Debug: Self avatar not found, will broadcast empty avatar to friends
[22:18:20.803 UTC] persistence/db/rawdatabase.cpp:600 : Warning: Failed to prepare statement "SELECT count(*) FROM sqlite_master" with error 26
[22:18:20.803 UTC] persistence/db/rawdatabase.cpp:193 : Warning: Database is unusable, check that the password is correct
[22:18:20.803 UTC] persistence/db/rawdatabase.cpp:117 : Debug: Couldn't create the backup of the database, won't upgrade
[22:18:20.879 UTC] persistence/db/rawdatabase.cpp:600 : Warning: Failed to prepare statement "SELECT count(*) FROM sqlite_master" with error 26
[22:18:20.879 UTC] persistence/db/rawdatabase.cpp:193 : Warning: Database is unusable, check that the password is correct
[22:18:20.879 UTC] persistence/db/rawdatabase.cpp:141 : Debug: Failed to open database with old salt
[22:18:20.879 UTC] persistence/profile.cpp:521 : Warning: Failed to open database for profile "tox_save"
[22:18:22.326 UTC] core/core.cpp:423 : Debug: "Connecting to 146.185.136.123:33445 (LittleVulpix)"
[22:18:22.327 UTC] core/core.cpp:423 : Debug: "Connecting to 163.172.136.118:33445 (LittleVulpix)"
[22:18:26.829 UTC] core/core.cpp:423 : Debug: "Connecting to 2001:bc8:4400:2100::1c:50f:33445 (LittleVulpix)"
[22:18:26.830 UTC] core/core.cpp:423 : Debug: "Connecting to 2a03:b0c0:0:1010::389:1:33445 (LittleVulpix)"
[22:18:29.827 UTC] core/core.cpp:387 : Debug: Connected to the DHT
[22:18:29.828 UTC] persistence/profile.cpp:373 : Debug: Saving tox save to  "/home/martin/.config/tox/tox_save.tox"
```

**Comment by zetok** [comment] 2017-01-05 23:01
Duplicate of #4054, thus closing.

**Closed as completed by zetok** 2017-01-05 23:01 UTC
Labels: U-low
