### ISSUE TITLE
drop when importing the contact list 

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#5061] opened 2018-04-06 12:56 UTC
Brief Description
OS: Windows 64x
qTox version: 1.14.1
Commit hash: fe552f28b63c7e7ae8159d2b55cb921dd45d9c1d
toxcore: 0.2.1
Qt: 5.9.3

Reproducible: Always

Steps to reproduce
try import contact list like this:
25925602206E214F7282647233DD2530....
F5FB05866A60C47CF29A6D7F521C5E88..
B931AED50AAE998BA7BED57A352CA56.
2AA55A6C53EBE57925603B4FD2BFF889....
BF4078493B03B4109181ED61820E442.
A7C55BA3A4FD8599FB0B118E270486....
C228A51AC7632C2DBA1F5F12C052....
D63BB66EE6D83D0476C22415D20....
5BEE775A33A80F97CC9E45BF789...
4260D93239E54233FA48EECF888B.....
Observed Behavior
crash

Expected Behavior
must send to all contacts request

If send by one that works
importing by list does not work at all, the program is crash when you select file

repeat #4962 , #5026 don't help

**Comment by HoraceBianchon** [comment] 2018-04-06 13:47
Can't reproduce on 
OS: Windows x64 
qTox version: 1.14.1
Qt: 5.9.3,
toxcore version: 0.1.11
Commit hash [ff57841](https://github.com/qTox/qTox/commit/ff578413c1bfba50db950f60924f595f435889d0)

**Comment by PKEv** [comment] 2018-04-06 13:55
@HoraceBianchon  Why do you have a different version toxcore  ?

**Comment by HoraceBianchon** [comment] 2018-04-06 13:58
Because I don't updated it. 😈 
I will try update tox core version and try reproduce.

**Comment by Diadlo** [comment] 2018-04-06 14:08
I'm sure, but seems #5026 was merged after 1.14.1 release, isn't it?

**Comment by anthonybilinski** [comment] 2018-04-06 17:31
Yes, the reason you're still seeing issue is that the latest release doesn't have the fix yet, but #4962 is fixed on master. It's not related to toxcore.

@PKEv Can you try a nightly build to verify it now works?

**Comment by zetok** [comment] 2018-09-29 19:09
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.

**Closed as completed by zetok** 2018-09-29 19:09 UTC
Labels: U-low, O-need-info
