### ISSUE TITLE
Notification sound is to low

### ISSUE THREAD

**Issue by hchr** [qTox/qTox#5076] opened 2018-04-12 09:34 UTC
##### Brief Description
I think the notification sound is to low. On this laptop I have to turn up the sound volume to hear the notifications. This however make all other sounds annoying loud.
Please make the build in sound louder.

OS: Linux Manjaro 
qTox version: untagged-c311d4df4007cd97cd2a
toxcore: 0.2.1 
Qt:  5.10.1
Hardware:  Laptop
…

Reproducible: Always

##### Additional Info
Buildin sound level:
![Soundlevel](https://user-images.githubusercontent.com/6417330/38668101-a29430e6-3e43-11e8-8c1d-45d9c7a02418.png)
If I increase the level to:
![New level](https://user-images.githubusercontent.com/6417330/38668181-d5ab2ab6-3e43-11e8-9abe-d6a6aead2eb2.png)

EDIT: This is not true, this only works in test sound with my notification.pcm. With it there's no notification sound at all:
And use that as
notification.pcm
and compile it's much better.

This is the notification.pcm I made:
[notification.pcm.zip](https://github.com/qTox/qTox/files/1902361/notification.pcm.zip)

**Comment by zetok** [comment] 2018-09-28 19:55
Duplicate of #2216, thus closing.

**Closed as completed by zetok** 2018-09-28 19:55 UTC
Labels: U-low, M-audio
