### ISSUE TITLE
qTox prevents kde plasma from logging out from session

### ISSUE THREAD

**Issue by dolohow** [qTox/qTox#3126] opened 2016-04-11 21:13 UTC
##### Brief Description

qTox prevents kde (plasma 5) from logging out.

OS: Arch Linux
qTox version: Nightly
Commit hash: built without git
toxcore: 0.0.0
Qt: 5.5.1
Hardware:  Not relevant
...

Reproducible: Always
##### Steps to reproduce
1. Log in to Plasma
2. Start qTox
3. Perform logout
##### Observed Behavior

qTox prevented plasma from logging out.
##### Expected Behavior

qTox does not interfere into logging out process.
##### Additional Info

Logs:

```
kwi 11 22:59:25 [HOSTNAME] ksmserver[1226]: ksmserver: Client  "/usr/bin/qtox"  ( 10c4c79895000146036067500000007290009 ) canceled shutdown.
```

**Comment by zetok** [comment] 2016-04-11 21:41
Looks like a duplicate of #3120, thus closing.

**Closed as completed by zetok** 2016-04-11 21:41 UTC
Labels: U-low
