### ISSUE TITLE
Full Screen Screen Share?

### ISSUE THREAD

**Issue by templa876** [qTox/qTox#5820] opened 2019-09-08 03:22 UTC
Is there any way to display a fullscreen in screen share like Skype, i was trying to figure it out. I am running the nightly version as the stable one was causing issues in screen share as seen here https://github.com/qTox/qTox/issues/5817. Any help would be appreciated thanks. It states that the option has already been created for full screen here https://qtox.github.io/blog/2018/06/28/qTox-1.16-features.html
OS: Windows 
qTox version: Nightly
Commit hash:  8a210d524bb14df4e59f7df543e1f8e8f6594ffa
toxcore:  0.2.10
Qt:  5.9.8
Hardware:  Windows 10;
Processor: i3-5010u 2.10GHZ 2100MHZ 2 cores
…

Reproducible: Always

**Comment by sudden6** [comment] 2019-09-08 10:47
Could it be that you're affected by this bug: https://github.com/qTox/qTox/issues/5782?

**Comment by anthonybilinski** [comment] 2022-02-19 12:59
Either issue is unclear or is a duplicate of https://github.com/qTox/qTox/issues/5782. Closing.

**Closed as completed by anthonybilinski** 2022-02-19 12:59 UTC
Labels: C-question, O-need-info, M-video
