### ISSUE TITLE
log od sended files not saved

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3828] opened 2016-10-24 20:00 UTC
##### Brief Description

qTox version: 1.4.0
…

Reproducible: Always
##### Steps to reproduce
1. send file
2. close qtox
3. open "sended files"
##### Observed Behavior

list of "sended files" are clean
##### Expected Behavior

log of sended files like history in chat, and is cleared by user request

**Comment by zetok** [comment] 2016-10-24 20:07
Duplicate of #1300, thus closing.

**Closed as completed by zetok** 2016-10-24 20:07 UTC
Labels: U-low
