### ISSUE TITLE
Group chat doesn't see remote users after the local connection disruption

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4224] opened 2017-03-01 21:34 UTC
1. I join the group chat and see its users.
2. Internet connection goes down, all chat users but me disappear.
3. Internet connection comes back up. Chat users are never shown again. I remain the only user in chat.

Once I have been invited, disruption of my local connection shouldn't modify the chat state.

**Comment by sudden6** [comment] 2017-03-02 09:50
duplicate of  #896

once you drop out of a groupchat you have to get invited again.

**Closed as completed by sudden6** 2017-03-02 09:50 UTC
Labels: U-low
