### ISSUE TITLE
1.16.3-850-gad042b09: Build is broken: delete called on 'IAboutFriend' that is abstract but has non-virtual destructor 

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6048] opened 2020-03-26 21:22 UTC
clang-8
FreeBSD 12
toxcore-0.2.11,1

```
[5/137] /usr/bin/c++  -DDESKTOP_NOTIFICATIONS=0 -DGIT_DESCRIBE="\"1.16.3.850 (rev.ad042b09)\"" -DGIT_VERSION="\"build without git\"" -DLOG_TO_FILE=1 -DQTOX_PLATFORM_EXT -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MESSAGELOGCONTEXT=1 -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSPELL_CHECKING -DUPDATE_CHECK_ENABLED=1 -DUSE_FILTERAUDIO=1 -Iqtox_static_autogen/include -I. -I/usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09 -I/usr/local/include/sqlcipher -I/usr/local/include/opus -I/usr/local/include/AL -isystem /usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtCore -isystem /usr/local/lib/qt5/mkspecs/freebsd-clang -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtOpenGL -isystem /usr/local/include/qt5/QtWidgets -isystem /usr/local/include/qt5/QtSvg -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/KF5/SonnetUi -isystem /usr/local/include/KF5 -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer -std=c++11 -fno-exceptions -fno-rtti -Wstrict-overflow -Wstrict-aliasing -Wold-style-cast -Wsign-compare -Wunknown-pragmas -Werror -Wdate-time -fstack-protector-all -Wstack-protector -pthread -pthread -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   -fPIC -MD -MT CMakeFiles/qtox_static.dir/src/widget/about/aboutfriendform.cpp.o -MF CMakeFiles/qtox_static.dir/src/widget/about/aboutfriendform.cpp.o.d -o CMakeFiles/qtox_static.dir/src/widget/about/aboutfriendform.cpp.o -c /usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09/src/widget/about/aboutfriendform.cpp
FAILED: CMakeFiles/qtox_static.dir/src/widget/about/aboutfriendform.cpp.o 
/usr/bin/c++  -DDESKTOP_NOTIFICATIONS=0 -DGIT_DESCRIBE="\"1.16.3.850 (rev.ad042b09)\"" -DGIT_VERSION="\"build without git\"" -DLOG_TO_FILE=1 -DQTOX_PLATFORM_EXT -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MESSAGELOGCONTEXT=1 -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSPELL_CHECKING -DUPDATE_CHECK_ENABLED=1 -DUSE_FILTERAUDIO=1 -Iqtox_static_autogen/include -I. -I/usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09 -I/usr/local/include/sqlcipher -I/usr/local/include/opus -I/usr/local/include/AL -isystem /usr/local/include -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtCore -isystem /usr/local/lib/qt5/mkspecs/freebsd-clang -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtOpenGL -isystem /usr/local/include/qt5/QtWidgets -isystem /usr/local/include/qt5/QtSvg -isystem /usr/local/include/qt5/QtXml -isystem /usr/local/include/KF5/SonnetUi -isystem /usr/local/include/KF5 -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer -std=c++11 -fno-exceptions -fno-rtti -Wstrict-overflow -Wstrict-aliasing -Wold-style-cast -Wsign-compare -Wunknown-pragmas -Werror -Wdate-time -fstack-protector-all -Wstack-protector -pthread -pthread -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   -fPIC -MD -MT CMakeFiles/qtox_static.dir/src/widget/about/aboutfriendform.cpp.o -MF CMakeFiles/qtox_static.dir/src/widget/about/aboutfriendform.cpp.o.d -o CMakeFiles/qtox_static.dir/src/widget/about/aboutfriendform.cpp.o -c /usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09/src/widget/about/aboutfriendform.cpp
In file included from /usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09/src/widget/about/aboutfriendform.cpp:20:
In file included from /usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09/src/widget/about/aboutfriendform.h:23:
In file included from /usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09/src/model/about/iaboutfriend.h:23:
In file included from /usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09/src/model/interface.h:23:
In file included from /usr/local/include/qt5/QtCore/QMetaObject:1:
In file included from /usr/local/include/qt5/QtCore/qobjectdefs.h:48:
In file included from /usr/local/include/qt5/QtCore/qnamespace.h:43:
In file included from /usr/local/include/qt5/QtCore/qglobal.h:142:
In file included from /usr/include/c++/v1/algorithm:644:
/usr/include/c++/v1/memory:2339:5: error: delete called on 'IAboutFriend' that is abstract but has non-virtual destructor [-Werror,-Wdelete-abstract-non-virtual-dtor]
    delete __ptr;
    ^
/usr/include/c++/v1/memory:2652:7: note: in instantiation of member function 'std::__1::default_delete<IAboutFriend>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/usr/include/c++/v1/memory:2606:19: note: in instantiation of member function 'std::__1::unique_ptr<IAboutFriend, std::__1::default_delete<IAboutFriend> >::reset' requested here
  ~unique_ptr() { reset(); }
                  ^
/usr/ports/net-im/qTox/work/qTox-1.16.3-850-gad042b09/src/widget/about/aboutfriendform.cpp:29:18: note: in instantiation of member function 'std::__1::unique_ptr<IAboutFriend, std::__1::default_delete<IAboutFriend> >::~unique_ptr' requested here
AboutFriendForm::AboutFriendForm(std::unique_ptr<IAboutFriend> _about, QWidget* parent)
                 ^
1 error generated.
```

**Comment by anthonybilinski** [comment] 2020-03-28 08:47
Duplicate of #6006. Fix #6029 is already merged to v1.17-dev branch, which will be merged to master in the next day or two.

**Closed as completed by anthonybilinski** 2020-03-28 08:47 UTC
