### ISSUE TITLE
update not completing at restart 

### ISSUE THREAD

**Issue by Neilglee** [qTox/qTox#4759] opened 2017-10-25 06:50 UTC
##### Brief Description

OS: Windows 7
qTox version: v1.12.1
Commit hash: d65c30b879ee2f00c16816aa332567fd627c0b2b
toxcore: 0.1.10
Qt: 5.6.3
Hardware: 

Reproducible: Always 
##### Steps to reproduce
1. It seems to me that the updater is not properly completing the update if I restart my machine:
2. qTox prompts me for an update download, I confirm
3. I restart my machine, qTox requests to install the update
4.  When the updater has finished, qTox prompts me for an update to download
    repeat
I am using Win7, 64bit
##### Observed Behavior
If i uncheck check for updates at start this does not happen

this happened on the previous version as weel so i installed the nightly and then updated and the problem was resolved

Tried this but it did not work

##### Expected Behavior
to work properly

**Comment by anthonybilinski** [comment] 2017-10-25 07:42
possibly a duplicate of https://github.com/qTox/qTox/issues/3771

**Comment by Neilglee** [comment] 2017-10-25 11:46
Yes it is but the version I am using is v1.12.1.and the previous version did the same
 

    On Wednesday, 25 October 2017, 09:42:43 GMT+2, Anthony Bilinski <notifications@github.com> wrote:  
 
 
possibly a duplicate of #3771

**Comment by sudden6** [comment] 2019-01-24 21:36
Auto update was discontinued in favor of an update notification.

**Closed as completed by sudden6** 2019-01-24 21:36 UTC
Labels: M-packaging
