### ISSUE TITLE
spellchecking for message

### ISSUE THREAD

**Issue by user67x** [qTox/qTox#4806] opened 2017-11-15 18:31 UTC
Hello,

Is it possible to have this feature : spellchecking for message entered in qTox, like in Skype or Hangout ?

This is the only restraint I have to switch totally to Qtox!

**Comment by Diadlo** [comment] 2017-11-15 18:38
Seems, duplicate of #1301, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2017-11-15 18:38 UTC
Labels: U-low
