### ISSUE TITLE
qTox uses Qt's file picker

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#3494] opened 2016-07-07 15:42 UTC
##### Brief Description

OS: Windows
qTox version: v1.4.0-252-g34fb127
Commit hash:  34fb127db122f24be4456681ee6b217742c9cb11
toxcore:  0.0.0
Qt:  5.5.1

Reproducible: Always
##### Steps to reproduce
1. Use the button to send a file to someone
2. See the file picker not being Windows' native one
##### Observed Behavior

A non pratical and weird file picker is used, and qTox is the only application to use that weird one, instead of the system one
##### Expected Behavior

qTox uses the system file picker on Windows

**Comment by antis81** [comment] 2016-07-07 16:01
Probably the only unweird file dialog on a weird system… :)

**Comment by zetok** [comment] 2016-07-07 16:05
It's a regression due to #3447

**Comment by antis81** [comment] 2016-07-07 16:38
@zetok 

``` c++
#ifdef Q_OS_WIN32
     Jada Windows bullshit blabla…
#else
    Everyone else…
#endif
```

It's not a regression, it's the way Windows likes to be "special"! :smile:

**Comment by antis81** [comment] 2016-07-07 16:40
IOW: We decided for Qt's consistent rendering, which is totally fine and not weird (whatever that means…)!

**Comment by zetok** [comment] 2016-07-07 16:42
@antis81 eh. The problem was that GTK decided to break things, and arch obviously had to use broken stuff, which resulted in qTox crashing when it tried to use (allegedly native, according to broken system info) file picker.

**Comment by zetok** [comment] 2016-07-07 16:44
As for the PR, it made experience for anyone who was able to use native file picker simply horrible. Qt has a shitty file picker – while I didn't have support for native file picker on my system, there are systems where shitty Qt file picker is replaced with a nice native one that integrates well with users' system.

**Comment by antis81** [comment] 2016-07-08 02:01
> Qt has a shitty file picker…

Does it? Interesting, to me it looks like - well, like a quite usual file-open-dialog, and a nice one as well:

![qt-file-picker](https://cloud.githubusercontent.com/assets/440517/16675218/58a42948-44bf-11e6-8379-ae6d89a68707.png)

Plus, it avoids unexpected crashes by incompatible or broken 3rd party libs. However, we can enhance that solution and introduce a settings flag, where users can chose to use a platform-independent, working solution or the system's "native" file-dialog. no problem.

Yet I'd like to know:
@TheNain38 What is weird? Is it weird, that you can chose a file? I suggest you post a screenshot of what it looks like on windows and probably someone with interest for this system will fix it for you.

**Comment by zetok** [comment] 2016-07-08 06:57
@antis81 yep, this one is crappy when compared to capabilities provided by a well-integrated, native file picker.

**Comment by antis81** [comment] 2016-07-08 08:57
@TheNain38 Pleas show your crappy explorer manager (aka screenshot), which will help greatly to get an experience about what your actual problem is. :)

I guess I'll add a settings flag and make it selectable by user.

**Comment by TheNain38** [comment] 2016-07-08 09:04
@antis81 Well, with the native file picker, you can go to the usual places, like, downloads etc... super easly, and it's much more convenient than Qt's file picker, which is pure shit, compared to what the system one can do, Qt's one work, but it's really, really... well, non convenient :)

**Comment by antis81** [comment] 2016-07-08 10:05
@TheNain38 Windows file picker is pure shit… :)

**Comment by TheNain38** [comment] 2016-07-08 10:10
@antis81 It's still muccch better than Qt's one, because it's well integrated into the system

**Comment by ElLamparto** [comment] 2016-07-08 10:22
It is very nice file picker! Most of people will drag-and-drop files without using picker at all.

**Comment by antis81** [comment] 2016-07-08 11:41
@TheNain38 Ok, it's a neat game to play and I just love bashing Windows wherever possible. Sorry, can't help… :) Yet I respect you and you for sure have good arguments why using Windows works for you… If you read my comment above, you'll find, that I tried making a "conciliable offer", which is by making it selectable by the user, if he/she likes the "green" or the "blue" dialog better. This is quite simple to implement and unlike the native dialog, doesn't introduce a real regression. Agree'd?

@anoadragon453 Would you mind extending your recent PR #3447 and implement something like this:

``` c++
namespace qTox {

class FileDialog {
    static inline QFileDialog::Options fileDialogOptions() {
        // read options from settings
        return Settings::getInstance().getFileDialogOptions();
    }

    static inline QString getOpenFileName(…) { 
        // set options depending on qTox settings
        QFileDialog::Options opts = fileDialogOptions();
        return QFileDialog::getOpenFileName(…, opts); 
    }

    // TODO: wrap all static public function from QFileDialog
};

}
```

@ElLamparto It is very nice file picker!…

Which one do you mean?

**Comment by TheNain38** [comment] 2016-07-08 11:57
@antis81 Yes, I saw that ^^ Else, I agree with adding a setting, to choose between Qt's file picker, and the native one, I **suggest** that using the native one as the default, it is better, since only some systems have problems, what is your opinion, on what I said?

**Comment by antis81** [comment] 2016-07-08 12:46
> I suggest that first using the native one, is better…

Will become default, yep.

**Comment by anoadragon453** [comment] 2016-07-08 20:18
@antis81 Yep I can do that.

**Comment by Diadlo** [comment] 2016-07-09 08:19
@antis81 I don't know how it seen on windows. But for me it's little bit ugly :(
![spectacle jh1190](https://cloud.githubusercontent.com/assets/6306608/16706916/4ed7c346-45cf-11e6-8218-a29fac1c5c32.png)

**Comment by antis81** [comment] 2016-07-09 08:59
@Diadlo Whoohoo, dark style. :) Looks like you are using a dark system theme, are you?

If so, qTox may set the "black" font in it's theming - which is wrong here. I'll have a look into that.

**Comment by Diadlo** [comment] 2016-07-09 09:24
Yes, I use dark system theme

**Comment by antis81** [comment] 2016-07-09 10:56
@Diadlo I found the problem! Have a look into [mainContent.css](https://github.com/tux3/qTox/blob/master/ui/settings/mainContent.css), which styles almost each and every widget in qTox and therefore creates a mixed up system/qTox style! This is basically not what we want, especially when "system dialogs appear".

@TheNain38 Please provide a screenshot of how it looks on windows. Probably also one for your native dialog.

@zetok CC

**Comment by TheNain38** [comment] 2016-07-09 11:08
@antis81 Also, there's one thing, Qt's file picker is in English, even if my system is set to French.
Qt:
![qt](https://cloud.githubusercontent.com/assets/13149763/16707643/2b83f390-45d6-11e6-9fc1-cc782806c2f3.png)
Native:
![native](https://cloud.githubusercontent.com/assets/13149763/16707656/8d865a1a-45d6-11e6-92be-f5049feb9bf3.png)

**Comment by antis81** [comment] 2016-07-09 12:22
@TheNain38 Probably your qTox is set to English??

**Comment by TheNain38** [comment] 2016-07-09 12:26
@antis81 No, it's set to French

**Comment by ovalseven8** [comment] 2016-07-10 08:08
=> https://github.com/tux3/qTox/issues/2499

**Comment by antis81** [comment] 2016-07-10 10:06
@ovalseven8 Thanks - so this one is actually (well, kind of) a duplicate. Please leave both open until PR is ready.

@TheNain38 

> No, it's set to French

You're right. I tried with German language on Lubuntu system. All of the UI elements (button, label, etc.) are translated, but the folders in the "left area" (favorites, places, or whatever you want to call it) are not. So translation is ~99%, but not like I'd expect it to be as a user.

**Comment by zetok** [comment] 2016-07-10 10:15
@antis81 no, this isn't a duplicate. The other issue is a packaging problem, while this one is about regression in qTox code.

**Comment by ElLamparto** [comment] 2016-07-13 08:05
@all, you spent time and energy on details like the file picker while under Linux audio hardly works (#3478) and video is practically inutilisable (I've opened a ticket a few months ago, but I cannot find it back).

**Comment by zetok** [comment] 2016-07-15 11:50
@ElLamparto Both audio & video problems are largely there due to insufficient testing of merged audio & video stuff.

Have you tried to test PRs? If not, you might want to :)

**Comment by TheNain38** [comment] 2016-12-01 12:04
Is there any news on this?

**Comment by zetok** [comment] 2016-12-01 12:11
No.

**Comment by ElLamparto** [comment] 2016-12-06 09:51
@TheNain38, personally I like the Qt picker. Anyway, like most people, I use drag and drop to transfer files. Rarely the picker. For me it is a very, very low priority issue.

**Comment by Diadlo** [comment] 2017-02-24 08:18
@antis81 suggest good solution: add file manager type selection to settings

**Comment by TheNain38** [comment] 2017-07-02 18:17
Is there anyone willing to take on this issue?

**Comment by Diadlo** [comment] 2017-07-03 15:00
As I can see -- no one

**Comment by anoadragon453** [comment] 2017-07-04 01:30
Would this not just be a simple `#ifdef Q_OS_WIN32` around the code file manager code block? I can take a look into this in a couple days.

**Comment by sudden6** [comment] 2017-07-04 09:06
maybe we can even find a proper solution so we can use the native file dialog where possible and only use the Qt one where it's needed.

**Comment by anoadragon453** [comment] 2017-07-04 09:08
Well windows and Mac should always return their file picker. Is there a
way to consistently get the DE's one on Linux and return Qt's if none
are found (i.e. tiling wm's)?

**Comment by sudden6** [comment] 2017-07-04 09:12
Maybe we can use a system similar to https://github.com/qTox/qTox/blob/master/src/widget/systemtrayicon.cpp

And use a whitelist of working DE's for the native dialog?

**Comment by anoadragon453** [comment] 2017-07-04 09:14
That looks fine, as long as KDE having Qt's native one is fine.

...does KDE have it's own file picker?

**Comment by sudden6** [comment] 2017-07-04 09:16
Yes, the KDE one is slightly different to the Qt one

**Comment by anoadragon453** [comment] 2017-07-04 09:17
Alright, well now one just has to figure out how to launch each of those from Qt pointing to a specific folder and we should be good. As I said I can take a crack at this, though possibly in a couple days, after July 4th and all that.

**Comment by sudden6** [comment] 2017-07-04 09:22
IIRC switching to the native file picker is just changing a parameter to `QFileDialog::getOpenFileName`

Take your time and enjoy your holidays :)

**Comment by anoadragon453** [comment] 2017-07-04 09:27
Oh yeah, I forgot how nice Qt is.

Thanks :)

**Closed as completed** 2017-07-13 16:35 UTC
Labels: D-easy, M-ui, proposal-accepted
