### ISSUE TITLE
optionally disable blinking for new messages when in "do not disturb" mode

### ISSUE THREAD

**Issue by aaannndddyyy** [qTox/qTox#3776] opened 2016-10-03 06:04 UTC
When I set myself to not disturb, the blinking when new messages arrive, can sometimes drive me crazy. would be nice to optionally disable notification of new messages by blinking in DND mode. It could simply chnage color once instead of permanent blinking. then it is also easily visible that there is an unread message, but less enervating.
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)

**Comment by Diadlo** [comment] 2016-10-03 08:12
Seems, duplicate of #3064, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2016-10-03 08:12 UTC
Labels: U-low, proposal, M-ui
