### ISSUE TITLE
Tails

### ISSUE THREAD

**Issue by Jucker7** [qTox/qTox#5003] opened 2018-03-14 15:05 UTC
Please, compile qTox as static for Tails!

OS: Tails 3.6

**Comment by tox-user** [comment] 2018-03-14 15:26
Would an appimage work too?

**Comment by tox-user** [comment] 2018-03-15 16:47
I'm closing this, because it looks like a duplicate of https://github.com/qTox/qTox/issues/4910. Let me know if it isn't.

**Closed as completed** 2018-03-15 16:47 UTC
Labels: U-low
