### ISSUE TITLE
Echo during A/V calls

### ISSUE THREAD

**Issue by alexeysvrv** [qTox/qTox#2517] opened 2015-11-07 10:54 UTC
There is a strong echo in the audio call. If you enable filtering of audio, it is still much hiss and noise, often interrupted by the voice. You can talk, but very uncomfortable. I use Echobot for check

**Comment by tux3** [comment] 2015-11-07 17:49
Isn't the point of Echobot to create echo? How do you check, since it's _supposed_ to echo back to you?

**Comment by alexeysvrv** [comment] 2015-11-07 17:52
@tux3 By increasing the sensitivity of the microphone or speaker, speaker begins to buzz, even if I do not say anything. And the echo of the bot is wrong, not the net, with echoes not natural

**Comment by tux3** [comment] 2015-11-07 17:56
@alexeysvrv If you increase the mic sensitivity above 100% it will degrade the quality a **LOT**, that's normal. If your speakers buzz when no sound is playing, now that's strange.
Do you have the same problem if you don't use Echobot?

**Comment by alexeysvrv** [comment] 2015-11-07 18:00
@tux3 I have no one to call to check, in addition to the bot. And more than 100% I did not do sensitivity. Even filter works very poorly.It gives noise. Without it, the sound is cleaner

**Comment by tux3** [comment] 2015-11-07 18:01
@alexeysvrv Okay, I'll try to reproduce it.

**Comment by alexeysvrv** [comment] 2015-11-07 18:05
@tux3 In qTox mic level 100%. In system mic level ~40-50%. If >50-60% is rising slowly squeaking speakers (

**Comment by rugk** [comment] 2015-11-09 19:32
I could reproduce this too.
Seems to be related to https://github.com/tux3/qTox/issues/2504

**Comment by alexeysvrv** [comment] 2015-11-09 19:38
@tux3 When this issue will be fixed?

**Comment by tux3** [comment] 2015-12-04 17:19
@alexeysvrv Filter audio is fixed, so I think that this issue is fixed now.

**Closed as completed** 2015-12-04 17:20 UTC
Labels: M-audio
