### ISSUE TITLE
Unable to run a second instance of the program

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1611] opened 2015-05-10 21:41 UTC
Windows 7 x32

If there was such idea,maybe can add a window with the reason of why not start

**Comment by tux3** [comment] 2015-05-10 22:01
This is on purpose, actually.
If you want to start a new instance, you currently need to start qtox with the "-p" flag on the command line.

**Comment by PKEv** [comment] 2015-05-10 22:03
if you run program with parameter like this:
qtox -p "user"
You find yourself in an endless cycle of selecting a profile (if the profile is certainly busy already running copy qtox)

**Comment by tux3** [comment] 2015-05-10 22:03
Yes. You can't have two instances on the same profile at once, that would corrupt everything.

We need to add some buttons so you can choose to exit/create a new profile in this case, but that's a different problem.

**Comment by PKEv** [comment] 2015-05-10 22:05
you can not terminate process (if you have not secont account) only by taskmanager

**Comment by tux3** [comment] 2015-05-10 22:05
Yes, we'll add an exit button. There's already an issue for this problem IIRC.

**Comment by linux-modder** [comment] 2015-05-11 01:15
Not sure I understand the need for dually active profiles ---I can see having multiples but why multis active concurrently

**Comment by tux3** [comment] 2015-05-11 01:46
@linux-modder Personally I use it a lot  to test qTox locally, but I could see a use for it if you want to separate contacts into different profiles and still talk to them at the same time, maybe.

**Comment by ProMcTagonist** [comment] 2015-05-11 08:25
I would use ^

**Comment by tux3** [comment] 2015-05-12 16:47
Closing, because this is by design.

You can force qTox to start a new instance with the "-p <profile>" option. But that option has not been extensively tested, and a potential bug could corrupt your profiles, so it's too early to make it a prominent option.

**Closed as completed by tux3** 2015-05-12 16:47 UTC
Labels: C-bug, proposal

**Comment by PKEv** [comment] 2015-05-12 21:39
ok, but adding small windows with message "qtox is alredy running", and then it will be possible for him to make a dialogue with the profile if you want to run a second copy of the program
