### ISSUE TITLE
Video-calls issue hasn't to be closed because video still doesn't work

### ISSUE THREAD

**Issue by Hintsmth** [qTox/qTox#4985] opened 2018-03-03 19:52 UTC
OS: Windows 7 Ultimate SP1
qTox version: v1.13.0
toxcore: 0.1.10
Qt: 5.9.3

After your announcement that you have fixed video-call problem, I downloaded the latest qTox version.  But still there is no image from the camera on the screen. Also I have tried to install nightly-build, but it doesn't work either.
C'mon guys...

![1](https://user-images.githubusercontent.com/33121649/36938636-53f1775a-1f1c-11e8-91e4-512b5e68e936.jpg)

I've already had this issue: #4764

**Comment by tox-user** [comment] 2018-03-04 02:49
Can you include the log to see if anything has changed?

**Comment by sudden6** [comment] 2018-03-04 11:38
Can you post the log output with the nightly build to [https://gist.github.com](https://gist.github.com) and post the link here?

**Comment by Hintsmth** [comment] 2018-03-05 19:03
This is the log from qTox version: v1.13.0:

``` 

[18:21:41.620 UTC] video/camerasource.cpp:267 : Debug: Opening device  "video=@device_pnp_\\\\?\\usb#vid_0c45&pid_6340&mi_00#6&295b300b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global"
[18:21:41.650 UTC] widget/form/settings/avform.cpp:382 : Debug: available Modes:
[18:21:41.650 UTC] widget/form/settings/avform.cpp:292 : Debug: selected Modes:
[18:21:41.650 UTC] widget/form/settings/avform.cpp:301 : Debug: width: 640, height: 480, FPS: 30.000029, pixel format: unknown

[18:21:41.651 UTC] widget/form/settings/avform.cpp:301 : Debug: width: 320, height: 240, FPS: 30.000029, pixel format: unknown

[18:21:41.651 UTC] widget/form/settings/avform.cpp:301 : Debug: width: 160, height: 120, FPS: 30.000029, pixel format: unknown

[18:21:41.651 UTC] audio/backend/openal.cpp:258 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[18:21:42.772 UTC] video/camerasource.cpp:321 : Warning: Codec not found
[18:21:49.582 UTC] audio/backend/openal.cpp:274 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[18:21:49.582 UTC] audio/backend/openal.cpp:477 : Debug: Closing audio input
[18:21:49.603 UTC] video/camerasource.cpp:383 : Debug: Closing device  `"video=@device_pnp_\\\\?\\usb#vid_0c45&pid_6340&mi_00#6&295b300b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global"

```

Nightly build surprisingly is working now, here is the log:

```

[19:00:52.725 UTC] video/camerasource.cpp:267 : Debug: Opening device  "none"
[19:00:52.725 UTC] video/cameradevice.cpp:152 : Debug: Tried to open the null device
[19:00:52.725 UTC] video/camerasource.cpp:280 : Warning: Failed to open device!
[19:00:52.744 UTC] widget/form/settings/avform.cpp:385 : Debug: available Modes:
[19:00:52.744 UTC] widget/form/settings/avform.cpp:294 : Debug: selected Modes:
[19:00:52.744 UTC] widget/form/settings/avform.cpp:303 : Debug: width: 640, height: 480, FPS: 30.000029, pixel format: unknown

[19:00:52.744 UTC] widget/form/settings/avform.cpp:303 : Debug: width: 320, height: 240, FPS: 30.000029, pixel format: unknown

[19:00:52.744 UTC] widget/form/settings/avform.cpp:303 : Debug: width: 160, height: 120, FPS: 30.000029, pixel format: unknown

[19:00:52.745 UTC] video/camerasource.cpp:384 : Debug: Closing device  "none"
[19:00:52.745 UTC] video/camerasource.cpp:267 : Debug: Opening device  "video=@device_pnp_\\\\?\\usb#vid_0c45&pid_6340&mi_00#6&295b300b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global"
[19:00:52.745 UTC] audio/backend/openal.cpp:676 : Debug: Audio source 2 created. Sources active: 1
[19:00:52.745 UTC] audio/backend/openal.cpp:246 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[19:00:56.934 UTC] audio/backend/openal.cpp:698 : Debug: Audio source 2 deleted. Sources active: 0
[19:00:56.940 UTC] audio/backend/openal.cpp:502 : Debug: Closing audio output
[19:00:56.943 UTC] audio/backend/openal.cpp:262 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[19:00:56.943 UTC] audio/backend/openal.cpp:467 : Debug: Closing audio input
[19:00:56.983 UTC] video/camerasource.cpp:384 : Debug: Closing device  "video=@device_pnp_\\\\?\\usb#vid_0c45&pid_6340&mi_00#6&295b300b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global"

```

**Comment by tox-user** [comment] 2018-03-24 22:03
@Hintsmth can you confirm that the problem is fixed in 1.14.1?

**Comment by Hintsmth** [comment] 2018-03-31 18:27
@tox-user well, this problem is fixed (the web-cam is detected), BUT the image quality under 480p is like it's under 60p :D 
And the audio is a real crap.
Don't know how it works on Linux, haven't tested.
Version 1.11.0 still works perfectly.
Maybe some downgrades? :)

**Comment by anthonybilinski** [comment] 2018-03-31 20:57
@Hintsmth I also noticed audio being "real crap" on Windows since 1.14.1, but not in 1.13.0, https://github.com/qTox/qTox/issues/5039. I think there's some regression there.

When you say video quality under 480p is bad, is that in the preview window in settings, or during a video call? Is your CPU maxed or anything? Is only video under 480p effected, i.e. is there a huge jump in quality between 480p and 720p? Maybe open a new issue if it's reproducible since the main problem from this issue is resolved.

**Comment by sudden6** [comment] 2018-04-01 09:48
@Hintsmth Also please attach a screenshot of the bad video quality, helps a lot to find the root cause.

I also think that is a new issue and a new one should be opened, maybe starting with the last three comments from here.

**Comment by Dimok777910** [comment] 2018-07-14 10:03
Hi. The problem with sound and video when making a video call. 
1.When video call (from laptop to laptop) the sound is very late,stutters,disappears.
2.When video calls from a smartphone to a smartphone, the sound comes with a long delay,stutters, disappears. In ASUS smartphones, there is another problem,when you turn the screen, the picture crumbles and as a result the image disappears on 2 devices.
I tried to fix it myself, changed the camera resolution, tried the sound settings, nothing helps. Please help me fix these problems, apparently they are not only I have one. On my laptop I have Linux Mint 18.3. Tox application was installed without problems and errors.
THANK YOU IN ADVANCE!

**Comment by tox-user** [comment] 2018-07-14 10:08
@Dimok777910
>2.When video calls from a smartphone to a smartphone, the sound comes with a long delay,stutters, disappears.

qTox doesn't work on smartphones, so it must be a problem with a different client.

I assume that you use qTox on your laptops though. What is the version of qTox and toxcore you are using? You can check that in settings->about.

**Comment by Dimok777910** [comment] 2018-07-14 10:32
qTox v1.16.1
toxcore: 0.2.3
Qt: 5.10.1

**Comment by Dimok777910** [comment] 2018-07-14 10:36
Is Antox software for smartphones not your development?

**Comment by tox-user** [comment] 2018-07-14 11:14
No, Antox repository is here: https://github.com/antox/antox

**Comment by sudden6** [comment] 2019-08-11 15:30
The original issue seems to be fixed.

**Closed as completed by sudden6** 2019-08-11 15:30 UTC
Labels: O-need-info, M-video
