### ISSUE TITLE
Audio filter doesn't work for all users

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1565] opened 2015-05-02 18:50 UTC
I use alsa and PA, changing audio filter to on/off doesn't make an difference. Tested with users and echobot.

@TGiFallen has the same problem on Windows 7.

**Comment by zetok** [comment] 2015-08-28 14:42
Things most likely should have changed with new versions of filter_audio, testing again may be needed.

**Comment by rugk** [comment] 2015-11-09 19:31
Duplicate of #2504?

**Comment by agilob** [comment] 2015-11-09 19:42
No, 2504 is duplicate of this issue, look at dates ;D

**Closed as completed** 2015-12-04 17:20 UTC
Labels: C-bug, O-need-info, M-audio
