### ISSUE TITLE
Qtox automatically sets  up links around URLs incorrectly and occasionally breaks them

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4284] opened 2017-03-24 09:56 UTC
The blue clicky part that is supposed to go only around the URLs, sometimes ends up around other stuff instead. Furthermore, sometimes it messes up the link a lot worse.

E.g., typing in http://google.com http://google.com yields: 
http://">ogle.com">http://google.com http://google.com

Expected behavior is that each link in an inline list has its own blue clicky part. And obviously, it shouldn't mangle URLs. Furthermore, sometimes the blue clicky part includes parts it shouldn't.

For example, typing in "http://google.com" (including the quotes) yields almost the correct behavior, but it includes the last quote mark in the blue clicky part.

There was also an instance of it just putting the blue clicky part around the wrong text altogether (and leaving the URL text intact), but I wasn't able to reproduce.

These errors combined make sharing youtube-dl download lists with people a very glitchy experience.

OS:
`uname -a`
Linux client0 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`lsb_release -a`
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

qTox version: v1.8.1-135-gf72c83a
Commit hash: f72c83afb76e4c4f055cb3e5bad9447bd03475e1
toxcore version: 0.1.2
Qt version: 5.5.1

Reproducible: Always

**Comment by zetok** [comment] 2017-03-24 10:15
Duplicate of #4275, thus closing.

Should be fixed on latest master, if it's not, please comment for reopen.

**Closed as completed by zetok** 2017-03-24 10:15 UTC
Labels: U-low
