### ISSUE TITLE
Video features working unstable

### ISSUE THREAD

**Issue by BiTOk** [qTox/qTox#3552] opened 2016-07-24 20:58 UTC
##### Brief Description

OS: Windows 10 x64
qTox version: night build 
Commit hash: e6e666fa8ce36cd3792d4536a59ab2b65fd5b546
toxcore:  0.0.0
Qt:  5.5.1
Hardware: standard
…

Reproducible: Always
##### Steps to reproduce
1. Run qtox
2. Call echobot with videocall
3. Go to AV settings
4. Go back to echobot call
##### Observed Behavior

Video doesn't start after video call to echobot despite correct AV settings (web camera). But video starts after several switches to/from AV settings. While AV settings preview doesn't works together with video call.
##### Expected Behavior

Video call starts without additional manipulations. Video preview similarly.

ADD: after first successful attempt to open camera, all working fine until qtox restart.

**Comment by BiTOk** [comment] 2016-07-24 21:03
Similar problems I have with desktop stream. Desktop preview works is I select Desktop 1, but doesn't work for Desktop 2. The same problem with stream desktop region.

**Comment by sudden6** [comment] 2016-07-25 17:11
@BiTOk Log files will be interesting

**Comment by BiTOk** [comment] 2016-07-25 17:39
After reboot I can't reproduce problem with camera, but can with desktop preview: 
`src/video/camerasource.cpp:219 : Debug: Opening device  "gdigrab#desktop"
src/video/camerasource.cpp:233 : Warning: Failed to open device!
src/video/videoframe.cpp:130 : Warning: None of the frames are valid! Did someone release us?`

@Diadlo has more info about this problem.

**Comment by Diadlo** [comment] 2016-07-25 20:14
Tried with @BiTOk manual start ffmpeg (from cmd.exe). With parameters same with qtox. All works fine. Don't have any idea.

**Comment by Diadlo** [comment] 2016-07-25 20:23
> src/widget/form/settings/avform.cpp:310 : Debug: 1920x1080+63616,65224 FPS: 0.000000, pixel format: unknown

↑ From @BiTOk log: https://gist.github.com/Diadlo/008492dafd84072403e8f1b465546580

> Capture area (1400,20),(1500,220) extends outside window area (-1920,-312),(1366,768)desktop: I/O error

↑ From ffmpeg

Seems ffmpeg requed negative x for second screen, but ~~Qt~~ ScreenshotGrabber use positive

**Comment by ElLamparto** [comment] 2016-07-26 13:39
This bug appeared recently. v1.4.0-339-ge6e666f-obs, Debian Jessie 32bit.
No video preview. Log attached.
[qtoxOutput.txt](https://github.com/tux3/qTox/files/383925/qtoxOutput.txt)

**Comment by Diadlo** [comment] 2016-07-26 14:02
@ElLamparto Can you do [regression test](https://github.com/tux3/qTox/wiki/Testing#regression-testing)?

**Comment by sudden6** [comment] 2016-07-26 17:49
@ElLamparto I think your problem isn't really related to this issue, because your logs show that at least the webcam and resolution gets properly detected, whereas for @BiTOk  this doesn't work. Also you seem to have problems with the webcam and this report is about a problem with screen streaming.

Please open a seperate issue.

**Closed as completed** 2016-08-26 09:09 UTC
Labels: C-bug, M-video
