### ISSUE TITLE
Groupchat user list is stretched if it contains names with fullwidth CJK characters

### ISSUE THREAD

**Issue by tsdko** [qTox/qTox#660] opened 2014-11-07 15:25 UTC
![](http://a.pomf.se/byvejj.png)

**Comment by zetok** [comment] 2015-08-21 06:53
Is it still the case on newest builds?

**Comment by zetok** [comment] 2015-09-10 14:06
No testcase to reproduce against - I've tried using nick `testみちる`, and couldn't reproduce, thus closing.

**Closed as completed by zetok** 2015-09-10 14:06 UTC
Labels: C-bug, P-low, O-need-info
