### ISSUE TITLE
Faux offline file delivery

### ISSUE THREAD

**Issue by wuniversales** [qTox/qTox#5967] opened 2020-01-23 16:03 UTC
OS: Linux Manjaro
qTox version:  v1.16.3
Commit hash:  https://github.com/qTox/qTox/commit/8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.10
Qt:  5.12.0
Reproducible: Always

Steps to reproduce

1. Open a contact that is offline
2. Send any file
3. Error displaying file sent

Expected Behavior

1. Open a contact that is offline
2. Send any file
3. Send the file (Wait for the user to connect to send the file)

**Comment by anthonybilinski** [comment] 2020-01-25 00:06
Duplicate of https://github.com/qTox/qTox/issues/1293, so I'll close. I agree it should be added, we've fairly recently added files to our history db, which is a decent chunk of the work.

**Closed as completed by anthonybilinski** 2020-01-25 00:06 UTC
Labels: C-feature-request
