### ISSUE TITLE
OSX qtox crash when trying to send a file

### ISSUE THREAD

**Issue by magicworks** [qTox/qTox#1054] opened 2015-01-26 12:53 UTC
Dubslow got annoyed by wall of text lol: https://gist.github.com/dubslow/8857498be230736724ee

**Comment by stqism** [comment] 2015-04-05 18:37
I'm unable to reproduce this, please let me know if it still persists.

@dubslow Please close this for now.

**Closed as completed** 2015-04-06 14:35 UTC
Labels: C-bug
