### ISSUE TITLE
The name column should be resizable

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1190] opened 2015-02-16 05:49 UTC
See xchat. When the mouse is over the invisible line dividing the names and the messages, it should become a <-> and let me drag to resize.

**Comment by zetok** [comment] 2015-08-25 10:24
one of ways of displaying peers from #2013 implements that.

Should be closable after PR gets merged.

**Comment by Diadlo** [comment] 2018-11-16 03:49
Related issues: #635 #1219

**Comment by sudden6** [comment] 2019-08-11 14:09
Duplicate of  #514

**Closed as completed by sudden6** 2019-08-11 14:09 UTC
Labels: P-low, M-ui, proposal-accepted
