### ISSUE TITLE
Freeze on file transfer and avatar changing

### ISSUE THREAD

**Issue by Kron4ek** [qTox/qTox#3597] opened 2016-08-06 11:57 UTC
##### Brief Description

OS: Arch Linux x86_64. Linux 4.6.4-1-ARCH.
qTox version: 1.4.1
toxcore: 3747
Qt:  5.7.0

Reproducible: Always
##### Steps to reproduce
1. Click "Send file(s)" button or click profile avatar
##### Observed Behavior

qTox freezes with these errors:

```
(qtox:7321): GLib-GObject-WARNING **: cannot register existing type 'GdkWindow'

(qtox:7321): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(qtox:7321): Gdk-CRITICAL **: gdk_window_ensure_native: assertion 'GDK_IS_WINDOW (window)' failed
```

**Comment by zetok** [comment] 2016-08-06 12:19
Duplicate of #3436, thus closing.

Edit: btw, it's fixed on master, you can get it from AUR.

**Closed as completed by zetok** 2016-08-06 12:19 UTC
Labels: U-low
