### ISSUE TITLE
Minor: alias changing

### ISSUE THREAD

**Issue by Bargest** [qTox/qTox#1959] opened 2015-07-02 19:17 UTC
Contact name in history doesn't update after changing contact alias. First alias is AZAZA:
![image](https://cloud.githubusercontent.com/assets/13108544/8485635/b5f8a3e4-2107-11e5-934f-6da848562363.png)
After changing, it becomes FOOO, but in history it is still AZAZA:
![image](https://cloud.githubusercontent.com/assets/13108544/8485650/cdc5617e-2107-11e5-9838-de684490e260.png)
But if I clear chat window and re-read history, the new name is displayed:
![image](https://cloud.githubusercontent.com/assets/13108544/8485669/ff4efb7e-2107-11e5-9de4-60ceb0b55a9a.png)

I think it should either update after changing alias or (maybe) still the same after history reloading.

P.S. I thought it is already known, but coulnd't find similar issue.

**Comment by ProMcTagonist** [comment] 2015-07-02 19:54
It should stay the same. Contact name at time of each message is important context data that should be respected.

**Comment by PKEv** [comment] 2015-07-03 09:07
#1189

**Comment by Bargest** [comment] 2015-07-03 11:31
This one is bit different. I mean, in one scenario qTox doesn't update name in chat, and in other does. It's definitely not an "enhancement", as marked at #1189, it is a bug: qTox behaves differently in similar usecases.
The behaviour should be unified.

**Comment by zetok** [comment] 2015-08-25 10:17
> I think it should either update after changing alias or (maybe) still the same after history reloading.

Yes, it should be saved in the history, and "renaming" stuff after reloading history is not the desired way.

Closing, since it's a ~duplicate of #659

**Closed as completed by zetok** 2015-08-25 10:17 UTC
Labels: U-low, proposal
