### ISSUE TITLE
Question about date time signature(s) in messages

### ISSUE THREAD

**Issue by stefanos82** [qTox/qTox#6305] opened 2021-02-19 20:44 UTC
##### Brief Description

```
OS: GNU / Linux Debian testing 64-bit
qTox version: qTox version v1.17.2-1.1-debian
Commit hash:  build without git
toxcore:  0.2.12
Qt:  5.15.1
```

This is my message on your IRC channel:

> greetings everyone. I wanted to ask a question but didn't know whether I should ask it via github ticket or ask here. My question is the following: I am currently online and a friend is offline. I sent him messages but of course he will receive them when he gets online. Is there a way for him to see the datetime on each message I originally sent them? The only datetime he will see are the one of receiving.
> 
> the date is displayed on top of each day in center and the time signature at the far right of messenger. Can we add at the left of time signature something like [sent at 01/01/1970 00:00:00]?
>

**Comment by anthonybilinski** [comment] 2021-02-23 04:12
Currently the Tox protocol doesn't have anyway to send a "sent time" along with the message, so all we have it display is the received time. I agree it would be nice to have both though, and there is a path forward to add it mentioned here: https://github.com/qTox/qTox/issues/4851#issuecomment-595407092 using https://github.com/toxext/toxext which was integrated into qTox recently.

This issue is generally a duplicate of https://github.com/qTox/qTox/issues/4851 though, so I'll close it.

**Closed as completed by anthonybilinski** 2021-02-23 04:12 UTC
