### ISSUE TITLE
No indication as to who sent a message

### ISSUE THREAD

**Issue by geeteshtabjul** [qTox/qTox#4193] opened 2017-02-22 10:49 UTC
There is only a notification sound, but there is no indication to show who messaged us. A count of unread messages next to the person in the contact list would be better or maybe just a highlight.

**Comment by Diadlo** [comment] 2017-02-22 16:21
Notification mesage is duplicate of #2921
Friend status already highlighted (area around ststus icon)
Message count and another indication is duplicate of #1095
Closing. Please use a search before create new issue. Thanks

**Closed as completed by Diadlo** 2017-02-22 16:21 UTC
