### ISSUE TITLE
avatar not sended

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#1765] opened 2015-06-01 22:08 UTC
error in win 7 x32 
log file:
[00:51:31.221] src/profilelocker.cpp:56 : Debug: clearAllLocks: Wiping out all lock files
[00:51:31.222] src/nexus.cpp:45 : Debug: Starting up
[00:51:31.223] src/widget/widget.cpp:245 : Debug: Loaded translation "ru"
[00:51:31.223] src/widget/widget.cpp:257 : Debug: System translation not loaded "ru"
[00:51:31.225] src/core/core.cpp:58 : Debug: loading Tox from "C:/Users/Ольга/AppData/Roaming/tox/Olchik.tox"
[00:51:31.227] src/audio.cpp:179 : Debug: "Trying to open output Динамики (Устройство с поддержкой High Definition Audio)"
[00:51:31.312] src/audio.cpp:212 : Debug: "Opening audio output Динамики (Устройство с поддержкой High Definition Audio)"
[00:51:31.313] src/audio.cpp:138 : Debug: "Trying to open input Микрофон (Устройство с поддержкой High Definition Audio)"
[00:51:31.370] src/audio.cpp:157 : Debug: Opening audio input  "Микрофон (Устройство с поддержкой High Definition Audio)"
[00:51:33.021] src/core/core.cpp:243 : Debug: Starting up
[00:51:33.056] src/core/core.cpp:912 : Debug: loadConfiguration: reading from  "C:/Users/Ольга/AppData/Roaming/tox/Olchik.tox"
[00:51:33.058] src/core/core.cpp:141 : Debug: Core starting with IPv6 enabled
[00:51:33.151] tools/qstring.cpp:7098 : Warning: QString::arg: Argument missing: ??????, ???????? ???? ? ???????, Olchik
[00:51:33.157] src/core/core.cpp:330 : Debug: Error loading self avatar
[00:51:34.085] src/widget/systemtrayicon.cpp:110 : Debug: Using the Qt backend
[00:51:34.762] src/autoupdate.cpp:137 : Debug: timestamp: 1433059072 , str: "277b4490c36fc4ebbdfa468949371962ea95229d"
[00:51:35.994] src/core/core.cpp:425 : Debug: Bootstrapping to the DHT ...
[00:51:35.996] src/core/core.cpp:434 : Debug: "Bootstrapping from Impyy, addr 178.62.250.138, port 33445"
[00:51:36.001] src/core/core.cpp:446 : Debug: "Adding TCP relay from Impyy, addr 178.62.250.138, port 33445"
[00:51:36.004] src/core/core.cpp:434 : Debug: "Bootstrapping from Thierry Thomas, addr 78.225.128.39, port 33445"
[00:51:36.009] src/core/core.cpp:446 : Debug: "Adding TCP relay from Thierry Thomas, addr 78.225.128.39, port 33445"
[00:51:39.882] src/core/core.cpp:396 : Debug: Connected to DHT
[00:51:39.893] src/core/coreencryption.cpp:311 : Debug: writing tox_save to  "C:/Users/Ольга/AppData/Roaming/tox/Olchik.tox"
[00:51:39.949] src/misc/settings.cpp:393 : Debug: "Saving settings in C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:51:39.983] src/misc/settings.cpp:494 : Debug: Saving personal settings in  "C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:51:49.916] tools/qstring.cpp:7098 : Warning: QString::arg: Argument missing: ??????, ???????? ???? ? ???????, Olchik
[00:51:49.921] src/core/coreencryption.cpp:311 : Debug: writing tox_save to  "C:/Users/Ольга/AppData/Roaming/tox/Olchik.tox"
[00:51:50.018] src/misc/settings.cpp:393 : Debug: "Saving settings in C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:51:50.033] src/misc/settings.cpp:494 : Debug: Saving personal settings in  "C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:51:59.318] tools/qstring.cpp:7098 : Warning: QString::arg: Argument missing: ??????, ???????? ???? ? ???????, Olchik
[00:51:59.327] src/core/coreencryption.cpp:311 : Debug: writing tox_save to  "C:/Users/Ольга/AppData/Roaming/tox/Olchik.tox"
[00:51:59.374] src/misc/settings.cpp:393 : Debug: "Saving settings in C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:51:59.402] src/misc/settings.cpp:494 : Debug: Saving personal settings in  "C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:52:00.883] src/core/coreencryption.cpp:311 : Debug: writing tox_save to  "C:/Users/Ольга/AppData/Roaming/tox/Olchik.tox"
[00:52:00.934] src/misc/settings.cpp:393 : Debug: "Saving settings in C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:52:00.960] src/misc/settings.cpp:494 : Debug: Saving personal settings in  "C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:52:01.482] tools/qstring.cpp:7098 : Warning: QString::arg: Argument missing: ??????, ???????? ???? ? ???????, Olchik
[00:52:01.490] src/core/coreencryption.cpp:311 : Debug: writing tox_save to  "C:/Users/Ольга/AppData/Roaming/tox/Olchik.tox"
[00:52:01.544] src/misc/settings.cpp:393 : Debug: "Saving settings in C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:52:01.581] src/misc/settings.cpp:494 : Debug: Saving personal settings in  "C:/Users/Ольга/AppData/Roaming/tox/qtox.ini"
[00:53:38.843] src/avatarbroadcaster.cpp:31 : Debug: Sending avatar to  0
[00:53:51.190] src/core/corefile.cpp:303 : Debug: onFileControlCallback: Received pause for file  0 : 0  

additionally:
maybe because of the Cyrillic alphabet in the profile path

**Comment by zetok** [comment] 2015-08-29 23:00
Is issue reproducible on OS other than windows?

**Comment by zetok** [comment] 2015-10-10 04:27
Apparently qTox sometimes doesn't send avatars, independently from OS - @agilob that's what you ran into recently when you were testing saving avatars to DB, right?

**Comment by agilob** [comment] 2015-10-10 07:53
Yup, Antox sends avatar only on change, never on connect, µtox not always. I received avatar from zetok automatically, but from his second account kotez, after a few hours of being online.

**Comment by subliun** [comment] 2015-10-11 10:57
> only on change, never on connect

Not true, see:
https://github.com/subliun/Antox/blob/master/app/src/main/scala/chat/tox/antox/callbacks/AntoxOnConnectionStatusCallback.scala#L53

**Comment by tux3** [comment] 2016-01-21 01:45
This should be fixed now, can anyone reproduce?

**Comment by zetok** [comment] 2016-01-22 09:44
> This should be fixed now, can anyone reproduce?

Yes :3

Not something that I explicitly looked for, but..
1. 2 clients that have each other avatars, Q1 and Q2.
2. Turn both of them on and wait until both will decline avatar from other side
3. Turn Q2 client off, and remove its `avatars/` dir [*]
4. Turn Q2 on, after it will come online, Q1 will not send its avatar to Q2, even though Q2 doesn't have Q1's avatar any longer.

↑ probably that to reproduce

[*] Instead of removing, I just moved `.tox`, and `.ini` files to some other dir and called qTox there with `HOME=$PWD qtox`

**Comment by tux3** [comment] 2016-01-22 13:22
@zetok That's because Q2 already declined Q1's avatar, so Q1 remembered that (since people rarely delete their avatar folder it makes sense to remember), Q1 will offer its avatar again to everyone after you restart it.

So I can make Q1 never remember that and always offer its avatar, but that's more network traffic.

**Comment by zetok** [comment] 2016-01-22 23:36
> So I can make Q1 never remember that and always offer its avatar, but that's more network traffic.

Hardly more network traffic - if someone already has an avatar, they decline file transfer, so practically no data is being sent. Really, those few bytes don't increase traffic that much.

On the other hand, if qTox remembers to whom avatar was "sent", then people encounter buggy behaviour.

**Comment by tux3** [comment] 2016-01-23 00:25
I remember it was a problem when toxcore had the tendency to oscillate between offline and online for contacts several times per second. I haven't seen that in a long time, so it should be fine now, you're right.

**Comment by zetok** [comment] 2016-05-10 09:40
Note from #3286, thanks to @qasmoke:

# 

OS: Windows 7 64
qTox version: v1.4.0-29-g08263e9.
Commit hash:  08263e98445e543eacb0b16ac4fefc7963baf7a3
Qt:  5.5.1
…

Reproducible: Always

##### Steps to reproduce
1. Your qTox is running, and some friends(with their own icons) are online.
2. Close qTox. Go to qtox.exe folder, and delete "avatar" folder.
3. Start qTox. All icons are gone(of course), so I set my avatar again.
4. About other friends icons,

**Comment by sudden6** [comment] 2018-07-10 22:03
Probably not a problem anymore, closing.

**Closed as completed by sudden6** 2018-07-10 22:03 UTC
Labels: C-bug, P-low
