### ISSUE TITLE
Import profile crashses qTox

### ISSUE THREAD

**Issue by carun** [qTox/qTox#3773] opened 2016-10-02 19:40 UTC
##### Brief Description

OS: Windows
qTox version: v1.5.1-8-gfd04a28.
Commit hash: fd04a2832aa885d260ded4e476eefcddd49237b3
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. Exit qTox.
2. Clean up C:\Users<User>\AppData\Roaming\tox
3. Run qTox.
4. Click on Load Profile -> Import.
5. Choose Tox profile file from Google drive sync location. ![1](https://cloud.githubusercontent.com/assets/471374/19023191/c3b703ec-889c-11e6-8425-bf2062950b1a.png)
##### Observed Behavior

Exception and abort.
![2](https://cloud.githubusercontent.com/assets/471374/19023200/0c50c26e-889d-11e6-916d-61d4854e67cd.PNG)
##### Expected Behavior

Should load the profile and ask for profile password.

**Comment by zetok** [comment] 2016-10-02 19:43
Duplicate of #3660, thus closing.

Fixed on newest `master`.

**Closed as completed by zetok** 2016-10-02 19:43 UTC
Labels: U-low, C-crash
