### ISSUE TITLE
qTox never reconnect itself when Internet connection dropped

### ISSUE THREAD

**Issue by JohnMkainne** [qTox/qTox#3241] opened 2016-05-02 02:22 UTC
##### Brief Description

OS: Windows 8/7
qTox version: v1.4.0-29-g08263e9.
toxcore:  0.0.0
Qt:  5.5.1 
…

Reproducible: Always
##### Steps to reproduce
1. qTox is running.
2. qTox is using network proxy(TCP only, no IPv6). e.g., 10.20.30.40:5678
3. Network proxy server's Internet is going down.
4. And up again after 5 minutes or so.
5. Open qTox's contact list.
##### Observed Behavior

a. All contacts are "red circle"(offline).
b. Open one of them show "XXX is now offline" in his chat window.
c. And my status is green filled circle(online).

Friends are ALWAYS online, so why they are offline?
(they become online once I close qTox and fire it up again)
##### Expected Behavior

a. Reconnect if the internet is down.
b. Show red circle if the internet is down(my client side)
##### Additional Info

"BitMessage" detect internet status almost realtime. It says Offline when internet is down, and online also.

**Comment by zetok** [comment] 2016-05-02 06:11
Needs to be improved in toxcore.

**Comment by zetok** [comment] 2016-05-02 06:19
Actually, a duplicate of #1560, thus closing.

**Closed as completed by zetok** 2016-05-02 06:19 UTC
Labels: C-bug, U-low, upstream
