### ISSUE TITLE
Flag emoji are incorrectly displayed

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5147] opened 2018-05-17 21:56 UTC
##### Brief Description

OS: openSUSE Leap 42.3
qTox version: v1.15.0-45-g1f58e1c0
Commit hash: 1f58e1c0af1f216431528cce3bc787afc481de38
toxcore: 0.2.2
Qt: 5.6.2
Hardware: 
…

Reproducible: Always

##### Steps to reproduce

1. open chat
2. enter the "german flag emoji" 🇩🇪 via emoji picker
3. press "Send" button

##### Observed Behavior

It's displayed as flag in the input box, but if you send it, it becomes the "D emoji" and "E emoji"

##### Expected Behavior

"german flag emoji" is displayed in the chat log

##### Additional Info
"D emoji" and "E emoji"
![spectacle d12727](https://user-images.githubusercontent.com/5585762/40205788-bc70bf9c-5a2d-11e8-8ecd-5cc519ae1d12.png)

happens with all flag emojis

**Comment by tox-user** [comment] 2018-05-18 14:58
Confirmed. It's been like that since 1.14.0 or 1.14.1.

**Comment by sudden6** [comment] 2018-05-18 15:45
maybe has something to do with the recent changes around multi byte emois by @anthonybilinski ?

**Comment by tox-user** [comment] 2018-05-18 16:03
It most likely does.

**Comment by anthonybilinski** [comment] 2018-10-04 00:09
Yes it does, introduced in 9643e48ef1d68948d52feec4e1be28c3ad61c0da. Parsing logic needs to be updated to favour multi-Ucs4-length emoji (flags) which are made up of multiple single-length valid emoji, i.e. the [US flag] is made up of the emoji [U] and [S] next to each other.

**Comment by anthonybilinski** [comment] 2021-02-17 04:40
Fixed by https://github.com/qTox/qTox/pull/6302.

**Closed as completed by anthonybilinski** 2021-02-17 04:40 UTC
Labels: C-bug, M-ui
