### ISSUE TITLE
Tox closes audio input and opens it only on Settings tab

### ISSUE THREAD

**Issue by drequivalent** [qTox/qTox#3743] opened 2016-09-23 23:42 UTC
#### Audio works only on settings tab

Linux (Elementary OS Loki)  
qTox version: qTox version v1.5.1-obs 
Commit hash:  https://github.com/qTox/qTox/commit/f05b7e040a073c7afadaf763dda5beaf130c6dbd
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  
…

Reproducible: Almost Always
##### Steps to reproduce
1. Open Qtox
2. Wait for somebody to call
3. Realize that they hear nothing
4. Open Audio/Video settings tab
5. Now your recipient hears you
##### Observed Behavior

So, it seems that the audio si only working when I open Audio/Video settings tab
##### Expected Behavior

Audio should work right away
##### Additional Info

Console output. Right from the start:

```
[23:31:24.033 UTC] src/persistence/settings.cpp:134 : Debug: "Loading settings from /home/equivalent/.config/tox/qtox.ini"
[23:31:24.065 UTC] src/ipc.cpp:59 : Debug: Our global IPC ID is  12520251134782629955
[23:31:24.065 UTC] src/main.cpp:204 : Debug: built on:  19:27:53 Sep 10 2016 ( 1473535669 )
[23:31:24.065 UTC] src/main.cpp:205 : Debug: commit:  f05b7e040a073c7afadaf763dda5beaf130c6dbd 

[23:31:24.065 UTC] src/persistence/profile.cpp:109 : Debug: Loading tox save  "/home/equivalent/.config/tox/dr.tox"
[23:31:24.066 UTC] src/persistence/settings.cpp:404 : Debug: "Saving global settings at /home/equivalent/.config/tox/qtox.ini"
[23:31:24.084 UTC] src/persistence/settings.cpp:319 : Debug: Loading personal settings from "/home/equivalent/.config/tox/dr.ini"
[23:31:24.084 UTC] src/nexus.cpp:84 : Debug: Starting up
[23:31:24.880 UTC] src/core/core.cpp:238 : Debug: Loading user profile
[23:31:24.880 UTC] src/persistence/profile.cpp:290 : Debug: Loading tox save  "/home/equivalent/.config/tox/dr.tox"
[23:31:24.880 UTC] src/core/core.cpp:131 : Debug: Core starting with IPv6 enabled
[23:31:24.981 UTC] src/core/core.cpp:307 : Debug: Self avatar not found, will broadcast empty avatar to friends
[23:31:25.189 UTC] src/widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
[23:31:26.839 UTC] src/core/core.cpp:415 : Debug: "Connecting to 2a02:f680:1:1100::3313:33445 (ru_maniac)"
[23:31:26.864 UTC] src/core/core.cpp:415 : Debug: "Connecting to 192.99.168.140:33445 (WIeschie)"
[23:31:33.261 UTC] src/core/core.cpp:415 : Debug: "Connecting to 185.58.206.164:33445 (ru_maniac)"
[23:31:33.261 UTC] src/core/core.cpp:415 : Debug: "Connecting to maggie.prok.pw:33445 (Prototik)"
[23:31:35.298 UTC] src/core/core.cpp:379 : Debug: Connected to the DHT
[23:31:35.298 UTC] src/persistence/profile.cpp:364 : Debug: Saving tox save to  "/home/equivalent/.config/tox/dr.tox"
[23:31:40.819 UTC] src/widget/form/chatform.cpp:509 : Debug: enableCallButtons
[23:31:40.820 UTC] src/widget/form/chatform.cpp:522 : Debug: timer started!!
[23:31:57.741 UTC] src/core/coreav.cpp:605 : Debug: "Received call invite from 7"
[23:31:57.741 UTC] src/audio/audio.cpp:345 : Debug: Opening audio input "Built-in Audio Analog Stereo"
[23:31:57.748 UTC] src/audio/audio.cpp:363 : Warning: Failed to initialize audio input device: "Built-in Audio Analog Stereo"
[23:31:57.748 UTC] src/audio/audio.cpp:293 : Warning: Failed to subscribe to audio input device.
[23:31:57.748 UTC] src/audio/audio.cpp:386 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[23:31:57.750 UTC] src/audio/audio.cpp:396 : Warning: Cannot open output audio device "Built-in Audio Analog Stereo"
[23:31:57.750 UTC] src/audio/audio.cpp:655 : Warning: Failed to subscribe to audio output device.
[23:31:57.750 UTC] src/audio/audio.cpp:345 : Debug: Opening audio input "Built-in Audio Analog Stereo"
[23:31:57.752 UTC] src/audio/audio.cpp:369 : Debug: Opened audio input "Built-in Audio Analog Stereo"
[23:31:57.752 UTC] src/audio/audio.cpp:298 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[23:31:57.752 UTC] src/audio/audio.cpp:314 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[23:31:57.752 UTC] src/audio/audio.cpp:515 : Debug: Closing audio input **<- This line looks fishy**
[23:31:57.752 UTC] src/widget/form/chatform.cpp:282 : Debug: onAvInvite
[23:31:57.759 UTC] src/audio/audio.cpp:386 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[23:31:57.761 UTC] src/audio/audio.cpp:400 : Debug: Opened audio output "Built-in Audio Analog Stereo"
[23:32:00.554 UTC] src/widget/form/chatform.cpp:413 : Debug: onAnswerCallTriggered
[23:32:00.555 UTC] src/core/coreav.cpp:195 : Debug: "answering call 7"
[23:32:00.567 UTC] src/widget/form/chatform.cpp:323 : Debug: onAvStart
[23:32:00.782 UTC] src/audio/audio.cpp:669 : Debug: Audio source 3 created. Sources active: 1
```

When I open settings:

```
AL lib: (WW) FreeContext: (0x33cb180) Deleting 1 Source(s)
[23:32:36.443 UTC] src/audio/audio.cpp:548 : Debug: Closing audio output
AL lib: (WW) FreeDevice: (0x341f450) Deleting 4 Buffer(s)
[23:32:36.444 UTC] src/audio/audio.cpp:386 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[23:32:36.446 UTC] src/audio/audio.cpp:400 : Debug: Opened audio output "Built-in Audio Analog Stereo"
[23:32:36.450 UTC] src/audio/audio.cpp:345 : Debug: Opening audio input "Built-in Audio Analog Stereo"
[23:32:36.452 UTC] src/audio/audio.cpp:369 : Debug: Opened audio input "Built-in Audio Analog Stereo"
[23:32:36.453 UTC] src/widget/form/settings/avform.cpp:351 : Debug: available Modes:
[23:32:36.453 UTC] src/widget/form/settings/avform.cpp:365 : Debug: selected Modes:
[23:32:36.453 UTC] src/audio/audio.cpp:298 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[23:32:36.463 UTC] src/audio/audio.cpp:669 : Debug: Audio source 2 created. Sources active: 1
```

**Comment by Diadlo** [comment] 2016-09-24 07:27
Seems, duplicate of #3538, so it will be closed. Please comment if it isn't

**Closed as completed by Diadlo** 2016-09-24 07:27 UTC
Labels: U-low
