### ISSUE TITLE
move the cancel file transfer button

### ISSUE THREAD

**Issue by Tempy111** [qTox/qTox#3680] opened 2016-09-03 09:06 UTC
OS: Windows 10
qTox: 1.5.1-8-gfd04a28

Suggestion about Relocating the Cancel file transfer button from under the accept button to next to it.

While it's partly the fault of the user, it is easy to go to click on Accept as a new message comes in from the other person which means instead of clicking on 'accept', you click on decline. it's a bit annoying ^_^

**Comment by antis81** [comment] 2016-09-03 10:10
This is a duplicate of #2597 -> closing.

**Closed as completed by antis81** 2016-09-03 10:10 UTC
Labels: U-low
