### ISSUE TITLE
Groupchat peer list layout is badly broken

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#988] opened 2015-01-06 10:15 UTC
Picrelated.

![](http://a.pomf.se/hycsab.png)

**Comment by zetok** [comment] 2015-01-06 13:18
duplicate of #919?

Edit: it's not really broken, if one doesn't count layout. Someone just set their nick to something long.

**Comment by agilob** [comment] 2015-01-06 14:15
@zetok no it's a duplicate of #752 which I broke some time ago ;)

It's fixed [here](https://github.com/tux3/qTox/pull/989)

**Closed as completed** 2015-01-15 07:50 UTC
