### ISSUE TITLE
Cleared messages come back after program is restarted

### ISSUE THREAD

**Issue by Kelvets** [qTox/qTox#6199] opened 2020-07-30 15:45 UTC
##### Brief Description

OS: Windows 10
qTox version: 1.17.2
…

Reproducible: Always

##### Steps to reproduce

1. Clear the messages of any conversation
2. Exit qTox
3. Log into your qTox again
4. The cleared messages will be displayed again. Makes the clear function pretty pointless.

##### Observed Behavior
Cleared messages reappear

##### Expected Behavior
Cleared messages are removed from the chat history. On this note, there should be an option to clear individual messages rather than the whole conversation.

**Comment by anthonybilinski** [comment] 2020-07-31 20:32
"Clear displayed messages" by design only removes them from view and not from history. I think this is still useful on its own e.g. if people can see your screen where you are and don't want them to be able to read past text, but don't want to delete your history for later either.

In terms of actually deleting history, the only options that are currently supported are:
1. Right click on friend in friend list -> Show details -> Remove history
1. When removing a friend there's an option to remove history.
1. In Settings -> Privacy there's an option to not store chat history. When this is unchecked an option to delete all current history is presented.

From https://github.com/qTox/qTox/issues/6200 it sounds like you want to delete just partial history, in which case I think like https://github.com/qTox/qTox/issues/6200 mentioned a way to do it per message is a better option than doing it based on all text that is currently visible like "Clear chat history" does.

I agree that that would be a nice feature to add.

**Comment by SlugFiller** [comment] 2020-08-04 21:06
> Makes the clear function pretty pointless.

It conserves memory. If you tend to leave your computer and qTox on for days, having a chat log that grows endlessly could harm performance significantly. Even if you don't, simply loading the chat log too far back, or using the search feature to look for a very old message, could leave you in a situation where, without "Clear displayed messages", your only recourse would be to restart qTox, or wait seconds, or even minutes, every time you switch between chats.

**Comment by anthonybilinski** [comment] 2020-08-09 22:22
I'll close this and keep #6200 around to track the feature of deleting partial history, which seems like it accomplishes the same thing. Let me know if you think that doesn't solve the same problem, @Kelvets.

**Closed as completed by anthonybilinski** 2020-08-09 22:22 UTC
