### ISSUE TITLE
Ability to use in-built qTox desktop notifications rather than system ones

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2884] opened 2016-01-28 16:05 UTC
Though the desktop notifications which are built-into the system that I use (Ubuntu GNOME 15.10 with GNOME 3.18) look rather nice, I think that it would be good if at least the user had the option to use qTox built-in notification which appear somewhere like the bottom-right-hand-end of the screen like with Skype. Though this is probably a low priority feature request, I think it would look quite nice if qTox had its own built-in notification system, one that maybe would even display more information than is in the built-in system ones, such as part of the content of a received message. Anyway, I think this would look quite nice, but of course would be optional, though probably on by default.

**Comment by zetok** [comment] 2016-01-28 17:21
It's kinda a duplicate of https://github.com/tux3/qTox/issues/483#issuecomment-59753519, thus closing.

**Closed as completed by zetok** 2016-01-28 17:21 UTC
Labels: U-low
