### ISSUE TITLE
Filter audio in qTox is broken

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2504] opened 2015-11-06 09:11 UTC
Hello,

since the merge of ToxAV, the filter audio function is broken in qTox.
You can activate it but the audio is awfully ugly then.

Also tested it with uTox and it works fine - it seems only to be a qTox issue.

**Comment by TheNain38** [comment] 2015-11-07 12:56
Maybe it is caused because now, microphone's gain can be modified? Maybe, the filtering is not done at the right moment.

**Comment by rugk** [comment] 2015-11-09 19:31
Duplicate of https://github.com/tux3/qTox/issues/2504?

**Comment by ovalseven8** [comment] 2015-11-09 19:44
@agilob: Why are you closing this issue? It's not a duplicate of #1565.

**Comment by antis81** [comment] 2015-11-09 21:32
Hey guys. ~~This behaviour is likely to be caused by timer based reading of audio input.~~ Reading now happens within the `Audio` class. I'll address and fix this in #2509.

**EDIT:** Found, that the buffers were setup with wrong size -> fixed in the above mentioned PR!

**Comment by TheNain38** [comment] 2015-11-09 21:34
@antis81 Cool! Thank you very much!

**Comment by antis81** [comment] 2015-11-21 10:46
@TheNain38 Could you compile and check #2509 please?

**Comment by TheNain38** [comment] 2015-11-21 11:29
@antis81 It is fixed, thanks. But I've observed another bug, if I go to the audio/video settings the sound is buggy and it wasn't that buggy than before

**Comment by TheNain38** [comment] 2015-11-21 11:37
Uh, nevermind... I think it was because I was testing using my virtual machine and my pc, with the same devices... Because when testing with someone else I don't have this bug

**Comment by antis81** [comment] 2015-11-21 11:51
@TheNain38 It was actually reproducible on my machine -> fixed it once and for good… :)

**Closed as completed** 2015-12-04 17:20 UTC
Labels: C-bug, M-audio
