### ISSUE TITLE
Unity tray icon does not stop blinking unless main window gets focussed (Multiple windows mode)

### ISSUE THREAD

**Issue by ByteCommander** [qTox/qTox#2316] opened 2015-09-28 18:51 UTC
I have set **Multiple windows mode** in `qtox-unity` on Ubuntu 15.04, so that the left main window (contact list) and chat/settings windows are separated and independent of each other.

Now when have the main window and a chat window open, both are not focussed and in background, the tray icon starts blinking when I receive a message (of the user in my open chat window). But when I now click on the chat window so that it gets focussed, the blinking tray icon does not stop! Same if the main window is closed and only the chat window is open in background.

The blinking only stops when I (open, if necessary, and ) focus the main window.

**Proposed attempt to fix:**
Don't switch the tray blinking off when the main window gets focussed, but when the respective chat window gets focussed.

**Comment by FabrizioMarana** [comment] 2015-09-28 19:06
Same here.  

lsb_release --short --codename&&uname --kernel-release 
trusty
3.13.0-63-generic

Commit hash: 42c29c8b8fa5e719c9c78c15f109b358c9225c0c

Any other info you need: shout!

**Comment by zetok** [comment] 2015-09-28 19:55
This looks like a duplicate of #2211

**Comment by zetok** [comment] 2015-09-29 07:04
Closing, since it's a duplicate.

**Closed as completed by zetok** 2015-09-29 07:04 UTC
Labels: C-bug, U-low, OS-linux, P-low, M-ui
