### ISSUE TITLE
qtox portable can not write received files anywere

### ISSUE THREAD

**Issue by zoff99** [qTox/qTox#4034] opened 2017-01-02 09:12 UTC
##### Brief Description

OS: Windows
qTox version: https://build.tox.chat/job/qTox_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86-64_release.zip
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always

##### Steps to reproduce

1. recevie a file
2. try to save it anywhere

##### Observed Behavior
message says can not write to that directory

##### Expected Behavior
should be able to write somewhere

**Comment by zetok** [comment] 2017-01-02 09:52
Version of qTox, windows, other info?

**Comment by zoff99** [comment] 2017-01-02 11:12
![unbenannt](https://cloud.githubusercontent.com/assets/6833516/21588259/644cd4ea-d0e5-11e6-829e-43de71aec79a.PNG)
https://build.tox.chat/job/qTox_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86-64_release.zip

this version from just now
32bbdb2b9857341f7230b88114f6a07e62113e3e

windows 7

**Comment by zoff99** [comment] 2017-01-02 11:19
```
[11:16:07.987 UTC] core/corefile.cpp:323 : Debug: "Received file request 0:65536 kind 0"
[11:16:08.022 UTC] chatlog/content/filetransferwidget.cpp:133 : Warning: Cannot write to  "C:/Users/xxx/qtoxsave2/01-20170102_10:28:41.avi"
[11:16:08.051 UTC] core/corefile.cpp:323 : Debug: "Received file request 0:131072 kind 0"
[11:16:08.051 UTC] core/corefile.cpp:323 : Debug: "Received file request 0:196608 kind 0"
[11:16:08.057 UTC] chatlog/content/filetransferwidget.cpp:133 : Warning: Cannot write to  "C:/Users/xxx/qtoxsave2/02-20170102_10:15:14.avi"
[11:16:08.062 UTC] chatlog/content/filetransferwidget.cpp:133 : Warning: Cannot write to  "C:/Users/xxx/qtoxsave2/10-20170102_10:20:41.avi"
```

**Comment by zetok** [comment] 2017-01-02 11:26
What are the permission in the dir you're trying to save, and as which user is qTox running as?

**Comment by zoff99** [comment] 2017-01-02 11:44
i have created that directory with the same user as running qtox. also i can not save to any directory on any drive.
maybe its the ":" in the filenames? or something like that

**Comment by zetok** [comment] 2017-01-02 11:48
>maybe its the ":" in the filenames? or something like that

Oh, right. Sometimes I forget how stupid windows' limitations are.

Duplicate of #1304, thus closing.

**Closed as completed by zetok** 2017-01-02 11:48 UTC
Labels: C-bug, U-low, OS-windows
