### ISSUE TITLE
Nickname shouldn't be empty

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2112] opened 2015-08-25 15:37 UTC
Hello,

at the moment it's possible to have an empty nickname. I think it's not a great solution, a fallback would be better at my point of view.

Currently, when you join a groupchat your name is 'Tox User' then in the groupchat if your nickname is empty.

**Comment by ovalseven8** [comment] 2015-08-25 15:38
Same issue here: https://github.com/Antidote-for-Tox/Antidote/issues/142

**Comment by zetok** [comment] 2015-08-25 17:03
Why user shouldn't be allowed to set an empty name?

**Comment by agilob** [comment] 2015-08-25 17:04
If it's common for all clients isn't it a toxcore issue?

**Comment by ProMcTagonist** [comment] 2015-08-25 17:22
Why should the user be prohibited from setting an empty name?

**Comment by ovalseven8** [comment] 2015-08-25 18:42
Well, I can also live with the current situation if it's fine for you.
But the fallbacks should be homogeneous for all Tox clients -> https://github.com/Antidote-for-Tox/Antidote/issues/142

I think here we need a decision, then.

**Comment by zetok** [comment] 2015-08-25 18:57
Uuh, looks like we've got a bit of misunderstanding here. I thought that `nickname` is used to refer to `name`, whereas it apparently was used in linked Antidote's issue to refer to `aliases`.

Closing issue, since qTox handles empty aliases correctly.

# 

@agilob BTW, since there was confusion and we've talked about change to the way `names` are being handled - user being able to set empty `name` is a correct behaviour, by design.

**Closed as completed by zetok** 2015-08-25 18:57 UTC

**Comment by ovalseven8** [comment] 2015-08-26 13:01
At the moment, if you've an empty nickname:
- In group peer list you're known as 'Tox User'
- If somebody is writing something, EVERY message is highlighted for you. > not good solution
- If there are two peers in group with an empty name it seems like it doesn't work well. Only one peer is highlighted on top (group peer list). One peer listens to 'Tox User' and one peer listens to every message. Bug.

How should we handle empty names in future? @tux3 @TheSpiritXIII @zetok

**Comment by zetok** [comment] 2015-08-26 13:49
> In group peer list you're known as 'Tox User'

Yes, that's the desired behaviour.

> If somebody is writing something, EVERY message is highlighted for you. > not good solution

That's actually a separate problem, mind opening an issue with it?

> If there are two peers in group with an empty name it seems like it doesn't work well. Only one peer is highlighted on top (group peer list). One peer listens to 'Tox User' and one peer listens to every message. Bug.

Not a bug - if someone sets an empty name, it's their problem.

**Comment by ovalseven8** [comment] 2015-08-26 14:51
> Not a bug - if someone sets an empty name, it's their problem.

No, it seems qTox has problems with empty nicknames and nicknames that are more than once in a groupchat. But it will be fixed with the new groupchat, hopefully. :wink:
