### ISSUE TITLE
Bogus 'locked profile' messages

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4073] opened 2017-01-11 21:35 UTC
After qTox finishes ungracefully, it sometimes complains about the locked profile when restarted. The problem is this file: ~/.config/tox/{user}.tox.p33979

I think 33979 above is pid. It should only create a warning message when this pid is alive locally. When it is dead the file should be deleted.

Another improvement is to add the hostname to this file name. If my hostname isn't the same as the file's hostname qTox should still warn, in case some other host uses this tox account.

**Comment by zetok** [comment] 2017-01-11 22:16
Duplicate of #3129, thus closing.

**Closed as completed by zetok** 2017-01-11 22:16 UTC
Labels: U-low
