### ISSUE TITLE
[Feature request] Possibility to save group and his history

### ISSUE THREAD

**Issue by tele1** [qTox/qTox#4456] opened 2017-06-10 16:26 UTC
Possibility to save and remove  group and his history,

To write with people in next day,
because in my qTox v1.6.0-obs after reboot not have groups.

**Comment by Diadlo** [comment] 2017-06-10 16:35
Seems, duplicate of #896, so it will be closed. Please comment if it isn't

**Comment by Diadlo** [comment] 2017-06-10 16:36
Also, it's WIP TokTok/c-toxcore#295

**Closed as completed by Diadlo** 2017-06-10 16:35 UTC
Labels: U-low, upstream
