### ISSUE TITLE
Accessibility Issue for Screen Reader Users

### ISSUE THREAD

**Issue by Deyce1988** [qTox/qTox#1215] opened 2015-02-17 22:29 UTC
The QTox Windows Client is not accessible for Users with Assistive Technologies.
See: http://qt-project.org/doc/qt-4.8/accessible.html

**Comment by tyrylu** [comment] 2015-02-21 07:53
Or consider upgrading to the latest QT5 version, there were some substantial accessibility improvements and the entire qtaccessibblewidgets stuff was simplified.

**Comment by sudden6** [comment] 2015-08-22 14:05
duplicate of https://github.com/tux3/qTox/issues/300?

**Closed as completed** 2015-08-22 14:20 UTC
Labels: U-low, proposal, P-high, O-need-info
