### ISSUE TITLE
qTox closes to tray even if the option is not enabled

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1281] opened 2015-02-25 18:02 UTC
Happens when it can't go online.

**Comment by tux3** [comment] 2015-02-25 18:13
I can't reproduce. Can you actually open it back after it closed to tray ?

**Comment by suhr** [comment] 2015-02-26 03:18
This happens together with https://github.com/tux3/qTox/issues/953 (yes, it is actually not fixed). Rare bug that can be fixed by removing some files in tox directory. I really don't know how to reproduce this.

>  Can you actually open it back after it closed to tray ?

Yep.

**Comment by PKEv** [comment] 2015-05-17 07:31
this problem is already fixed?

**Comment by agilob** [comment] 2015-05-17 07:49
No, I disabled close to tray and closed qtox. worked as expected.

**Comment by PKEv** [comment] 2015-05-17 07:52
I can't repeat in Windows 7

**Comment by agilob** [comment] 2015-05-17 07:58
fixed in #1619

**Closed as completed** 2015-05-17 12:29 UTC
Labels: C-bug
