### ISSUE TITLE
Infinite recursion on changeGroupTitle attempt

### ISSUE THREAD

**Issue by tobeaver** [qTox/qTox#4803] opened 2017-11-13 12:14 UTC
```
./src/widget/widget.cpp
1862 connect(newgroup, &Group::titleChanged, core, &Core::changeGroupTitle);

./src/core/core.cpp
695 void Core::changeGroupTitle(int groupId, const QString& title){
//...
700    if (success && error == TOX_ERR_CONFERENCE_TITLE_OK) {
701        emit groupTitleChanged(groupId, getUsername(), title);

./src/nexus.cpp
226    connect(core, &Core::groupTitleChanged, widget, &Widget::onGroupTitleChanged);

./src/widget/widget.cpp
1752 void Widget::onGroupTitleChanged(int groupnumber, const QString& author, const QString& title)
//...
1773 g->setName(title);

./src/model/group.cpp
69 void Group::setName(const QString& name)
//...
73        emit titleChanged(groupId, title);
```

**Comment by Diadlo** [comment] 2017-11-13 12:23
Thanks. Duplicate of #4800

**Comment by sudden6** [comment] 2017-11-13 12:23
@Diadlo I guess this will also be fixed in https://github.com/qTox/qTox/pull/4801?

**Comment by sudden6** [comment] 2017-11-13 12:23
Seems I'm too slow^^

**Closed as completed** 2017-11-13 12:23 UTC
Labels: C-bug, U-low
