### ISSUE TITLE
No application file in distributive

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#3801] opened 2016-10-09 19:29 UTC
in archive by link: 64 bit portable (https://build.tox.chat/job/qTox_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86-64_release.zip)
no file of application

**Comment by Diadlo** [comment] 2016-10-09 19:50
Seems duplicatoe of closed (why?) #3557

**Comment by sudden6** [comment] 2016-10-09 22:51
I closed it because when I checked, the build contained an executable. Maybe this problem happens only to some builds?

**Comment by rodolpheh** [comment] 2016-10-25 07:58
Could you reopen it ? It seems that the executable is not present since the last four builds (since October 15th).

**Comment by initramfs** [comment] 2016-10-25 10:11
@rodolpheh Issue confirmed. The issue seems to be that when Jenkins fails a compile, it doesn't quit out, listing it as a successful compile. As such, when packaging no qtox.exe is available since it doesn't exist.

The current issue stems from commit abaa41e which removes RTTI. Unfortunately one instance of code requiring RTTI still existed and didn't play well with the compiler on Jenkins. PR #3830 fixes this issue.

**Comment by zetok** [comment] 2016-10-25 10:15
> The issue seems to be that when Jenkins fails a compile, it doesn't quit out, listing it as a successful compile. As such, when packaging no qtox.exe is available since it doesn't exist.

@nurupo / @optimumtact could you fix that?

**Comment by initramfs** [comment] 2016-10-25 10:20
@zetok I submitted issue #3831 to track that problem since this issue will get autoclosed as soon as PR #3830 gets merged.

**Comment by nurupo** [comment] 2016-10-26 08:10
@zetok replied in https://github.com/qTox/qTox/issues/3831

**Closed as completed** 2016-10-26 09:33 UTC
Labels: M-packaging, OS-windows
