### ISSUE TITLE
Please give us an option to disable the icon blinking

### ISSUE THREAD

**Issue by roranicus** [qTox/qTox#3203] opened 2016-04-25 21:36 UTC
##### Brief Description

OS: Linux Mint 17.3, Xfce edition
qTox version: v1.4.0-1-gfa5ee5b
Commit hash:  fa5ee5b1adbfa2cfde3595cdee1a42ca4cac8a11
toxcore:  0.0.0
Qt:  5.5.1

…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
##### Steps to reproduce
1. Minimize qTox to the taskbar
2. Wait for someone to send a message
3. Notice the Tox icon flashes yellow, indicating there is a message
##### Observed Behavior

The icon gives notification that a message is received
##### Expected Behavior

An option to disable this notification. It's annoying and breaks workflow. I get that some people want their messenger to notify them when a message is received, but it it extremely annoying to others. Any type of notification should be easy to disable

**Comment by zetok** [comment] 2016-04-26 04:40
Duplicate of #3064, thus closing.

**Closed as completed by zetok** 2016-04-26 04:40 UTC
Labels: U-low
