### ISSUE TITLE
Echo during call which only I can hear

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2778] opened 2016-01-07 20:19 UTC
When I called someone today on qTox although they had setup their audio settings properly, and so had I, I could hear an echo of my own voice slightly distorted almost immediately after I spoke, though I was the only one who could hear it. Apart from that, they also sounded a bit like a robotic sheep from time-to-time, but at least they didn't sound like a Dalek (that issue I reported and was fixed).

---

**OS Information:**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Flavour: GNOME
GNOME Version: 3.18
```

**Package Information:**

```
qtox:
  Installed: 414-e952d1a
  Candidate: 414-e952d1a
  Version table:
 *** 414-e952d1a 0
        500 https://pkg.tox.chat/debian/ nightly/release amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by antis81** [comment] 2016-01-08 04:31
@SeventhSonOfASeventhSon Yeah, this is a known issue (see #2756). I'm working on this in #2768. If you like to help improving the audio concept by reviewing the code I'd be more than happy.

@agilob @tux3 
Apart from physical sources, the echo (and probably other "buggy effects" like pitched voce etc.) origins from the "input gain" implementation (this scary thing with the "400" max. value). This actually alters audio data (which it never should!), before sending them via tox api, adding some spooky `pow(vol^2)` to the buffer data which makes things uncontrollable (keep in mind, that both sides are sending the **altered** data). I didn't find a way to control the input gain directly via OpenAL. Initially I thought of applying an audio source and create an input device context (just like with output device context), but this is not allowed (Error 40961: Invalid Device). Further, setting the volume requires the audio device to be opened/initialized. Would be great, if you could also have a look at #2768.

**Comment by zetok** [comment] 2016-01-08 08:59
Since it's a duplicate of #2756, closing.

**Closed as completed by zetok** 2016-01-08 08:59 UTC
Labels: U-low
