### ISSUE TITLE
No way to resize nickname column in chat

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#514] opened 2014-10-23 19:59 UTC
Sometime the nickname column is too small in chat, especially on high DPI displays.

**Comment by zetok** [comment] 2015-08-21 06:10
Done in #2013, should be closed after PR will be merged.

**Comment by anthonybilinski** [comment] 2022-02-19 12:55
If this is talking about the friend list column, it is currently resizable.
If it's talking about the author column in group chats, duplicate of https://github.com/qTox/qTox/issues/635.
Either way, closing.

**Closed as completed** 2022-02-19 12:57 UTC
Labels: P-low, M-ui, U-high, proposal-accepted
