### ISSUE TITLE
synchronisation between devices

### ISSUE THREAD

**Issue by 71GA** [qTox/qTox#6363] opened 2021-08-19 12:14 UTC
Currently I can't see any synchronisation between devices. Can it be done?

**Comment by anthonybilinski** [comment] 2021-08-19 19:00
Unfortunately it's currently not supported, but is a long term goal.

It's possible to copy your profile and history between devices, but you can only be connected with one of the copies at a time or else the two instances will basically fight each other and your friends will see your flick off/online and deliver half of their messages to each.

The normal use case for now is to use a new profile on each device.

**Comment by anthonybilinski** [comment] 2021-09-23 07:49
Closing as duplicate of https://github.com/qTox/qTox/issues/5634.

**Closed as completed by anthonybilinski** 2021-09-23 07:49 UTC
