### ISSUE TITLE
UI/refactor discussion

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3903] opened 2016-11-21 12:04 UTC
https://github.com/qTox/qTox/milestone/6
https://github.com/qTox/qTox/pull/3639#issuecomment-261916356

@antis81 
>I am closing this one and treat development, as if it was a usual feature PR with a single commit. It is not possible to perform this rather important step without "breaking" master!

As has been said before: @Diadlo seems to be doing just fine moving stuff from UI/refactor in small chunks to master, so it's not impossible. With that in mind, even those small chunks could introduce regressions.

>We should really think about stabilizing the master branch and work with a development branch, where all the work for the next milestone goes into.

This probably wouldn't work, and in the end would result in more stuff not getting merged. Like it happened plenty of times with large changesets.

Master is stable. There is also no problem with having a development branch.

The only problem that could exist, is suggesting people to base their changes on development branch. That is, as long as development branch introduces regressions. Which would be the case for ~whole time that it would exist, and only would change when it gets merged to master (and shortly before that).

**Comment by Diadlo** [comment] 2016-11-21 19:59
@antis81 
>  usual feature PR with a single commit

Better describe `usual feature` not as `single commit` , but `less, than few changes`.
Problem not in amount of commits. The problem is that it's impossible to review this PR.

**Comment by Diadlo** [comment] 2017-08-05 19:35
Most part was merged

**Closed as completed by Diadlo** 2017-08-05 19:35 UTC
Labels: C-discussion
