### ISSUE TITLE
Need better notifications (of both messages and contact status)

### ISSUE THREAD

**Issue by Delocca** [qTox/qTox#3859] opened 2016-11-06 11:25 UTC
My biggest issue with qTox is that I miss messages due to the lack of visual notifications and I have to keep the contacts window open to see if friends connect.

I've checked all the notification options you already have but it's not enough. 
For new messages, I'd like to have blinking tray icon and desktop notification.
For contact connection, I'd like a sound and desktop notification.

Thanks!

**Comment by Diadlo** [comment] 2016-11-06 11:56
Duplicate of #483 and #3696
And blinking icon already implemented

**Closed as completed by Diadlo** 2016-11-06 11:56 UTC
Labels: U-low
