### ISSUE TITLE
No settings are saved (new API version)

### ISSUE THREAD

**Issue by Draako** [qTox/qTox#1549] opened 2015-04-28 00:24 UTC
No settings can be saved unless qTox is run as admin. Windows 7 64-bit. I could save any setting I wanted with previous builds.

**Comment by tux3** [comment] 2015-05-07 20:11
Did you accidentally break the permissions in the qTox save folder (%APPDATA%/tox) ?

Can you open that folder and just create a text file in explorer.exe?

**Comment by Draako** [comment] 2015-05-07 20:16
> Can you open that folder and just create a text file in explorer.exe?

With ease.

**Comment by tux3** [comment] 2015-05-07 20:42
Alright, thanks. Could you post the qtox.log to see if something strange is happenning?

**Comment by Draako** [comment] 2015-05-07 20:48
No need for that. I've just upgraded from a few days old build to the newest one and that did the trick. I still have that log from a few days old build if you want it.

**Comment by tux3** [comment] 2015-05-07 20:55
Yes, please. Even if it's the kind of bug that disappears magically, I'd like to try and find the root cause if I can :)

**Comment by Draako** [comment] 2015-05-07 21:05
The bug strikes back. I wanted to check one more option and after restarting I couldn't make any change.

Here's that log:

https://mega.co.nz/#!MVtxnSxZ!NbDBKl_JWNnj0u07cjT5hcXLv023XJkkWlCSG0LQ9gg

**Comment by tux3** [comment] 2015-05-07 21:22
@Draako do you have the "Make qTox portable" option checked in the settings?

**Comment by Draako** [comment] 2015-05-07 21:27
It's unchecked with qTox in `D:\PROGRAMS\qTox\bin`.

**Comment by zetok** [comment] 2015-08-28 14:37
Is this bug fixed? And if so, shouldn't it be closed?

**Comment by agilob** [comment] 2015-08-29 16:10
I'm closing this because it was related to migration to new toxcore api and no one else reported it.

**Closed as completed by agilob** 2015-08-29 16:10 UTC
Labels: C-bug, O-need-info
