### ISSUE TITLE
How long qtox estimate will be stable?

### ISSUE THREAD

**Issue by dcapeletti** [qTox/qTox#2808] opened 2016-01-16 12:55 UTC
I would ask if a developer has an estimated to be stable qtox time. Thank you

**Comment by tux3** [comment] 2016-01-16 13:08
I would estimate it will take a couple months to iron out the remaining bugs in our stable branch, then we can focus on stabilizing new features from master.

**Comment by ovalseven8** [comment] 2016-01-16 13:16
First of all, it depends on how you define "stable".

At the moment, qTox is far from being solid from my point of view. There are a lot of open and important issues, the code hasn't been reviewed yet and it is important to know that toxcore isn't stable as well.
So, perhaps you can call qTox alpha software. But it doesn't really matter.

All in all, a software will never be done at all.
The problem is that the project has far too few developers, unfortunately.

**Comment by dcapeletti** [comment] 2016-01-16 17:30
Too bad there are few developers in a project as interesting as qtox.
Define a "stable release" as that version that can be used for production use. That is, it meets the requirements for which it was designed and all features work well.
For example, program security, chat and video call works as expected on all platforms. Users can work in peace and without cuts in the calls.

I think qtox should focus on audio and video calls, make them work well on all platforms.

**Comment by antis81** [comment] 2016-01-17 00:12
@dcapeletti I'm currently working on the audio topic, which is loosely bound to video. I know this is currently not really usable. At least we have a stable concept base now to build upon. Most harmful problems (echo, volume control, …) with audio will be fixed, when #2768 leaves WIP status. Group calls are not yet functional. Depending on available time, this will take a couple of days/weeks for me to implement.

**Comment by dcapeletti** [comment] 2016-01-17 16:02
@antis81 That good news just given me, glad you could make this a useful tool for customer calls. Ojala is illuminated to do the hard work. I wish I could do, I love qtox, but I am unable at the moment.

**Comment by ddobrev** [comment] 2016-01-22 16:11
I can definitely confirm that stability is what's crucial at the moment. Just chat with history and audio cover at least 80 % of all usage. What really prevents the client from getting more popular is not the lack of features but issues such as https://github.com/tux3/qTox/issues/2820, silent crashes while just staying idle, occasional crashes when making audio calls and usability problems such as https://github.com/tux3/qTox/issues/2836.

**Comment by dcapeletti** [comment] 2016-01-23 14:32
I agree with @ddobrev that stability is essential at this time. The features are fine, but we need stability.

**Comment by Diadlo** [comment] 2017-05-08 19:50
1) **No one can say for sure how long** (no one know)
2) Currently whole tox project is [experemental](https://github.com/TokTok/c-toxcore#-1)
3) There is many problem with project structure and architecture. It's problem №1 for me (AFAIK for others maintainer too) now

**Closed as completed by Diadlo** 2017-05-08 19:50 UTC
Labels: C-question
