### ISSUE TITLE
Default option: writing chat history option enabled

### ISSUE THREAD

**Issue by KasperGreen** [qTox/qTox#4654] opened 2017-09-18 13:20 UTC
Writing chat history by default it is not sequre practice. If chat opponent device disclosed this discloing all users who chatting with him.

P.S. Sory my english 

##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment] 2017-09-20 09:32
Duplicate of https://github.com/qTox/qTox/issues/1479

**Closed as completed** 2017-09-20 11:52 UTC
