### ISSUE TITLE
qTox portable - profile location on first start

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3547] opened 2016-07-24 11:23 UTC
##### Brief Description

We should have a possibility to create a profile in qtox folder when it is in portable mode and this mode can be chosen without profile creation.

OS: Windows
qTox version: v1.4.0-332-geb1e009  
Commit hash: eb1e0091c420caec8f8e3492b6abb78400cf348b 
toxcore: 0.0.0
Qt: 5.5.1

Reproducible: Always
##### Steps to reproduce
1.  Download https://build.tox.chat/job/qTox_build_windows_x86_release/lastSuccessfulBuild/artifact/qTox_build_windows_x86_release.zip
2. Unpack it.
3. Run qtox.exe
4. Create new profile.
##### Observed Behavior
1. qtox create first profile in _%APPDATA%\Roaming\tox_ folder.
2. qtox does not copy profile files to its folder before restart, after `Make Tox portable` option is chosen.
3. qtox does not delete created profile files from _%APPDATA%\Roaming\tox_ folder after `Make Tox portable` option is chosen and restart.
##### Expected Behavior
1. qtox should permit to make it portable without load a profile.
2. Or qtox should look if _tox_ folder exist in its executables folder and create profile files in it. Please see issue #3545.
3. qtox should copy profile files to its folder before restart, after `Make Tox portable` option is chosen.
4. qtox should delete created profile files from _%APPDATA%\Roaming\tox_ folder after `Make portable` option is chosen.
##### Workarounds:
1. Create qtox.ini file with the following content, before first start: 
   
   <pre>
   [%General]
   makeToxPortable=true
   </pre>
2. Create junction in Windows, before first start:
   
   <pre>
   cd qtox
   :: Windows XP
   :: (will not work, please see: https://github.com/tux3/qTox/issues/3548)
   :: junction.exe %APPDATA%\tox .
   junction.exe %USERPROFILE%\AppData\Roaming\tox .
   ::
   :: Windows Vista and above
   mklink /J %APPDATA%\tox .
   </pre>
3. Create first profile and then chose `Make Tox portable` option:
   - Create first profile and load it.
   - Chose `Make Tox portable` option.
   - Log out from this profile.
   - Remove first created profile.
   - Create your first profile for using.

**Comment by zetok** [comment] 2016-07-24 11:27
> qtox should delete created profile files from %APPDATA%\Roaming\tox folder after Make Tox portable option is chosen and restart.

No. Removing any data when not explicitly done by user is wrong. What should be done instead, is simply not creating profile in %APPDATA%` if portable setting is set.

**Comment by Diadlo** [comment] 2016-07-29 12:44
Duplicate of #2802?

**Comment by zetok** [comment] 2016-07-29 18:37
Yep, thanks; closing.

**Closed as completed by zetok** 2016-07-29 18:37 UTC
Labels: U-low, proposal
