### ISSUE TITLE
UDP check box is disabled without explanation

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5602] opened 2019-03-31 21:47 UTC
OS: FreeBSD

qTox is installed from the port.
When a major feature is disabled, it should be explained, either near the checkbox, or in its tooltip.

![screenshot](https://user-images.githubusercontent.com/271906/55295585-a3012480-53c3-11e9-8556-1044193bb67b.png)

**Comment by anthonybilinski** [comment] 2019-03-31 21:53
This sounds like a duplicate of https://github.com/qTox/qTox/issues/5311 which was fixed in https://github.com/qTox/qTox/pull/5313, merged as a2c44cbeda247bf06953a641d8d745fd0d3df62c. What hash of qTox are you running?

**Comment by yurivict** [comment] 2019-03-31 22:11
It's version ```1.16.3```.

**Comment by anthonybilinski** [comment] 2019-03-31 22:25
Ok, this has been fixed since v1.16.3, so no action is required.

To work around the issue you can select "Proxy type" to "None" (currently it's blank, which is the bug), and then you'll be able to check "Enable UDP" again. If no change is made, it will fix itself on next update.

**Closed as completed by anthonybilinski** 2019-03-31 22:25 UTC
Labels: U-low, O-need-info
