### ISSUE TITLE
Delete/correct/reorder offline messages

### ISSUE THREAD

**Issue by notramo** [qTox/qTox#5322] opened 2018-08-30 07:35 UTC
Since unsent offline messages are stored locally, it would be good if they could be removed from the send queue.
Also, an `edit`  button should be for these messages, which would open the offline message in the composing field at the bottom of the screen, but when the user hits Enter, it wouldn't be placed at the end of the queue, but the message would be updated.
Also changing the order of offline messages could be useful.

**Comment by zetok** [comment] 2018-10-01 16:49
Duplicate of #1306, thus closing.

**Closed as completed by zetok** 2018-10-01 16:49 UTC
Labels: U-low, proposal, M-ui
