### ISSUE TITLE
qTox deleted my circles

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1931] opened 2015-06-29 11:11 UTC
I don't know why, I don't know how but I closed qTox before to sleep and when I logged this morning my circles were gone :/

**Comment by TheSpiritXIII** [comment] 2015-07-01 13:18
I have had my circles deleted when I switched branches or used an older qTox version. This is possibly because the setting files were incompatible. Maybe this could be the reason?

**Comment by zetok** [comment] 2015-08-30 09:31
Is this still reproducible?

**Comment by zetok** [comment] 2015-09-10 14:18
No answer, assuming that it was fixed, thus closing.

**Closed as completed by zetok** 2015-09-10 14:18 UTC
Labels: C-bug, O-need-info
