### ISSUE TITLE
Memory leak after closing new chat window

### ISSUE THREAD

**Issue by SmoothDude** [qTox/qTox#2217] opened 2015-09-13 11:26 UTC
To reproduce issue:
- Open your favourite task manager (to watch memory growth)
- Launch qtox
- Open new chat window from any contact
- Close it
- Repeat 2 last steps until you notice that some memory still isn't freed after new chat window closed

**Comment by zetok** [comment] 2015-09-14 06:46
Could partially reproduce (after a lot of opening and closing detached window of a contacts).

Memory usage increased from ~77MB to ~81436 KB.

With that being said, when I've tried to continuously open & close same contact, memory stayed at ~81436 KB, (aside from +2MB increase during the time when detached window was open).

Possibly opening & closing other contacts would increase memory usage further.

**Comment by dmshynk** [comment] 2015-09-28 03:26
This issue is apparently caused by a memory leak in QClipboard. See this Valgrind output:
```
559 (48 direct, 511 indirect) bytes in 1 blocks are definitely lost in loss record 10,895 of 11,658
  in AddFriendForm::setIdFromClipboard() in /home/ds/Programming/qTox/src/widget/form/addfriendform.cpp:149
  1: operator new(unsigned long) in /var/tmp/portage/dev-util/valgrind-3.11.0/work/valgrind-3.11.0/coregrind/m_replacemalloc/vg_replace_malloc.c:333
  2: 0x1a5e57f9
  3: QClipboard::text(QClipboard::Mode) const in /usr/lib64/libQt5Gui.so.5.4.2
  4: AddFriendForm::setIdFromClipboard() in /home/ds/Programming/qTox/src/widget/form/addfriendform.cpp:149
  5: AddFriendForm::show(ContentLayout*) in /home/ds/Programming/qTox/src/widget/form/addfriendform.cpp:88
  6: Widget::onAddClicked() in /home/ds/Programming/qTox/src/widget/widget.cpp:640
  7: Widget::init() in /home/ds/Programming/qTox/src/widget/widget.cpp:339
  8: Nexus::showMainGUI() in /home/ds/Programming/qTox/src/nexus.cpp:177
  9: LoginScreen::onLogin() in /home/ds/Programming/qTox/src/widget/loginscreen.cpp:210
  10: QtPrivate::FunctorCall&lt;QtPrivate::IndexesList&lt;&gt;, QtPrivate::List&lt;&gt;, void, void (LoginScreen::*)()&gt;::call(void (LoginScreen::*)(), LoginScreen*, void**) in /usr/include/qt5/QtCore/qobjectdefs_impl.h:500
  11: void QtPrivate::FunctionPointer&lt;void (LoginScreen::*)()&gt;::call&lt;QtPrivate::List&lt;&gt;, void&gt;(void (LoginScreen::*)(), LoginScreen*, void**) in /usr/include/qt5/QtCore/qobjectdefs_impl.h:519
  12: QtPrivate::QSlotObject&lt;void (LoginScreen::*)(), QtPrivate::List&lt;&gt;, void&gt;::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) in /usr/include/qt5/QtCore/qobject_impl.h:143
  13: QMetaObject::activate(QObject*, int, int, void**) in /usr/lib64/libQt5Core.so.5.4.2
  14: /usr/lib64/libQt5Widgets.so.5.4.2
  15: QMetaObject::activate(QObject*, int, int, void**) in /usr/lib64/libQt5Core.so.5.4.2
  16: QWidgetLineControl::processKeyEvent(QKeyEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
  17: QLineEdit::keyPressEvent(QKeyEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
  18: QWidget::event(QEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
  19: QLineEdit::event(QEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
  20: QApplicationPrivate::notify_helper(QObject*, QEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
  21: QApplication::notify(QObject*, QEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
  22: QCoreApplication::notifyInternal(QObject*, QEvent*) in /usr/lib64/libQt5Core.so.5.4.2
  23: /usr/lib64/libQt5Widgets.so.5.4.2
  24: QApplicationPrivate::notify_helper(QObject*, QEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
  25: QApplication::notify(QObject*, QEvent*) in /usr/lib64/libQt5Widgets.so.5.4.2
```

**Closed as completed** 2015-10-23 14:51 UTC
Labels: C-bug, P-low
