### ISSUE TITLE
Use localization if possible

### ISSUE THREAD

**Issue by genodeftest** [qTox/qTox#3925] opened 2016-11-28 23:28 UTC
##### Brief Description

OS: Linux: Fedora 25
qTox version: v1.6.0-38-g5921122
Commit hash:  592112296012a2159f09571bcff93066b8b6f847
toxcore:  dcf2aaa53005060608353b9d66b9917fd7ed18a9 (2016-09-28)
Qt:  5.7.0

Reproducible: Always

##### Steps to reproduce
1.  on a localized system, start qTox. System defaults to German in my case
2.  have a look at UI lanugage

##### Observed Behavior
qTox is not choosing translation automatically

##### Expected Behavior
If translation is available (it is, in my case), choose translation.

**Comment by zetok** [comment] 2016-11-28 23:56
Duplicate of #2758, thus closing.

**Closed as completed by zetok** 2016-11-28 23:56 UTC
Labels: C-bug, U-low
