### ISSUE TITLE
Problem of advanced settings in Fusion style

### ISSUE THREAD

**Issue by broncotc** [qTox/qTox#1216] opened 2015-02-18 04:10 UTC
<p><img src="http://blog.broncotc.com/wp-content/uploads/2015/02/bugjsaogirjgoee.png"></img></p>

In Fusion style, the choices about the storage of chat histories are layouted together, as it shows in the picture.

**Comment by dubslow** [comment] 2015-02-18 04:16
Hmm... does this happen in other languages as well? It could be a Qt issue with the font rendering...?

**Comment by broncotc** [comment] 2015-02-18 10:49
![image](https://cloud.githubusercontent.com/assets/7097407/6245893/15065c38-b79e-11e4-88fd-32e992ca477b.png)
![image](https://cloud.githubusercontent.com/assets/7097407/6245916/3bdf7466-b79e-11e4-8908-89fc8a346f24.png)
![image](https://cloud.githubusercontent.com/assets/7097407/6245924/4e70474a-b79e-11e4-8945-5e2f8c195c61.png)
Yes, it happens. First one is "a language"...
second is mannol
third is english. It seems like it happens everywhere. 
![image](https://cloud.githubusercontent.com/assets/7097407/6245963/ca8f0c80-b79e-11e4-8918-0ef1abdca9e9.png)
This image maybe shows the version.

**Comment by zetok** [comment] 2015-09-18 17:07
Is this still reproducible on newest qTox?

**Comment by TheNain38** [comment] 2015-09-20 18:24
I can't reproduce it on Windows 8.1 64-bit a53f6f2adfff59b28fa27fb522ccff235d7a7e58 in French and English language.

**Comment by zetok** [comment] 2015-09-20 21:37
Well then, since it doesn't appear to be reproducible with Qt 5.5, closing.

**Closed as completed by zetok** 2015-09-20 21:37 UTC
Labels: C-bug, upstream, P-low, M-ui
