### ISSUE TITLE
UI issue: Necessary interface improvements.

### ISSUE THREAD

**Issue by korenevskiy** [qTox/qTox#4536] opened 2017-07-25 23:21 UTC
##### Brief Description

OS: Windows 10 PRO 64
qTox version: 1.11.0
Commit hash:   66b133c8d4a4d8f60e62475b0b56b509527b1488
toxcore:  0.1.9
Qt:  5.6.2
Hardware:  
…

Reproducible: Always
  
##### Expected Behavior
Necessary interface improvements:
.
1...You need to add a function in parameter. In order to reopen the program, the old program was open (unfolded) instead of a new copy of it.
.
2...Add the parameter of the program startup com- mand line, which specifies the user name for which the program window will open with automatic profile download. And if such a profile is already running, then you just need to expand the programm window with his profile.
.
3...Add a floating window, above the system menu, where messages will be displayed, as well as the buttons to answer the call.
.
##### Additional Info
(links, images, etc go here)

----

**Comment by Diadlo** [comment] 2017-07-26 06:18
Use `qtox -h`. Probably, `-p <profile name>` it's what you whant
And seems 3 is duplicate of #2921

**Closed as completed** 2017-07-26 09:51 UTC
Labels: U-low
