### ISSUE TITLE
Paste images as files from clipboard

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3897] opened 2016-11-19 19:42 UTC
##### Brief Description

OS: Windows 7 x64
qTox version: v1.5.1-8-gfd04a28.
Commit hash: fd04a2832aa885d260ded4e476eefcddd49237b3
toxcore version: 0.0.0

Can you please add feature to paste images from clipboard?

I want to get working the following scenario:

1) Open some application.
2) Choose specific window of that application and press Alt + PrintScreen
3) Then press Shift+Ins inside qTox chat area.
4) So image file will be send with image from clipboard.

It is like Skype works.

**Comment by zetok** [comment] 2016-11-19 19:56
Duplicate of #1290, thus closing.

**Closed as completed by zetok** 2016-11-19 19:56 UTC
Labels: U-low
