### ISSUE TITLE
contact ID doesn't exists!

### ISSUE THREAD

**Issue by bitchecker** [qTox/qTox#1346] opened 2015-03-06 12:40 UTC
referencing to https://github.com/tux3/qTox/issues/1345, I also tried to add contacts between them but they are seen to respond both that the ID of the other contact does not exist!

**Comment by bitchecker** [comment] 2015-03-06 12:43
[ update ]

when you click on a contact to copy its ID you get an ID that is not really the user's full tested by clicking on "copy of the ID" or making me send the ID from the contact itself!

**Comment by TheLastProject** [comment] 2015-03-06 17:54
Duplicate of #951.

**Closed as completed** 2015-03-06 21:51 UTC
