### ISSUE TITLE
Segfault when starting on a fresh Debian Stretch install.

### ISSUE THREAD

**Issue by 01BTC10** [qTox/qTox#4156] opened 2017-02-07 20:40 UTC
OS: Debian Stretch
qTox version: v1.6.0-obs.
Commit hash:  5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore:  0.0.0 
Qt:   5.7.1

Reproducible: Always

##### Steps to reproduce

1. Install qtox from "deb http://download.opensuse.org/repositories/home:/antonbatenev:/tox/Debian_Stretch/" on a fresh install.
2. Start qtox and create new profile.

##### Observed Behavior

Segmentation fault: 
Thread 5 "qTox Database" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc16c4700 (LWP 18833)]
0x00007ffff3c2775d in EVP_EncryptUpdate () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) back
#0  0x00007ffff3c2775d in EVP_EncryptUpdate () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007ffff3f71e3b in ?? () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#2  0x00007ffff3f8247e in sqlcipher_page_cipher () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#3  0x00007ffff3f94104 in sqlite3Codec () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#4  0x00007ffff3fa2799 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#5  0x00007ffff3faa5fa in ?? () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#6  0x00007ffff3faa7cf in ?? () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#7  0x00007ffff3fae421 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#8  0x00007ffff3fdd926 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#9  0x00007ffff3fde8cf in sqlite3_step () from /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0
#10 0x0000555555629060 in ?? ()
#11 0x00005555556c1b75 in ?? ()
#12 0x00007fffef350499 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fffefd76b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007fffefd7e341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fffef3239e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007fffef32616d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fffef377c43 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff02ca7f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff02caa60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff02cab0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fffef37804f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fffef3219ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fffef14f0f3 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fffef153da8 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007fffeebff424 in start_thread (arg=0x7fffc16c4700) at pthread_create.c:333
#26 0x00007fffee0a59bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

##### Additional Info

I then tried starting utox without issue. When I restarted qtox using the newly created utox profile then it started without issue.

**Comment by sudden6** [comment] 2017-02-08 00:05
duplicate of  #4054 closing

**Closed as completed by sudden6** 2017-02-08 00:05 UTC
Labels: U-low
