### ISSUE TITLE
Messages arrive out of order when some of them are delayed by network

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4228] opened 2017-03-02 18:32 UTC
Any individual message can get lost in transit.

Here's what I did to simulate the problem:
1. Created 3 faux messages: msg1, msg2, msg3.
2. Deleted the record for msg2 in faux_offline_pending (so that it appears to have been sent).
3. Started the receiving account, messages msg1, msg3 got sent.
4. Shut down both ends, added the record for msg2 back to faux_offline_pending.
5. Started both ends.
6. Message msg2 got sent, but it is shown as the last on the receiving end, not in the chronological order.

I know that this has to do with the fact that Tox message doesn't have "sent" time, only "received" time. So this probably will not get fixed until the tox protocol starts transmitting "sent" time with the message. There is/was a bug# for this.

**Comment by sudden6** [comment] 2017-03-02 20:56
I can see nothing, where this has anything to do with the network. With the procedure you described, it is exactly the behavior I would expect from the implementation.

qTox only has "faux" (not real) offline messaging, because toxcore doesn't provide real offline messaging.

With your step 2 you basically told qTox "remove this message from the send queue" and qTox continues to try and send msg1 and msg3. When the other client comes online qTox sends the messages (receives receive acknowledge from toxcore) and removes them from the send queue. In step 4 you tell qTox there's another message in the send queue and it will send it and the other client will receive it as a new message. toxcore has no way to know, that the last message was intended to be msg2 actually, because toxcore is only called by the offline message engine when the friend comes online.

To somewhat mitigate that issue, qTox could keep some sort of sequence number in the chat history, but IMO this is useless, as long as no one tampers with the db ;)

Tox messages also don't have a "received time" on the protocol or toxcore level, that is added by qTox.

Additionally I don't think reliable "sent times" will ever happen in toxcore, because one can not ensure the sender isn't lying. What I think would be a great addition, are cryptographically secured sequence numbers of some sort, but that has to happen in toxcore.

**Comment by yurivict** [comment] 2017-03-02 21:03
If the network was 100% reliable and stable, this problem would have never happened. This is how it is related to network. Message loss triggers the problem.

I think both sequence numbers and sent timestamp should happen. There is no way to prevent lying, if someone chooses to lie, but good faith sent timestamp will be useful.

**Comment by sudden6** [comment] 2017-03-02 21:36
toxcore ensures that only messages really received by the other client are marked as sent, so message loss should not happen.

If you suspect a bug in toxcore or qTox, the instructions above are most probably not the correct way to find it.

**Comment by yurivict** [comment] 2017-03-02 22:28
They are all sent, but this happens when receipts arrive out of order.

**Comment by Diadlo** [comment] 2017-03-03 05:59
If toxcore will support offline messaging through blockchain, then we can prevent lying.
But I think, it will not

**Comment by yurivict** [comment] 2017-03-03 06:06
Fixing the order without lying prevention would be great. Random network failures cause messages being reordered, which is a major problem.

**Comment by Diadlo** [comment] 2017-03-03 07:03
I think we should not implement anything what add ability to lie. ~Your~ @Renha's [example](https://github.com/TokTok/c-toxcore/issues/485#issuecomment-282985451) with "no" "dial" will be able (IMO this variant worse)

**Comment by anthonybilinski** [comment] 2019-06-27 07:16
Toxcore guarantees message. If your second message in your example was truly dropped from network, it would be resent and delivered before the third message, so I think the entire premise and test case of this issue is invalid.

From the [spec](https://toktok.ltd/spec.html#net-crypto)
> When sending a lossless packet, the packet is created with its packet number being the number of the last lossless packet created + 1 (starting at 0). The packet numbers are used for both reliability and in ordered delivery and so must be sequential.

I'll close this issue. Please comment if you see this issue occur with real network conditions.

**Closed as completed by anthonybilinski** 2019-06-27 07:16 UTC
