### ISSUE TITLE
fake offline file upload 

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6312] opened 2021-03-03 05:12 UTC
can Implement fake offline file upload? I need it please

**Comment by anthonybilinski** [comment] 2021-03-07 18:42
Duplicate of https://github.com/qTox/qTox/issues/1293, but this should be pretty easy to implement since file transfers were added to history in https://github.com/qTox/qTox/pull/5354.

**Closed as completed by anthonybilinski** 2021-03-07 18:42 UTC
