### ISSUE TITLE
Why qTox permanently uses audio system?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2067] opened 2015-08-09 13:21 UTC
Hi there!

I am using latest qTox from pkg.tox.chat repo. I have only 1 question: why it uses microphone&speaker regardless of call penging?

I see microphone icon all time at my panel.

Tnx a lot :)

**Comment by suhr** [comment] 2015-08-09 20:44
OpenAL-related issue. See https://github.com/tux3/qTox/issues/1880.

**Comment by antis81** [comment] 2015-08-21 09:49
Closing as duplicate of #1880

**Closed as completed by antis81** 2015-08-21 09:49 UTC
Labels: U-low
