### ISSUE TITLE
Sound gone after update (16.01.2015)

### ISSUE THREAD

**Issue by mastir** [qTox/qTox#2806] opened 2016-01-16 06:40 UTC
Sound freezes, after audio settings open. If i switch setting tabs, microphone noise freezes and sound gone, forever (almost)

way to reproduce: open settings->audio, open any user or settings tab, return to settings->audio.
how to fix: close settings, close qtox window (to tray) open qtox, sound works again.

ubuntu 14.04, qtox-unity
now i've got qtox commit: c576a1485a6d0a1fed8911f1341709bff08bd96c

**Comment by tux3** [comment] 2016-01-16 11:39
@antis81 Any ideas? I'd like to work on other things, but there's quite a lot of audio bugs left unsolved and that's going to block the next stable release.

**Comment by antis81** [comment] 2016-01-16 12:36
Yes, I have a very exact idea of why this happens to user's. If there's a problem with the release, there's a ~~simple~~ quick solution: Remove (deactivate) the WIP feature "gain meter widget" within the A/V settings tab.

**Comment by tux3** [comment] 2016-01-16 12:42
@antis81 Okay, do you know how to fix this reasonably soon? Otherwise I think it would be better to kill the gain meter (or whatever is causing all those bugs) and pull it back when it's ready.

**Comment by antis81** [comment] 2016-01-16 12:49
@tux3
I'll setup two PR's:
1. Deactivate the "gain meter widget" feature -> closes this issue (#2806) and #2703.
2. Finish the feature implementation in a new PR.

Is that a plan?

**Comment by tux3** [comment] 2016-01-16 12:53
@antis81 Alright. If that solves it, it's all good; if not we'll have to go a bit further.

**Comment by ElLamparto** [comment] 2016-01-20 12:46
For me the sound always works (except that the microphone choice sometimes disappears from the settings. Linux/Windows - no difference).

The gain meter usually works under Linux and usually doesn't under Windows. The audio is not affected by the meter's caprices.

If audio is accompanied by video, then there is a lot of freezing (there is another ticket for that).

**Comment by antis81** [comment] 2016-01-20 19:43
> For me the sound always works (except that the microphone choice sometimes disappears from the settings. Linux/Windows - no difference).

Thanks for this positive feedback. :) Please post an issue for your mentioned problem. I never noticed this behaviour, but there's probably a logical reason for that.

> The gain meter usually works under Linux and usually doesn't under Windows. The audio is not affected by the meter's caprices.

This feature is currently deactivated, because there's multiple problems with that:
1. The concept needs to be implemented less resource hungry and actually use available data from the audio input.
2. Stopping the "measuring thread" leads to a crash, which is not easily reproducible and not worth fixing, before 1 is solved.

As those problems interfere with other not yet solved tasks in the audio context, we decided to remove that, allowing us to stabilize the overall audio concept first.

**Comment by antis81** [comment] 2016-01-20 19:57
@mastir This issue should now be gone -> closing. Please reopen, if audio settings still freeze an audio call.

**Closed as completed by antis81** 2016-01-20 19:57 UTC
Labels: C-bug, M-audio

**Comment by mastir** [comment] 2016-01-21 08:07
@antis81 thank you, cant reproduce this bug in current version, but i like this meters, hope to see them later.
