### ISSUE TITLE
May I set nightly style?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3598] opened 2016-08-06 12:21 UTC
##### Brief Description

OS: Archlinux
qTox version:v1.4.0-387-g34aa905
Commit hash:  
toxcore:  
Qt:  
Hardware:  Thinkpad T420
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
##### Steps to reproduce
1. The backgroud of chat window is white, but I want set it to black.
2. So can you improve the theme of chat window? Thank you.
3. …
##### Additional Info

(links, images, etc go here)

---

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment] 2016-08-06 12:32
Sounds like a duplicate of #1427 / #1639 ?

**Closed as completed** 2016-08-06 12:32 UTC
Labels: U-low
