### ISSUE TITLE
qTox doesn't close /dev/videoN

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6057] opened 2020-04-01 18:01 UTC
After opening the video/audio test page and closing it several times qTox keeps open file descriptors for /dev/video:
```
$ lsof /dev/video0
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
qtox    97631 yuri   35u  VCHR  0,205      0t0  205 /dev/video0
qtox    97631 yuri   38u  VCHR  0,205      0t0  205 /dev/video0
qtox    97631 yuri   43u  VCHR  0,205      0t0  205 /dev/video0
qtox    97631 yuri   44u  VCHR  0,205      0t0  205 /dev/video0
```

1. There should be no multiple open file descriptors for /dev/audio
2. Open descriptor should only exist while testing or using video, and not in any other cases.

qTox-1.16.3-784-g981ecfca
FreeBSD 12

**Comment by anthonybilinski** [comment] 2020-04-04 22:56
Duplicate of https://github.com/qTox/qTox/issues/5743, closing so that we can track the bug in one place.

**Closed as completed by anthonybilinski** 2020-04-04 22:56 UTC
