### ISSUE TITLE
qTox not save GUI settings after close left tab in chat window

### ISSUE THREAD

**Issue by FenioPL** [qTox/qTox#4465] opened 2017-06-14 15:22 UTC
OS: Windows 10 x64 (Version 10.0.15063)
qTox version: 1.10.2
Commit hash:  b73603b45a32e63a649294537a62a9f11176c73d
toxcore:  0.1.8
Qt:  5.6.2
Hardware:  Xeon E3 1225 V3, 16GB DDR3, Geforce GTX1060 3GB
…

Reproducible: Always

##### Steps to reproduce

1. Open chat window.
2. Close left tab in chat window 
3. Close chat window
4. Open chat window

##### Observed Behavior

qTox not save chat window view settings. Left tab is alywas open after close and re-open chat window.

##### Expected Behavior

After close left tab in chat window save view settings. re-open chat window without left tab.

![1](https://user-images.githubusercontent.com/13021550/27140274-67d790da-5125-11e7-8b3f-5f0eca608097.jpg)

**Comment by ezavod** [comment] 2017-06-15 19:32
Duplicate of #4387, this should be fixed in latest master.

**Comment by Diadlo** [comment] 2017-06-15 20:21
@ezavod Thanks

**Closed as completed by Diadlo** 2017-06-15 20:21 UTC
Labels: U-low
