### ISSUE TITLE
crashed many times can't get audio video 

### ISSUE THREAD

**Issue by gkrawchuk** [qTox/qTox#5957] opened 2020-01-17 18:14 UTC
##### Brief Description

OS: Windows 10 (10.0)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment] 2020-01-17 18:30
@gkrawchuk this ticket isn't actionable. Without at least logs and repro steps we have no way to work on it.

Can you add more information to the ticket description?

**Comment by gkrawchuk** [comment] 2020-01-17 18:54
I log in and if I go to settings audio / video tab it will crash always `within a second.

I can text but cannot use video microphone to call

**Comment by anthonybilinski** [comment] 2020-01-17 19:09
Can you try with a nightly build at https://github.com/qTox/qTox-nightly-releases/releases/tag/ci-master-latest, and post the logs from it if it crashes again? You can get the logs from Settings -> Advanced.

**Comment by gkrawchuk** [comment] 2020-01-18 01:37
it's crashing again and video works text works no audio
Greg Krawchuk

**Comment by sudden6** [comment] 2020-01-19 18:58
@anthonybilinski maybe #5926 can help with this one too?

**Comment by anthonybilinski** [comment] 2020-01-19 22:36
@sudden6 I'm still not sure what the problem is and can't repo locally, could be something as simple as having the wrong input device selected. But #5926 helped with #5949 (which I can't repro either :disappointed:), so does seem good to get in.

**Comment by anthonybilinski** [comment] 2020-03-23 09:27
Going to close this issue as #5926 is merged and fixes a known audio crash, and there are no logs or repro of another audio or video crash.

If the issue is still reproducible on nightlies, please comment with repro steps and logs.

**Closed as completed by anthonybilinski** 2020-03-23 09:27 UTC
Labels: C-crash
