### ISSUE TITLE
Do not open friend list, open chat window instead.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3320] opened 2016-05-20 01:01 UTC
##### Brief Description

OS: Windows 7 x64/32
qTox version:  v1.4.0-68-g8d225a8
Commit hash:  8d225
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
##### Steps to reproduce
1. qTox is running on PC A and B.
2. Both qTox is configured to check "Multi window mode" and "Open each chat in...".
3. All qTox windows are closed, qTox is running in task tray.
4. Send a message from A to B.
##### Observed Behavior

qTox open "Friend list" window, doesn't open chat window.
##### Expected Behavior
1. Do not open "Friend list".
2. Open "Chat Window with A" only.

Have you ever used "Windows Live Messenger"? If you receive a message, it will open a chat window,
not contact list.

**Comment by Chiitoo** [comment] 2016-05-23 17:54
Looks like a duplicate of #3212 (Open a chat window if the user receive message.).

**Comment by zetok** [comment] 2016-05-23 18:57
Oh, right, thanks.

**Closed as completed by zetok** 2016-05-23 18:57 UTC
Labels: U-low, proposal-accepted
