### ISSUE TITLE
Feedback widget is not refreshed properly

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#2444] opened 2015-10-22 15:33 UTC
The feedback widget isn't refreshed when I choose another capture device. I have to click to another tab and then to 'Audio/Video' again to let it work.

**Comment by zetok** [comment] 2015-10-22 18:42
I can't reproduce it.

I do have some strange freezes though when switching between cam and desktop.

**Comment by ovalseven8** [comment] 2015-11-06 08:55
Works now. :+1:

**Comment by zetok** [comment] 2015-11-06 09:07
If it works, close the issue?

**Comment by ovalseven8** [comment] 2015-11-06 09:07
Yep, you can close it.

**Closed as completed** 2015-11-06 09:07 UTC
Labels: C-bug, M-video
